### ISSUE TITLE
有两台搭建了cnpmjs.org的服务器，能够互相之间同步@scope的package么？

### ISSUE THREAD

**Issue by realzbc** [cnpm/cnpmjs.org#1008]
现在有两台cnpm服务器，其中一台A从淘宝的npm同步，另一台机器B从A同步，现在发现在A 上的私有包，无法同步到B，提示get package error: package not exists, status: 404

**Comment by alsotang** [comment]
这两台能不能考虑用同一个sql服务器，作为对等的两个server服务？

2016-08-05 16:31 GMT+08:00 二叉树之恋 <notifications@github.com>:
