### ISSUE TITLE
npm install报错问题

### ISSUE THREAD

**Issue by lxqbupt2013** [cnpm/cnpmjs.org#1017]
您好！
我想通过一个可以连接外网的服务器为企业内网用户搭建一个私有的npm源服务器，现在已经按照指引成功启动了cnpm的服务器，通过7002端口访问网页版，显示在内网环境下可以正常同步外部包。
也已经把内网本地npm源修改成了http://服务器对应的IP:7001的形式，但是npm install xxx 命令一直报错，错误日志显示内网客户端一直在尝试连接registry.npm.taobao.org失败。下面是报错信息。
![image](https://cloud.githubusercontent.com/assets/5647279/17760277/3accc078-6531-11e6-9baf-4441ab941ec3.png)

已经确认本机客户端连接服务器不通过代理，找不到是在哪里出现了问题，能否帮忙解答，非常感谢
下图是服务器运行截图
![image](https://cloud.githubusercontent.com/assets/5647279/17760378/d868068a-6531-11e6-98de-dafbbe9bf61e.png)

![image](https://cloud.githubusercontent.com/assets/5647279/17760361/c0775242-6531-11e6-897b-9c7778970030.png)

**Comment by hbrls** [comment]
不要用 Windows ？

**Comment by lxqbupt2013** [comment]
内网用户都是用的windows，就是要为他们提供服务o(╯□╰)o

**Comment by phlill** [comment]
请问这个最后怎么解决的？？
