### ISSUE TITLE
npm run start报错

### ISSUE THREAD

**Issue by loveatting** [cnpm/cnpmjs.org#1023]
我是在98e8e7d   Merge pull request #671 from ibigbug/use-qn-dn 这条记录进行安装的,node版本为v0.12.7  
执行npm run start报错,报错内容如下

> cnpmjs.org@2.2.1 start /data/cnpmjs.org
> ./bin/nodejsctl start && cp History.md docs/web/history.md

sh: ./bin/nodejsctl: /bin/bash^M: bad interpreter: No such file or directory

npm ERR! Linux 2.6.32-431.29.2.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! cnpmjs.org@2.2.1 start: `./bin/nodejsctl start && cp History.md docs/web/history.md`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the cnpmjs.org@2.2.1 start script './bin/nodejsctl start && cp History.md docs/web/history.md'.
npm ERR! This is most likely a problem with the cnpmjs.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/nodejsctl start && cp History.md docs/web/history.md
npm ERR! You can get their info via:
npm ERR!     npm owner ls cnpmjs.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/cnpmjs.org/npm-debug.log

**Comment by EricPoker** [comment]
> sh: ./bin/nodejsctl: /bin/bash^M: bad interpreter: No such file or directory
很明显应该是行末尾被加入了个^M。一种可能是在windows下用文本编辑工具修改过参数变量，在保存的时候没注意编码格式造成的。还有可能是用vi修改时，在行末尾按了ctrl_v。可以用如下命令移除：

> sed -i -e 's/\r$//' nodejsctl
