### ISSUE TITLE
Refactor with egg

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#1025]
https://github.com/eggjs/aliyun-egg
- [x] oss -> https://github.com/eggjs/egg-oss
- [x] orm -> https://github.com/eggjs/egg-sequelize
- [x] 基于 SQL 的跨进程跨服务器锁。 https://github.com/cnpm/cnpmjs.org/issues/1025#issuecomment-278210350
- [ ] egg-ejs, view base on ejs
- [ ] one process, multi ports: web-7002, registry-7001

**Comment by fengmk2** [comment]
这几天晚上尝试改造。

**Comment by fengmk2** [comment]
https://cnodejs.org/topic/562bd9b7004756b058c237e9 基于 mysql 实现的队列锁

**Comment by fengmk2** [comment]
@alsotang 这个也能搞定？

**Comment by fengmk2** [comment]
还要考虑跨数据库引擎，看来没法使用特定数据库的语法。

**Comment by fengmk2** [comment]
## 使用乐观锁来实现跨进程锁

结合已有的 `total` 表，`查询条件`：`WHERE name = 'total' AND (sync_status=0 OR gmt_modified < NOW() - 10分钟)`

- 先根据`查询条件`查询是否有空闲的任务（这个瞬间可能会有多个进程拿到查询结果）
  ```sql
  SELECT id, sync_status, gmt_modified FROM `total` WHERE name = 'total' AND (sync_status=0 OR gmt_modified < NOW() - 10分钟);
  ```
- 有任务则尝试使用 ` WHERE name='total' AND gmt_modified=gmt_modified` 更新该条记录，如果更新成功，则代表抢到任务，开始同步任务。数据库有行锁，只有有一个进程能够更新成功。
  ```sql
  UPDATE 'total' SET gmt_modified=NOW() WHERE name='total' AND gmt_modified=$last_gmt_modified;
  ```

**Comment by fengmk2** [comment]
```
registryPort: 7001,
webPort: 7002,
```

@dead-horse 按不同端口来区分2个应用的这种场景，egg 好像目前没法组织代码结构。

**Comment by fengmk2** [comment]
- [ ] egg-ejs

**Comment by jtyjty99999** [comment]
https://github.com/eggjs/egg-sequelize/pull/2 发版本了

**Comment by fengmk2** [comment]
@jtyjty99999 给力，还有一个问题没想好怎么解决 https://github.com/cnpm/cnpmjs.org/issues/1025#issuecomment-279456593 。

**Comment by fengmk2** [comment]
@dead-horse 突然想到一个更加彻底的方法。将 web.cnpmjs.org 和 registry.cnpmjs.org 分离，web 完全依赖 registry 的 api 来实现，它不会直接去访问数据库，这样 web 可以单独先基于 egg 改造。并且 web 只需要部署一台服务器即可。 registry 才是需要保证高可用的，它需要部署多台服务器。

这样就不需要纠结一个 app 多端口的问题了，web 和 registry 天然是2个独立的 app。

**Comment by popomore** [comment]
有理，想参与一下

**Comment by fengmk2** [comment]
@popomore 那新版 web 的架构设计你来做吧。

**Comment by popomore** [comment]
Get

**Comment by popomore** [comment]
Web 请求用的是什么 token

**Comment by fengmk2** [comment]
web 目前都是只读 registry 的，不需要 token

**Comment by popomore** [comment]
看了下还挺简单的
fengmk2 <notifications@github.com>于2017年2月16日 周四10:16写道：

**Comment by dead-horse** [comment]
可以整 antd + dva

**Comment by dead-horse** [comment]
可以拉上 @afc163 @sorrycc 整 egg + antd + dva 的最佳实践？

**Comment by popomore** [comment]
这个还是要 seo 的吧？

**Comment by popomore** [comment]
第一步前平迁吧，之后改起来就简单了。

**Comment by popomore** [comment]
迁移是不需要讨论的，其他的还需要进一步摸索，感觉先让 egg 落地，cnpm 也可以做一个部署的范例。

之后改造成其他的成本就会低很多。

**Comment by popomore** [comment]
https://github.com/eggjs/egg-view-ejs

**Comment by hbrls** [comment]
迁移会影响到数据库或者包的结构吗

**Comment by thonatos** [comment]
基于egg的改造放弃了么？
