### ISSUE TITLE
使用nohup命令后应用仍然不能稳定运行

### ISSUE THREAD

**Issue by lxqbupt2013** [cnpm/cnpmjs.org#1029]
RT
我启动cnpm服务器，使用的命令是：
[root@npm-source cnpmjs.org]# nohup node --harmony dispatch.js &
但是每一次关闭CRT连接，应用就自动关闭了，查看服务器日志发现没有任何错误的log，想问一下这是为什么？我怎么才能让应用稳定的在服务器上跑？
谢谢！

**Comment by alsotang** [comment]
自行 google
