### ISSUE TITLE
how to backup and restore?

### ISSUE THREAD

**Issue by chanjetsdp** [cnpm/cnpmjs.org#1032]

**Comment by alsotang** [comment]
把文件和数据库备份就好了啊，这个项目对于这块没有什么特殊的点需要注意

2016-09-07 16:07 GMT+08:00 chanjetsdp <notifications@github.com>:

**Comment by alsotang** [comment]
Just backup your db and files. There is no special things related to cnpmjs.org.

**Comment by chanjetsdp** [comment]
thank you!

1. install directory:  cnpmjs.org
2. database:
    mysql backup and restore commandline:
         mysqldump -u [uname] -p[pass] [dbname] | gzip -9 > [backupfile.sql.gz]
         gunzip < [backupfile.sql.gz] | mysql -u [uname] -p[pass] [dbname]
3.dataDir:
    default: ~/.cnpmjs.org

**Comment by alsotang** [comment]
Yeah. And I prefer sync against backup.

For example, use amazon rds or custom master-slave for mysql. Use amazon s3 or other object storage for files.
