### ISSUE TITLE
atom 镜像同步不正常

### ISSUE THREAD

**Issue by stawidy** [cnpm/cnpmjs.org#1040]
atom同步到1.9.9之后就没有继续更新了，麻烦排查下？

**Comment by fengmk2** [comment]
https://npm.taobao.org/mirrors/atom/1.10.2/ 有的啊。。

**Comment by fengmk2** [comment]
![image](https://cloud.githubusercontent.com/assets/156269/18682991/00974a4c-7fa1-11e6-9792-44b15e46cb0f.png)

**Comment by stawidy** [comment]
没注意到，抱歉 发自网易邮箱大师 在2016年09月21日 02:12 ，fengmk2写道： https://npm.taobao.org/mirrors/atom/1.10.2/ 有的啊。。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
