### ISSUE TITLE
如何修改admin的密码？

### ISSUE THREAD

**Issue by bayun2** [cnpm/cnpmjs.org#1050]
通过adduser设置了密码后，要如何修改管理员密码呢

**Comment by gehaidong** [comment]
同问

**Comment by alsotang** [comment]
```js
/*
这个文件是用来帮助用户修改密码。目前 tnpm 没有自动化修改密码的方式
 */

var utility = require('utility');

// select * from user where name = 'username1' limit 1;
var salt = 'c964f06181ff4axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'; // 从数据库中，user 表获得
var password = 'password1'; // 让用户告知

var password_sha = utility.sha1(password + salt)

// 将 password_sha 更新到 user 表中去。即完成了密码修改的过程。
// update user set password_sha = 'ad9c8233xxxxxxxxxxxxxxx' where name = 'username1';
console.log(password_sha)

```


这是我目前的做法。。。

**Comment by alsotang** [comment]
你们可以先把这个脚本拿去用 https://github.com/cnpm/cnpmjs.org/pull/1070

**Comment by gehaidong** [comment]
./bin/chanpassword.js:行1: 未预期的符号 `(' 附近有语法错误
./bin/chanpassword.js:行1: `var UserModel = require('../models').User;'

**Comment by gehaidong** [comment]
你好。这边按照你的脚本
var UserModel = require('../models').User;
var co = require('co');
var utility = require('utility');
 
var username = process.argv[2];
var newPassword = process.argv[3];
 
co(function * () {
  var user = yield UserModel.find({where: {name: username}});
  var salt = user.salt;
  console.log(`user original password_sha: ${user.password_sha}`);
  var newPasswordSha = utility.sha1(newPassword + salt);
  user.password_sha = newPasswordSha;
  user = yield user.save();
  console.log(`change user password successful!! user new password_sha: ${user.password_sha}`);
  process.exit(0);
}).catch(function (e) {
  console.log(e);
});
提示./bin/chanpassword.js:行1: 未预期的符号 `(' 附近有语法错误
./bin/chanpassword.js:行1: `var UserModel = require('../models').User;'
