### ISSUE TITLE
镜像里增加atom-shell

### ISSUE THREAD

**Issue by keyiis** [cnpm/cnpmjs.org#1051]
恳请cnpm的团队能在镜像中增加atom-shell!也有可能是我没找到，请指教！不甚感激！这个atom-shell并不是atom编辑器(cnpm已有),而是在electron-rebuild（构建electron应用）时需要用到的，下面是运行electron-rebuild时需要下载的几个包

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.6.1 | win32 | x64
gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v1.4.4/iojs-v1.4.4.tar.gz
gyp http 200 https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v1.4.4/iojs-v1.4.4.tar.gz
gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v1.4.4/SHASUMS256.txt
gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v1.4.4/win-x86/iojs.lib
gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v1.4.4/win-x64/iojs.lib
gyp http 200 https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v1.4.4/win-x86/iojs.lib
gyp http 200 https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v1.4.4/SHASUMS256.txt
gyp http 200 https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v1.4.4/win-x64/iojs.lib
```

**Comment by hbrls** [comment]
https://npm.taobao.org/mirrors/ 这里有你想要的吗

**Comment by keyiis** [comment]
@hbrls 没有找到,mirrors/ 下面的electron和atom都看过。

**Comment by dead-horse** [comment]
atom-shell 已经改名为 electron 了啊，https://npm.taobao.org/mirrors/electron/ 里面的老版本你还能找到 atom-shell 的下载包，新版本都改名了

**Comment by keyiis** [comment]
@dead-horse 且慢！请仔细看下我前面贴的下载内容，不是electron，是编译electron需要的头文件。

**Comment by keyiis** [comment]
@dead-horse 它和electron版本是保持同步的，绝对不是老的哦！

**Comment by fengmk2** [comment]
@keyiis https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v1.4.4/win-x86/iojs.lib 这个是 iojs？不应该去下载 iojs 的库才对的。

cc @zcbenz

**Comment by fengmk2** [comment]
https://github.com/electron/electron-rebuild

**Comment by keyiis** [comment]
@fengmk2 我看了cnpm镜像里的iojs,没有1.4.4,只有1.4.3而且文件目录也不是完全一致的，所以应该不是一个东西。

**Comment by fengmk2** [comment]
这个 1.4.4 应该是 atom-shell 的版本，等 @zcbenz 上线解答。

**Comment by fengmk2** [comment]
mv to https://github.com/cnpm/cnpmjs.org/issues/1112
