### ISSUE TITLE
tar包没有同步是什么问题？

### ISSUE THREAD

**Issue by lijax** [cnpm/cnpmjs.org#1053]
最近几天老是出现一些模块安装404的问题，有开启syncByInstall的，主动同步模块也不行。
最后发现模块信息是更新了，就是tgz包不存在，nfs目录下旧版本的包全有，就是最新同步的没有，重新同步也没有用，有人遇到过这种情况么？

**Comment by fengmk2** [comment]
同步日志贴上来看看。

**Comment by lijax** [comment]
已经解决，把数据库清空了重新装了😂，不知道什么时候同步tar包没有下载下来，再次同步这些模块的话并不会再去下载包

**Comment by fengmk2** [comment]
不太可能，同步逻辑是确保文件保存成功，才会写数据库的。看情况是你的文件在磁盘上被删除了。

**Comment by lijax** [comment]
这个不清楚哦，问题是版本信息更新之后，不管磁盘上有没有这个版本的tar包，以后同步都不会再下载么？

**Comment by fengmk2** [comment]
数据库有记录代表存储成功了，是不会再去检查 tgz 文件是否存在的，因为这个无法做到，一定做了，同步就很慢了。

**Comment by lijax** [comment]
好的，明白了。那有没有命令清空某个模块的同步记录呢，这样就可以重新去同步解决这种问题。

**Comment by fengmk2** [comment]
npm unpublish pkg@version

**Comment by lijax** [comment]
这样就可以操作本地仓库么？我还在那里找unsync命令😂。。。。多谢了@fengmk2

**Comment by fengmk2** [comment]
只要你是你的 cnpmjs.org 管理员，都可以删除。

**Comment by lijax** [comment]
嗯，好的，了解了，谢谢你
