### ISSUE TITLE
环境搭建后cnpm update已有的包，无法更新

### ISSUE THREAD

**Issue by zhiyan** [cnpm/cnpmjs.org#1054]
cnpmjs.org环境都搭好了，建了个私有包@xx/yy, 正常install没有问题，但是cnpm update无法更新到最新版，必须uninstall之后重新install才能安上最新版, 请问是配置有问题吗?
install和update npm上的包都没问题，就是无法update私有包

**Comment by listenmiss** [comment]
我也遇到同样的问题。。。。

**Comment by listenmiss** [comment]
你解决了吗？

**Comment by Jonathan-Rao** [comment]
我也遇到这个问题
