### ISSUE TITLE
安装 sqlite3 被坑死了，有什么办法不依赖吗？

### ISSUE THREAD

**Issue by nateyang** [cnpm/cnpmjs.org#1055]
一直提示：
node-pre-gyp install --fallback-to-build

**Comment by fengmk2** [comment]
```bash
$ npm i -g cnpm --registry=https://registry.npm.taobao.org
$ cnpm install
```

先装个 cnpm 吧。

**Comment by nateyang** [comment]
可以了，非常感谢~

**Comment by C2015** [comment]
我安装了淘宝镜像还是提示这个   
`8 run "node-pre-gyp install --fallback-to-build"
'node-pre-gyp' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Install fail! Error: post install error, please remove node_modules before retry!`
