### ISSUE TITLE
定时同步过程中有某些版本的模块有丢失

### ISSUE THREAD

**Issue by JiaxiangZheng** [cnpm/cnpmjs.org#1060]
内部 CNPM 已经稳定使用快三个月了，中间有不少同事说安装的过程中提示给定版本的包没有找到，见下图：

![image](https://cloud.githubusercontent.com/assets/1008308/19953651/69046c1e-a1ab-11e6-9a34-067f68b453bf.png)

相应 config 为只开启了 `syncModel='all'`，看源代码里，这段逻辑在 `npmService.fetchUpdatesSince` 中，用的是 `/-/all/since?stale=update_after&startkey=` （注：我配置的是淘宝镜像源）这个接口拉取最新更新的包。我用上面截图中包（`object-hash@1.1.4`）的 publish_time 拉取从那个时间起的 [所有的更新包](https://registry.npm.taobao.org/-/all/since?stale=update_after&startkey=1470069700000)，在结果中并没有找到 `object-hash` 这个包。

想问一下，这种问题是淘宝接口提供数据的问题吗？需要怎么解决呢？

**Comment by fengmk2** [comment]
`syncModel='all'` 你是一开始就设置，还是后来才改的？

**Comment by fengmk2** [comment]
如果是中途才改的，那么需要重置一下 total 表的第一行记录的 last_sync_time 字段。

**Comment by fengmk2** [comment]
官方 npm 是请求 /:package 接口，然后没版本就报错了。建议你使用 cnpm 来包装你的内部 npm cli，因为它是去请求 /:package/:version 的，这样如果这个版本不在，会自动去源站下载和同步的，就不会报这种版本不存在的错误了。

**Comment by JiaxiangZheng** [comment]
应该一开始就设成 `all` 的，这个我记得不是太清楚。不过，我的意思是，我设置了 last_sync_time （1470069700000） 去调用 npmService.fetchUpdatesSince，从返回的结果里，并没有看到我需要同步的那个包（object-hash）啊。

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmjs.org/blob/master/controllers/registry/package/list_since.js#L46 有一个限制的，不能超过一周时间，要不然服务端性能扛不住。

**Comment by JiaxiangZheng** [comment]
嗯嗯  看到相关了，我把 total 表里 last_sync_module 和 last_sync_time 重置，重新开始全量同步，问题似乎解决了。
