### ISSUE TITLE
为什么有的包能够正常同步，有些不行？

### ISSUE THREAD

**Issue by jadyyang** [cnpm/cnpmjs.org#1064]
我在服务器上部署了cnpmjs.org，基本上都能正常运行。但发现一个问题，有些包怎么安装和同步都会报错。

我在客户端电脑上使用cnpm install kola react angular都能成功。但是cnpm install moment，总是提示：

> `\ Installing moment@2.14.1Error: GET http://npmjsregistry.XXX.com/moment/download/moment-2.14.1.tgz response 404 status
>     at get (C:\Users\name\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\get.js:49:17)
>     at next (native)
>     at onFulfilled (C:\Users\name\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)
> npminstall version: 2.11.2
> npminstall args: C:\Program Files\nodejs\node.exe C:\Users\name\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --userconfig=C:\Users\name\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://npmjsregistry.xxx.com/ moment`

然后在网页上点同步，总是能同步成功，但是重新 cnpm install moment，却还是提示上面的内容。在服务器的nfs文件夹里也没有moment文件夹。请问这是怎么回事？

**Comment by fengmk2** [comment]
curl -v 'http://npmjsregistry.XXX.com/moment/download/moment-2.14.1.tgz' 返回什么呢？将打印出来的内容贴上来。

**Comment by jadyyang** [comment]
`[www@m162p235 ~]$ curl -v 'http://npmjsregistry.xxx.com/moment/download/moment-2.14.1.tgz'
* About to connect() to npmjsregistry.xxx.com port 80 (#0)
*   Trying 192.168.162.235... connected
* Connected to npmjsregistry.xxx.com (192.168.162.235) port 80 (#0)
> GET /moment/download/moment-2.14.1.tgz HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: npmjsregistry.xxx.com
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Server: nginx
< Date: Thu, 10 Nov 2016 09:51:48 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 9
< Connection: keep-alive
< 
* Connection #0 to host npmjsregistry.xxx.com left intact
* Closing connection #0
`

**Comment by jadyyang** [comment]
nfs里也没有发现moment文件夹，这是什么原因导致的？我看数据库里有moment的信息，是不是从源服务器上下载时出错了，但是数据库里已经有了，后续就不再不同步了？

**Comment by fengmk2** [comment]
@jadyyang 我们的逻辑是 nfs 一定要写成功才会写到数据库的 https://github.com/cnpm/cnpmjs.org/blob/master/controllers/sync_module_worker.js#L995

所以是你们的 nfs 磁盘被人修改了。

**Comment by jadyyang** [comment]
@fengmk2 哦，那我现在把数据库中关于moment的记录全部删掉，然后再sync一次？还是有别的命令可以直接搞定这件事？

**Comment by fengmk2** [comment]
删除 moment 的记录，目前还没其他方式。

**Comment by jadyyang** [comment]
@fengmk2 ok 我试试

**Comment by jadyyang** [comment]
@fengmk2 清楚moment数据，重新sync好了，谢谢了
