### ISSUE TITLE
tarball url 错误

### ISSUE THREAD

**Issue by wmzy** [cnpm/cnpmjs.org#1065]
![image](https://cloud.githubusercontent.com/assets/5526525/20127617/4c2b18f4-a606-11e6-9e18-e77f3778a7e3.png)

如上图：使用 npm 安装的时候回去`r.cnpmjs.org`这个域下去下载tar包，cnpm 客户端应该无此问题。
请问是仓库配置有问题吗？

**Comment by fengmk2** [comment]
会有什么问题？我直接 npm i --registry=https://r.cnpmjs.org 都是能够下载的啊

**Comment by wmzy** [comment]
@fengmk2 请看上图浏览器地址栏中的地址，我是用 npm i --registry=**https://rnpm.xxxxx.com** 命令安装的

**Comment by hbrls** [comment]
我遇到的问题是 scope 包也被指向了这个 tarball url，结果找不到

**Comment by hbrls** [comment]
研究了一下，这个配置项需要手动指定，看来看历史好像最近升过级

    // registry url name
    registryHost: 'registry.your.campany.domain',
