### ISSUE TITLE
npm install hexo-related-popular-posts --save 失败

### ISSUE THREAD

**Issue by liangpu597** [cnpm/cnpmjs.org#1079]
你好，最近看到github上hexo 更新了一个插件，这是地址：[https://github.com/tea3/hexo-related-popular-posts](url)
我的npm已经设置为cnpm了。
可是使用：
`$ cnpm install hexo-related-popular-posts --save`
还是出错了，
一下是错误代码：
`[kuromoji@0.1.1] download ShasumNotMatchError: real sha1:5d8eb388a5d1f5b37f7a4f4f432bb5f1c5f09547 not equal to remote:4aabf39bcced8b8ad92d007a04a26be6da8477c9 (kuromoji@0.1.1) (C:\Users\Tony\.npminstall_tarball\k\u\r\o\kuromoji\0.1.1-4aabf39bcced8b8ad92d007a04a26be6da8477c9.tgz), fail count: 1
[kuromoji@0.1.1] download ShasumNotMatchError: real sha1:ec0b14d3d4d0138b96b4a51db6d962ac85f52b82 not equal to remote:4aabf39bcced8b8ad92d007a04a26be6da8477c9 (kuromoji@0.1.1) (C:\Users\Tony\.npminstall_tarball\k\u\r\o\kuromoji\0.1.1-4aabf39bcced8b8ad92d007a04a26be6da8477c9.tgz), fail count: 2
[kuromoji@0.1.1] download ShasumNotMatchError: real sha1:a371a6eb0d992a77e251e46de70876710c41edd0 not equal to remote:4aabf39bcced8b8ad92d007a04a26be6da8477c9 (kuromoji@0.1.1) (C:\Users\Tony\.npminstall_tarball\k\u\r\o\kuromoji\0.1.1-4aabf39bcced8b8ad92d007a04a26be6da8477c9.tgz), fail count: 3
ShasumNotMatchError: real sha1:a371a6eb0d992a77e251e46de70876710c41edd0 not equal to remote:4aabf39bcced8b8ad92d007a04a26be6da8477c9 (kuromoji@0.1.1) (C:\Users\Tony\.npminstall_tarball\k\u\r\o\kuromoji\0.1.1-4aabf39bcced8b8ad92d007a04a26be6da8477c9.tgz)
    at ReadStream.<anonymous> (C:\Users\Tony\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\download\npm.js:395:21)
    at emitNone (events.js:72:20)
    at ReadStream.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
npminstall version: 2.12.1
npminstall args: C:\Program Files\nodejs\node.exe C:\Users\Tony\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --userconfig=C:\Users\Tony\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org hexo-related-popular-posts --save
`

请问，这是怎么回事？
谢谢！

**Comment by dead-horse** [comment]
试试 `cnpm install hexo-related-popular-posts --save --no-cache`

**Comment by liangpu597** [comment]
可以了，谢谢！

2016-11-25 17:19 GMT+08:00 Yiyu He <notifications@github.com>:
