### ISSUE TITLE
python 镜像与官方不同步

### ISSUE THREAD

**Issue by gucong3000** [cnpm/cnpmjs.org#1081]
https://npm.taobao.org/mirrors/python/
https://www.python.org/ftp/python/

https://github.com/felixrieseberg/windows-build-tools/issues/40

**Comment by fengmk2** [comment]
重新开启同步，估计要明天才能同步完 https://npm.taobao.org/mirrors/python/2.7.10/

**Comment by gucong3000** [comment]
已同步
