### ISSUE TITLE
cnpm服务重启以后，发现所有包都404了

### ISSUE THREAD

**Issue by cxd7744556** [cnpm/cnpmjs.org#1085]
cnpm服务重启以后，发现所有包都404了， 数据库都正常，info都在
`http://****download/*****-1.0.5.tgz`访问tarball的shi hou404，not found
`Error: fetch failed with status code 404`
请问是什么原因呢？如何防范再次出现这种问题呢？

**Comment by fengmk2** [comment]
看看配置，存储的目录是不是被删除了。

**Comment by cxd7744556** [comment]
没有动过配置文件呢，请问如果没有改git上拉下来的有关存储的配置，哪具体的tar包是放在你们的cdn上，还是本地文件夹里呢。文件夹路径是？

**Comment by chrischjh** [comment]
我是升级cnpmjs.org后遇到这个问题，不过重新publish后就好了

**Comment by ljgeneral** [comment]
我也是这个问题
