### ISSUE TITLE
淘宝源同步大量出现 ECONNRESET

### ISSUE THREAD

**Issue by JiaxiangZheng** [cnpm/cnpmjs.org#1090]
看日志里，从 12.06 开始就大量出现 ECONNRESET 的异常，导致包同步出错，这种情况是被淘宝拉黑了么？

具体日志如下贴图：

![image](https://cloud.githubusercontent.com/assets/1008308/21038476/02b83954-be11-11e6-995c-6b2ff610ba00.png)

**Comment by fengmk2** [comment]
你curl一下这个url，看看具体的headers和status

**Comment by JiaxiangZheng** [comment]
如下：

```bash
$ curl -v http://registry.npm.taobao.org/webpack/download/webpack-1.14.0.tgz
* About to connect() to registry.npm.taobao.org port 80 (#0)
*   Trying 114.55.80.225...
* connected
* Connected to registry.npm.taobao.org (114.55.80.225) port 80 (#0)
> GET /webpack/download/webpack-1.14.0.tgz HTTP/1.1
> User-Agent: curl/7.28.1
> Host: registry.npm.taobao.org
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection #0
curl: (56) Recv failure: Connection reset by peer
```

**Comment by fengmk2** [comment]
看来是你那边网络不通…我这边测试好的，而且没有加ip限制

**Comment by fengmk2** [comment]
换成https看看？

**Comment by JiaxiangZheng** [comment]
我现在临时切成了 npm 官方的源，就是同步的速度比较慢。https 目前来看是可以的，我待会尝试重启一下试试，如果 https 被封，感觉还是一样没有解决问题。😂

**Comment by JiaxiangZheng** [comment]
从响应来看是 Connection reset by peer，应该是服务器那边关闭请求了，而且我换了台服务器似乎是可以通的。也是尴尬。。

**Comment by fengmk2** [comment]
我们这边没有做任何变更。是不是你们的网络有变更？

**Comment by JiaxiangZheng** [comment]
我问了运维那边，好像并没啥变动。我再跟进下，后续再在这里反馈。

**Comment by fengmk2** [comment]
刚才看了一下 http 的监控，确实下午有一段时间出问题了。但是 https 的访问正常。建议以后都走 https 吧

![image](https://cloud.githubusercontent.com/assets/156269/21046281/e9775cc6-be3e-11e6-95da-140d91827cb7.png)
