### ISSUE TITLE
cnpm install --save-dev postcss@5.2.8 error 

### ISSUE THREAD

**Issue by zhangping2014** [cnpm/cnpmjs.org#1103]
Error: unknown compression method (postcss@5.2.8) (/Users/drank/.npminstall_tarball/p/o/s/t/postcss/5.2.8-05720c49df23c79bda51fd01daeb1e9222e94390.tgz)
at Zlib._handle.onerror (zlib.js:363:17)
npminstall version: 2.2.1
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/.bin/npminstall --china --userconfig=/Users/drank/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org postcss

**Comment by fengmk2** [comment]
看来是 `/Users/drank/.npminstall_tarball/p/o/s/t/postcss/5.2.8-05720c49df23c79bda51fd01daeb1e9222e94390.tgz` 这个文件不完整导致的。我得加个重试才行。

**Comment by fengmk2** [comment]
@zhangping2014 你可以先清空 cache 临时解决

```bash
$ rm -rf /Users/drank/.npminstall_tarball
```

**Comment by zhangping2014** [comment]
@fengmk2  试过了 没什么用 再次 cnpm install 的时候还会报同样的错误

**Comment by fengmk2** [comment]
呃，奇怪，为何会这样。。。你先关闭 cache 吧，加个 `--no-cache` 参数

**Comment by fengmk2** [comment]
@zhangping2014 完整的日志也贴一下吧

**Comment by fengmk2** [comment]
@zhangping2014 你重新安装一下 cnpm，这样会使用最新版本的 npminstall 的，我看已经实现了本地文件解压失败容灾的逻辑了的。

```bash
cnpm i -g cnpm
```

**Comment by zhangping2014** [comment]
好的 试试看

**Comment by zhangping2014** [comment]
换了node版本 npm版本 解决了
