### ISSUE TITLE
 部署npm private 第一步安装提示错；最后一步发布失败

### ISSUE THREAD

**Issue by zxydaisy** [cnpm/cnpmjs.org#1104]
参考 https://github.com/cnpm/cnpmjs.org/wiki/Deploy-a-private-npm-registry-in-5-minutes
1. 第一步安装提示错误
/usr/bin/cnpm -> /usr/lib/node_modules/cnpm/bin/cnpm
/usr/bin/cnpmjs.org -> /usr/lib/node_modules/cnpmjs.org/bin/cli.js

> sqlite3@3.1.8 install /usr/lib/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.9.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/sqlite3/.node-gyp"
make: Entering directory `/usr/lib/node_modules/sqlite3/build'
make: *** No rule to make target `../.node-gyp/6.9.3/include/node/common.gypi', needed by `Makefile'.  Stop.
make: Leaving directory `/usr/lib/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.13.0-96-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/lib/node_modules/sqlite3/lib/binding/node-v48-linux-x64"
gyp ERR! cwd /usr/lib/node_modules/sqlite3
gyp ERR! node -v v6.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/lib/node_modules/sqlite3/lib/binding/node-v48-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 3.13.0-96-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/sqlite3
node-pre-gyp ERR! node -v v6.9.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/lib/node_modules/sqlite3/lib/binding/node-v48-linux-x64' (1)
/usr/lib
├── cnpm@4.4.2
└── cnpmjs.org@2.19.1

npm ERR! Linux 3.13.0-96-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "-g" "--build-from-source" "--registry=https://registry.npm.taobao.org" "--disturl=https://npm.taobao.org/mirrors/node" "cnpmjs.org" "cnpm" "sqlite3"
npm ERR! node v6.9.3
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.8 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-debug.log
root@c4v153:/tmp# make
make: *** No targets specified and no makefile found.  Stop.
root@c4v153:/tmp# npm install -g node-gyp
npm WARN deprecated has-color@0.1.7: Renamed to supports-color. If you're using chalk, upgrade to the latest version. https://github.com/chalk/supports-color
/usr/bin/node-gyp -> /usr/lib/node_modules/node-gyp/bin/node-gyp.js

2. 最后一步发布也报错

root@c4v153:/tmp/helloworld# cnpm publish @xxx/helloworld@1.0.0
npm ERR! Linux 3.13.0-96-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/root/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=http://192.168.16.15:7001" "publish" "@xxx/helloworld@1.0.0"
npm ERR! node v6.9.3
npm ERR! npm  v3.10.10
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED 192.168.16.15:7001
npm ERR!     at Object.exports._errnoException (util.js:1022:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:1045:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
npm ERR!  { Error: connect ECONNREFUSED 192.168.16.153:7001
npm ERR!     at Object.exports._errnoException (util.js:1022:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:1045:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '192.168.16.15',
npm ERR!   port: 7001 }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/helloworld/npm-debug.log

**Comment by fengmk2** [comment]
> npm ERR! Error: connect ECONNREFUSED 192.168.16.15:7001

连不上

**Comment by zxydaisy** [comment]
这个虚拟机的IP就是192.168.16.15； 在这个虚拟机上按照步骤执行，提示出错
