### ISSUE TITLE
使用 cnpm 时，遇到webpack打包总是获取最新版jquery的问题

### ISSUE THREAD

**Issue by valsun2016** [cnpm/cnpmjs.org#1107]
大致情况如下，经过一天的排查，知道是cnpm导致的，但是不明白原因：

基本环境：
linux /  windows ，
node 4.x / 6.x / 7.x ，
npm命令安装（淘宝源） ，
package.json 中的依赖。。。。 "jquery": "1.12.4"

正常测试描述：

最后webpack打包，均可正常（是我需要的jquery版本）

异常测试描述：

上述环境不变，把使用 npm 改用 cnpm后，再使用webpack打包，则异常（不是我需要的jquery版本），
得到的打包js文件中jquery竟然是。。。。  jQuery JavaScript Library v3.1.1，
查了一下， v3.1.1 是当前jquery的最新版。

疑惑之处描述：

但问题是cnpm 安装后，node_modules下 只有"jquery": "1.12.4"这个版本。在webpack打包时自动去网上找了最新的jquery依赖？？？但为什么用npm就ok呢？，我理解webpack和cnpm貌似没什么关系啊，一个是做打包，一个是做安装，但经过屡次测试，的确是用了cnpm后，导致上述现象，求大神解惑~~~~

**Comment by fengmk2** [comment]
能否提供一下可重现的代码方式？

**Comment by tangtang4321** [comment]
+1  
cnpm安装私有库包时，总是下载的最新包，而不是指定版本
