### ISSUE TITLE
cnpm私服搭建起来后，模块发布成功了，install时出错，提示tgz包找不到404

### ISSUE THREAD

**Issue by onlyWuj** [cnpm/cnpmjs.org#1110]
查看命令是有安装这个模块的
> cnpm view @zd/dbl
---------------------------------------------------------------------------------------------------
{ name: '@zd/dbl',
  description: '前端工程化工具：创建项目，生成脚手架、webpack配置文件；启动本地s
erver调试项目，顺带启动一个mock服务；开发完成后构建项目，进行压缩合并等。',
  'dist-tags': { latest: '1.0.0' },
  maintainers: [ 'admin <wj@163.com>' ],
  time:
   { modified: '2017-01-19T12:31:40.000Z',
     created: '2017-01-19T12:31:40.669Z',
     '1.0.0': '2017-01-19T12:31:40.669Z' },
  users: {},
  author: '',
  repository: { type: 'git', url: 'git+https://github.com/cc17/dbl.git' },
  versions: [ '1.0.0' ],
  readmeFilename: 'readme.md',
  homepage: 'https://github.com/cc17/dbl#readme',
  bugs: { url: 'https://github.com/cc17/dbl/issues' },
  license: 'ISC',
  version: '1.0.0',
  main: 'index.js',
  scripts: { test: 'echo \\"Error: no test specified\\" && exit 1' },
  keywords: [],
  dependencies:
   { async: '^1.4.2',
     chalk: '^1.1.1',
     commander: '^2.7.1',
     connect: '^3.4.0',
     'css-loader': '^0.17.0',
     directory: '^0.1.0',
     'directory-copy': '^0.1.0',
     'extract-text-webpack-plugin': '^0.8.2',
     gulp: '^3.9.0',
     'gulp-htmlmin': '^1.1.3',
     'gulp-replace': '^0.5.4',
     'gulp-util': '^3.0.6',
     'html-webpack-plugin': '^1.6.1',
     'jsx-loader': '^0.13.2',
     less: '^2.5.1',
     'less-loader': '^2.2.0',
     lodash: '^3.10.1',
     mock2easy: '0.0.6',
     mock2easynew: '0.0.1',
     'serve-favicon': '^2.3.0',
     'serve-static': '^1.10.0',
     'style-loader': '^0.12.3',
     underscore: '^1.8.3',
     webpack: '^1.12.1',
     'webpack-dev-middleware': '^1.2.0' },
  dist:
   { shasum: 'ca186458fd100465d3f318e2a5bbd38d6f6e2f7a',
     size: 26376,
     key: '/@zd/dbl/-/@zd/dbl-1.0.0.tgz',
     tarball: 'http://r.cnpmjs.org/@zd/dbl/download/@zd/dbl-1.0.0.tgz' },
  publish_time: 1484829100669 }
`---------------------------------------------------------------------------------------------------
安装命令报错
>cnpm install @zd/dbl
`---------------------------------------------------------------------------------------------------
- Installing @zd/dbl@*Error: GET http://r.cnpmjs.org/@zd/dbl/download/@zd/dbl-1.
0.0.tgz response 404 status
    at get (E:\dev\node\node-v6.9.4-win-x64\node_node_global\node_modules\cnpm\n
ode_modules\npminstall\lib\get.js:51:17)
    at next (native)
    at onFulfilled (E:\dev\node\node-v6.9.4-win-x64\node_node_global\node_module
s\cnpm\node_modules\co\index.js:65:19)
npminstall version: 2.16.1
npminstall args: E:\dev\node\node-v6.9.4-win-x64\node.exe E:\dev\node\node-v6.9.
4-win-x64\node_node_global\node_modules\cnpm\node_modules\npminstall\bin\install
.js --china --userconfig=C:\Users\Administrator\.cnpmrc --disturl=https://npm.ta
obao.org/mirrors/node --registry=http://192.168.32.27:7001/ @zd/dbl

`---------------------------------------------------------------------------------------------------
cnpm的服务config/index.js里的scope配置也是有这个域的
 // registry scopes, if don't set, means do not support scopes
  scopes: [ '@cnpm', '@cnpmtest', '@zd' ],

不明白怎么回事了。求救。

**Comment by dead-horse** [comment]
为什么还是访问的 `r.cnpmjs.org` 访问 tgz 包，看看配置里面是不是没改

**Comment by onlyWuj** [comment]
@dead-horse
小弟不太懂，应该改哪个配置

**Comment by myyuanyuan5200** [comment]
@onlyWuj 是把registryHost改成自己的地址么？

**Comment by onlyWuj** [comment]
@myyuanyuan5200 这样是可以了，但后来一直用得很少，不晓得有没有什么问题

**Comment by pengfeiWang** [comment]
@onlyWuj 你是怎么解决的, 要改什么配置么

**Comment by ZengTianShengZ** [comment]
你模块是怎么发布成功的呢
我添加用户的时候
```
npm adduser
npm WARN invalid config registry="http:127.0.0.1:7001/"
npm WARN invalid config Must be a full url with 'http://'
Username: zts
Password: 
Email: (this IS public) test@gmail.com
```
接着就报错了，请问是怎么添加 user 的呢，还是直接login？
但我直接login：
```
npm login
npm WARN invalid config registry="http:127.0.0.1:7001/"
npm WARN invalid config Must be a full url with 'http://'
Username: zts
Password: *** // 这边密码我不知道填写什么就随便写，有默认密码吗
Email: (this IS public) test@gmail.com   // 这么填写的邮箱是对应 config.js 下 admins 的配置
``` 
也还是报错
```
Username: zts
Password: 
Email: (this IS public) test@gmail.com
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR! 
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zengtiansheng/.npm/_logs/2017-11-13T04_14_16_265Z-debug.log
```
请问怎么解决呢

**Comment by ZengTianShengZ** [comment]
./congif.js 下需要修改一下配置文件
```
   // registry url name（模块下载请求地址，必须设置）
   registryHost: '127.0.0.1:7001',
```

**Comment by xiepJ** [comment]
哇，简直是爆炸，不是说好优先从私有仓库里获取么，为什么一个远程仓库地址会影响到 私有模块的 install，心好累，这大半天，想回家

**Comment by dryqiao** [comment]
@dead-horse @onlyWuj @ZengTianShengZ 请问下为什么我把本地cnpm配置的registryHost改成私有仓地址了，还是从r.cnpmjs.org访问啊？？

```
cnpm config list
; cli configs
disturl = "https://npm.taobao.org/mirrors/node"
metrics-registry = "http://localhost:17001/"
registry = "http://localhost:17001/"
scope = ""
user-agent = "npm/6.4.1 node/v8.11.2 win32 x64"
userconfig = "C:\\Users\\qiao\\.cnpmrc"

; userconfig C:\Users\qiao\.cnpmrc
registry = "http://localhost:17001/"
registryHost = "http://localhost:17001"
scopes = "@md"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\qiao\Desktop\demo
; HOME = C:\Users\qiao
; "npm config ls -l" to show all defaults.
```

**Comment by xiepJ** [comment]
你的同步策略配置的什么，没的包它还是需要去r.cnpmjs.org同步的，所以404 是正常的，如果一切顺利你稍后install就会成功，你也可以观察日志或者 7001 的概要信息，观察同步工作是否正常进行，这个跟网速有关，你也可以手动同步。


发自网易邮箱大师
在2018年9月14日 15:43，QIAO<notifications@github.com> 写道：

@dead-horse@onlyWuj@ZengTianShengZ 请问下为什么我把本地cnpm配置的registryHost改成私有仓地址了，还是从r.cnpmjs.org访问啊？？

cnpm config list
; cli configs
disturl = "https://npm.taobao.org/mirrors/node"
metrics-registry = "http://localhost:17001/"
registry = "http://localhost:17001/"
scope = ""
user-agent = "npm/6.4.1 node/v8.11.2 win32 x64"
userconfig = "C:\\Users\\qiao\\.cnpmrc"

; userconfig C:\Users\qiao\.cnpmrc
registry = "http://localhost:17001/"
registryHost = "http://localhost:17001"
scopes = "@md"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\qiao\Desktop\demo
; HOME = C:\Users\qiao
; "npm config ls -l" to show all defaults.

**Comment by dryqiao** [comment]
@xiepJ 同步配置是默认的，本地publish的私有包也要同步？
