### ISSUE TITLE
mirror atom-shell dist

### ISSUE THREAD

**Issue by keyiis** [cnpm/cnpmjs.org#1112]
每次运行[electron-rebuild](https://www.npmjs.com/package/electron-rebuild)编译electron应用时都需要翻墙，因为编译时需要的头文件都要去 https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist 下载， 如果能将这个加入 https://npm.taobao.org/mirrors 那就太好了！

**Comment by fengmk2** [comment]
@keyiis 我尝试过的，但是不知道如何拉到 dist 列表。

@zcbenz 有办法让我同步这个 s3 资源吗？

**Comment by fengmk2** [comment]
@keyiis https://github.com/cnpm/cnpmjs.org/issues/1051 之前你已经提交过的

**Comment by keyiis** [comment]
@fengmk2 是的，这次又碰到了，哎

**Comment by fengmk2** [comment]
@keyiis 你告诉我如何重现，我去看看代码，看看是否有办法拿到同步列表。

**Comment by fengmk2** [comment]
按道理应该不需要重新编译 electron 才对的

**Comment by keyiis** [comment]
@fengmk2 多谢！因为默认是安装和系统nodejs同架构的，例如系统安装的nodejs是64位的，electron也是64位的，但我的应用需要兼容32位的系统，所以不得不再手动编译一次。
重现的步骤：
第一步 npm i sqlite3
第二步 npm i electron  --arch=ia32 --save-dev
第三步 npm i electron-rebuild
第四步 .\node_modules\.bin\electron-rebuild.cmd -a ia32

**Comment by fengmk2** [comment]
你可以找一台装了32位系统的服务器来编译，会比较节省时间。

**Comment by keyiis** [comment]
@fengmk2 不好意思，前面我没说清楚，应该是我需要在electron应用中访问sqlite3数据库，但是访问数据需要调用c写的文件，由于默认安装sqlite3是编译成nodejs的，但electron使用的是iojs，因此需要重新编译sqlite3这类需要调用c的包，在编译时无论是32位还是64位都需要下载electron的头文件才能完成编译。

**Comment by zcbenz** [comment]
好像可以通过把s3:ListBucket权限公开实现，我研究一下。

**Comment by zcbenz** [comment]
现在通过调用S3的`ListObjects` API 就可以抓取文件列表了，头文件都在`s3://gh-contractor-zcbenz/atom-shell/dist/`下。

**Comment by fengmk2** [comment]
@zcbenz 确实可以了！赞 https://gh-contractor-zcbenz.s3.amazonaws.com/

**Comment by fengmk2** [comment]
@keyiis @zcbenz 通过那个环境变量来改变 mirror url 的地址呢？

**Comment by keyiis** [comment]
@fengmk2 electron-rebuild 有一个参数 --dist-url 来设置download url的地址`-d, --dist-url               Custom header tarball URL`

**Comment by fengmk2** [comment]
@keyiis 可以了 `-d https://npm.taobao.org/mirrors/atom-shell/`

**Comment by fengmk2** [comment]
会去下载了

```
./node_modules/.bin/electron-rebuild --loglevel=http --verbose -d https://npm.taobao.org/mirrors/atom-shell/
✖ Rebuild Failed
An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@6.9.4 | darwin | x64
gyp http GET https://npm.taobao.org/mirrors/atom-shell/v1.4.15/iojs-v1.4.15.tar.gz
gyp http 404 https://npm.taobao.org/mirrors/atom-shell/v1.4.15/iojs-v1.4.15.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://npm.taobao.org/mirrors/atom-shell/v1.4.15/iojs-v1.4.15.tar.gz

```

**Comment by keyiis** [comment]
@fengmk2 @zcbenz  可以下载了，谢谢你们！祝新春快乐！

**Comment by jareguo** [comment]
感谢大神们！

**Comment by noyobo** [comment]
@fengmk2  https://npm.taobao.org/mirrors/atom-shell/  看起来很久没更新了？  最新的镜像没有了

**Comment by keyiis** [comment]
@fengmk2 真的是没有更新了，不要放弃啊.....

**Comment by xmsz** [comment]
现在有解决办法吗
