### ISSUE TITLE
cnpm同步默认存储位置问题

### ISSUE THREAD

**Issue by guayeguaye** [cnpm/cnpmjs.org#1119]
未修改存储位置啊，为什么会到这个地方位置去下载
![image](https://cloud.githubusercontent.com/assets/19300958/22731491/d40d6d6e-ee25-11e6-891d-ae627e8b32b8.png)

我的同步位置在这里啊
![image](https://cloud.githubusercontent.com/assets/19300958/22731590/1d65b16a-ee26-11e6-9751-0676d834998a.png)

**Comment by fengmk2** [comment]
你是怎样启动的？配置改了？

**Comment by guayeguaye** [comment]
我是用 node dispatch.js这个命令启动的。感觉在git里面启动是正常的，在cmd里面启动则会出现这个问题。
