### ISSUE TITLE
scope不支持同步

### ISSUE THREAD

**Issue by myyuanyuan5200** [cnpm/cnpmjs.org#1121]
scope的包不能从taobao镜像同步过来，但是服务器挂了，重新搭了一个服务，scope的历史包都没有了，现在同步会报 ignore sync private scoped ["@***"] package
能设置scope的包也能够同步么？
如果先把scope设置去掉，同步过来以后，再继续发包可以么？

**Comment by fengmk2** [comment]
你私有的 scoped 根本没有发布到 taobao npm 的，只有你们自己有，别人都没有的。

**Comment by myyuanyuan5200** [comment]
我们是会taobao和我们自己服务器各发一份的。

**Comment by myyuanyuan5200** [comment]
是不是基本这个scope就失去了私有的意义？
如果taobao都会发，那我们基本就不用发到我们私有包，如果实现安装更快的目的的话，就直接同步过来到私有库就好了吧~~
多谢这么晚了还回答我的问题，非常感谢

**Comment by fengmk2** [comment]
是的，如果你会发布到 npm，那么每必要发到自己的 scope。都是 public 的了。

私有的才会需要 scope 的。

**Comment by myyuanyuan5200** [comment]
再问一嘴，是不是带scope的public包也不能同步到私有服务器上啊？
