### ISSUE TITLE
web 层改造

### ISSUE THREAD

**Issue by popomore** [cnpm/cnpmjs.org#1124]
将 cnpmjs.org 的 web 层单独抽出来成为独立应用，并迁移到 [egg] https://github.com/cnpm/cnpmjs.org/issues/1025#issuecomment-280058210

### 首页

https://cnpmjs.org/

### 模块页面

https://cnpmjs.org/package/urllib

### 查询页面

https://cnpmjs.org/browse/keyword/urllib

### 同步页面

https://cnpmjs.org/sync/urllib

这里有一个操作

### 用户页面

https://cnpmjs.org/~fengmk2

### badge

https://cnpmjs.org/badge/v/urllib.svg

### 私有模块

https://cnpmjs.org/privates

## 中间件

- maxrequests - 添加 app/middleware/maxrequests，使用 koa-maxrequests
- block - 去掉
- rt - 添加 app/middleware/rt，使用 koa-rt
- rewrite - 配置 siteFile
- staticCache - 使用 egg-static
- pagemock - 暂无
- opensearch - 配置 siteFile
- proxyToNpm - 添加 app/middleware/proxy_to_npm，沿用原来逻辑
- bodyParser - 使用 egg 内置 
- auth - 去掉
- notFound - 使用 egg 内置
- compress - 是不是可以去掉
- conditional - 是不是可以去掉
- etag - 是不是可以去掉
- markdownMiddleware - 使用 koa-markdown，渲染首页
- ejs - 增加 egg-view-ejs

## service

将原来的依赖的 service 都转调 registry

- packageService.getModule - /:name/:version
- packageService.getModuleByTag - /:name/:tag
- packageService.getUnpublishedModule
- packageService.listDependents - /-/package/:name/dependents
- packageService.listStarUserNames
- packageService.listMaintainers
- packageService.listPrivateModulesByScope
- packageService.listModules
- packageService.search
- packageService.listModulesByUser
- userService.getAndSave
- SyncModuleWorker.sync 需要操作
- Log.get
- DownloadTotal.getTotalByName

## 其他

~~下面两个并非页面，是否要做到 web~~ 去掉

~~https://cnpmjs.org/total~~
~~https://cnpmjs.org/_list/search/search~~

## Action

- [ ] 首页
- [ ] 模块页面
- [ ] 查询页面
- [ ] 同步页面
- [ ] 用户页面
- [ ] badge
- [ ] 私有模块

[egg]: https://eggjs.org/

**Comment by popomore** [comment]
sync 有个操作，

**Comment by popomore** [comment]
service 估计得重写，不能用内部 API，写的时候再看看

**Comment by popomore** [comment]
建个 web.cnpmjs.org ?

**Comment by fengmk2** [comment]
sync 操作调用 registry 的 sync 接口即可。

@popomore 建吧

**Comment by fengmk2** [comment]
需要写一个 npm-registry-client 了

**Comment by fengmk2** [comment]
> block - 添加 app/middleware/block，沿用原来逻辑

web 层这个可以去掉了。

**Comment by fengmk2** [comment]
去掉对 koa-middlewares 的依赖，koa-middlewares 很难维护了。

**Comment by fengmk2** [comment]
> auth - web 是只读的，好像没啥用？

嗯，没有用

**Comment by fengmk2** [comment]
> SyncModuleWorker.sync 需要操作

去掉了，调用 registry

**Comment by fengmk2** [comment]
> 下面两个并非页面，是否要做到 web

去掉吧，不应该属于 web

**Comment by popomore** [comment]
感觉大部分 sla 都可以去掉，web 层流量没那么大

**Comment by popomore** [comment]
https://github.com/cnpm/cnpmjs.org/blob/master/controllers/web/package/show.js#L68

这个数据好像没用

**Comment by fengmk2** [comment]
@popomore 我先将 Search api 做到 registry 里面，这样就不影响 web 改造了 https://github.com/cnpm/cnpmjs.org/issues/1141

**Comment by popomore** [comment]
好，search 比较独立，可以放最后做
