### ISSUE TITLE
站点搭建起来了，但是报[SequelizeDatabaseError: SQLITE_ERROR: no such table: tag]

### ISSUE THREAD

**Issue by packjs** [cnpm/cnpmjs.org#1129]
{ [SequelizeDatabaseError: SQLITE_ERROR: no such table: tag]
  name: 'SequelizeDatabaseError',
  message: 'SQLITE_ERROR: no such table: tag',
  parent: 
   { [Error: SQLITE_ERROR: no such table: tag]
     errno: 1,
     code: 'SQLITE_ERROR',
     sql: 'SELECT module_id FROM tag WHERE LOWER(name) LIKE LOWER(\'jquery%\') AND tag=\'latest\'     ORDER BY name LIMIT 100;' },
  original: 
   { [Error: SQLITE_ERROR: no such table: tag]
     errno: 1,
     code: 'SQLITE_ERROR',
     sql: 'SELECT module_id FROM tag WHERE LOWER(name) LIKE LOWER(\'jquery%\') AND tag=\'latest\'     ORDER BY name LIMIT 100;' },
  sql: 'SELECT module_id FROM tag WHERE LOWER(name) LIKE LOWER(\'jquery%\') AND tag=\'latest\'     ORDER BY name LIMIT 100;',
  url: '/browse/keyword/jquery' }
SequelizeDatabaseError: SQLITE_ERROR: no such table: tag
    at Query.formatError (/home/zhaoyadong/Work/site/cnpmjs.org/node_modules/sequelize/lib/dialects/sqlite/query.js:348:14)
    at afterExecute (/home/zhaoyadong/Work/site/cnpmjs.org/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
    at replacement (/home/zhaoyadong/Work/site/cnpmjs.org/node_modules/sqlite3/lib/trace.js:19:31)

**Comment by dead-horse** [comment]
表建好了么

**Comment by packjs** [comment]
建好了。

**Comment by packjs** [comment]
表都建立好了。






在 2017-02-19 22:37:08，"Yiyu He" <notifications@github.com> 写道：


表建好了么

**Comment by packjs** [comment]
有谁能帮助一下啊。

**Comment by dead-horse** [comment]
`no such table: tag`

这个报错就是说你的这张表没有建好，你通过其他工具连上去检查一下吧，要么就是配置到了其他的 db 上了

**Comment by packjs** [comment]
我检查一下db配置看看。

**Comment by packjs** [comment]
database: {
    db: 'cnpmjs_test',
    username: 'root',
    password: '',

    // the sql dialect of the database
    // - currently supported: 'mysql', 'sqlite', 'postgres', 'mariadb'
    dialect: 'sqlite',

    // custom host; default: 127.0.0.1
    host: '127.0.0.1',

    // custom port; default: 3306
    port: 3306,

    // use pooling in order to reduce db connection overload and to increase speed
    // currently only for mysql and postgresql (since v1.5.0)
    pool: {
      maxConnections: 10,
      minConnections: 0,
      maxIdleTime: 30000
    },

    // the storage engine for 'sqlite'
    // default store into ~/.cnpmjs.org/data.sqlite
    storage: path.join(dataDir, 'data.sqlite'),

    logging: !!process.env.SQL_DEBUG,
  },

**Comment by louiszhu2zgf** [comment]
@dead-horse,请问cnpmjs是默认使用sqlite的对吧，我看网上有很多教程说如果默认是sqlite不用建表？我在mac上测试部署的时候也遇到了这个问题

**Comment by dead-horse** [comment]
sqlite 也要建表，建表的 SQL：https://github.com/cnpm/cnpmjs.org/blob/master/docs/db.sql

**Comment by louiszhu2zgf** [comment]
这个应该是mysql的语法，sqlite需要做一些更改的吧

**Comment by packjs** [comment]
我用的linux centos

**Comment by jerossh** [comment]
同步一下就好，看见你用 Sequelize ，建好表的时候 sync 一下就可以了

**Comment by meikidd** [comment]
是没有建表，官方文档的配置默认使用 sqllite，但没有说要先执行一步建表 
```
node ./models/init_script.js
```

**Comment by newsn** [comment]
大家看看makefile里面的脚本，也许就有收获哦。我执行了里面的make init-database就ok了。

**Comment by nicklv** [comment]
@meikidd 就是这位大兄弟说的问题。所以，文档有点坑人。
可以在dockerfile里面调整下，通过启动传参进来，如果是sqlite，就执行下node ./models/init_script.js
