### ISSUE TITLE
如何通过修改数据库强制授权?

### ISSUE THREAD

**Issue by stoneChen** [cnpm/cnpmjs.org#1137]
有个包的主人离职了，当初忘了交接这个包。
如果交接的时候，记得的话，可以通过`npm owner add <new ower name>`来授权给接手的人。
请问，有什么办法可以通过修改mysql，强制修改包的owner么？

**Comment by fengmk2** [comment]
管理员可以加 owner

**Comment by whilefor** [comment]
cnpm owner add <user> [<@scope>/]<pkg> 提示成功了，owner ls还是没有。

**Comment by fengmk2** [comment]
owner ls {packagename}

**Comment by whilefor** [comment]
@fengmk2 添加显示成功之后，owner ls {packagename}，没有添加成功

**Comment by fengmk2** [comment]
将执行的命令和返回提示都截图发上来看看，感觉你没有操作正确。

**Comment by whilefor** [comment]
![0e372cc1-97cd-4129-b44f-dd3c5a4d7593](https://cloud.githubusercontent.com/assets/5251462/23548902/a45091a6-0044-11e7-917b-bb0528a4525e.png)

**Comment by stoneChen** [comment]
可以了，谢谢
<img width="561" alt="qq20170303-191530 2x" src="https://cloud.githubusercontent.com/assets/4470552/23549182/dfbd6452-0045-11e7-9d55-f5c605fc0b33.png">
ps: 我的当前项目.npmrc是指向公司cnpm服务器的。所以直接用npm命令就行了，registry也不用指定。

**Comment by whilefor** [comment]
mac下也尝试按照wiki里面的安装， 然后使用添加owner无效。（管理员账号，没有scope情况下）
