### ISSUE TITLE
node-inspector 镜像好像好久都没更新了？

### ISSUE THREAD

**Issue by tomoat** [cnpm/cnpmjs.org#1147]
node-inspector 镜像: https://npm.taobao.org/mirrors/node-inspector/

**Comment by fengmk2** [comment]
node 已经内置了，不需要这个模块了吧 https://github.com/node-inspector/node-inspector#overview

**Comment by tomoat** [comment]
有些模块有依赖它，安装的时候报错，亚马逊的地址下载不了。。。。
