### ISSUE TITLE
support `the abbreviated package metadata document`

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#1148]
https://github.com/npm/registry/pull/143

**Comment by soldair** [comment]
we dont have this document in a changes stream yet. not sure what the timeline is there. thanks for reminding me to bring it up though :)

I use https://github.com/soldair/minify-registry-metadata to shrink full size docs down to the spec but another process altogether to find out if the tars have shrinkwraps.

**Comment by fengmk2** [comment]
Yep, the `_hasShrinkwrap` is the key point!

**Comment by soldair** [comment]
its also an order of magnitude smaller for lots of modules. both gzipped and uncompressed
