### ISSUE TITLE
cnpm and the public userdata endpoint

### ISSUE THREAD

**Issue by soldair** [cnpm/cnpmjs.org#1154]
i'm just curious in what contexts cnpm might send these requests.
`/-/user/org.couchdb.user:username`

we added some rate limiting logic and cnpm traffic is of a shape and rate that it should never be effected i just want to make sure =)

**Comment by fengmk2** [comment]
registry.cnpmjs.org registry will sync user info when the user not in our database. So it won't be a lot of requests.

https://github.com/cnpm/cnpmjs.org/blob/2daa34faab9b61891775e163645fb27b9f7d5add/controllers/sync_module_worker.js#L429

**Comment by soldair** [comment]
ok thanks.
