### ISSUE TITLE
能否删除nfs文件夹？

### ISSUE THREAD

**Issue by yanyu0517** [cnpm/cnpmjs.org#1159]
900G的硬盘，已经100%了，现在cnpm完全用不了了，能否删除nfs文件夹呢？然后重新sync呢？

**Comment by fengmk2** [comment]
npm registry 目前大小已经长到2T了，你单机磁盘装不下的话，不建议开启完全同步模式，只开启 exists 模式即可。

**Comment by yanyu0517** [comment]
恩，我之前确实是完全同步模式，硬盘感觉装不下了。那我能够直接rm掉nfs文件夹，然后开启exists模式重新sync吗？

**Comment by fengmk2** [comment]
你得将数据库也删除了才行，因为是否同步是依赖数据库的记录来决定的。你要小心不要删除了内部模块。

**Comment by yanyu0517** [comment]
请问需要清空数据库中的哪些表？

**Comment by fengmk2** [comment]
你的私有模块还需要保留吗？不需要保留的话，建议你新创建 db，这样出问题了还能切回来

**Comment by yanyu0517** [comment]
了解了，非常感谢

**Comment by wmzy** [comment]
@fengmk2 如果有私有模块呢?私有模块能否单独存储/备份?
