### ISSUE TITLE
在同一个 scope 下既有私有包也有 npmjs 的公开包，可以吗？

### ISSUE THREAD

**Issue by hbrls** [cnpm/cnpmjs.org#1171]
`npmjs` 最近放开了组织名注册，可以免费放公开包。

那么如果我想 `@company/private` 在公司内架设的 `cnpmjs` 上可以搜和装，`@company/public` 通过公司内架设的 `cnpmjs` 代理到 `npmjs`，这样可以吗？`privatePackages` 是做这个用处的吗？

*代理我是指  `syncModel: 'none'`*

**Comment by taoqf** [comment]
我也想这样做?可以吗?

**Comment by taoqf** [comment]
我是想把原来放在npm上的公共包更新成cnpm上的私有包,发现无论如何修改配置文件,都无法做到.发布时出错:`forbidden user`

**Comment by alsotang** [comment]
应该是不行的。一个scope如果是公司私有的，就不会在404的时候再去上游拉东西了。
建议公司的私有scope取一个独特的名字，然后所有包放这个下面，最大程度避免混乱。
