### ISSUE TITLE
config/index.js文件有问题

### ISSUE THREAD

**Issue by YardWill** [cnpm/cnpmjs.org#1176]
![image](https://cloud.githubusercontent.com/assets/16497201/26090054/e1a4ec26-3a34-11e7-88cc-31d971fde6b2.png)
这个路径应该为cnpm.org吧

**Comment by Asher-Tan** [comment]
不是的。这个目录是放数据的，package文件之类的。和代码放一块不好。

**Comment by YardWill** [comment]
挺奇怪的 我部署了两台机器，一台需要改成'cnpmjs.org' config文件才能生效，一台直接clone就能部署，暂时还没搞清楚问题出现在哪里。
