### ISSUE TITLE
cnpm error ,what??????

### ISSUE THREAD

**Issue by ghost** [cnpm/cnpmjs.org#1178]
$ cnpm install
Get /binary-mirror-config/latest from https://registry.npm.taobao.org error: Err                     or: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
[npminstall:get] retry GET https://registry.npm.taobao.org/vue/%3E%3D2.2.1%20%3C                     3.0.0 after 100ms, retry left 4, error: ResponseError: socket hang up (req "erro                     r"), GET https://registry.npm.taobao.org/vue/%3E%3D2.2.1%20%3C3.0.0 -1 (connecte                     d: true, keepalive socket: false, agent status: {"createSocketCount":14,"createS                     ocketErrorCount":0,"closeSocketCount":4,"errorSocketCount":0,"timeoutSocketCount                     ":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npm.taobao.org:443:::                     ::::false:":10},"requests":{}})
headers: {}
platform unsupported babel-loader@6.4.1 › webpack@2.5.1 › watchpack@1.3.1 › chokidar@1.7.0 › fsevents@^1.0.0 Package require os(darwin) not compatible with your platform(win32)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(win32)
√ Installed 19 packages
√ Linked 579 latest versions
Cached binary found at C:\Users\Administrator\.npminstall_tarball\node-sass\4.5.3\win32-x64-48_binding.node
Binary found at C:\Users\Administrator\Desktop\hybridapp\haoshiqi\node_modules\_node-sass@4.5.3@node-sass\vendor\win32-x64-48\binding.node
Testing binary
Binary is fine
√ Run 1 scripts
Recently updated (since 2017-05-15): 20 packages (detail see file C:\Users\Administrator\Desktop\hybridapp\haoshiqi\node_modules\.recently_updates.txt)
  Today:
    → css-loader@0.25.0 › postcss-modules-scope@^1.0.0(1.1.0) (06:55:57)
    → css-loader@0.25.0 › postcss-modules-local-by-default@^1.0.1(1.2.0) (06:54:26)
    → css-loader@0.25.0 › postcss-modules-extract-imports@^1.0.0(1.1.0) (06:56:43)
    → css-loader@0.25.0 › postcss-modules-values@^1.1.0(1.3.0) (06:58:41)
    → css-loader@0.25.0 › postcss-modules-values@1.3.0 › icss-replace-symbols@^1.1.0(1.1.0) (06:57:36)
    → sass-loader@5.0.1 › async@^2.0.1(2.4.1) (11:57:15)
√ All packages installed (637 packages installed from npm registry, used 47s, speed 24.9kB/s, json 706(1.15MB), tarball 0B)

**Comment by Fantasy9527** [comment]
我也碰到了同样的问题
