### ISSUE TITLE
Nexus Repository Manager 不能正常连接自建npm服务

### ISSUE THREAD

**Issue by Arnosir** [cnpm/cnpmjs.org#1179]
Nexus Repositories 
用 https://registry.npm.taobao.org/ 可以正常使用
而用自建的 https://xxx.company.com/ 则不能使用。
![image](https://cloud.githubusercontent.com/assets/8611744/26335594/93a1374e-3f9f-11e7-89e5-b899aab9e449.png)

注：
命令行通过npm 指定--registry  可以正常使用自建源
自建源的 sync_model是‘exist’
自建源版本：cnpmjs.org-2.19.4

**Comment by hbrls** [comment]
这个截图不是 maven 么

**Comment by Arnosir** [comment]
@hbrls https://www.sonatype.com/nexus-repository-oss

**Comment by Arnosir** [comment]
已找到原因。
java中缺乏对沃通证书的信任，所以需要把证书加入到信任中，并强制 ```Use certificates stored in the Nexus truststore to connect to external systems```
另外，sync_model 为exist的情况，使用Nexus Repository Manager过程会有很多WARN/ERROR，但不影响使用。
