### ISSUE TITLE
docker-compose up

### ISSUE THREAD

**Issue by zhaochenglan** [cnpm/cnpmjs.org#1200]
npm http request GET https://registry.npm.taobao.org/sequelize
npm info attempt registry request try #1 at 5:58:21 AM
npm http request GET https://registry.npm.taobao.org/thunkify-wrap
npm info attempt registry request try #1 at 5:58:21 AM
npm http request GET https://registry.npm.taobao.org/treekill
npm info attempt registry request try #1 at 5:58:21 AM
npm http request GET https://registry.npm.taobao.org/tunnel-agent
npm info attempt registry request try #1 at 5:58:21 AM
npm http request GET https://registry.npm.taobao.org/urllib
npm info attempt registry request try #1 at 5:58:21 AM
npm http request GET https://registry.npm.taobao.org/utility
npm info attempt registry request try #1 at 5:58:21 AM
npm http request GET https://registry.npm.taobao.org/xss
npm info retry will retry, error on last attempt: Error: connect ENETUNREACH 114.55.80.225:443

**Comment by rhinoceros** [comment]
你用的容器网络是不是ipv6;
参考一下：
https://github.com/npm/npm/issues/6857
https://github.com/nodejs/node/issues/6307
