### ISSUE TITLE
部署好私有cnpm后发布模块再安装报错

### ISSUE THREAD

**Issue by Asher-Tan** [cnpm/cnpmjs.org#1203]
大佬们，部署好cnpm后可以发布模块，但是再安装会报错找不到依赖模块，
![_ _20170727122607](https://user-images.githubusercontent.com/6188453/28654506-7d0413a2-72c7-11e7-88da-e380e3c92315.png)

而且我看私有库上的模块数量也很少，
![_ _20170727122858](https://user-images.githubusercontent.com/6188453/28654561-e347062e-72c7-11e7-888c-97060183fbd4.png)

**Comment by ZengTianShengZ** [comment]
./congif.js 下需要修改一下配置文件
```
   // registry url name（模块下载请求地址，必须设置）
   registryHost: '127.0.0.1:7001',
```
