### ISSUE TITLE
cnpm adduser 之后，.cnpmrc文件中没有authToken

### ISSUE THREAD

**Issue by lhang** [cnpm/cnpmjs.org#1204]
我需要在GitlabCI中配置自动发布到cnpm的脚本，但是发现在权限这里有些问题，npm中登录之后是有authToken可以配置CI的，在cnpm中应该怎么处理呢。

**Comment by chengjianhua** [comment]
@lhang 最后有解决这个问题吗 ?

打扰下 ~ @fengmk2 

想请教下, 即使没有这个 authToken, 有什么比较好的方法在 CI 中登录到私服么 ?

**Comment by lhang** [comment]
@chengjianhua 最后的解决方法是把,cnpmrc的文件放到gitlab CI的变量里，然后在跑任务的时候直接输出到项目目录里，可以直接登录

**Comment by chengjianhua** [comment]
@lhang 这个方法测试了可以, 谢谢啦 ~ 之前我用了一种比较 hack 的方式来输入登录信息 ...

**Comment by zxbin2000** [comment]
@lhang 请教下你是怎么解决的呢，我在 script 脚本里，加变量好像也不起作用

`  
script:
    - echo 'registry=http://npm-registry.***.com/' > .npmrc
    - echo '//npm-registry.***.com/:_password=***' > .npmrc
    - echo '//npm-registry.***.com/:username=admin' > .npmrc
    - echo '//npm-registry.***.com/:email=zxb@***.com' > .npmrc
    - echo '//npm-registry.***.com/:always-auth=false' > .npmrc
    - semantic-release-gitlab || true
`

**Comment by lhang** [comment]
@zxbin2000 这样应该也没问题，检查一下你这么输出之后格式是否正确吧
