### ISSUE TITLE
atom-shell缺乏更新

### ISSUE THREAD

**Issue by yhostc** [cnpm/cnpmjs.org#1206]
atom-shell项目目前只能更新到3月份的v1.6.5版本，之后的新版本都无法更新到资源。

我检查了亚马逊的源，确实比较难找入口去正确下载到新版本的内容。但是建议CNPM增加手工同步指定项目版本的方法或能力，感谢！

**Comment by keyiis** [comment]
最近升级项目碰到同样的问题

**Comment by mtaa** [comment]
同样+1

**Comment by fengmk2** [comment]
请问如何重现你说反馈的问题？

**Comment by Sean-214** [comment]
@fengmk2 electron-rebuild新版本的electron已经无法使用这个镜像了

> 见网站https://npm.taobao.org/mirrors的Usage
> electron-rebuild -d=http://npm.taobao.org/mirrors/atom-shell

**Comment by alsotang** [comment]
@Sean-214 https://npm.taobao.org/mirrors/electron/  这个可以用吗？

**Comment by alsotang** [comment]
如果你能直接提 pr 更好： https://github.com/cnpm/mirrors/blob/master/views/home.html

**Comment by Sean-214** [comment]
@alsotang 有时候下载的就比较费劲了，还是很需要一个镜像的。
```
gyp http GET https://atom.io/download/electron/v4.0.1/win-x86/node.lib
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 54.231.49.48:443
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
```

**Comment by alsotang** [comment]
同步失败主要是 https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/index.json 这个文件拉不动。我看看怎么替代这个逻辑

**Comment by alsotang** [comment]
https://github.com/electron/electron/search?q=atom-shell%2Fdist&unscoped_q=atom-shell%2Fdist
看了看。electron跟这个atom-shell还是有关系的，所以照着原来的逻辑修复了一下。
https://github.com/cnpm/mirrors/pull/212

**Comment by alsotang** [comment]
@Sean-214 再试试，应该好了。

**Comment by Sean-214** [comment]
@alsotang 可以了，非常感谢！！！

**Comment by Constaline** [comment]
atom-shell 镜像目前只更新到19年10月份的 v7.0.0-beta.7 版本，后续的新版本都没有更新。
