### ISSUE TITLE
代理貌似有问题

### ISSUE THREAD

**Issue by pengfeiWang** [cnpm/cnpmjs.org#1209]
```
node 7
npm 4
mac os
cnpmjs.org 2.19.4
```
因公司网络限制, 想链接外网必须使用代理, 我本机网络是有代理的

本地环境 `.npmrc`  在无代理与有代理情况下分别做了测试
在 `cnpmjs/config` 下无代理与有代理情况下分别做了测试
`cnpmjs/config` 
`httpProxy: http://user:pass@proxy.com:8080`

都会出现问题, 问题分别是 `407`, `Sync packages from official registry failed` , `Error message is RequestError: connect ETIMEDOUT 114.55.80.225:443 (req "error")`

```
Sync Error
Sync packages from official registry failed.
Start sync time is Mon Jul 31 2017 14:55:28 GMT+0800 (CST).
Error message is RequestError: connect ETIMEDOUT 114.55.80.225:443 (req "error"), GET https://registry.npm.taobao.org/-/short -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":1,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npm.taobao.org:443:::::::::":1},"requests":{}})
headers: {} (sync package error)
Error: connect ETIMEDOUT 114.55.80.225:443
at Object.exports._errnoException (util.js:1050:11)
at exports._exceptionWithHostPort (util.js:1073:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14).
```

**Comment by fengmk2** [comment]
是的，代理的问题需要等 https://github.com/node-modules/urllib/pull/226 合并发布后，我才能彻底解决。

**Comment by loveatting** [comment]
我也碰到了这个问题，会在后面的版本解决么？要是往前的话，能告知下哪个版本是OK的么？

**Comment by fengmk2** [comment]
代理功能目前还不够稳定，我也没有真实环境可以部署测试。

**Comment by 4garfield** [comment]
finally, found this issue about the proxy error...

let me describe my error:
1. environment:
```
node v8.11.1
npm 6.0.0
cnpmjs.org 3.0.0-beta.1
```
2. issue description
my server & local machine has different proxy settings, whatever set proxy mode to `none` or `exist`, the local proxy will just request https://registry.npm.taobao.org and get an 407 error.

Here, there are serveral issues about the proxy settings:
* the internal cnpmjs server cannot direct sync packages from https://registry.npm.taobao.org. and no error logs when using web interface http://localhost:7002/sync/connect to sync
* local machine cannot use cnpmjs server proxy to connect https://registry.npm.taobao.org, it always use  local proxy, which respond 407

**Comment by zyqshanshui** [comment]
@pengfeiWang

请问这个问题解决了么。我也遇到了相同的问题。

**Comment by pengfeiWang** [comment]
@zyqshanshui  https://github.com/cnpm/cnpmjs.org/pull/1303
