### ISSUE TITLE
如何灵活的切换cnpmjs库

### ISSUE THREAD

**Issue by mygaochunming** [cnpm/cnpmjs.org#1217]
我安装了两个cnpmjs库，其中一个测试库ip：91，一个正式库ip：92

我想在开发的时候，把测试内容发布到测试库上，测试通过了发布到正式库中。

目前我是这样做的：

测试：
1、基础库：npm login --registry://192.168.88.91:7001 --scope=@hd
     登录后，npm publish 发布
2、应用侧：npm login --registry://192.168.88.91:7001 --scope=@hd
     登陆后，npm update @hd/ui
     启动项目测试基础库的组件。

正式发布：
1、基础库：npm login --registry://192.168.88.92:7001 --scope=@hd
     登录后，npm publish 发布
2、应用侧：npm login --registry://192.168.88.92:7001 --scope=@hd
     登陆后，npm update @hd/ui
     启动项目。

这样挺费劲，有什么办法我在package.json中写个命令，类似：
基础库：
publish：npm publish --registry://192.168.88.92:7001
publish-test：npm publish --registry://192.168.88.91:7001

应用侧：
update：npm update--registry://192.168.88.92:7001
update-test：npm update --registry://192.168.88.91:7001

**Comment by ijse** [comment]
你是要这个么？
https://docs.npmjs.com/files/package.json#publishconfig

或者其实一个库就可以了，通过配置semver规则来实现
