### ISSUE TITLE
integrity checksum failed when using sha1: wanted ... but got ...

### ISSUE THREAD

**Issue by tedtse** [cnpm/cnpmjs.org#1218]
按照 Deploy a private npm registry in 5 minutes 的步骤安装之后可以正常发布，
但是本地安装会报这个错误“ **integrity checksum failed when using sha1: wanted ... but got ...**  ”
config/index.js 中的 registryHost 已改为本地地址(http://127.0.0.1:7001/)

**Comment by pre1ude** [comment]
if you have package-lock.json generated by using the official NPM registry it will create a shashum and if you change the registry on the next npm i you should also remove package-lock.json and regenerate it.
