### ISSUE TITLE
2.19.4版本forcePublishWithScope配置无效

### ISSUE THREAD

**Issue by stoneChen** [cnpm/cnpmjs.org#1221]
关于forcePublishWithScope的文档说明，已经是2014年7月的了，不知是否功能改过了而文档没有更新。

2.12.2版本即使管理员也不能发布不带scope的包，这应该是合理的。

2.19.4版本的表现是：
普通登陆用户，只能发布带scope前缀的包(无论服务端是否设置了`scopes`字段),
管理员用户，可以发布任意名字的包，包括带scope和不带scope的包。

而2.19.4版本的表现，表示不理解。

**Comment by fengmk2** [comment]
只有配置来 https://github.com/cnpm/cnpmjs.org/blob/master/config/index.js#L155 `privatePackages` 参数的模块，才能不带 scope 的，其他情况一定要带 scope 才能发布，不管管理员还是普通用户。

**Comment by stoneChen** [comment]
@fengmk2 莫非是我哪里姿势不对么？我是用`cnpmjs.org`全局命令起的服务。刚又做了个测试，我确认没有配置`privatePackages`字段：
<img width="600" alt="cli 2x" src="https://user-images.githubusercontent.com/4470552/30013317-77ffd56a-9178-11e7-8471-8e4b901b066a.png">
![qq20170904-135155](https://user-images.githubusercontent.com/4470552/30013327-7ff17198-9178-11e7-89e8-af428d7c486e.png)

**Comment by fengmk2** [comment]
那就是代码有bug了

**Comment by stoneChen** [comment]
囧，不过暂时可以通过设置`enablePrivate: false`，降低影响面，只要管理员别乱来就行。
另外，还有个停服命令的问题，请关注一下我提的PR，谢谢~
快速通道：https://github.com/cnpm/cnpmjs.org/pull/1220

**Comment by zhump** [comment]
@stoneChen  https://github.com/cnpm/cnpmjs.org/issues/1262
能帮忙看看吗？版本 3.0.0-alpha.16

**Comment by AntSworD** [comment]
我发现如果没有配置 forcePublishWithScope 同样不能推非 scope  的模块包，全局搜索也没看到对应配置的代码，是文档陈旧了么

**Comment by stoneChen** [comment]
@zhump 我是通过新建`cnpmjs.org/config/config.js`来设置配置的(最终会覆盖隔壁的index.js配置)，附上我的配置(敏感信息已屏蔽)：
```js
module.exports = {
    debug: false,
    scopes: [
      "@xxx"
    ],
    enableCluster: true, // enable cluster mode
    enablePrivate: false, // enable private mode, only admin can publish, other use just can sync package from source npm
    enableCompress: true,
    syncModel: 'exist', // 'none', 'all', 'exist', 推荐exist模式
    registryHost: '',
    database: {
        db: 'cnpmjs',
        username: 'xxx',
        password: 'xxx',
        dialect: 'mysql', // 这句是重点
        host: 'localhost',
        port: 3306, // mysql默认端口
        pool: {
          maxConnections: 10,
          minConnections: 0,
          maxIdleTime: 30000
        },
        logging: false  // 不打印数据库log日志
    },
    admins: {
      xxx: 'yyy@zzz.com' // 邮箱没有其他相关逻辑，可随意指定
    },
  };
```

数据库与cnpmjs.org服务在同一台机器。
如果不涉及新老cnpmjs.org服务scope包同步问题，以上配置可以比较良好的运行。
如果涉及同步问题，就比较折腾了，可以参考 https://github.com/cnpm/cnpm/issues/222  ，请做好心理准备，过程很坎坷。

@AntSworD 『如果没有配置 forcePublishWithScope 同样不能推非 scope 的模块包』是这样的。
我是希望设置`forcePublishWithScope: true`之后, 连admin也不能发布scope的包。
不过目前，只有我是管理员，我自己自觉就好，其他人是只能发布scope的包，也算可以规避这个问题。
