### ISSUE TITLE
Path must be a string, but received undefined

### ISSUE THREAD

**Issue by weihomechen** [cnpm/cnpmjs.org#1222]
你好，node环境下使用了forever，应用挂了之后会尝试重启，重启失败报了下图的错误：
![image](https://user-images.githubusercontent.com/16172317/30030540-6a26468e-91c0-11e7-9115-9a3a3bcf8155.png)

似乎是这个函数path.join方法报的错？还请各位解解惑，谢谢～
![image](https://user-images.githubusercontent.com/16172317/30030715-21d62876-91c1-11e7-8de0-d020fe79dd3c.png)

**Comment by ibigbug** [comment]
`export HOME=/root/` 试试？
