### ISSUE TITLE
发布缓慢

### ISSUE THREAD

**Issue by BlackSkyJY** [cnpm/cnpmjs.org#1225]
发布一个组件需要2分钟，请问有什么参数可以提高发布速率吗？

**Comment by ibigbug** [comment]
是不是你的组件包含了二进制文件或者其他大文件？或者网速太慢？

**Comment by BlackSkyJY** [comment]
嗯，我们改了一下服务器内存提升为12G，速度就上去了

**Comment by ibigbug** [comment]
是服务器内存到瓶颈了? 可以配上监控。
