### ISSUE TITLE
同步 extract-loader 失败

### ISSUE THREAD

**Issue by anhulife** [cnpm/cnpmjs.org#1226]
[同步日志](https://npm.taobao.org/sync/extract-loader#logid=6739932)

**Comment by ibigbug** [comment]
看上去是这个[包(https://replicate.npmjs.com/extract-loader)]没有 maintainers 信息  https://github.com/cnpm/cnpmjs.org/blob/master/controllers/sync_module_worker.js#L1323

**Comment by anhulife** [comment]
嗯，是的。

不过[这块代码](https://github.com/cnpm/cnpmjs.org/blob/master/controllers/sync_module_worker.js#L1323)可以优化，增加`sourcePackage.maintainers `不为空的判断。

**Comment by fengmk2** [comment]
fixed by 95aa035a275089b50dfc2590497e3bc7319f4f6b

**Comment by fengmk2** [comment]
https://npm.taobao.org/sync/extract-loader#logid=1000098 重新同步成功。还追加了一个修复才成功 bfb29f82c967cb68f4de3a314200d95a8c59baff
