### ISSUE TITLE
希望添加 chromium 镜像源

### ISSUE THREAD

**Issue by Cap32** [cnpm/cnpmjs.org#1246]
对不起，这不是一条 issue，但实在找不到提交建议的渠道。

新版本的 [puppeteer](https://github.com/GoogleChrome/puppeteer/) 将支持通过配置环境变量 [PUPPETEER_DOWNLOAD_HOST](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#environment-variables)  来定义下载源，目前官方源在大陆实在十分令人感到抓狂。

希望采纳，十分感谢。

**Comment by chikara-chan** [comment]
+1

**Comment by fengmk2** [comment]
我看看。

**Comment by fengmk2** [comment]
已经配置了一个代理，请使用 https://storage.googleapis.com.cnpmjs.org

```js
PUPPETEER_DOWNLOAD_HOST=https://storage.googleapis.com.cnpmjs.org npm i puppeteer
```

**Comment by fengmk2** [comment]
cnpm i  puppeteer 现在也会去代理自动下载了。

**Comment by yandongxu** [comment]
https://storage.googleapis.com.cnpmjs.org 挂了？

```
MissingSecurityHeaderYour request was missing a required header.Authorization
```

**Comment by SAOSO** [comment]
ERROR: Failed to download Chromium r526987! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: Download failed: server returned code 404. URL: https://cdn.npm.taobao.org/dist/chromium-browser-snapshots/Win_x64/526987/chrome-win32.zip
    at response (E:\code\PuppeteerDemo\node_modules\_puppeteer@1.0.0@puppeteer\lib\Downloader.js:228:21)
    at ClientRequest.require.request.res (E:\code\PuppeteerDemo\node_modules\_puppeteer@1.0.0@puppeteer\lib\Downloader.js:279:7)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:549:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:438:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
× Install fail! Error: post install error, please remove node_modules before re
try!
Run "C:\Windows\system32\cmd.exe /d /s /c node install.js" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "C:\Windows\system32\cmd.exe /d /s /c node install.js" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\admin.DESKTOP-S4PVBPA\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:74:21)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npminstall version: 3.3.0
npminstall args: C:\Program Files\nodejs\node.exe C:\Users\admin.DESKTOP-S4PVBPA\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --userconfig=C:\Users\admin.DESKTOP-S4PVBPA\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://registry.npm.taobao.org puppeteer --save

**Comment by vc1** [comment]
@SAOSO  可以设置环境变量然后用npm安装
```bash
PUPPETEER_DOWNLOAD_HOST=https://storage.googleapis.com.cnpmjs.org
npm i puppeteer
```

**Comment by fwh1990** [comment]
如果使用`npm config set`的形式。key必须是小写的。（一直用PUPPETEER_DOWNLOAD_HOST，被坑了好久）

```js

npm config set puppeteer_download_host=https://storage.googleapis.com.cnpmjs.org

```

**Comment by meathill** [comment]
@fwh1990 This works for me, under Windows 10 cmd.

**Comment by poppinlp** [comment]
@fengmk2 
Hi，请问相关代理是出现问题了么？今天发现安装的过程下载 chromium 的速度很慢，连还是每次都能稳定连上。之前使用起来是很快的。
我这里 ping storage.googleapis.com.cnpmjs.org 出来是一个来自澳大利亚的 IP。
辛苦，谢谢。

**Comment by DiamondYuan** [comment]
现在要用 https://npm.taobao.org/mirrors 这个地址

**Comment by vv314** [comment]
这么设置，亲测可用
```
npm config set puppeteer_download_host=https://npm.taobao.org/mirrors
```

**Comment by NicholasNC** [comment]
我比较习惯用 yarn 安装

一开始没有换源之前，安装不了，一直卡在：
![image](https://user-images.githubusercontent.com/10840542/54249502-63d97380-457b-11e9-86dc-b14d6495d93b.png)

更换源之后（`yarn config set registry https://registry.npm.taobao.org`），可以安装
不过命令行报了一些小提示（可以运行，不影响）：
![image](https://user-images.githubusercontent.com/10840542/54249597-b024b380-457b-11e9-9fa8-67f45dce2664.png)

只是不甘心（有点洁癖），执行 `yarn config set puppeteer_download_host=https://npm.taobao.org/mirrors`后重新安装，不过结果还是同上

**但是**，直接用 cnpm 安装就没有问题

**Comment by NickeyLin** [comment]
@NicholasNC 你应该是写错了。 `yarn` 应该这样设置：`yarn config set puppeteer_download_host https://npm.taobao.org/mirrors`。空格，不是等号。

**Comment by cnscorpions** [comment]
> 这么设置，亲测可用
> 
> ```
> npm config set puppeteer_download_host=https://npm.taobao.org/mirrors
> ```

换了源之后，yarn安装就可以了

**Comment by liudonghua123** [comment]
`npm config set puppeteer_download_host=https://npm.taobao.org/mirrors` works like a charm :haha
More details, see https://github.com/GoogleChrome/puppeteer/blob/master/install.js#L36

**Comment by zksfyz** [comment]
> 这么设置，亲测可用
> 
> ```
> npm config set puppeteer_download_host=https://npm.taobao.org/mirrors
> ```

已经流水线执行过，可行，非常优秀。

**Comment by fengmk2** [comment]
请使用新的域名

```bash
npm config set puppeteer_download_host=https://npmmirror.com/mirrors/
```
