### ISSUE TITLE
如何使用nexus3.6与cnpm建立代理仓库

### ISSUE THREAD

**Issue by wanliyunyan** [cnpm/cnpmjs.org#1249]
依照这个文档[https://help.sonatype.com/display/NXRM3/Quick+Start+Guide+-+Proxying+Maven+and+NPM](url)我可以正确建立关于npm的代理仓库，然后当我把其中的远程url 换成registry.npm.taobao.org，之后cnpm config set registry http://localhost:8081/repository/npm-proxy，生成cnpmrc文件，执行cnpm i antd命令报错，错误如下

C:\Users\css\1>cnpm i antd
- [npminstall:get] retry GET http://localhost:8081/repository/antd after 100ms, retry left 4, error: SyntaxError: Unexpected token < in JSON at position 1
[npminstall:get] retry GET http://localhost:8081/repository/antd after 200ms, retry left 3, error: SyntaxError: Unexpected token < in JSON at position 1
| [0/1] Installing antd@^2.13.9[npminstall:get] retry GET http://localhost:8081/repository/antd after 300ms, retry left 2, error: SyntaxError: Unexpected token < in JSON at position 1
- [0/1] Installing antd@^2.13.9[npminstall:get] retry GET http://localhost:8081/repository/antd after 400ms, retry left 1, error: SyntaxError: Unexpected token < in JSON at position 1
× Install fail! SyntaxError: Unexpected token < in JSON at position 1
SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at _get (C:\Users\css\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\get.js:70:26)
    at _get.next (<anonymous>)
    at onFulfilled (C:\Users\css\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npminstall version: 3.2.1
npminstall args: D:\Program Files\nodejs\node.exe C:\Users\css\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --userconfig=C:\Users\css\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://localhost:8081/repository/cnpm-proxy antd

请问是我的配置错了吗，问题怎么解决呢？？？

**Comment by wanliyunyan** [comment]
挑上 Use certificates stored in the Nexus truststore to connect to external systems 这个就好了，就可以用了

**Comment by 12d** [comment]
你的解决了吗，我也遇到了同样的问题

**Comment by wanliyunyan** [comment]
@12d 我不都回答了吗，挑上那个checkbox就好了
