### ISSUE TITLE
SQLITE3_BINARY_SITE 无效

### ISSUE THREAD

**Issue by yanxyz** [cnpm/cnpmjs.org#1250]
[mirrors](https://npm.taobao.org/mirrors) 页面说 

```sh
SQLITE3_BINARY_SITE=http://npm.taobao.org/mirrors/sqlite3 npm install sqlite3
```

不过我这里始终从 s3.amazonaws.com 下载 binary。

翻看了一下源码， node-pre-gyp [versioning.js](https://github.com/mapbox/node-pre-gyp/blob/master/lib/util/versioning.js#L303)，这么做

```sh
npm install sqlite3 --node_sqlite3_binary_host_mirror=http://npm.taobao.org/mirrors
```

结果成功。

`SQLITE3_BINARY_SITE`  来自哪里呢？

我的系统环境

- win10 x64
- Node.js v8.9.1 
- npm v5.5.1

**Comment by codertony** [comment]
楼主正解，亲测可行
淘宝镜像是不是没人维护了，不给答案，至少维护一下https://npm.taobao.org/mirrors的文档呀。
全网都是从这个文档copy出来的错误方案

**Comment by codertony** [comment]
楼主正解，亲测可行
淘宝镜像是不是没人维护了，不给正面回复，至少维护一下 [mirrors](https://npm.taobao.org/mirrors)的文档呀。
全网都是从这个文档copy出来的错误方案

**Comment by fengmk2** [comment]
cnpmjs.org 是开源项目，欢迎大家提交 pr 修复问题。

**Comment by codertony** [comment]
https://npm.taobao.org/mirrors  这个网站的文件，代码里有没有呀。就是维护一下文档的事。

**Comment by codertony** [comment]
[PR已提](https://github.com/cnpm/mirrors/pull/222)
