### ISSUE TITLE
已经有半年没有和官方库同步了，大量npm包缺失

### ISSUE THREAD

**Issue by clockfly** [cnpm/cnpmjs.org#1255]
FROM: https://cnpmjs.org/

Sync Status

This registry will sync all packages from official registry.

Last sync time is Thu _# **Jun 22 2017**_ 19:59:54 GMT+0800 (CST).

检查代码:
1. http://registry.npmjs.org/@jupyterlab%2fvdom-extension
最新版本是0.12.0
2. https://r.cnpmjs.org/@jupyterlab%2fvdom-extension 最新版本是0.11.1

**Comment by iunfire** [comment]
我也遇到了这个问题

**Comment by fengmk2** [comment]
用 https://npm.taobao.org/
