### ISSUE TITLE
npm >= v5.5.0 login 已经不使用email字段了

### ISSUE THREAD

**Issue by wmzy** [cnpm/cnpmjs.org#1275]
https://github.com/cnpm/cnpmjs.org/blob/5e264beba9f06370b562729cbfbcc526a0767949/controllers/registry/user/add.js#L54
https://github.com/npm/npm/blob/v5.5.0/lib/auth/legacy.js#L23

导致cnpm登录失败.而且server响应422 cnpm并不报错,还不确定这是不是npm的bug.

**Comment by vhtml** [comment]
我也是刚发现这个问题，只能说cnpm更新慢了点，只能自己改了

**Comment by fengmk2** [comment]
使用的是最新版本的 cnpm？

**Comment by wmzy** [comment]
@fengmk2 是的,看我上面贴的代码.

**Comment by fengmk2** [comment]
但是它异常了还会使用 email 来重试一次 https://github.com/npm/npm/blob/v5.5.0/lib/auth/legacy.js#L25

**Comment by wmzy** [comment]
但是它好像并不抛异常: https://github.com/npm/npm-profile/blob/npm-profile/v2.0.5/lib/index.js#L233

**Comment by AntSworD** [comment]
npm@5.6.0 npm-profile@2.0.5 会出现用错误密码显示成功登录，或者 adduser 失败也显示成功创建并登录

npm@5.5.1 npm-profile@2.0.4 可以成功登录
原因正是像 @wmzy  说的那里在 npm-profile@2.0.5 中失败不抛异常，npm-profile@2.0.4 是正常抛出的

可以用 dockerhub 镜像 node:8.9.4 和 node:8.9.0 两个复现出这个差异

不知道现在这个问题应该在哪边进行修复， @fengmk2 你们有计划么

**Comment by gssify** [comment]
重新安装 4.5.1 版本即可

**Comment by SwenChan** [comment]
最近也在搭建私有仓库, 但是一直```npm adduser```失败
关于修复的问题, npm的issue [issues#6126](https://github.com/npm/npm/issues/6126), 似乎一直是搁置状态, 所以....... @fengmk2 有计划吗.

**Comment by fengmk2** [comment]
@SwenChan @wmzy 是否能帮助我们解决问题？可以提交 pr 修复。

**Comment by wmzy** [comment]
@fengmk2 可以，我已经在我们私有仓库里临时hack了这个问题，给我点时间我熟悉一下cnpm的代码，然后提pr给你们。

**Comment by SwenChan** [comment]
关键是准备在哪一端修复这个问题. 是在client (cnpm or npm)端还是在server (cnpm.org)端
cnpm.org我能想到的一个适应客户端方法是返回一个npm能识别到的异常, 例如400, 虽然不符合语义, 但是这样能让npm和cnpm都不用做改动.
另外一个方法, cnpm里面限制一定要输入email要不然就报错呗, 但是npm, yarn用户就没法用了, 只能用cnpm了.
以上两种解决方法两位怎么看? @fengmk2 @wmzy

**Comment by AntSworD** [comment]
@fengmk2 @wmzy @SwenChan 最新的 npm-profile 已经修复这个问题了，能正常抛出非 2xx 报错了
[commit history](https://github.com/npm/npm-profile/commit/6a439a39f42ff86c8b3d93076a775075cec1f30b#diff-6d186b954a58d5bb740f73d84fe39073)

**Comment by wmzy** [comment]
@AntSworD 并没有发 hotfix 版本，可能是要跟新版的npm一起发吧。我之前给他们提过这个[issue](https://github.com/npm/npm/issues/19424)，好像不被关注。

即便客户端能抛出非2xx错误，也不应该每次login都要重试一遍，所以这对cnpm来说依然是个bug。

@SwenChan 我们用了`customUserSerivce`,所以只要把email的验证去掉就好了.如果你们没有用到，可以把错误响应里的`error`字段去掉，具体可以参考上面的pr。另外关于400和422状态码的语义问题，[这里](https://stackoverflow.com/questions/16133923/400-vs-422-response-to-post-of-data)是有争议的。

**Comment by SwenChan** [comment]
谢谢指教~我这边是用了hack了addUser里面的返回, 就是上面我提到返回一个400错误, 因为我这边认为还是需要限制一下email的. 那现在就等你这个pr合并我就更新一下版本就行了.

**Comment by fengmk2** [comment]
![](https://i.loli.net/2018/03/10/5aa39fe31c799.jpg)
