### ISSUE TITLE
gulp-cli 同步错误

### ISSUE THREAD

**Issue by gucong3000** [cnpm/cnpmjs.org#1277]
http://registry.npmjs.com/gulp-cli
官网最新版本为2.0.0
```json
"dist-tags": {
  "latest": "2.0.0"
},
```

http://registry.npm.taobao.org/gulp-cli
镜像中最新版本为1.4.0
```json
"dist-tags": {
  "latest": "1.4.0"
},
```

**Comment by Shawyeok** [comment]
是否尝试过使用cnpm手动同步一下？
```
$ cnpm sync gulp-cli --registry=your-registry-url
```

若同步失败可以把同步的日志贴出来看一下。

**Comment by gucong3000** [comment]
没有装cnpm客户端，访问如下url后恢复正常
https://npm.taobao.org/sync/gulp-cli
