### ISSUE TITLE
npm ERR! no_perms only allow publish with @test-company scope(s): compression

### ISSUE THREAD

**Issue by baoendemao** [cnpm/cnpmjs.org#1285]
问题1:   可不可以不指定scope上传包？
问题2：mynpm install 上传的前端vue工程，发现在工程目录前套了两层目录node_modules/@test-company，这个有办法解决吗，如何避免套这么多层目录结构？

**Comment by yoyayoyayoya** [comment]
你不要指定scope不就行了
