### ISSUE TITLE
npm ERR! publish Failed PUT 401

### ISSUE THREAD

**Issue by guoleisong** [cnpm/cnpmjs.org#1291]
E:\>npm login
Username: admin
Password:
Email: (this IS public) admin@example.org
Logged in as admin on http://localhost:8081/repository/cnpm/.

E:\>npm publish test
npm ERR! publish Failed PUT 401
npm ERR! code E401
npm ERR! 404 401 Unauthorized

npm ERR! A complete log of this run can be found in:
npm ERR!     E:\node\node_cache\_logs\2018-01-23T07_08_14_055Z-debug.log

**Comment by gssify** [comment]
```
npm uninstall -g cnpm
npm install -g cnpm@4.5.1 
// >=5 的版本用的 npm 版本都是 5.6.0
```
相关问题 #1275

**Comment by qq76319973** [comment]
@guoleisong 相同问题，请问兄弟是怎么解决的？

**Comment by nihaoye** [comment]
看看数据库的user表里面有没有admin这条记录，没有应该就不行的，可以跑一下test目录下的init_db.js初始化一下user表，看的懂源码的话自己写一个adduser方法加上admin也可以，然后在config/index.js里面的admins属性添加对应的user表里的名字就可以了

**Comment by jpuncle** [comment]
升级 npm 版本即可，貌似只有 npm@5.6.0 存在这个问题
