### ISSUE TITLE
最新版本安装一直报错误，没有配置sqlite，一直报这个错误

### ISSUE THREAD

**Issue by wenshan** [cnpm/cnpmjs.org#1292]
Error: expected { error: 'no_perms',
  reason: 'Private mode enable, only admin can publish this module' } response body, got { error: 'SequelizeDatabaseError',
  reason: 'SQLITE_ERROR: no such table: user' }
      + expected - actual

       {
      -  "error": "SequelizeDatabaseError"
      -  "reason": "SQLITE_ERROR: no such table: user"
      +  "error": "no_perms"
      +  "reason": "Private mode enable, only admin can publish this module"
       }

**Comment by SwenChan** [comment]
你的db是不是mysql? 启动的时候有没有初始化db?
