### ISSUE TITLE
alwaysAuth 问题

### ISSUE THREAD

**Issue by linxuanwei** [cnpm/cnpmjs.org#1294]
当我设置   alwaysAuth=true 后, 启动 cnpm 

cnpm install 时会进行权限验证

我用admin登录  但是cnpm install 依然返回401

请问,  我应该怎样设置我账户的 authToken 或者有什么办法可以使我依然可以方便的使用cnpm install 命令安装私有的库

**Comment by qq76319973** [comment]
同问，希望得到解答，谢谢！

**Comment by qq76319973** [comment]
enablePrivate:false，这个属性设置成false也无济于事，我是npm publish的时候报401权限问题
