### ISSUE TITLE
如何处理https?

### ISSUE THREAD

**Issue by wuchuguang** [cnpm/cnpmjs.org#1313]
npm run start后，
localhost:7001
localhost:7002
都正常了。
npm config set register localhost:7001
后，
npm install --save mysql2无法install
报：
$ npm install --save mysql2
npm ERR! Only HTTP(S) protocols are supported

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wuchuguang/.npm/_logs/2018-04-06T08_16_37_511Z-debug.log

**Comment by wrannaman** [comment]
http://localhost:7001
