### ISSUE TITLE
npm ERR! publish Failed PUT 401

### ISSUE THREAD

**Issue by qq76319973** [cnpm/cnpmjs.org#1320]
用的是admin登录的，用普通账号也不行，并且密码随便输入会提示登录成功能解决下吗？谢谢。完整的报错如下：
qiujianhuadeMacBook-Air:cm-helloworld qiujianhua$ npm publish
npm ERR! publish Failed PUT 401
npm ERR! code E401
npm ERR! 404 unauthorized Login first: cm-helloworld
npm ERR! 404 
npm ERR! 404  'cm-helloworld' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/qiujianhua/.npm/_logs/2018-04-10T01_04_29_735Z-debug.log

**Comment by qq76319973** [comment]
@fengmk2 求助大神

**Comment by popomore** [comment]
npm login

**Comment by qq76319973** [comment]
@popomore 登录了，显示登录成功，但发布总是报这个错误

**Comment by qq76319973** [comment]
可能是防火墙引起的
