### ISSUE TITLE
npm私有包同步需要哪些mysql权限？

### ISSUE THREAD

**Issue by qq76319973** [cnpm/cnpmjs.org#1321]
在企业搭建npm私有库，可同步不了包，考虑是权限问题，公司提供的是一个权限很少的数据库账号，现在提申请流程扩充数据库账号权限，所以我要知道npm私有包同步需要哪些mysql权限，谢谢。
具体账号提供的权限如下：
GRANT USAGE ON *.* TO 'cnpmopr'@'%'                               |
GRANT SELECT, INSERT, UPDATE, DELETE ON `cnpm`.* TO 'cnpmopr'@'%'

**Comment by qq76319973** [comment]
@fengmk2 大神，可以帮帮我吗？饭碗要丢了

**Comment by fengmk2** [comment]
读写权限。
