### ISSUE TITLE
企业内网服务器采用代理的方式能同步包吗？

### ISSUE THREAD

**Issue by qq76319973** [cnpm/cnpmjs.org#1322]
如题，企业内网服务器采用代理的方式通外网能同步下载包吗？求救 @fengmk2

**Comment by qq76319973** [comment]
@fengmk2 可以帮忙解答一下吗？今天要搞定这个npm同步工作才不会死的很惨

**Comment by fengmk2** [comment]
不行，目前不支持这种方式。

**Comment by hihl** [comment]
@qq76319973 给机器设置全局代理不行么？

**Comment by johnsonGong** [comment]
> 不行，目前不支持这种方式。

那 同步到本地的公共库源代码，又有什么意义呢？
