### ISSUE TITLE
请问如何清理cnpm中的包，并同时刷新数据库？

### ISSUE THREAD

**Issue by gohonsen** [cnpm/cnpmjs.org#1326]
cnpm空间满了，想把不用的包或过期版本清理掉，请问该如何清理 ？

**Comment by gohonsen** [comment]
@qinmeifang  你清了数据库，是不是又重新同步了呀；如果数据库中信息存在，磁盘上没对应的文件，cnpm不会重新同步，就会下载失败

**Comment by qinmeifang** [comment]
关键我得私有包都能下载下来

**Comment by fengmk2** [comment]
不建议放磁盘存储，可以参考 https://github.com/cnpm/npm.taobao.org 的代码，使用 oss 存储。
