### ISSUE TITLE
registry.npm.taobao.org 是不是挂了？

### ISSUE THREAD

**Issue by pfdgithub** [cnpm/cnpmjs.org#1328]
今天 2018-05-02 从杭州访问 registry.npm.taobao.org 间歇性 200 500 502 504
杭州电信和移动 4G 都会出现，有没有其他人遇到？

**Comment by Colin6618** [comment]
+1 

![image](https://user-images.githubusercontent.com/3047309/39514309-730a5670-4e29-11e8-9ce7-d4864fde3263.png)

**Comment by pfdgithub** [comment]
看来真出问题了，暂时使用 npm 应急。
现在淘宝的 npm 镜像已经成了国内的前端基础设施了。
感觉维护工作应该转交给响应的的组织，避免大面积服务不可用。

**Comment by fengmk2** [comment]
我们已经在第一时间接收到监控报警并接入排查问题和修复。
已经安排好数据库扩容。
