### ISSUE TITLE
同步模式none，all，exist方式都不适用

### ISSUE THREAD

**Issue by guowei1651** [cnpm/cnpmjs.org#1330]
环境搭建好同步了5天了，然后界面上提示同步了17%。磁盘使用情况如下：
`/dev/sda2       1.7T  639G  929G  41% /data`

同步模式配置为：
`syncModel:'all'`

现在发现使用exist模式根本就不同步，使用all模式我计算了一下同步完成需要3.6T，使用none方式又不适用我们现在情况。

有什么办法可以解决这种情况吗？

**Comment by guowei1651** [comment]
顶一下

**Comment by qinmeifang** [comment]
我使用的是exist确实会同步项目使用到的包，但是项目跑的时候很占用内存。
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
26941 root      20   0 1528844 394448   8876 R 104.3 10.2  31:24.23 node
