### ISSUE TITLE
在window上搭建`process.env.HOME` 找不到值报错

### ISSUE THREAD

**Issue by zwwtj2014** [cnpm/cnpmjs.org#1348]
下面两处代码，`process.env.HOME` 在window下取不到值，导致在给join方法传参的时候抛异常，可以考虑有`os.homedir()` 取代吗？

https://github.com/cnpm/cnpmjs.org/blob/master/bin/cli.js#L54
`var dataDir = options.dataDir || path.join(process.env.HOME, '.cnpmjs.org');`

https://github.com/cnpm/cnpmjs.org/blob/master/bin/cli.js#L97
`var dataDir = options.dataDir || path.join(process.env.HOME, '.cnpmjs.org');`

**Comment by rhinoceros** [comment]
可以考虑在环境变量中设置HOME
```bat
set HOME=%USERPROFILE%
npm run start
```
