### ISSUE TITLE
Add tables definition for postgres

### ISSUE THREAD

**Issue by k-miras** [cnpm/cnpmjs.org#1356]
Rewrite ```docs/db.sql``` for postgres or allow sequelize generate tables

**Comment by ibigbug** [comment]
isn't this what you need ? https://github.com/cnpm/cnpmjs.org/tree/master/models

**Comment by k-miras** [comment]
@ibigbug  not exactly - if database doesn't have this tables, cnpmjs.org throws error and nothing works. But there is table definitions at ```docs/db.sql``` - it is valid only for mysql
