### ISSUE TITLE
求教：cnpm本地测试发布包都正常，但是无法install

### ISSUE THREAD

**Issue by qinmeifang** [cnpm/cnpmjs.org#1360]
⠸ [0/1] Installing @test/hello@*[@test/hello@1.0.0] download ResponseError: socket hang up, GET https://cnpmjs.oss-ap-southeast-1.aliyuncs.com/%40test/hello/-/%40test/hello-1.0.0.tgz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":6,"createSocketErrorCount":0,"closeSocketCount":6,"errorSocketCount":0,"timeoutSocketCount":6,"requestCount":2,"freeSockets":{},"sockets":{},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}, fail count: 3
✖ Install fail! ResponseError: socket hang up, GET https://cnpmjs.oss-ap-southeast-1.aliyuncs.com/%40test/hello/-/%40test/hello-1.0.0.tgz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":6,"createSocketErrorCount":0,"closeSocketCount":6,"errorSocketCount":0,"timeoutSocketCount":6,"requestCount":2,"freeSockets":{},"sockets":{},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
ResponseError: socket hang up, GET https://cnpmjs.oss-ap-southeast-1.aliyuncs.com/%40test/hello/-/%40test/hello-1.0.0.tgz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":6,"createSocketErrorCount":0,"closeSocketCount":6,"errorSocketCount":0,"timeoutSocketCount":6,"requestCount":2,"freeSockets":{},"sockets":{},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
    at createHangUpError (_http_client.js:329:15)
    at TLSSocket.socketCloseListener (_http_client.js:361:23)
    at emitOne (events.js:120:20)
    at TLSSocket.emit (events.js:210:7)
    at _handle.close (net.js:547:12)
    at TCP.done [as _onclose] (_tls_wrap.js:356:7)

找到一个和我类似的iisue，不过他的是下载第三方包，是同步的问题。但是我连本地私有的都下载不了。

**Comment by qinmeifang** [comment]
尝试了重新搭建，也不行

**Comment by qinmeifang** [comment]
这个问题我最后解决了。直接拉的Git的代码有问题。去下载release的包就可以了

**Comment by rhinoceros** [comment]
和代码关系不大吧。 把 registryHost: '改成你的注册服务器的地址',就可以了。
```
  // registry url name
  // registryHost: 'r.cnpmjs.org',
  // registryHost: '改成你的注册服务器的地址',
registryHost: '127.0.0.1:7001'
```
