### ISSUE TITLE
启动包7001和7002端口有问题

### ISSUE THREAD

**Issue by xiaqun** [cnpm/cnpmjs.org#1361]
启动的时候端口和进程都是有有的，日志里面显示如下的错误，不能正常同步包
Starting cnpmjs.org ...
cluster: false
admins: {"fengmk2":"fengmk2@gmail.com","admin":"admin@cnpmjs.org","dead_horse":"dead_horse@qq.com"}
scopes: ["@cnpm","@cnpmtest","@cnpm-test"]
sourceNpmRegistry: https://registry.npm.taobao.org
syncModel: all
[Tue Jul 17 2018 18:55:47 GMT+0800 (CST)] [worker:27744] Server started, registry server listen at undefined:7001, web listen at undefined:7002, cluster: false
[Tue Jul 17 2018 18:55:47 GMT+0800 (CST)] [sync_worker:27744] syncing with all mode, changesStreamingSync: undefined

**Comment by rhinoceros** [comment]
```
# 提供更多的日志信息，是不能同步所有包吗？还是个别包。
# 你可以在浏览器打开页面： server_ip:7002 
#       https://server_ip:7002 /browse/keyword/rockey-react
#       搜索一个你需要的包，然后执行SYNC试试
```
