### ISSUE TITLE
Leaking package author email address to pubic

### ISSUE THREAD

**Issue by ankurk91** [cnpm/cnpmjs.org#1373]
Hi there.

The website https://cnpmjs.org is leaking package author's email addresses to pubic. Bots can scrape the site and can spam easily.

Take this example https://cnpmjs.org/~yyx990803
If you view source `view-source:https://cnpmjs.org/~yyx990803` of the page; you will find that email address is visible and has not been obfuscated.

Email addresses are also visible to Google (see screenshot)
![screenshot from 2018-08-19 09 23 16](https://user-images.githubusercontent.com/6111524/44305290-a0e8d900-a391-11e8-8aed-5957249bd676.png)

You should have been using packages like:
https://www.npmjs.com/package/obfooscator
Obfuscate strings ensure that spam bots can not harvest them.

The official npmjs site does not show email address at all. See
https://www.npmjs.com/~yyx990803

Thanks.

**Comment by fengmk2** [comment]
OK, I will change it as soon as possible. Thanks!

**Comment by fengmk2** [comment]
But stil can get email from the npm registry, like mine: http://registry.npmjs.com/-/user/org.couchdb.user:fengmk2

**Comment by ankurk91** [comment]
There are several other ways to find user email id, for example GitHub commit history.

I can submit a PR if you want.
I think i would only need to change the lines

https://github.com/cnpm/cnpmjs.org/blob/bd87907b69d3e65aa544930b5c7f04e75bdbc773/controllers/web/user/show.js#L37
and
https://github.com/cnpm/cnpmjs.org/blob/bd87907b69d3e65aa544930b5c7f04e75bdbc773/view/web/profile.html#L17
