### ISSUE TITLE
如何查看某一个包的同步记录

### ISSUE THREAD

**Issue by yanyu0517** [cnpm/cnpmjs.org#1378]
问题描述：
yarn安装时，有一个包安装报错，yarn.lock中记录的hash与仓库里的hash不符合，报错如下：

`error http://172.16.116.19:7001/capture-stack-trace/download/capture-stack-trace-1.0.1.tgz: Fetch succeeded for undefined. However, extracting "http://172.16.116.19:7001/capture-stack-trace/download/capture-stack-trace-1.0.1.tgz" resulted in hash "a6c0bbe1f38f3aa0b92238ecb6ff42c344d4135d", which did not match the requested hash "ed0a1edb87c05d4db1037c5f8f483d8a3b5f0825".
`
请问怎么能够在仓库里查找到这个包的同步记录呢？我想定位下到底是什么问题

**Comment by fengmk2** [comment]
将 yarn.lock 删除了重新建即可。

**Comment by fengmk2** [comment]
也将你的 http://172.16.116.19:7001/capture-stack-trace/download/capture-stack-trace-1.0.1.tgz 文件删除了重新同步。

**Comment by yanyu0517** [comment]
恩，是的，但是我想了解下这个问题是怎么引入的
我觉得应该是在自开始yarn install的时候计算包的hash错误了，所以想追一下这个包的同步记录

**Comment by yanyu0517** [comment]
不知道是否可以查到某一个具体包的同步记录

**Comment by rhinoceros** [comment]
```

# 直接查数据库
#-----
select * from `module_log`  where `name` = 'capture-stack-trace' LIMIT 0,50;


#查日志：
#-----
ls ~/.cnpmjs.org/logs/sync_*
grep -rI capture-stack-trace ~/.cnpmjs.org/logs/sync_* |more
##（默认日志路径：~/.cnpmjs.org/logs，除非你配置过config/index.js， 中的 dataDir 或者  logdir）
```

**Comment by saysmy** [comment]
lock文件里每个#后的hash值是模块内容的hash值么？为什么会出现yarn.lock中记录的hash与仓库里的hash不符合的问题呢

**Comment by saysmy** [comment]
好的~~收到~~
