### ISSUE TITLE
包已经发布上去，并且能搜索出来，但是详细页面打不开，也不能获取

### ISSUE THREAD

**Issue by BubbleLeaf** [cnpm/cnpmjs.org#1395]
问题如上图所示：
![image](https://user-images.githubusercontent.com/16011072/46928557-c29ecd80-d06d-11e8-93db-a8aad0bed4e4.png)
![image](https://user-images.githubusercontent.com/16011072/46928567-d5190700-d06d-11e8-9334-973705993514.png)

**Comment by rhinoceros** [comment]
```
/*

包的名称，
发布包的命令，
检查一下发布时设置的registry
      npm get registry
      或者
      cnpm get registry
搜索出来的页面url和截图，
详细页面对应的url和打不开的截图，

*/
```

**Comment by BubbleLeaf** [comment]
谢谢解答，经过重新安装之后解决，估计是一开始尝试5分钟部署的教程留下的问题
