### ISSUE TITLE
cnpmjs启动后 无法成功安装依赖

### ISSUE THREAD

**Issue by nsuedu** [cnpm/cnpmjs.org#1397]
前置条件:
1. 操作系统:centos7

实际结果
通过 node dispatch.js 启动后出现报错
sync package from official registry failed.......Error  message is Error :can not find total info ...

**Comment by rhinoceros** [comment]
贴一下：config/index.js 中 sync configs
```
/**
   * sync configs
   */

  // the official npm registry
  // cnpm wont directly sync from this one
  // but sometimes will request it for some package infomations
  // please don't change it if not necessary
  officialNpmRegistry: 'https://registry.npmjs.com',
  officialNpmReplicate: 'https://replicate.npmjs.com',

  // sync source, upstream registry
  // If you want to directly sync from official npm's registry
  // please drop them an email first
  sourceNpmRegistry: 'https://registry.npm.taobao.org',
  sourceNpmWeb: 'https://npm.taobao.org',

  // upstream registry is base on cnpm/cnpmjs.org or not
  // if your upstream is official npm registry, please turn it off
  sourceNpmRegistryIsCNpm: true,

  // if install return 404, try to sync from source registry
  syncByInstall: true,

  // sync mode select
  // none: do not sync any module, proxy all public modules from sourceNpmRegistry
  // exist: only sync exist modules
  // all: sync all modules
  syncModel: 'none', // 'none', 'all', 'exist'

  syncConcurrency: 1,
  // sync interval, default is 10 minutes
  syncInterval: '10m',

  // sync polular modules, default to false
  // because cnpm can't auto sync tag change for now
  // so we want to sync popular modules to ensure their tags
  syncPopular: false,
  syncPopularInterval: '1h',
  // top 100
  topPopular: 100,

  // sync devDependencies or not, default is false
  syncDevDependencies: false,
  // try to remove all deleted versions from original registry
  syncDeletedVersions: true,

  // changes streaming sync
  syncChangesStream: false,
  handleSyncRegistry: 'http://127.0.0.1:7001',
```

**Comment by nsuedu** [comment]
但是还是有一个问题 💇 : 我install  依赖的时候总是提示找不到一些依赖
我的配置如下
```
'use strict';

var mkdirp = require('mkdirp');
var copy = require('copy-to');
var path = require('path');
var fs = require('fs');
var os = require('os');

var version = require('../package.json').version;

var root = path.dirname(__dirname);
var dataDir = path.join(process.env.HOME || root, '.cnpmjs.org');

var config = {
   enableAbbreviatedMetadata:true,	
  version: version,
  dataDir: dataDir,


  enableCluster: false,
  numCPUs: os.cpus().length,


  registryPort: 7001,
  webPort: 7002,
   bindingHost:'0.0.0.0',	



  debug: process.env.NODE_ENV === 'development',

  pagemock: process.env.NODE_ENV === 'development',
 
  sessionSecret: 'cnpmjs.org test session secret',
 
  jsonLimit: '10mb',
 
  logdir: path.join(dataDir, 'logs'),
 
  uploadDir: path.join(dataDir, 'downloads'),

  viewCache: false,


  limit: {
    enable: false,
    token: 'koa-limit:download',
    limit: 1000,
    interval: 1000 * 60 * 60 * 24,
    whiteList: [],
    blackList: [],
    message: 'request frequency limited, any question, please contact fengmk2@gmail.com',
  },

  enableCompress: false,

 
  admins: {
    admin: 'admin@standata.org',
  },


  mail: {
    enable: false,
    appname: 'cnpmjs.org',
    from: 'cnpmjs.org mail sender <adderss@gmail.com>',
    service: 'gmail',
    auth: {
      user: 'address@gmail.com',
      pass: 'your password'
    }
  },

  logoURL: 'https://os.alipayobjects.com/rmsportal/oygxuIUkkrRccUz.jpg',
  adBanner: '',
  customReadmeFile: '',
  customFooter: '', 
  npmClientName: 'cnpm',
  packagePageContributorSearch: true, 

 
  maxDependencies: 200,
  
  backupFilePrefix: '/cnpm/backup/',


  database: {
    db: 'cnpmjs',
    username: 'standata',
    password: 'stand123',
    dialect: 'mysql',
    host: '192.168.30.236',
    port: 3306,
    pool: {
      maxConnections: 10,
      minConnections: 0,
      maxIdleTime: 30000
    },
    storage: path.join(dataDir, 'data.sqlite'),
    logging: !!process.env.SQL_DEBUG,
  },
  nfs: require('fs-cnpm')({
    dir: path.join(dataDir, 'nfs')
  }),
  downloadRedirectToNFS: false,
  registryHost: '127.0.0.1:7001',

  enablePrivate: false,


  scopes: [ '@cnpm', '@cnpmtest', '@cnpm-test' ],


  privatePackages: [],

  officialNpmRegistry: 'https://registry.npmjs.com',
  officialNpmReplicate: 'https://replicate.npmjs.com',


  sourceNpmRegistry: 'https://registry.npm.taobao.org',
sourceNpmWeb:'https://npm.taobao.org',	


  sourceNpmRegistryIsCNpm: true,


  syncByInstall: true,


  syncModel: 'exist', 

  syncConcurrency: 1,

  syncInterval: '10m',


  syncPopular: false,
  syncPopularInterval: '1h',
 
  topPopular: 100,


  syncDevDependencies: false,

  
  syncChangesStream: false,
  handleSyncRegistry: 'http://127.0.0.1:7001',


  badgePrefixURL: 'https://img.shields.io/badge',
  badgeSubject: 'cnpm',

  userService: null,


  alwaysAuth: false,


  httpProxy: null,

  
  snykUrl: 'https://snyk.io',
};

if (process.env.NODE_ENV !== 'test') {
  var customConfig;
  if (process.env.NODE_ENV === 'development') {
    customConfig = path.join(root, 'config', 'config.js');
  } else {
    customConfig = path.join(dataDir, 'config.json');
    if (!fs.existsSync(customConfig)) {
      customConfig = path.join(root, 'config', 'config.js');
    }
  }
  if (fs.existsSync(customConfig)) {
    copy(require(customConfig)).override(config);
  }
}

mkdirp.sync(config.logdir);
mkdirp.sync(config.uploadDir);

module.exports = config;

config.loadConfig = function (customConfig) {
  if (!customConfig) {
    return;
  }
  copy(customConfig).override(config);
};

```

**Comment by rhinoceros** [comment]
数据库密码都贴出来了，改改吧。。

**Comment by nsuedu** [comment]
改了  🈂️ （  ，，大佬可以帮我看看么

**Comment by rhinoceros** [comment]
1. install 依赖的时候总是提示找不到一些依赖
  这个的输出贴一下

2. 在服务器上看一下日志吧：
~/.cnpmjs.org/logs

**Comment by nsuedu** [comment]
--------------------------------------------报错信息
[root@cxcs cnpmjs.org]# npm config set registry http://127.0.0.1:7001
[root@cxcs cnpmjs.org]# npm install -g umi
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @types/react@^16.0.27
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'umi'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-19T02_40_55_468Z-debug.log


--------------------------------------------------------日志信息
018-10-19 09:04:26.933 nodejs.TypeErrorException: TypeError: Cannot read property 'last_exist_sync_time' of null
    at checkSyncStatus (/usr/local/node-v8/lib/node_modules/cnpmjs.org/sync/index.js:200:26)
    at checkSyncStatus.next (<anonymous>)
    at onFulfilled (/usr/local/node-v8/lib/node_modules/cnpmjs.org/node_modules/_co@4.6.0@co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
pid: 14609
Host: cxcs
URL:
Data: ''
2018-10-19 09:04:26.933
2018-10-19 09:04:26.934 nodejs.TypeErrorException: TypeError: Cannot read property 'last_exist_sync_time' of null
    at checkSyncStatus (/usr/local/node-v8/lib/node_modules/cnpmjs.org/sync/index.js:200:26)
    at checkSyncStatus.next (<anonymous>)
    at onFulfilled (/usr/local/node-v8/lib/node_modules/cnpmjs.org/node_modules/_co@4.6.0@co/index.js:65:19)
    at <anonymous>
pid: 14609
Host: cxcs
URL:
Data: ''
2018-10-19 09:04:26.934
2018-10-19 09:08:03.464 nodejs.TypeErrorException: TypeError: Cannot read property 'last_exist_sync_time' of null
    at checkSyncStatus (/usr/local/node-v8/lib/node_modules/cnpmjs.org/sync/index.js:200:26)
    at checkSyncStatus.next (<anonymous>)
    at onFulfilled (/usr/local/node-v8/lib/node_modules/cnpmjs.org/node_modules/_co@4.6.0@co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
pid: 18511
Host: cxcs
URL:
Data: ''
2018-10-19 09:08:03.464
2018-10-19 09:08:03.465 nodejs.TypeErrorException: TypeError: Cannot read property 'last_exist_sync_time' of null
    at checkSyncStatus (/usr/local/node-v8/lib/node_modules/cnpmjs.org/sync/index.js:200:26)
    at checkSyncStatus.next (<anonymous>)
    at onFulfilled (/usr/local/node-v8/lib/node_modules/cnpmjs.org/node_modules/_co@4.6.0@co/index.js:65:19)
    at <anonymous>
pid: 18511
Host: cxcs
URL:
Data: ''
2018-10-19 09:08:03.465
2018-10-19 09:11:50.706 nodejs.TypeErrorException: TypeError: Cannot read property 'last_exist_sync_time' of null
    at checkSyncStatus (/usr/local/node-v8/lib/node_modules/cnpmjs.org/sync/index.js:200:26)
    at checkSyncStatus.next (<anonymous>)
    at onFulfilled (/usr/local/node-v8/lib/node_modules/cnpmjs.org/node_modules/_co@4.6.0@co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
pid: 21776
Host: cxcs
URL:
Data: ''
2018-10-19 09:11:50.706
2018-10-19 09:11:50.713 nodejs.TypeErrorException: TypeError: Cannot read property 'last_exist_sync_time' of null
    at checkSyncStatus (/usr/local/node-v8/lib/node_modules/cnpmjs.org/sync/index.js:200:26)
    at checkSyncStatus.next (<anonymous>)
    at onFulfilled (/usr/local/node-v8/lib/node_modules/cnpmjs.org/node_modules/_co@4.6.0@co/index.js:65:19)
    at <anonymous>
pid: 21776
Host: cxcs
URL:
Data: ''
2018-10-19 09:11:50.713
2018-10-19 09:13:21.521 nodejs.TypeErrorException: TypeError: Cannot read property 'last_exist_sync_time' of null
    at checkSyncStatus (/usr/local/node-v8/lib/node_modules/cnpmjs.org/sync/index.js:200:26)
    at checkSyncStatus.next (<anonymous>)
    at onFulfilled (/usr/local/node-v8/lib/node_modules/cnpmjs.org/node_modules/_co@4.6.0@co/index.js:65:19)
    at <anonymous>

**Comment by rhinoceros** [comment]
数据库有问题。
你是新安装的吗？
你查查你的数据库中有total表吗？

**Comment by nsuedu** [comment]
是通过npm install cnpmjs.org -g 安装的， 数据库也有total表，但是没有数据

**Comment by rhinoceros** [comment]
个人建议你用这个方式换个主机，新建个数据库重装吧：
https://github.com/cnpm/cnpmjs.org/wiki/Deploy

**Comment by rhinoceros** [comment]
total表 中有字段last_exist_sync_time吗

**Comment by nsuedu** [comment]
total表 存在字段last_exist_sync_time

**Comment by rhinoceros** [comment]
> total表 存在字段last_exist_sync_time
你安装后，显示的版本是多少？

**Comment by rhinoceros** [comment]
默认会在total表中插入一条记录，目前看没有这条默认的记录。
你停止一下服务，清理一下日志文件（移动到其他地方），然后启动服务，再看看这几个日志中是否有数据库相关的错误；
--------
error.2018-10-19.log
sync_error.2018-10-19.log
sync_info.2018-10-19.log

**Comment by nsuedu** [comment]
大佬可以帮我看看日志吗? 日志地址在这里:https://github.com/nsuedu/reading_notes

**Comment by rhinoceros** [comment]
把db备份一下，重新执行一下数据库脚本吧。
https://github.com/cnpm/cnpmjs.org/blob/2.19.4/docs/db.sql
看样子是你的db有问题，没有默认的total记录
![image](https://user-images.githubusercontent.com/512834/47265242-7d8c0700-d557-11e8-84b4-4469c0a83443.png)

**Comment by rhinoceros** [comment]
@nsuedu  你的问题解决了吗
