### ISSUE TITLE
after 100ms, retry left 4, error: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by SnowFlowers** [cnpm/cnpmjs.org#1398]
每次 cnpm install 的时候，总会有这个报错，但是最后却又成功了，中间非常耗时，想问一下这个是什么问题。

**Comment by SnowFlowers** [comment]
![image](https://user-images.githubusercontent.com/16875486/47165889-8dc09e00-d32d-11e8-8113-4983269d1e53.png)

**Comment by rhinoceros** [comment]
试试
```
npm install  --registry=http://192.168.92.24:7001 
```

----
https://github.com/cnpm/cnpm/issues/54#issuecomment-101299085
```
Unexpected end of JSON input： 
按 npm ERR! SyntaxError: Unexpected end of input 错误信息看来，是这个包的 json 信息没用下载完整
```

**Comment by SnowFlowers** [comment]
@rhinoceros 为什么会出现这种问题呢，是cnpm私库服务出问题了吗，而且，下载的retry error之后，重试的仓库怎么写到 https://registry.npm.taobao.com呢，我对了每个config/index下面的配置，没有发现这个配置项，现在还是默认的npm仓库

**Comment by rhinoceros** [comment]
npm install  --registry=http://192.168.92.24:7001 
能执行成功吗？

**Comment by rhinoceros** [comment]
我最近在熟悉cnpmjs.org 也是初学者，有的地方也不清楚；

我们也用cnpm install，有时候会报错，但npm install会成功。

**Comment by sunxiuguo** [comment]
遇到了同样的问题。
查看了一下，这种报错的包package.json都是空的，而且有好多这种包
