### ISSUE TITLE
配置的https，yarn安装的时候找到的tgz包是http

### ISSUE THREAD

**Issue by nigelvon** [cnpm/cnpmjs.org#1408]
npm安装没有问题，通过yarn安装报错
error An unexpected error occurred: "http://registry.npm.xxx.com/@aaa-bbb/ccc/download/@aaa-bbb/ccc-1.0.0.tgz: Request failed \"404 Not Found\"".

暂时通过http301跳转https解决

**Comment by rhinoceros** [comment]
> > 查一下是不是有yarn.lock, yarn.lock中会锁定地址。
> 
> yarn.lock中的地址也是cnpmjs.org服务返的吧。

yarn.lock已经锁定的地址 和 cnpmjs.org没关系。
你编辑一下你的yarn.lock看看地址是不是 http://registry.npm.xxx.com/@aaa-bbb/ccc/download/@aaa-bbb/ccc-1.0.0.tgz

**Comment by nigelvon** [comment]
> > > 查一下是不是有yarn.lock, yarn.lock中会锁定地址。
> > 
> > 
> > yarn.lock中的地址也是cnpmjs.org服务返的吧。
> 
> yarn.lock已经锁定的地址 和 cnpmjs.org没关系。
> 你编辑一下你的yarn.lock看看地址是不是 http://registry.npm.xxx.com/@aaa-bbb/ccc/download/@aaa-bbb/ccc-1.0.0.tgz

咱俩说的好像不是一个维度的问题？既然会报这个错，yarn.lock当然是这个地址了。这是第一次安装的时候从registry服务上拉取的。删了lock重新装也还会是这个地址。

**Comment by rhinoceros** [comment]
执行一下，看看输出：
npm get regsitry
yarn config list

**Comment by nigelvon** [comment]
> yarn config list

出错的信息里包的registry服务器是对的。唯一错的只有https->http
配置里的都是https，确认了没错

**Comment by rhinoceros** [comment]
我是在SLB（以前是nginx）上配置的https。
不清楚你是怎么配置的？
