### ISSUE TITLE
compress 逻辑位置提升

### ISSUE THREAD

**Issue by alsotang** [cnpm/cnpmjs.org#1412]
![image](https://user-images.githubusercontent.com/1147375/49066801-359a8700-f25d-11e8-95db-2ed12d6e7424.png)
https://github.com/cnpm/cnpmjs.org/blob/769af76c732aa1cff905f9425a2571abfa8b96e6/servers/registry.js#L34-L46

这个地方，compress逻辑应该放到notFound之前。

我今天在处理 `flatmap-steam` 这个包的时候，发现 registry 这边不能正确返回 404 的请求。
http://r.tnpm.oa.com/flatmap-stream 。当 request 不声明接受 gzip 时，返回是正确的；当接受时，返回是gzip解压错误 `curl: (61) Error while processing content unencoding: invalid distance too far back` 。

虽然 notFound 里面有个判断  body.name 的逻辑，但我怀疑这个 body 由于已经被 compress 组件消费过了，所以这个判断没有生效。

----

我很奇怪为何 https://r.cnpmjs.org/flatmap-stream 可以正确返回？

**Comment by alsotang** [comment]
从原理上来说， compress也应该是放在最接近入口处。现在这种写法，会有几率在 compress 处理完成后，继续设置 header 和 body

**Comment by fengmk2** [comment]
@alsotang enableCompress 功能没开启过，都使用 nginx 的。

**Comment by alsotang** [comment]
还是合一下吧？改动很小
