### ISSUE TITLE
能否推出官方docker镜像？

### ISSUE THREAD

**Issue by snowdream** [cnpm/cnpmjs.org#1416]
类似： https://hub.docker.com/r/hbrls/cnpmjs/

**Comment by Pingze-github** [comment]
https://hub.docker.com/r/supermp/cnpmjs.org/
这个第三方的就可以用。Dockerfile很简单，自己构建也行。

**Comment by rhinoceros** [comment]
可参考：
https://github.com/cnpm/cnpmjs.org/pull/1422
我的测试环境是用docker-compose启动的。
