### ISSUE TITLE
downloads目录，残留大小为0的tag文件

### ISSUE THREAD

**Issue by ShangguanQuail** [cnpm/cnpmjs.org#1418]
sync 模式为all，理论上downloads下面的tar文件在上传之后会删除，但是现在很多tar文件还在，文件大小为0

**Comment by rhinoceros** [comment]
看是否有 sync_error 日志

**Comment by ShangguanQuail** [comment]
没有，而且tar包也正常上传了，并不是一个所有的包都会这样，就是同步的包多了之后，很小一部分会这样
