### ISSUE TITLE
部分包在官方可以下载，但是taobao源不能下载

### ISSUE THREAD

**Issue by ShangguanQuail** [cnpm/cnpmjs.org#1423]
查找部分包的时候，在官方源上能找到该包，但是在taobao源上就找不到，就算在https://npm.taobao.org/ 上手动点了sync还是查询不到。具体的包列表如下：

 ["@alifd/theme-2530","@alifd/theme-2534","@alifd/theme-2543","@aynode/xpdf","@bbge/vm","@charnwood-borough/vue-tagsinput","@chrysalis-api/hardware-keyboardio-model01","@chrysalis-api/keymap-transformer-core","@clubajax/react-form","@cnbritain/wc-theme-mixins","@cnbritain/wc-top-stories","@cnbritain/wc-video-theatre","@cnguy/bs-react-highlight","@coachcare/datepicker","@coast-team/mute-core","@coast-team/mute-crypto","@cobalt-engine/cobalt","@code-dot-org/blockly","@code-dot-org/bramble","@code-dot-org/dance-party","@codeurs/php-bin-linux64","@cognigy/wndb-with-exceptions","@cognite/3d-viewer","@cognite/griff-react","@coinspot-official/react-stockcharts","@coldandgoji/firebase","@collab-ui/core","@collab-ui/icons","@collab-ui/react","@colonise/sevenzip","@colony/colony-js-adapter-ethers","@colony/colony-js-client","@colony/colony-js-contract-client","@coloradoide/authenticator","@colorful/core","@colorfulwindmill/five-films-interface","@colorfulwindmill/five-films-service","@comicrelief/pattern-lab","@comicrelief/storybook","@commaai/log_reader","@comparenetworks/imsmart-web","@compositor/x0","@condenast/flyway-schema-validator","@conductorlab/components","@conduitvc/dynamodb-emulator","@congresspolymedia/devextreme","@connectedcars/api-types","@conscia/tika","@container-stack/client-core","@container-stack/core","@container-stack/graphql-gql","@container-stack/hemera-brigade-gw-plugin","@container-stack/hemera-plugin","@container-stack/microservice-hemera-plugin","@container-stack/openssl","@container-stack/server-core","@container-stack/store-mongo","@container-stack/utils","@containerlabs/functions-compose","@containerlabs/react-apollo-shared","@containership/kubernetes.client","@contentacms/contentajs","@contentacms/contentajs-graphql","@contentful/rich-text-from-markdown","@contentful/rich-text-html-renderer","@contentful/rich-text-plain-text-renderer","@contentful/rich-text-types","@contentful/structured-text-types","@contentpass/pubsub","@contentpass/zxcvbn","@contentthat/contentthat-js","@contextaware/lite-scanner","@contextual-learning/elsa-bottom-sheet","@continutech/sd-angular-jsonapi","@control-fitness/helper-graphql-client","@control-fitness/helper-i18n","@conversationai/wpconvlib","@conveyal/analysis-ui","@conveyal/commute","@coorpacademy/history","@coorpacademy/nova-icons","@divante/planner","@dmant/ez-ui-components","@edu-fe/version-controll","@eduardomoroni/babel-preset-react-app","@eduardomoroni/react-scripts","@edvolution/create","@edvolution/eslint-config","@fes/static-deploy","@fes/vuee","@gedigital-apm/apm-monitor","@gltf-transform/atlas","@gltf-transform/cli","@gltf-transform/split","@goldajs/core","@guardian/atom-renderer","@headswap/lib-engine-event","@helpusersvote/react","@here/harp-font-resources","@hifaraz/frite","@hitask/blueprint-select","@hitask/blueprint-table","@ibm-watson/speech-to-text-nodejs","@ibm/plex","@kontur.candy/engine","@lifter/lifter-app","@loopback/cli","@matibat/cordova-plugin-fcm-with-translations","@midion/electron","@muenzpraeger/sfdx-plugin","@musicglue/mg-express","@my-ideas/loggy","@ng2-dynamic-forms/core","@ngageoint/geopackage","@ngcommerce/core","@ngcore/base","@ngcore/core","@ngtools/webpack","@ngx-dino/geomap","@ngx-dino/science-map","@ngxs/devtools-plugin","@ngxs/form-plugin","@ngxs/logger-plugin","@ngxs/storage-plugin","@ngxs/store","@ngxs/websocket-plugin","@nicolaudie-group/xhl_js_addon-linux","@nicolaudie-group/xhl_js_addon-linux-debug","@nicolaudie-group/xhl_js_addon-osx","@nicolaudie-group/xhl_js_addon-osx-debug","@nio/ui-kit","@nlabs/lex","@noaestudio/forms","@nsivertsen/test","@nsjtt/common","@nuxtjs/google-tag-manager","@nuxtjs/localforage","@nuxtjs/offline","@oclif/semantic-release-dev","@okiba/easings","@orcden/od-carousel","@osome/burger","@osome/legal-address","@osome/osome-address","@oss-stealth/bodhi","@oss-stealth/nodelibs","@sooho/advisory-db","@sunshower/aire","@vpubevo/vpubd-rpc","NFO-Generator","Sheet","aboard","actors","ajforce","ajtalkjs-core","ajtalkjs-troy","allsync","app-js-dom","astream","async-memoizer","atman","axon-rpc#0.0.3","backbone-api-client-redis","backbone.appmodule","backbone.monitor","backdroid","background-cache","basket","bbc-goodfood-scraped","beanlogger-client","big-block-input","bluebird-hooks","blya!","bootstrap-npm","bower#1.3.5","brain***_games***","browser-harness","buildfu","bumm","burokrat","byu-catan","caliel","candy-theme-moeclub","cbind","cf-env","chalk256","chord.js","cirru-mustache","component-test-builder","conferge","connect-fonts-sourcesanspro","connect-stylus","cortex-server","couch-promise","cqwrap","create-init","csvmapper","customs","datapackage-jsonld","dirty-html-content-parser","domain.js","dorante","easypack","eert","eql-engine","equiprose","express-blogger","express-dyngodb","express-hashcash.io","ez-c4db","f*","foo!","foo~","fuck!","funcoffee","gch","generator-ionicjs","generator-licensetxt","generator-node-app","generator-ntesmail","geocodify","gimbus","git-static-diffuse","gitman","gitolite","grunt-borschik","grunt-encrypt","grunt-mocha#~0.4.10","grunt-saucelabs-qunit","grunt-weblint","gulp-distributor","ha-api","hannah-js","hash!","hashable","hashcash.io","hello_world_founder","highcharts-*","html-form-tools","indexed-db-cache","iracing","itag","jade-to-wire","jivejs","jski","json-bundle-stream","jwt-express-login","latex-watcher","ld.js","level-create","lhotse","libirc","limbo#0.1.8","lincell","lokick","luc-devutils","magfa","marionette-debug","markalldown","markdoc","markdown-outline","markdown-walker","markdown2slides","markdowns","markdownstream","marker","markers","market-enb-techs","market-req","marketplace-client","markitdown","markov-algorithm","markpoint","markshow","markstache","marktex","markup-server","marlboro","mary","masher","mashup","masm-cucumber","masm-log","masstransit","master-worker","matches","matchmaker","math-buffer","math-numbers","math_examp","math_example","math_example111","math_example13","math_example2_sergiomp","math_example_bcote","math_example_canlink","math_example_cfletcher","math_example_iustinian","math_example_kdf","math_example_mirfan","math_example_smeel","math_example_vineetsharda","math_examplens","math_package","math_test","mathematics","mathexample","mathio","mathistutils","maths_example_jwnz","mathsync-generator","matrix-paths","matrix2","matrix3","matrixjs","mauve","maximum-subarray","maxmind-reload","maxminded","mayday","mbrace","mbrando_math_example","mbsymfix","mbt","mca","mega-db","metaflac","microkern","module-graph","mongo-edit","mongo-query-operators","mongo-select","monkeybars","mtime","mysql-prettify","mysql2geojson","nacl","napat","napat-github-example","national-rail","navcodec","night-watch","nlopt","nlp_comprimise","node-awesome-npm-package","node-ckan-crawler","node-coloredcoins","node-crocodoc","node-document-storage","node-fetch-url","node-heroku","node-pub-sub","node-ralf","node-version-resolver","nodealytics","nodeginx","nodejs-common","nodeportal","nodize","nodyst","note","nw-raf-demo","nwitch-base64","nx-parser","occur","olli-github-example","osrs-top","pachube","page2images-visual-link","pandoc-highlighter","particles-seed","periodic.app.web-client","periodic.component-static.list-view","periodic.component-static.media-list-view","periodic.component.full-width-slideshow","periodic.component.navigation-header","pimp","pixel-ping","plunker-share","private-project-init","private.shopify","pro.js","process-ui","pulldown-middle-man","pybee!batavia","quassel-proxy","ractive-backbone-tmp","rapportive","recore-admin","recore-admin-ui","refresh-couch-views","ren","respondu","rest-browser","riak2-protobuf","rind-modules","roach","roblox-scraper","rs-hiscores","sara","sargam","sass-vars-to-js-loader","scratch-gui","screeba-file","sdh-slackbot","sdrc-loader","selenium-service-example","selenium-test-runner","serval-i18n","simple-assets","sky-process-ui","sky-user","slush-meanjs","solq","somepackage-dev","sorted-set","sshfs","sudatadata","swk-valid","syncler","telekinesis-di","temp-testing-project","tequila","test.css","testbed","tfs_vts","thomas-github-testexample","todayjs","toerr","trying-out-some-stuff-i-guess","tvstt","twitterwall","typekit","uns-ccap","v-jntable","vertx-eventbus-client","vouch","wanna","wd40","wmi","worklist","yae","youtube-get","ypm","zequals"];

**Comment by ShangguanQuail** [comment]
部分包（比如 @bbge/vm）同步失败的原因是 https://github.com/cnpm/cnpmjs.org/issues/1318

**Comment by fengmk2** [comment]
都可以同步了。
