### ISSUE TITLE
包的发布权限校验逻辑有问题（从上游同步的私包）

### ISSUE THREAD

**Issue by linxixuan** [cnpm/cnpmjs.org#1432]
复现的逻辑比较简单
1. 将新的私服的upstream设成老的私服的regsitry
2. 通过页面sync一个私包
3. 在新的私服上登录
4. publish一个新的版本，会报错“你无权修改这个包”

我看了cnpm的源码，sync 页面，前端会调用/sync/:name这个接口，但是永远没有透传publish这个参数，sync_module_worker是永远无法给私包加上publsih on cnpm 为true的逻辑的

**Comment by alsotang** [comment]
这就是正确的逻辑啊。你怎么能覆盖上游的包呢？即使上游也是你的私有仓库。假如你在下游覆盖了上游的包，上游的包同版本更新之后，下游就无法判定了。

**Comment by shilucus** [comment]
如果是作为迁移使用，如何在新的服务上publish新的版本呢？

从服务A迁移到服务B，在服务B上publish新的版本
