### ISSUE TITLE
无效的database配置

### ISSUE THREAD

**Issue by WhiteYin** [cnpm/cnpmjs.org#1435]
# 场景
1. 在/cnpmjs.org/config/config.js文件中，使用如下配置
```
module.exports = {
    database: {
        // 数据库名
        db: "myNpm",
        username: "root",
        password: "root",
        // 数据库类型
        dialect: "sqlite",
    },
}; 
```
2. 执行建表命令，终端显示执行成功，且.tables可以查看到有表。
```
node ./models/init_script.js true
```
3. 执行启动命令，能够成功访问页面
```
npm run start
```
# 问题
* sqlite日志报错：`SequelizeDatabaseError: SQLITE_ERROR: no such table: total`
* 不显示当前已有的包数量 && 搜索失败

# 暂时解决的方法
删除config.js中database字段及其值，使用config/index.js中的默认配置，则可以正确显示当前私有仓库中的包数量和正常的搜索功能。

**想请教一下是什么原因？**

**Comment by alsotang** [comment]
> 删除config.js中database字段及其值，使用config/index.js中的默认配置，则可以正确显示当前私有仓库中的包数量和正常的搜索功能

感觉是初始化的时候，少传了什么参数，导致建表的位置错了。如果你删了config中的database字段，那程序访问的是哪里？这个问题需要想一想。
而且如果你看看配置里面的 `dialect: "sqlite",` 这个地方是不是填错了？应该是mysql或者pg？

**Comment by WhiteYin** [comment]
@alsotang 
> 而且如果你看看配置里面的 `dialect: "sqlite",` 这个地方是不是填错了？应该是mysql或者pg？  

我写出来是想说明我使用的是sqlite数据库。

> 感觉是初始化的时候，少传了什么参数，导致建表的位置错了。如果你删了config中的database字段，那程序访问的是哪里？

我也不清楚访问的数据库是哪儿。看了`/.cnpm.org/`目录下，是有`data.sqlite`文件的。

**Comment by WhiteYin** [comment]
我现在发现只要`config/config.js`导出的配置对象中包含`database`字段，数据库就无法访问。不知道是否有人能够复现？

文档中对于database字段的说明还是太少了。我看了源码，大概理解流程是：
1. 执行`/models/init_script.js`，这个js文件读取config文件夹中的`index.js`模块；
2. `/config/index.js`会读取同目录下的`config.js`文件中导出的配置，使用`copy`函数进行配置拷贝；
3. 将复制后的配置对象传给`init_script.js`，进行建数据库和表操作。

根据我的情况，我怀疑是`copy`函数执行后返回的配置对象中，`database`属性值是不全的。

**Comment by alsotang** [comment]
sqllite 数据库为什么需要账号和密码？不是提供一个文件地址就行了吗？

**Comment by WhiteYin** [comment]
@alsotang 
一开始是在linux服务器上启动的，然后换成本地调试。找到问题原因了。
# 代码
```
// 在/config/config.js中自定义配置
module.exports = {
    database: {
        // 数据库名
        db: "my-npm-db",
        username: "root",
        password: "",
        // 数据库类型
        dialect: "sqlite",
    },
};
```
# 断点调试
![database字段被覆盖](https://user-images.githubusercontent.com/11420425/52759537-2ef30300-3047-11e9-8861-e777ca494c44.png)  


# 结论
如果/config/config.js中存在database字段，则/config/index.js导出的配置对象中的database字段会被覆盖。  
导致这一结果的代码是/config/index.js中line 285~287
```
if (fs.existsSync(customConfig)) {
    copy(require(customConfig)).override(config);
}
```

不明白为什么这么设计？合理的逻辑应该是默认配置与用户配置合并吧……
