### ISSUE TITLE
可否整体调整下数据库字段长度限制?

### ISSUE THREAD

**Issue by acrazing** [cnpm/cnpmjs.org#1437]
比如 `module.version` 这个字段, 现在的限制是 30, 如果发一个带 tag 的版本的话, 很容易就超了, 比如:

![image](https://user-images.githubusercontent.com/10029810/53003479-f9e11900-3469-11e9-9227-bd77dae23c43.png)

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmjs.org/blob/master/docs/db.sql#L84 目前我们数据太大，没法改了。
你的数据库数据量不大的话，可以改改。

**Comment by alsotang** [comment]
> 目前我们数据太大，没法改了
这是啥？这个开源项目跟具体的某个部署是绑定的？ @fengmk2
