### ISSUE TITLE
报错的详情字段变更

### ISSUE THREAD

**Issue by alsotang** [cnpm/cnpmjs.org#1443]
https://github.com/npm/npm-registry-fetch/blob/44918439b7460a1597efc246973385af144ccb7a/errors.js#L45

现在npm是使用返回值里面的 `body.error` 字段来显示详情。但我看 cnpm server这边是使用 `body.reason` 来返回详情的。

https://github.com/cnpm/cnpmjs.org/blob/316e722a2e08d4591005d613312240ac5323ec29/controllers/registry/package/save.js#L131

这块要不要跟进一下？

我今天有个用户 publish 的时候，报错是 forbidden，然后没有详情，搞得他疑惑了很久。

**Comment by alsotang** [comment]
但好像这里的详情还是在 reason 中 https://replicate.npmjs.com/aaaaaaaaaabsdfsdf

**Comment by alsotang** [comment]
```bash
curl https://registry.npmjs.org/rhooks -X PUT
{"error":"You must be logged in to publish packages."}

curl https://r.cnpmjs.org/rhooks -X PUT
{"error":"unauthorized","reason":"Login first"}
```

**Comment by alsotang** [comment]
腾讯内网的tnpm已经将所有 reason 的地方改成 error

方法：
在 vscode 中，批量替换。   `error.+\n\s+reason:`   换成 `error:` 。然后搜索 `reason` 再手动替换一些 edge cases.

**Comment by fengmk2** [comment]
@alsotang 可以提个 pr，将 error 完善一下，跟 npm 对齐。

**Comment by alsotang** [comment]
我提个 pr 将项目中的 reason 字段都改成 error，你看可以吗？ @fengmk2

**Comment by fengmk2** [comment]
@alsotang 提上来。
