### ISSUE TITLE
cypress二进制包路径与淘宝源的不符

### ISSUE THREAD

**Issue by mlzzen** [cnpm/cnpmjs.org#1447]
```
URL: https://npm.taobao.org/mirrors/cypress/desktop/3.2.0?platform=win32&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found
----------

Platform: win32 (10.0.17763)
```
我这样设置的淘宝源yarn config set cypress_download_mirror https://npm.taobao.org/mirrors/cypress -g;

**Comment by creanme** [comment]
似乎你家的url是https://npm.taobao.org/mirrors/cypress/3.2.0/win64/

**Comment by zWingz** [comment]
路径确实对不上
![image](https://user-images.githubusercontent.com/13031838/76484640-55a38900-6455-11ea-8925-a55a41265a19.png)

https://docs.cypress.io/guides/getting-started/installing-cypress.html#Mirroring

**Comment by yingzhiji** [comment]
cpress 默认会在你设置的镜像地址后面加上 destop，所以导致路径不匹配，希望官方能改一下

**Comment by Stupidism** [comment]
问题依然没有解决么 #1560

**Comment by fengmk2** [comment]
cnpm i cypress 可以安装。npm 不知道如何 hack。

**Comment by FrankFang** [comment]
把 cypress.io 加入 proxifier 的翻墙白名单吧。

**Comment by weizy0219** [comment]
我是npm写死的：
npm config set CYPRESS_INSTALL_BINARY=https://npm.taobao.org/mirrors/cypress/6.8.0/win32-x64/cypress.zip //windows系统
npm config set CYPRESS_INSTALL_BINARY=https://cdn.cypress.io/desktop/6.8.0/linux64/cypress.zip //linux系统

**Comment by fengmk2** [comment]
使用最新的环境变量 https://github.com/cnpm/binary-mirror-config/pull/41
