### ISSUE TITLE
开机启动问题

### ISSUE THREAD

**Issue by pengfeiWang** [cnpm/cnpmjs.org#1449]
之前就提过这个问题, 后来因为工作内容原因也没有太关注
最近又接之前的工作了, 这个问题也一直没有解决

对 linux 程序了解不多, 烦请对这方面有了解的指点下

系统: ubuntu 16

在 `/etc/init.d/` 下增加  `cnpm-start.sh`

sh 脚本代码

```sh
#!/bin/bash

### BEGIN INIT INFO
# Provides:       cnpm-start.sh
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the cnpm-start.sh web server
# Description:       starts cnpm-start.sh using start-stop-daemon
### END INIT INFO

cd /home/ubuntu/
Now=`date "+%Y-%m-%d-%H:%M:%S"`
echo "test-${Now}" >> ./t.log

case "$1" in
  start)
        #开机需要执行的逻辑
        cd /home/ubuntu/cnpmjs.org/ && npm run start

        ;;
  stop)
        #关机需要执行的逻辑
        cd /home/ubuntu/cnpmjs.org/
        echo "test-${Now}" >> ./stopt.log
        npm run stop
        ;;
  *)
        ;;
esac
```

现在的问题是 `npm start` 是执行成功的
可以访问 `localhost:7002`
浏览器控制台查看`network`, 发现 `/total` 这个服务报错 `500 (Internal Server Error)`

明明已经正常启动了, `/total` 这个服务是怎么回事呢

**Comment by july-12** [comment]
应该是你的mysql数据库有报错了，你可以vi  ~/.cnpmjs.org/logs/nodejs_stdout.log 浏览下日志找到有Error的地方是不是有  **MySQL 8.0 - Client does not support authentication protocol requested by server; consider upgrading MySQL client **的报错，如有该错误尝试登陆至数据库执行: ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password' (注意：用户名和密码要修改至对应设置)
