### ISSUE TITLE
私有库安装304，修改registryHost后也没有作用

### ISSUE THREAD

**Issue by lmf** [cnpm/cnpmjs.org#1450]
请求信息如下：
```javascript
npm http fetch GET 304 http://test.dykt123.com:9999/@dykt/util 217ms (from cache)
npm http fetch GET 404 http://r.cnpmjs.org/@dykt/util/download/@dykt/util-1.0.0.tgz 824ms
```
registryHost: test.dykt123.com:9999

求教是什么原因

**Comment by lmf** [comment]
<img width="958" alt="image" src="https://user-images.githubusercontent.com/3777374/55371646-82ef7380-5531-11e9-8c37-68cd248bd85b.png">
@fengmk2 这是install时候的debug信息，帮忙看看原因

**Comment by blingbling-110** [comment]
304应该说明请求到之前的缓存了
我今天也遇到了这个问题，解决详情在https://blog.csdn.net/weixin_44256803/article/details/118152643
不清楚适不适用于你的情况
