### ISSUE TITLE
淘宝源与 pnpm 不兼容，cnpmjs 源偶发

### ISSUE THREAD

**Issue by sodatea** [cnpm/cnpmjs.org#1458]
## 复现仓库
https://github.com/sodatea/pnpm-taobao-test

## 复现步骤
```
npm i -g pnpm

git clone https://github.com/sodatea/pnpm-taobao-test.git
cd pnpm-taobao-test
pnpm i
```

## 说明

如果用 https://registry.npm.taobao.org/ 作为源，每次安装都会卡住，强行 Ctrl + C 会看到 400 Bad Request 报错

如果用 https://r.cnpmjs.org/ 的话，偶尔会出现这个错误，大部分情况下正常

请问这两个源有何区别？

碰到这个问题是因为 Vue CLI 3 中增加了对网络状况的检测，发现用户到 npmjs.org 的连接过慢时会建议用淘宝源。而最近的 3.6 中新增了 pnpm 客户端的支持，结果测试中发现指定用淘宝源安装肯定会失败。

如果 Bug 不好定位/修复，且这两个源区别不大的话，Vue CLI 考虑改用 r.cnpmjs.org 作为中国用户的默认源，这样是否推荐？

**Comment by SilverLeaves** [comment]
同样的问题：
https://github.com/pnpm/pnpm/issues/1785

**Comment by fengmk2** [comment]
具体是什么原因不兼容呢？

**Comment by sodatea** [comment]
抓了下包是有个 302 请求被重定向到 `http://cdn.npm.taobao.org:443/eslint-loader/-/eslint-loader-2.1.2.tgz`……

**Comment by fengmk2** [comment]
@sodatea 我使用最新的 pnpm 测试你的代码库，ok的啊

![image](https://user-images.githubusercontent.com/156269/56597193-8c499880-6624-11e9-95da-e97b9762ad24.png)

**Comment by sodatea** [comment]
@fengmk2 刚想说……复现里不小心加了 lockfile 导致结果不一样……

```
rm -rf node_modules pnpm-lock.yaml
rm -rf ~/.pnpm-store
pnpm i
```

再试试？

**Comment by fengmk2** [comment]
![image](https://user-images.githubusercontent.com/156269/56597426-00843c00-6625-11e9-8b24-742dab11d255.png)

**Comment by fengmk2** [comment]
已经定位到问题，通过 7f0c141ac2f7679b5322aadd537c5ff1bef0b032 修复。等会重新部署即可。

**Comment by sodatea** [comment]
👍效率好高

**Comment by fengmk2** [comment]
@sodatea 好了，修复了。
