### ISSUE TITLE
指向私有仓库安装私有包，引用的公共依赖报错404。

### ISSUE THREAD

**Issue by fivehundredmiless** [cnpm/cnpmjs.org#1459]
帮忙看下，有遇到同样问题的吗
syncModel: 'none'   "none,exist,all

问题1. syncModel 选exist之后，安装本地仓库的私有包，私有包的其他依赖也指向本地仓库了，报错404。
问题2.syncModel 选择none之后，安装私有私有包（已经上传到私有仓库）可正常安装，但是安装public包每次都会去官方下载，本地并不做缓存，速度较慢。

为什么设置为exist之后安装私有包的时候，一些公共的依赖也指向本地仓库，同时本地仓库并没有这些模块，日志报错404。

**Comment by ijse** [comment]
也同遇到过这个问题，

后来改为none，自己手动清理公共的包的数据库和文件
