### ISSUE TITLE
是否考虑 unpkg 类似的 http 调用

### ISSUE THREAD

**Issue by 132yse** [cnpm/cnpmjs.org#1460]
如题，unpkg 可以使得我们直接调用 package.json 里的入口文件
但是国外的 cdn 在国内仍然不友好

cnpm 有做类似的事情，或者准备做吗

**Comment by alsotang** [comment]
这件事情跟cnpm感觉不是强相关的。完全可以以cnpm为上游搭建自己的unpkg服务。不必嵌入。

**Comment by 132yse** [comment]
@alsotang 自己搭建的话，买不起 cdn 呀，感觉还是阿里云更加靠谱

**Comment by fengmk2** [comment]
@132yse 阿里云也不是免费赞助的，能赞助 淘宝 npm 我们已经很满足了。 unpkg 这种暂时很难拉到赞助。
