### ISSUE TITLE
Is there any official Amazon S3 storage wrapper?

### ISSUE THREAD

**Issue by kaelzhang** [cnpm/cnpmjs.org#1461]
https://github.com/cnpm/cnpmjs.org/wiki/NFS-Guide

**Comment by kaelzhang** [comment]
Found one: https://github.com/QubitProducts/s3-cnpm

**Comment by alsotang** [comment]
added https://github.com/QubitProducts/s3-cnpm to https://github.com/cnpm/cnpmjs.org/wiki/NFS-Guide
