### ISSUE TITLE
使用cnpm安装angular应用的依赖 ，会导致编译失败！

### ISSUE THREAD

**Issue by rdkmaster** [cnpm/cnpmjs.org#1463]
复现此问题的仓库，[点击这里](https://github.com/rdkmaster/jigsaw-seed)，使用npm安装则一切正常，而使用cnpm安装了依赖，虽然安装过程一切正常，但是使用下面这个命令编译：

```
ng s
```

则报下面这个错误：

![image](https://user-images.githubusercontent.com/16191626/57976760-7c05bd00-7a1a-11e9-9450-5d0245bf587c.png)

经过初步分析后，原因大致如下：

在node_modules目录下，我发现有大量的下划线开头的包：

![image](https://user-images.githubusercontent.com/16191626/57976763-be2efe80-7a1a-11e9-9cc4-f62517434863.png)

然后，cnpm通过创建与npm同名的软连接，并让他们指向这些下划线开头的包，达到模拟npm安装效果的目的：

![image](https://user-images.githubusercontent.com/16191626/57976772-1403a680-7a1b-11e9-91cd-586e7d0963e6.png)

这个方式对于普通的库，没有问题，但是对于angular这样定义了全局标识符的库，则会导致在编译时，报出最上面那个截图上的错误：

```
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/@rdkmaster/jigsaw/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

其中，`ngDevMode`就是一个全局标识符，由于存在两份（一个是软链，一个是下划线开头的包），因此出错。

**Comment by killmojo** [comment]
最近也碰到了类似问题，cnpm安装的grapecity的 spread-sheet-vue，运行后总是报错，改用npm就好了。也是发现了很多_@grapecity的文件夹，还有会为依赖在子目录中再创建一个node_modules的文件夹，导致全局的引用不一致。
