### ISSUE TITLE
cnpm 同步服务挂了

### ISSUE THREAD

**Issue by JeromeLin** [cnpm/cnpmjs.org#1466]
![image](https://user-images.githubusercontent.com/9812721/58221942-fe59ee00-7d46-11e9-965a-92b4e45173ed.png)

https://npm.taobao.org/sync/zarm

**Comment by wangyingjun** [comment]
https://registry.npm.taobao.org/
https 的服务挂了 502 谁能修复一下
http 是好的

**Comment by shady-xia** [comment]
23号就挂了吗？现在24号中午还是没好。。

**Comment by fengmk2** [comment]
@shady-xia 你确定23号就挂了？

早上有慢请求，已经恢复。
