### ISSUE TITLE
cnpm 下载node-release的时候报404了

### ISSUE THREAD

**Issue by Kuohao-wu** [cnpm/cnpmjs.org#1471]
![image](https://user-images.githubusercontent.com/16506726/58304101-87475700-7e25-11e9-8118-89be6943e6a3.png)

**Comment by fengmk2** [comment]
已修复。

**Comment by raylee1994** [comment]
貌似还有这个问题

**Comment by fengmk2** [comment]
https://registry.npm.taobao.org/node-releases/download/node-releases-1.1.21.tgz 可以下载的。
