### ISSUE TITLE
syncModel: 'none'问题

### ISSUE THREAD

**Issue by xwjune** [cnpm/cnpmjs.org#1475]
syncModel: 'none' 包能成功发布，且能收到上传的包，但是点进去，却是提示没有找到匹配的包

搜索提示：
Packages match "npm-demo"
. npm-demo npm私有仓库测试包

点击去提示：
Can not found package match npm-demo. You can SYNC from official npm registry or SEARCH in official npm website.

**Comment by xwjune** [comment]
@vincentmrlau @fengmk2 @dead-horse @ibigbug @alsotang @XadillaX @JacksonTian

**Comment by vincentmrlau** [comment]
要用@scope，如@npm/demo

**Comment by ijse** [comment]
我配置了`syncModel: 'none'`， 但是 cnpm install时有个包总是旧版本，查了本地数据库，module, tag表中也没有这个包相关信息，但cnpm info时返回就是旧的包，这可咋整？

@dead_house
@alsotang
