### ISSUE TITLE
Cypress binary files are absent since v3.3.0 in cnpm/taobao mirrors

### ISSUE THREAD

**Issue by AngusFu** [cnpm/cnpmjs.org#1489]
## Links

https://cnpmjs.org/mirrors/cypress/
https://cnpmjs.org/mirrors/cypress/3.3.0/osx64/

## What happened

The directory seems empty.

![image](https://user-images.githubusercontent.com/8180186/61577464-2e8cf580-ab1a-11e9-91b2-4fe85a7f7900.png)

## Expected

A `cypress.zip` binary is expected, like v3.2.0 ——

![image](https://user-images.githubusercontent.com/8180186/61577468-419fc580-ab1a-11e9-937f-bf3d62c4235e.png)

**Comment by fengmk2** [comment]
https://cnpmjs.org/mirrors/cypress/3.3.0/ platform 名称改了

![image](https://user-images.githubusercontent.com/156269/63633177-5bcb4700-c676-11e9-9a68-08f5ebb43ea7.png)
