### ISSUE TITLE
"syncModel": "exist" 到底有什么用，使用此模式安装包，各种404，愁人啊，这玩意有啥毛用。

### ISSUE THREAD

**Issue by fivehundredmiless** [cnpm/cnpmjs.org#1490]
"syncModel": "exist"

因为不可能使用all模式，太占用空间，使用none模式，不缓存公共包，开发反应很慢，所以只能使用exist模式，但是exist模式安装公共模块各种404啊，难道淘宝这个仓库就不能设置下载过的包，仓库缓存一份吗。

看了16年的issue（syncMode: 'exist' 模式，似乎当安装一个本地不存在的包的时候会直接报错，而不是从source下载）。

这到现在还不行啊。果真坑。

**Comment by alsotang** [comment]
你仔细看看，我觉得 exist 模式要配合 syncByInstall 使用。当包不存在的时候，自动去source同步，并且把请求302到source去。

**Comment by fivehundredmiless** [comment]
> 你仔细看看，我觉得 exist 模式要配合 syncByInstall 使用。当包不存在的时候，自动去source同步，并且把请求302到source去。

请帮忙看下，这个问题一直没解决，谢谢。配置文件已经设置 syncByInstall: true,302重定向如何配置啊。

**Comment by PunkMoon** [comment]
我的设置syncByInstall: true 也没用 @fivehundredmiless 现在你那里解决了吗

**Comment by WJXZ** [comment]
syncByInstall: true 还是会导致no match

**Comment by luckyxutao** [comment]
我的也是exist模式 安装不了模块
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react@^16.13.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'npm-test'
npm ERR! notarget

**Comment by whiteape** [comment]
那这个怎么破呢？还是有个这个问题嗄。
