### ISSUE TITLE
unpublish 之后哪个版本会变成新的 latest，是前一个 latest 版本，还是所有 tag 下最新的版本

### ISSUE THREAD

**Issue by conanmy** [cnpm/cnpmjs.org#1491]
我的包当前 latest 版本为 6.0.1，发布了 alpha 版本 6.1.0-alpha.1 一直到 6.1.0-alpha.6，然后误操作将 6.1.0-alpha.7 发布为latest。此时 unpublish，新的 latest 版本会是 6.1.0-alpha.6 还是 6.0.1？

我看 npm registry 会是6.0.1，而 cnpm 的逻辑看起来会是 6.1.0-alpha.6。我还没有亲自试验，想问下正确的逻辑应该怎样处理这个事，应该是跟 PUT package 接口对 latest tag 的计算逻辑有关。我看 npm cli 调用接口时也会传入新的包的 latest 为  6.1.0-alpha.6，但是API执行后的结果 latest 变为了 6.0.1。

**Comment by vellengs** [comment]
这个看起来是bug 吧，误操作了，unpublish 看上去不能恢复原样的latest.
