### ISSUE TITLE
electron安装失败

### ISSUE THREAD

**Issue by Sean-214** [cnpm/cnpmjs.org#1498]
npm的electron已更新到v6.0.3，但是electron镜像[https://npm.taobao.org/mirrors/electron]还是v6.0.2，导致安装后无法下载而报错。
npm是可以手动同步的，希望镜像也可以手动同步。或electron镜像和npm的electron同步更新。

**Comment by alsotang** [comment]
这个地方有点奇怪。2019-08-20 发布的两个release没有同步过来，但是 2019-08-15 的已经同步过来了。
今天作为 2019-08-21 ，不应该这么慢的，我看源码是5分钟同步一次吗？

https://github.com/cnpm/mirrors/blob/a8be4ed5eef43f12bb7a8cc8caa113390989aca2/config/index.js#L97

**Comment by Sean-214** [comment]
@alsotang 我看了下electron是用electron-download这个包下载预编译文件的。地址好像变了

现在是

> https://github.com/electron/electron/releases/download/v6.0.3/electron-v6.0.3-linux-arm64.zip

我看你链接中的代码是

> disturl: 'https://github.com/atom/electron/releases',

**Comment by loliconer** [comment]
是啊，昨天安装的时候失败了，今天看了一下还是没同步过来

**Comment by alsotang** [comment]
@Sean-214  `https://github.com/atom/electron/releases` 会跳转到 `https://github.com/electron/electron/releases` 是一样的。

这个sync问题得等 @fengmk2 来看才行了。我外围看到的，没看出什么问题

**Comment by ZhangQi-HUST** [comment]
哈，最近想入门electron，上来就装不了，百度一下用了cnpm，还装不了……
哈哈哈

**Comment by alsotang** [comment]
@ZhangQi-HUST 先用 6.0.2

**Comment by fengmk2** [comment]
我看看。

**Comment by fengmk2** [comment]
恢复了。

由于最近 github 将我们的同步服务器 ip 封了，导致我们目前的同步很不稳定。后续有问题只能走一步看一步。

@zcbenz 看看有没办法将 `47.88.255.146` 这个 ip 解封了，它是淘宝 npm 在新加坡用于同步 github 资源的服务器。


```bash
👿  cnpm i electron
✔ Installed 1 packages
✔ Linked 132 latest versions
[1/1] scripts.postinstall electron@* run "node install.js", root: "/private/tmp/node_modules/_electron@6.0.4@electron"
Downloading tmp-37985-1-SHASUMS256.txt-6.0.4
[============================================>] 100.0% of 4.54 kB (4.54 kB/s)
[1/1] scripts.postinstall electron@* finished in 5s
✔ Run 1 scripts
Recently updated (since 2019-08-17): 3 packages (detail see file /private/tmp/node_modules/.recently_updates.txt)
  Today:
    → electron@*(6.0.4) (08:01:37)
✔ All packages installed (143 packages installed from npm registry, used 7s(network 2s), speed 178.76kB/s, json 133(269.03kB), tarball 0B)
```

**Comment by zcbenz** [comment]
我去问问看。

**Comment by zcbenz** [comment]
这个IP应该已经解封了，原因好像是被判定成了proxy，我还要去问问怎么避免以后再出现这种情况。

**Comment by Sean-214** [comment]
非常感谢~！

**Comment by fengmk2** [comment]
@zcbenz 那台服务器要去同步的数据 https://cnpmjs.org/mirrors/ 可能实在太多，被认为 proxy 也是比较正常。
