### ISSUE TITLE
PNPM无法正下载

### ISSUE THREAD

**Issue by SilverLeaves** [cnpm/cnpmjs.org#1499]
![图片](https://user-images.githubusercontent.com/31165554/63571052-9dde8500-c5b1-11e9-8b6a-056b245ba10b.png)

**Comment by fengmk2** [comment]
retry 即可。

**Comment by zkochan** [comment]
was this fixed on the proxy side?

**Comment by SilverLeaves** [comment]
@fengmk2 it not works.
