### ISSUE TITLE
Npx 还是不工作吗？

### ISSUE THREAD

**Issue by yifanchen** [cnpm/cnpmjs.org#1500]
想跑如下命令，但是是在 npmjs.org 上去找，返回 404
```
npx install-peerdes 
```

有其他的解决方法吗？感谢。

**Comment by ShangguanQuail** [comment]
install-peerdes 这个npm包不存在啊，请问你的问题是？

**Comment by alsotang** [comment]
@ShangguanQuail https://www.npmjs.com/package/install-peerdeps

**Comment by yifanchen** [comment]
@ShangguanQuail missing a `p`,  should be `npx install-peerdeps`. thanks for @

**Comment by yifanchen** [comment]
补充一下：

为了测试，我有一个相同的 package，同时 publish 到 npm 和 cnpm 的 custom registry 上，现在的问题是 npx 这个命令在跑 npm package 是工作的，相反在 cnpm 的 registry 上则不工作。

**Comment by alsotang** [comment]
找下原因吧。如果原因在cnpmjs.org这边，我们就修。如果问题是npx的，就看看是不是少了什么配置。

**Comment by yifanchen** [comment]
https://github.com/cnpm/cnpm/issues/250
