### ISSUE TITLE
co模块在 搭建的私服中 缺失

### ISSUE THREAD

**Issue by busyRobots** [cnpm/cnpmjs.org#1501]
您好，我最近使用cnpm 私服遇到一个问题，
首先，通过cnpm -version 获取到的配置如下：
![image](https://user-images.githubusercontent.com/15335914/63819798-422d4680-c979-11e9-9746-22eda0b6e771.png)
然后，我项目中有依赖，co@4.0.0的模块，
我在服务器端同步的情况如下图：
![image](https://user-images.githubusercontent.com/15335914/63819873-99cbb200-c979-11e9-9757-413e63783831.png)
然后，查看对应的私服地址，情况如下，有显示co 模块的地址i：
![image](https://user-images.githubusercontent.com/15335914/63819912-c2ec4280-c979-11e9-80f4-34954218ae5b.png)
但是，我点击地址进入，缺是undefined
![image](https://user-images.githubusercontent.com/15335914/63819943-e8794c00-c979-11e9-835c-e54072bb5357.png)

最后我在项目中使用，也无法获取到搭建的私服上的资源，如下图：
![image](https://user-images.githubusercontent.com/15335914/63819984-1068af80-c97a-11e9-8ec1-9e06b4499472.png)
![image](https://user-images.githubusercontent.com/15335914/63820005-2f674180-c97a-11e9-87e2-80ecf9838ccc.png)

另外，我还尝试安装了其他的包，发现可以正常安装，

我想请教一下，这样的问题，应该如何排查？ 或者是否有可能手动将，对应的co模块手动更新到私服里面来？我看官方API只有，sync 这一个同步命令；

**Comment by alsotang** [comment]
如果其他包都能正常安装的话，建议排查一下 404 的 tgz 为何不存在

1. 先去 co 的文件夹下面看看一共存在多少个版本。是只缺了4.6.0还是都不存在
2. 如果都在的话，排查一下 tgz 那个请求走过的路径卡在了哪里
3. 如果文件夹下确实缺少 tgz，则根据 `cnpm sync` 去找到下载文件的地方，看看具体是怎么下载失败的。

**Comment by alsotang** [comment]
修好了吗？回馈一下解决过程吧。
