### ISSUE TITLE
同步styled-components时，一些版本同步时报错，导致同步缺失某些版本

### ISSUE THREAD

**Issue by busyRobots** [cnpm/cnpmjs.org#1502]
### 首先，环境情况如下：
![image](https://user-images.githubusercontent.com/15335914/63991511-be12c480-cb1a-11e9-95e2-b64a93138f28.png)
**使用npm run dev启动环境** 

### 同步报错情况如下图：
![image](https://user-images.githubusercontent.com/15335914/63991451-8146cd80-cb1a-11e9-95fe-552b53cd1674.png)

### 同步执行完成后的情况如下图：【第一个是我本地搭建，第二个是我去淘宝镜像查看到的】
![image](https://user-images.githubusercontent.com/15335914/63991581-f0242680-cb1a-11e9-94c8-63c2e4615b6e.png)
![image](https://user-images.githubusercontent.com/15335914/63991602-07fbaa80-cb1b-11e9-841d-90b08924e203.png)
### 表现现象：
从现象看好像是从0.4.1, 往后的若干版本没有同步到，

我有去淘宝镜像官方去看，发现那里是正常的，想请教下可能的原因， 或在官方私服是否有遇到相同的情况；

### 其他环境说明：

我搭建时参考的教程为：https://www.kancloud.cn/csnikey/fepro-guide/334551
本地mysql版本为：Server version: 5.7.25 MySQL Community Server (GPL)
本地Node版本为：12.7.0

**Comment by busyRobots** [comment]
我检查的本地的.cnpm.org/nfs 里面是有缺失的版本的tgz的文件的
![image](https://user-images.githubusercontent.com/15335914/63995548-7fd1d100-cb2b-11e9-9140-46f113fe1c40.png)

在数据库中是没有的
![image](https://user-images.githubusercontent.com/15335914/63995562-8b24fc80-cb2b-11e9-809f-ff51f50523af.png)

**Comment by busyRobots** [comment]
问题已经修复：
原因是 Emoji 的问题  + 字符集的问题；
参考了下方链接上的资料；
（1） https://dba.stackexchange.com/questions/161460/error-1366-incorrect-string-value-xf0-x9f-x98-x8a-x0ac-for-column-text-bo

（2）  https://github.com/sequelize/sequelize/issues/6258

（3） https://github.com/sequelize/sequelize/issues/1220

另外说一下，我在config/index.js 中的database 中的dialect 配置mysql，
![image](https://user-images.githubusercontent.com/15335914/63998623-173b2200-cb34-11e9-8c28-abad4192ba9d.png)

翻看源代码，有2个逻辑通路，我在我使用到的那个通路中，加了处理【参见下方的截图】，按照上面的那个逻辑，使用dialect: 'sqlite',的，应该可以，直接在配置字段中添加修改；
![image](https://user-images.githubusercontent.com/15335914/63998713-58333680-cb34-11e9-970c-c0cfbd617f40.png)

是否可以考虑扩展一下 dialect: 'mysql'的情况下也支持，通过配置修改字符集方式变动呢？ 毕竟老外的库使用Emoji 的情况是蛮多的  @alsotang

**Comment by alsotang** [comment]
cnpm一直有这个 utf8md4 的问题。不过由于我是直接改数据修的，所以不懂在代码里面哪个位置去设置默认的 utf8md4 。你的意思是改 sequalize 的配置可以是吧？
干脆提个pull request上来吧。

**Comment by alsotang** [comment]
所以你的数据库是在 sequalize 初始化的时候，由 sequalize 自动创建的？

**Comment by alsotang** [comment]
而且你截图中的 `config.dialect` 这个地方应该是代码写错了，应该是 `database.dialect`。感觉你建议的修改你也没在机器上跑过是吧。。。？

**Comment by alsotang** [comment]
这个地方应该是维护者只更新了 https://github.com/cnpm/cnpmjs.org/blob/master/docs/db.sql ，忽视了 sequalize 也联动变更。

**Comment by alsotang** [comment]
说说你的修复过程先吧。你是直接改了数据库中的字段类型，还是说sequalize改配置改好的？

**Comment by busyRobots** [comment]
（1）数据库的话，我是使用docs/db.sql创建的，创建之后，就没有再操作他，在使用的时候，才更新的数据库的内容
（2）config.dialect 你是指的下方图中的么？
![image](https://user-images.githubusercontent.com/15335914/64001440-684e1480-cb3a-11e9-9cbe-f8dcb750493e.png)

我并没有修改这个，我只是在其中加入了那段代码做测试，【感谢您指出问题，这也许也是源码上需要修改的地方的】

 我刚刚查阅了我的修改，我发现我违反了控制变量法的原则，我之前测试的时候在两个地方进行了修改（一个是上图，一个是配置文件中）
![image](https://user-images.githubusercontent.com/15335914/64003195-553d4380-cb3e-11e9-823f-2066e13bcc7b.png)

@alsotang

**Comment by busyRobots** [comment]
我的修复过程，大致是这样的，
（1）发现了问题，然后给去查找问题的原因，一开始有怀疑和数据库有关系，
（2）根据报错信息，我找到了，我上面贴的链接
（3）尝试根据配置是试验，就提到了上方我修改的2个地方，一个配置文件中加了个字段，另个就是在错误的判断下面加入了逻辑，【为之前没有找到合适输出逻辑验证是否走到了代码，是我的错误，感谢您的指出】
(4) 就是 使用npm run dev 重新运行私服，并cnpm sync styled-components， 同步，并查看 nfs 和module 中的相关资源是否存在，来验证修改是否生效了

现在看来我没有遵循控制变量，导致了这的歧义，真的不好意思； @alsotang

**Comment by alsotang** [comment]
所以总的来说，你这里是怎么修好的？

**Comment by alsotang** [comment]
听你的意思，应该是在配置文件中加了字段修好的？

**Comment by busyRobots** [comment]
在配置文件中，修改了配置为：
dialectOptions: {
      // if your server run on full cpu load, please set trace to false
      trace: true,
      charset: 'utf8mb4'
    },

![image](https://user-images.githubusercontent.com/15335914/64004089-2d4edf80-cb40-11e9-9f0c-93774ecb5e97.png)

**Comment by alsotang** [comment]
好吧。我本地这里用的版本比较旧，没有 dialectOptions 这个字段，但既然你是这么修好的，我也帮这个项目加上这个配置吧。

https://github.com/cnpm/cnpmjs.org/pull/1504/files 帮忙看一眼吧。

**Comment by busyRobots** [comment]
其实，在同步完成之后，还发现有个version 字段长度的问题，
styled-components 在版本version: 5.0.0-beta.5-removefoldedcomponentids，的时候确实比较长
![image](https://user-images.githubusercontent.com/15335914/64004536-047b1a00-cb41-11e9-84d0-0d24ff153340.png)

看module的配置是30，而这个版本其实超过了
![image](https://user-images.githubusercontent.com/15335914/64004768-80756200-cb41-11e9-9a2c-5409303edbf9.png)

![image](https://user-images.githubusercontent.com/15335914/64004745-6f2c5580-cb41-11e9-8525-4ffe43bdfb1c.png)

**Comment by busyRobots** [comment]
恩恩，刚刚看到你的修复了，感谢你

**Comment by alsotang** [comment]
根据 https://github.com/cnpm/cnpmjs.org/issues/1479
version 的默认长度我从 30 改到 70 了。奇怪，这个version的问题在 `docs/db.sql` 竟然一直没更新
