### ISSUE TITLE
npm run start error

### ISSUE THREAD

**Issue by chen-chuan** [cnpm/cnpmjs.org#1505]
i clone from cnpmjs.org.git,and install dependencies,when i use npm run start ，the following error is prompted.

C:\Projects\cnpmjs.org>npm run start

> cnpmjs.org@3.0.0-rc.29 start C:\Projects\cnpmjs.org
> ./bin/nodejsctl start && cp History.md docs/web/history.md

'.' is not recognized as an internal or external command,
operable program or batch file.

**Comment by alsotang** [comment]
`cnpmjs.org` does not support windows.
please try https://verdaccio.org/

**Comment by alsotang** [comment]
use Linux
