### ISSUE TITLE
lost wiki Deploy-a-private-npm-registry-in-5-minutes

### ISSUE THREAD

**Issue by YellowPure** [cnpm/cnpmjs.org#1507]
https://github.com/cnpm/cnpmjs.org/wiki/Deploy-a-private-npm-registry-in-5-minutes is empty

**Comment by YellowPure** [comment]
At README.md, the first guide to deploy a private cnpm is empty.

**Comment by alsotang** [comment]
This guide is outdated.

I am updating the readme https://github.com/cnpm/cnpmjs.org/pulls

**Comment by alsotang** [comment]
follow this one https://github.com/cnpm/cnpmjs.org/wiki/Deploy

readme is updated.
