### ISSUE TITLE
使用docker的cnpm搭建完之后，yarn使用异常

### ISSUE THREAD

**Issue by darknessjs** [cnpm/cnpmjs.org#1508]
yarn install无法下载到包
并且yarn publish时始终报Couldn't publish package: "xxxxxx私有包": [maintainers_error] request body need maintainers

userservice使用的通过npm登录。
可以用npm publish和npm install
只是yarn无法使用

**Comment by alsotang** [comment]
关注一下这个参数 https://github.com/cnpm/cnpmjs.org/blob/master/config/index.js#L266

去服务端调试一下看看卡在哪一步。

**Comment by darknessjs** [comment]
有开always_auth,因为要给不同地区的人用。
但是同时也是必须要有权限才能用。
这种情况下没法使用cnpm吗？
尝试过关闭alwaysAuth之后确实yarn能正常使用，但是这和我这边需求对不上

**Comment by darknessjs** [comment]
npm config set always-auth true
添加这个就好了emmmmmm
不添加这个的话yarn不会增加登录凭证

**Comment by darknessjs** [comment]
不过加了只解决了不能yarn install。。。yarn publish还是有问题...

**Comment by darknessjs** [comment]
然后手动给package.json手动加了
  "maintainers": [{
  }]
......

**Comment by alsotang** [comment]
这个地方还是好排查的，一步步跟一下就好了。

**Comment by zhangyuheng** [comment]
npm7 的不兼容更新会默认丢掉 maintains 字段，不过 cnpmjs 在 2020 年已经就修复了，升级 cnpmjs 就自动好了。
理论上只要升级到最新版本 cnpm server 就不感知了。

顺便参考：https://github.com/cnpm/cnpmjs.org/pull/1592/files#r582055206
