### ISSUE TITLE
npm install xxx@notfound.version 在指定版本不存在时不会去更新

### ISSUE THREAD

**Issue by AntSworD** [cnpm/cnpmjs.org#1509]
npm install xxx@notfound.version 在指定版本不存在时不会去更新

报错 No matching version found

看了下 registry/list.js 的代码，发现只有在这个包安全没同步过的时候可以去源上同步，如果已有，只是缺版本的话，就不行了

这个有办法解决么

**Comment by alsotang** [comment]
去网页上，有个sync按钮可以点

**Comment by AntSworD** [comment]
> 去网页上，有个sync按钮可以点

看上去现在只有这个办法，不能自动 sync

**Comment by LaxusT** [comment]
@alsotang 官网按钮是哪个？
