### ISSUE TITLE
node-canvas 镜像未更新到最新

### ISSUE THREAD

**Issue by Cweili** [cnpm/cnpmjs.org#1511]
`node-canvas` 最新版本是 v2.6.0

[cnpmjs 的镜像](https://npm.taobao.org/mirrors/canvas-prebuilt) 最新版本是 v2.0.0-alpha.14

**Comment by alsotang** [comment]
> NOTE: the canvas-prebuilt package is deprecated. As of version 2, canvas itself bundles prebuilt versions from this repo. Install by running

from https://github.com/node-gfx/node-canvas-prebuilt

换个包试试

**Comment by alsotang** [comment]
顺便去 https://github.com/cnpm/binary-mirror-config/blob/master/package.json 这里搜一下 canvas

**Comment by Cweili** [comment]
谢谢！@alsotang 

原来现在应该使用 https://npm.taobao.org/mirrors/node-canvas-prebuilt
