### ISSUE TITLE
npm 6.12.0镜像里没有同步

### ISSUE THREAD

**Issue by inetufo** [cnpm/cnpmjs.org#1518]
https://cnpmjs.org/mirrors/npm 
https://npm.taobao.org/mirrors/npm
这两个镜像里面npm v6.12.0版本没有同步

**Comment by inetufo** [comment]
貌似v6.11.2之后都没有同步了

**Comment by FETE-CH** [comment]
折腾好久才发现是这个问题...好坑啊👎

**Comment by alsotang** [comment]
这个mirror是什么场景会用到的？

**Comment by FETE-CH** [comment]
> 这个mirror是什么场景会用到的？

我是使用 gnvm 安装不同版本 node 和 npm 时，国外源没速度，使用了这个源，然后发现没有就没用了

**Comment by alsotang** [comment]
linux上，npm 可以通过 npm 自身来重装的，我平时都这样。
windows不是很清楚。

我觉得gnvm这个用法我不太理解，我觉得它应该考虑从 https://r.npm.taobao.org/npm 来获取 npm

**Comment by inetufo** [comment]
使用NVM设置了https://npm.taobao.org/mirrors/npm镜像加速，安装最新版本的12.13.0会失败，原因是NPMV6.12.0没有同步到镜像站点

**Comment by inetufo** [comment]
https://github.com/coreybutler/nvm-windows  我是使用的windows的NVM ，然后在settings.txt里面设置了镜像
node_mirror: https://npm.taobao.org/dist/
npm_mirror: https://npm.taobao.org/mirrors/npm/

**Comment by madonghao** [comment]
问题一样，等待解决

**Comment by inetufo** [comment]
已经同步了
