### ISSUE TITLE
怎么可以发布一个npm上已经存在的包

### ISSUE THREAD

**Issue by taoqf** [cnpm/cnpmjs.org#1526]
如题.
原本我在npm上发布的公共包,现在我想转为私有库,但是发现在私有库上发布不了.提示
```log
npm ERR! code E403
npm ERR! 403 Forbidden - PUT http://172.168.0.23:7001/@xxx%2fxxx- forbidden user
```

**Comment by alsotang** [comment]
最好把这个包放到私有scope中，不要去覆盖上游。

**Comment by taoqf** [comment]
比如我不想让使用者不修改包名的情况下还可以使用我发布到私有库的包.就会用到这个功能.
@alsotang

**Comment by taoqf** [comment]
我现在临时解决了,但是有一点点风险(cnpm不调整策略就没问题):

1. 在私有库上unpublish已发布到npm上并且同步过的包.
1. 在私有库重新发布新包.

除了同步策略的风险外,还有个问题就是私有库上没有了以前在npm上发布到过的公开包.我需要重新在私有库上再次发布之前发布过的版本.

**Comment by taoqf** [comment]
多谢关注这个问题 @alsotang .但实际上确实我现在有这样的需求,scope要换名字的话,代价太大,历史包袱太重.
我最希望的是我既能同步npm上的包,也可以在私有库上发布新包(版本号不会一样,但包名要一样).这样是最好啦.

**Comment by alsotang** [comment]
我个人是宁愿修复的时候麻烦点，修复完的结果是稳定可靠的。我也不太清楚你这么做的潜在风险，可能官方npm上不发新版本就没问题吧。

**Comment by taoqf** [comment]
风险就是cnpm现在不会到npm上同步已发布到私有库上的包.这个策略只要不变就没事.

**Comment by alsotang** [comment]
我刚开始搭建内网npm的时候也做过这事，设置那个 private pkgs 选项。大概搞了5个包左右。后来一律拒绝了。。。
