### ISSUE TITLE
cnpm怎么做类似于主从备份

### ISSUE THREAD

**Issue by avengang** [cnpm/cnpmjs.org#1528]
之前部署在一台服务器上，后面这台服务器磁盘出问题，导致整个cnpm都不能用，现在我们想做容灾，就是类似主从备份，多个节点，而且还想吧之前坏掉都磁盘都数据（已修好）放到新搭建的机器上，请问有办法吗？

**Comment by ShangguanQuail** [comment]
用 OSS 存 tar 包更合适一点

**Comment by alsotang** [comment]
https://github.com/cnpm/oss-cnpm 用云对象存储
