### ISSUE TITLE
electron/get 修改了镜像的读取地址路径，请管理人员协调一下调整镜像的路径别名

### ISSUE THREAD

**Issue by nickfan** [cnpm/cnpmjs.org#1530]
electron的官方的get子包的镜像下载路径变了，customDir中的版本号加了v前缀。

> 
> when i use mirror site
> it seems that @electron/get request the wrong url:
> 
> https://npm.taobao.org/mirrors/electron/v7.0.0/electron-v7.0.0-darwin-x64.zip
> in 6.1.2
> 
> https://npm.taobao.org/mirrors/electron/6.1.2/electron-v6.1.2-darwin-x64.zip
> 

https://github.com/electron/electron/issues/20739#issuecomment-546568300

请镜像这边按和github的release的路径一样调整一下

https://npm.taobao.org/mirrors/electron/

中的目录命名（加个v前缀软链？别名？）

**Comment by alsotang** [comment]
https://github.com/electron/get

用 `customDir` 能解决你的问题吗

**Comment by nickfan** [comment]
> https://github.com/electron/get
> 
> 用 `customDir` 能解决你的问题吗

customDir只能临时解决，难道每升级一个小版本号都要手工设置一遍customDir么？

**Comment by alsotang** [comment]
我也没办法，这个项目目前的维护处于停滞状态

**Comment by nickfan** [comment]
> 我也没办法，这个项目目前的维护处于停滞状态

能联系上管理员吗？

**Comment by fengmk2** [comment]
看官方 issue，已经解决

**Comment by nickfan** [comment]
> 看官方 issue，已经解决

能给个链接吗？我没看到issue被close哦：

https://github.com/electron/get/issues/120

**Comment by ekoneko** [comment]
可以参考下这个 [electron/electron#21251](https://github.com/electron/electron/issues/21251)
现在 electron 与 electron-builder 的 mirror 处理逻辑不一致，不建议 cnpm 调整别名

**Comment by nickfan** [comment]
> 可以参考下这个 [electron/electron#21251](https://github.com/electron/electron/issues/21251)
> 现在 electron 与 electron-builder 的 mirror 处理逻辑不一致，不建议 cnpm 调整别名

我没看懂这波操作，逻辑不一致就另外写个package然后写一堆说明如何绕道，不是应该发PR去推动么？
而且官方也没有close我提到的issue啊？只有人给出了临时解决方案，每次升级手工设置customDir，
这个明明是镜像批量加一下软链或者改一下策略就能解决的问题啊。

**Comment by nickfan** [comment]
> 看官方 issue，已经解决

@fengmk2 你看的哪个官方issue已解决？PR哪里？合并了么？
给个链接看一下？

**Comment by ekoneko** [comment]
> > 可以参考下这个 [electron/electron#21251](https://github.com/electron/electron/issues/21251)
> > 现在 electron 与 electron-builder 的 mirror 处理逻辑不一致，不建议 cnpm 调整别名
> 
> 我没看懂这波操作，逻辑不一致就另外写个package然后写一堆说明如何绕道，不是应该发PR去推动么？
> 而且官方也没有close我提到的issue啊？只有人给出了临时解决方案，每次升级手工设置customDir，
> 这个明明是镜像批量加一下软链或者改一下策略就能解决的问题啊。

现在 electron 与 electron-builder 是两套 mirror resolve 规则，让镜像提供两个下载地址这个行为太怪异了。

我只是建议去 electron 的 issues 下讨论，目前官方并没有给出一个令人满意的解决方案。

PS：我写的那个库目的是解决多个项目重复安装 Electron 的问题, 现阶段恰好能适用于解决 mirror 的问题，其他的临时方案在我看来并不适合团队项目与 CI.

**Comment by nickfan** [comment]
> > > 可以参考下这个 [electron/electron#21251](https://github.com/electron/electron/issues/21251)
> > > 现在 electron 与 electron-builder 的 mirror 处理逻辑不一致，不建议 cnpm 调整别名
> > 
> > 
> > 我没看懂这波操作，逻辑不一致就另外写个package然后写一堆说明如何绕道，不是应该发PR去推动么？
> > 而且官方也没有close我提到的issue啊？只有人给出了临时解决方案，每次升级手工设置customDir，
> > 这个明明是镜像批量加一下软链或者改一下策略就能解决的问题啊。
> 
> 现在 electron 与 electron-builder 是两套 mirror resolve 规则，让镜像提供两个下载地址这个行为太怪异了。
> 
> 我只是建议去 electron 的 issues 下讨论，目前官方并没有给出一个令人满意的解决方案。
> 
> PS：我写的那个库目的是解决多个项目重复安装 Electron 的问题, 现阶段恰好能适用于解决 mirror 的问题，其他的临时方案在我看来并不适合团队项目与 CI.

https://github.com/electron/get/pull/134

官方这边已经有人提PR了，不过他没看清淘宝的镜像是path里没v但文件名有v，已回复了，不过估计修改完再过审还要等等。

**Comment by fengmk2** [comment]
已经修复了，使用这个这个环境变量即可 

ELECTRON_MIRROR="https://cdn.npm.taobao.org/dist/electron/"

**Comment by nickfan** [comment]
ok,thx.
