### ISSUE TITLE
npm自身淘宝镜像断更了

### ISSUE THREAD

**Issue by JeffesJiang** [cnpm/cnpmjs.org#1531]
最新到v6.9.2往后的镜像都没有同步！

**Comment by kongfu-cat** [comment]
有更新，不过由于文件排序问题，文件在上方
![Snipaste_2020-01-13_20-55-15](https://user-images.githubusercontent.com/21188115/72257709-3bad1c00-3647-11ea-9ccf-5d2e878186ae.png)
