### ISSUE TITLE
fsevents 很久没更新了

### ISSUE THREAD

**Issue by gclove** [cnpm/cnpmjs.org#1532]
https://npm.taobao.org/mirrors/fsevents

https://www.npmjs.com/package/fsevents

**Comment by alsotang** [comment]
上面这个应该是老地址了。

**Comment by alsotang** [comment]
https://github.com/cnpm/binary-mirror-config/blob/master/package.json

**Comment by gclove** [comment]
嗯，这个新地址没问题啦 👍 @alsotang
