### ISSUE TITLE
cnpm adduser 报错

### ISSUE THREAD

**Issue by chenyucheng** [cnpm/cnpmjs.org#1533]
bogon:project cyc$ clear
bogon:project cyc$ cnpm adduser
Username: chenyucheng
Password:
Email: (this IS public) chenyucheng@2006@sina.com
npm ERR! code E404
npm ERR! 404 Not Found - PUT http://registry.cnpm.atf.cn/-/user/org.couchdb.user:chenyucheng
bogon:project cyc$

**Comment by chenyucheng** [comment]
配置问题。已经解决

**Comment by kailong321200875** [comment]
> 配置问题。已经解决

请问你是怎么解决的。我也遇到这个问题

**Comment by fency12** [comment]
> 配置问题。已经解决

请问怎么解决的？？？
