### ISSUE TITLE
electron-builder-binaries镜像失效

### ISSUE THREAD

**Issue by tomriddly** [cnpm/cnpmjs.org#1539]
根据官网提示，electron-builder应该使用如下配置
`ELECTRON_BUILDER_BINARIES_MIRROR=http://npm.taobao.org/mirrors/electron-builder-binaries/ electron-builder build`
![image](https://user-images.githubusercontent.com/14344444/70764748-7e06e300-1d93-11ea-96df-75167923ff79.png)
然而下载全部提示404，直接访问发现里面全是空的
![image](https://user-images.githubusercontent.com/14344444/70764778-937c0d00-1d93-11ea-81d5-1b778b0166c7.png)

**Comment by nshusr** [comment]
克隆也失败了，希望解决这个问题 :cry:

**Comment by Airkro** [comment]
目录为空

**Comment by alsotang** [comment]
https://github.com/cnpm/binary-mirror-config/blob/master/package.json

**Comment by Azimiao** [comment]
失效+1

**Comment by Matrixbirds** [comment]
失效+2 理论上应该用https才对

**Comment by fengmk2** [comment]
@tomriddly 你的环境变量写错了吧，我按官方的文档测试是可以的

```bash
ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/ electron-builder
```

**Comment by fengmk2** [comment]
use  `ELECTRON_MIRROR` instead of `ELECTRON_BUILDER_BINARIES_MIRROR`

**Comment by tomriddly** [comment]
> @tomriddly 你的环境变量写错了吧，我按官方的文档测试是可以的
> 
> ```shell
> ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/ electron-builder
> ```
> 
> ![image](https://user-images.githubusercontent.com/156269/80304881-af84c600-87eb-11ea-8057-f4078b5cbf35.png)

编译本平台只需要MIRROR这个，编译其他平台要下载相应的binaries，这俩不是一个，可以仔细看下官网和截图

**Comment by fengmk2** [comment]
都配置到一个 url 下，不过需要将 winCodeSign 等都同步掉。

```bash
ELECTRON_BUILDER_BINARIES_MIRROR=https://npm.taobao.org/mirrors/electron/ ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/ electron-builder --win
```

![image](https://user-images.githubusercontent.com/156269/80305199-f96eab80-87ed-11ea-9670-58dd908a5f31.png)

**Comment by fengmk2** [comment]
> > @tomriddly 你的环境变量写错了吧，我按官方的文档测试是可以的
> > ```shell
> > ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/ electron-builder
> > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/156269/80304881-af84c600-87eb-11ea-8057-f4078b5cbf35.png)
> 
> 编译本平台只需要MIRROR这个，编译其他平台要下载相应的binaries，这俩不是一个，可以仔细看下官网和截图

主要你正文没有提到跨平台编译，所以我只写了一种。跨平台编译本身就是一件复杂的事情。

**Comment by tomriddly** [comment]
> 都配置到一个 url 下，不过需要将 winCodeSign 等都同步掉。
> 
> ```shell
> ELECTRON_BUILDER_BINARIES_MIRROR=https://npm.taobao.org/mirrors/electron/ ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/ electron-builder --win
> ```
> 
> ![image](https://user-images.githubusercontent.com/156269/80305199-f96eab80-87ed-11ea-9670-58dd908a5f31.png)

本身就是需要从这个镜像里面获取winCodeSign这些东西，我看你这个截图没有这些东西，包括我实验也是不成功的。
---
跨平台编译也只是需要这一个配置而已啊……应该不会特别复杂吧。。。。

**Comment by fengmk2** [comment]
已经同步好了。

```bash
ELECTRON_BUILDER_BINARIES_MIRROR=https://cnpmjs.org/mirrors/electron-builder-binaries/ ELECTRON_MIRROR=https://npm.taobao.org/mirrors/electron/ ./node_modules/.bin/electron-builder --linux

ELECTRON_BUILDER_BINARIES_MIRROR=https://cnpmjs.org/mirrors/electron-builder-binaries/ ELECTRON_MIRROR=https://npm.taobao.org/mirrors/electron/ ./node_modules/.bin/electron-builder --win
```

![image](https://user-images.githubusercontent.com/156269/80306593-d5fc2e80-87f6-11ea-94a2-9a001de96751.png)

**Comment by tomriddly** [comment]
@fengmk2 牛逼！o(￣▽￣)ｄ

**Comment by Matrixbirds** [comment]
@fengmk2 牛逼！o(￣▽￣)ｄ

**Comment by ytfrdfiw** [comment]
现在应该是可以了。
