### ISSUE TITLE
Only administrators can unpublish module

### ISSUE THREAD

**Issue by johnzhu12** [cnpm/cnpmjs.org#1545]
怎么把自己账号设置成admin

**Comment by ldsyzjb** [comment]
请问你这个是怎么解决的？

**Comment by ldsyzjb** [comment]
使用admin账户登陆。
在配置文件中admins属性中就是admin账户集合，使用任意一个登陆就可以unpublish。
键名为用户名，键值为邮箱，默认没有密码。
