### ISSUE TITLE
electron release版本路径问题

### ISSUE THREAD

**Issue by canvascat** [cnpm/cnpmjs.org#1546]
比如7.1.18版本的路径是`https://github.com/electron/electron/releases/v7.1.8/`而不是`https://github.com/electron/electron/releases/7.1.8/`了。

![image](https://user-images.githubusercontent.com/31235016/72232237-b56ae880-35fa-11ea-8185-9f6d892ffa74.png)

[electron/get](https://github.com/electron/get/blob/master/src/index.ts)包中会对`version`进行`normalizeVersion`处理
![image](https://user-images.githubusercontent.com/31235016/72232298-2b6f4f80-35fb-11ea-9b24-f07376ca61a4.png)
![image](https://user-images.githubusercontent.com/31235016/72232340-8739d880-35fb-11ea-9e8f-41b05ee4578d.png)

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmjs.org/issues/1530#issuecomment-561081645 请参考解决办法。

**Comment by fengmk2** [comment]
https://docs.npmjs.com/cli/run-script

> Scripts are run from the root of the module, regardless of what your current working directory is when you call npm run. If you want your script to use different behavior based on what subdirectory you’re in, you can use the **INIT_CWD** environment variable, which holds the full path you were in when you ran npm run.

**Comment by sxd1140** [comment]
之前替换成`https://cdn.npm.taobao.org/dist/electron/` 好了
