### ISSUE TITLE
electron的镜像地址错了

### ISSUE THREAD

**Issue by Gilbert-Qian** [cnpm/cnpmjs.org#1551]
GitHub上面路径和你们不一样，拼接的时候会出错，他们版本号前面有个v，望修复

**Comment by Matrixbirds** [comment]
试试这个？
```bash
export ELECTRON_MIRROR=https://npm.taobao.org/mirrors/electron/
```

**Comment by Gilbert-Qian** [comment]
> 试试这个？
> 
> ```shell
> export ELECTRON_MIRROR=https://npm.taobao.org/mirrors/electron/
> ```

没用的，问题是electron拼接出来的URL在镜像里面没有，是404，要自己去源码里把v删了。

**Comment by fuzi1996** [comment]
可以使用这里面提供的方法-->https://blog.csdn.net/qq_27005821/article/details/102748201

**Comment by umbrella22** [comment]
请更改您的地址为：
ELECTRON_MIRROR="https://cdn.npm.taobao.org/dist/electron/"

**Comment by Gilbert-Qian** [comment]
> 请更改您的地址为：
> ELECTRON_MIRROR="https://cdn.npm.taobao.org/dist/electron/"

这个是正解，的确可以访问到，谢谢大佬

**Comment by LinDaiDai** [comment]
非常感谢。但是好像应该写成：ELECTRON_MIRROR=https://cdn.npm.taobao.org/dist/electron/

**Comment by fengmk2** [comment]
@LinDaiDai 正确的应该是 

```
ELECTRON_MIRROR=https://npmmirror.com/mirrors/electron/
```
