### ISSUE TITLE
electron 8.0.1 版本缺失

### ISSUE THREAD

**Issue by alsotang** [cnpm/cnpmjs.org#1553]
截止20190217

https://npm.taobao.org/mirrors/electron/  最新版8.0.0

https://npm.taobao.org/package/electron 最新版8.0.1

官方已经更新3天了。mirrors这里版本号没有跟上。

**Comment by JeaceLiu** [comment]
而且使用指定版本安装（mac 平台  npm 版本  6.13.4 ） 如  @8.0.0  报错，  原因为路径不对，npm 生成的路径为 xxxx/v8.0.0/   实际没有 “v”

**Comment by alsotang** [comment]
@JeaceLiu v的问题搜issue，已经解决

**Comment by devmings** [comment]
我昨天也是没有这个版本，后来去华为的镜像下载的

**Comment by yw981** [comment]
> @JeaceLiu v的问题搜issue，已经解决

同样的问题，命令生成的地址是https://npm.taobao.org/mirrors/electron/v8.0.2/xxx实际地址https://npm.taobao.org/mirrors/electron/8.0.2/xxx没有前面那个v，请问如何解决？谢谢

**Comment by alsotang** [comment]
默默修复了看来。
