### ISSUE TITLE
electron 预编译包镜像 URL 中的 version 没有带 ‘v’，导致安装下载预编译包时 404

### ISSUE THREAD

**Issue by zzzze** [cnpm/cnpmjs.org#1554]
electron 预编译包镜像 URL 中的 version 没有带 ‘v’，导致安装时，下载预编译包都 404。

  * @electron/get 生成的 URL：`https://npm.taobao.org/mirrors/electron/v8.0.0/electron-v8.0.0-darwin-x64.zip`
  * 淘宝镜像源中的 URL：`https://npm.taobao.org/mirrors/electron/8.0.0/electron-v8.0.0-darwin-x64.zip`

**Comment by alsotang** [comment]
更新cnpm客户端应该就好了

详情看 https://github.com/cnpm/cnpmjs.org/issues/1551
