### ISSUE TITLE
electron 8.0.0的版本镜像安装有问题

### ISSUE THREAD

**Issue by c690554125** [cnpm/cnpmjs.org#1555]
@electron/get 这个包中对下载的路径的版本号做了一个Normalize。

function normalizeVersion(version) {
    if (!version.startsWith('v')) {
        return `v${version}`;
    }
    return version;
}
exports.normalizeVersion = normalizeVersion;

镜像这边的路径是 https://npm.taobao.org/mirrors/electron/8.0.0/，而下载的时候，路径是https://npm.taobao.org/mirrors/electron/v8.0.0/ 导致404。

**Comment by c690554125** [comment]
如果用的是阿里的镜像包的话，临时解决，可以在`@electron/get/cjs/utils.js`中normalizeVersion函数直接返回version。

这个问题根本解决是镜像这边改路径？还是electron那边改呢？

**Comment by alsotang** [comment]
https://github.com/cnpm/cnpmjs.org/issues/1551
