### ISSUE TITLE
Cypress 安装卡住, 搜到的淘宝源镜像不能用

### ISSUE THREAD

**Issue by Stupidism** [cnpm/cnpmjs.org#1560]
百度搜到的第一个链接: https://npm.taobao.org/mirrors/cypress

直接访问镜像地址: https://cdn.cypress.io/desktop/
能拿到 meta 信息:
```
{"name":"Cypress","version":"4.2.0","packages":{"mac":{"url":"https://cdn.cypress.io/desktop/4.2.0/darwin-x64/cypress.zip"},"win":{"url":"https://cdn.cypress.io/desktop/4.2.0/win32-ia32/cypress.zip"},"linux64":{"url":"https://cdn.cypress.io/desktop/4.2.0/linux-x64/cypress.zip"},"darwin":{"url":"https://cdn.cypress.io/desktop/4.2.0/darwin-x64/cypress.zip"},"win32":{"url":"https://cdn.cypress.io/desktop/4.2.0/win32-ia32/cypress.zip"},"linux":{"url":"https://cdn.cypress.io/desktop/4.2.0/linux-x64/cypress.zip"},"darwin-x64":{"url":"https://cdn.cypress.io/desktop/4.2.0/darwin-x64/cypress.zip"},"linux-x64":{"url":"https://cdn.cypress.io/desktop/4.2.0/linux-x64/cypress.zip"},"win32-ia32":{"url":"https://cdn.cypress.io/desktop/4.2.0/win32-ia32/cypress.zip"},"win32-x64":{"url":"https://cdn.cypress.io/desktop/4.2.0/win32-x64/cypress.zip"}}}
```

但是[下载](https://cdn.cypress.io/desktop/4.2.0?platform=darwin&arch=x64)的话结果就是 403:

![image](https://user-images.githubusercontent.com/5801015/77169147-fa783300-6af3-11ea-9e5b-2542083fd90b.png)

**Comment by fengmk2** [comment]
~~https://npm.taobao.org/mirrors/cypress/~~

https://npmmirror.com/mirrors/cypress/

**Comment by fengmk2** [comment]
可以的。

**Comment by hongdeyuan** [comment]
> https://npmmirror.com/mirrors/cypress/

没有  linux-arm64 版本
![image](https://github.com/cnpm/cnpmjs.org/assets/37143703/42131431-c6ba-4787-82a3-f2d3cdabe7b5)

@fengmk2

**Comment by fengmk2** [comment]
@hongdeyuan https://registry.npmmirror.com/binary.html?path=cypress/12.7.0/linux-arm64/
