### ISSUE TITLE
atom-shell 镜像目前只更新到19年10月份的 v7.0.0-beta.7 版本，后续的新版本都没有更新。

### ISSUE THREAD

**Issue by LeuisKen** [cnpm/cnpmjs.org#1561]
atom-shell 镜像目前只更新到19年10月份的 v7.0.0-beta.7 版本，后续的新版本都没有更新。

_Originally posted by @Constaline in https://github.com/cnpm/cnpmjs.org/issues/1206#issuecomment-593066237_

**Comment by loverto** [comment]
atom-shell 后来改名为 electron了，现在atom-shell 是electron的地址，
如果想用electron header来构建node 本地模块的话，需要让阿里的人再新增一个镜像地址，来镜像electron header
源地址是：https://electronjs.org/headers

**Comment by loverto** [comment]
刚刚用构建了个地址试了试，最后跟现在atom-shell的地址好像是同一个的样子
https://electronjs.org/headers/v8.2.1/node-v8.2.1-headers.tar.gz 这个地址，最后会重定向到一下的地址
https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v8.2.1/node-v8.2.1-headers.tar.gz
