### ISSUE TITLE
不是说十分钟与官方同步一次么，为什么有些模块还需要手动要求同步更新？

### ISSUE THREAD

**Issue by CHN-STUDENT** [cnpm/cnpmjs.org#1564]
如题，今天装node-red，结果提示jsonata@1.8.2找不到，我搜了一下还是上次的1.8.1版本，npm官方这个包在20多天前就发布了，为什么现在还没有么，难道只能用cnpm指令？

**Comment by CHN-STUDENT** [comment]
附手动同步方法：https://npm.taobao.org/sync/ + 包名
如：https://npm.taobao.org/sync/jsonata

**Comment by HaveF** [comment]
醉了，但这是为什么...

**Comment by jiangtj** [comment]
手动同步也没用，因为cnpm还没同步，这该怎么处理。。。

**Comment by fengmk2** [comment]
相同问题 https://github.com/cnpm/cnpmjs.org/issues/1582
