### ISSUE TITLE
和npm源的同步问题

### ISSUE THREAD

**Issue by HaveF** [cnpm/cnpmjs.org#1582]
谢谢提供同步源。汇报一个问题：

最近发现好几次和npm源不同步，在其他的 issue 中也是类似问题。

现在时间是 7/31，13: 52：

[@fluentui/date-time-utilities - npm](https://www.npmjs.com/package/@fluentui/date-time-utilities)
7.3.0 • Public • Published 7 days ago

而 https://r.cnpmjs.org/@fluentui/date-time-utilities 显示是 `{"latest":"7.1.5"}`

[而 registry.npm.taobao.org 是从 r.cnpmjs.org 进行全量同步的.](https://developer.aliyun.com/mirror/NPM?from=tnpm)

所以导致 registry.npm.taobao.org 中也是旧包

#1581 , #1579 , 以及我以为的 [package 不同步了 · Issue #548 · alibaba/hooks](https://github.com/alibaba/hooks/issues/548)

原因都是 r.cnpmjs.org 没有同步。

根据 @fluentui/date-time-utilities 的更新时间显示，`7 days ago`，7天前的包啊！

这说明 r.cnpmjs.org 内部机制只在某一个时刻同步，并不日常检查更新。

**Comment by HaveF** [comment]
简单翻了下 issue, 原来是个顽疾...

**Comment by fengmk2** [comment]
目前没法保证100%同步，如果发现有版本确实，请手动执行一次同步。
