### ISSUE TITLE
当 Accpet 头包含 application/vnd.npm.install-v1+json 时 peerDependenciesMeta 缺失

### ISSUE THREAD

**Issue by thynson** [cnpm/cnpmjs.org#1584]
会导致当某些 optional peer dependencies 的缺失的情况下产生unmet peer dependencies警告。
原本以为是 pnpm 的 bug，报到了 https://github.com/pnpm/pnpm/issues/2551, 详见该链接。

**Comment by fengmk2** [comment]
@thynson fixed in 283f149, thanks again.
