### ISSUE TITLE
https://github.com.cnpmjs.org/ 你家用这个来钓鱼吗？无耻！！！！（大家小心）

### ISSUE THREAD

**Issue by andygithubchen** [cnpm/cnpmjs.org#1601]

**Comment by alsotang** [comment]
发生了什么？

**Comment by lblblong** [comment]
发生甚麽事了

**Comment by colmugx** [comment]
一个 github.com 镜像站而已，直接 clone 一些「编译依赖」挺好的

那么大一个 cnpmjs.org 还能被钓鱼那也挺优秀的

**Comment by andygithubchen** [comment]
我当时访问 https://github.com.cnpmjs.org/ 时Chrome浏览器提示如下图，我的判断也是来自于此，出于本人不常用cnpmjs和懒惰的原因没有验证用https://github.com.cnpmjs.org/来clone 编译依赖或直接用github账号在此域名下登录是否有安全问题。再者，我本人仅凭Chrome浏览器提示就用市侩的句式做出了粗陋的主观臆断，在此向cnpmjs的作者、贡献者、使用者和关心者们致以诚挚的歉意，对不起！同时我就关闭此Issues。
![1](https://user-images.githubusercontent.com/7202281/102677332-df4e6700-41dc-11eb-8fe4-aee482688034.png)
