### ISSUE TITLE
需要调整 cypress 的镜像目录

### ISSUE THREAD

**Issue by colmugx** [cnpm/cnpmjs.org#1608]
https://npm.taobao.org/mirrors/cypress 中：

> Mirror index of https://cdn.cypress.io/desktop/

而 [Cypress 的文档](https://docs.cypress.io/guides/getting-started/installing-cypress.html#Mirroring)中是如此描述他们的环境变量是如何工作的

![image](https://user-images.githubusercontent.com/21327913/102862525-2dc56500-446c-11eb-93d9-de1fda1db282.png)

**Comment by fengmk2** [comment]
使用最新的环境变量 https://github.com/cnpm/binary-mirror-config/pull/41
