### ISSUE TITLE
npm adduser失败

### ISSUE THREAD

**Issue by fency12** [cnpm/cnpmjs.org#1609]
经过多次测试，发现添加账号失败，报错如下，请协助
[meprint@huaxing02 cnpmjs.org]$ npm adduser
Username: 123
Password: 
Email: (this IS public) 123@qq.com
npm ERR! code E404
npm ERR! 404 Not Found - PUT http://xxxxx.xxxxxxx.com/-/user/org.couchdb.user:123

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/meprint/.npm/_logs/2020-12-30T08_53_38_486Z-debug.log
[meprint@huaxing02 cnpmjs.org]$ cat ^C
[meprint@huaxing02 cnpmjs.org]$ vim  /home/meprint/.npm/_logs/2020-12-30T08_53_38_486Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/node-v14.15.3-linux-x64/bin/node',
1 verbose cli   '/usr/sbin/npm',
1 verbose cli   'adduser'
1 verbose cli ]
2 info using npm@6.14.9
5 verbose web login before first POST
6 http fetch POST 404 http://xxxxx.xxxxxxx.com/-/v1/login 68ms
7 verbose web login not supported, trying couch
8 verbose login before first PUT {
8 verbose login   _id: 'org.couchdb.user:123',
8 verbose login   name: '123',
8 verbose login   password: 'XXXXX',
8 verbose login   type: 'user',
8 verbose login   roles: [],
8 verbose login   date: '2020-12-30T08:53:38.437Z'
8 verbose login }
9 http fetch PUT 404 http://xxxxx.xxxxxxx.com/-/user/org.couchdb.user:123 19ms
10 verbose adduser before first PUT {
10 verbose adduser   _id: 'org.couchdb.user:123',
10 verbose adduser   name: '123',
10 verbose adduser   password: 'XXXXX',
10 verbose adduser   email: '123@qq.com',
10 verbose adduser   type: 'user',
10 verbose adduser   roles: [],
10 verbose adduser   date: '2020-12-30T08:53:38.458Z'
10 verbose adduser }
11 http fetch PUT 404 http://xxxxx.xxxxxxx.com/-/user/org.couchdb.user:123 16ms
12 verbose stack Error: 404 Not Found - PUT http://xxxxx.xxxxxxx.com/-/user/org.couchdb.user:123
12 verbose stack     at /usr/local/node-v14.15.3-linux-x64/lib/node_modules/npm/node_modules/npm-registry-fetch/check
-response.js:117:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
13 verbose statusCode 404
14 verbose cwd /home/meprint/data/app/npm/cnpmjs.org
15 verbose Linux 3.10.0-1062.el7.x86_64
16 verbose argv "/usr/local/node-v14.15.3-linux-x64/bin/node" "/usr/sbin/npm" "adduser"
17 verbose node v14.15.3
18 verbose npm  v6.14.9
19 error code E404
20 error 404 Not Found - PUT http://xxxxx.xxxxxxx.com/-/user/org.couchdb.user:123
21 verbose exit [ 1, true ]

**Comment by fency12** [comment]
环境如下：
[meprint@huaxing02 cnpmjs.org]$ npm -v
6.14.9
[meprint@huaxing02 cnpmjs.org]$ node -v
v14.15.3
[meprint@huaxing02 cnpmjs.org]$ cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)

**Comment by CookyG** [comment]
+1

**Comment by fency12** [comment]
@tq0fqeu    @焦霸   麻烦看下

**Comment by jwucong** [comment]
+1, 官方团队回复还是不够及时呀

**Comment by fency12** [comment]
已解决！没啥问题，是我搞错了nginx的配置，建议再测试前不要加nginx加的话一定要确定不同域名对应不同端口，她有两个端口一个是web访问的，一个是接口的我搞混了。
