### ISSUE TITLE
除了淘宝，还有其他npm镜像么

### ISSUE THREAD

**Issue by jiangtj** [cnpm/cnpmjs.org#1610]
淘宝npm镜像存在同步问题，我需要一个镜像下载包，毕竟npm完全被屏蔽了 :simple_smile:

**Comment by jiangtj** [comment]
https://mirrors.huaweicloud.com/repository/npm/  已测试华为云的镜像，同步比淘宝还慢，也不及时同步（如果包不存在）

**Comment by gozeon** [comment]
淘宝最近总500啊

**Comment by ypli0629** [comment]
> 淘宝最近总500啊
+1 ，CI 一直挂

**Comment by CeresY** [comment]
今天又是502服了

**Comment by fengmk2** [comment]
稳定性问题已经在跟进，由于访问量越来越大，并且淘宝镜像是完全免费并且非盈利的方式在维护的。
如果大家是强依赖在公司业务核心流程，建议搭建私有 npm registry，这是对公司稳定性保障的。
淘宝 npm 镜像我们会努力往 99.9% 的可用率上做。

借此再次感谢阿里云的云资源赞助，否则我们连这个仅有的能够做到尽可能全量同步的 npm 镜像都没了。

**Comment by jiangtj** [comment]
> 私有 npm registry

现在的问题是，我们无法访问npm仓库，小团队怕都不会给我们搭vpn的权利把，私有 npm registry完全不现实

**Comment by nAnderYang** [comment]
看样子要搭建一 个proxy 到官方去同步了.

**Comment by nAnderYang** [comment]
@fengmk2  希望能增加一和source 在首选source失效或者错误不可访问的时候可以从次选source进行数据同步。

**Comment by fengmk2** [comment]
华为和腾讯的镜像大家可以收藏 https://mirrors.cloud.tencent.com/help/npm.html
