### ISSUE TITLE
repository throws 502 error

### ISSUE THREAD

**Issue by MananJethwani** [cnpm/cnpmjs.org#1622]
I am trying to install phantomJs while using npm ci in GitHub action on a project for that I am using something like this -> 
```run: npm ci
      env:
        PHANTOMJS_CDNURL: http://cnpmjs.org/downloads
```
       
but I end up getting error 502. have a look here -> https://github.com/MananJethwani/mwoffliner/runs/1894056308?check_suite_focus=true

**Comment by fengmk2** [comment]
PHANTOMJS_CDNURL=https://npmmirror.com/mirrors/phantomjs
