### ISSUE TITLE
npm whoami 执行接口/-/whoami 会被 redirect 到 sourceNpmRegistry

### ISSUE THREAD

**Issue by edward32tnt** [cnpm/cnpmjs.org#1623]
https://github.com/cnpm/cnpmjs.org/blob/39c322332ffafc512bf56c1679d2904fece2ae07/middleware/proxy_to_npm.js#L11

看到是正则匹配中了 /-/whoami 的路由

**Comment by Link-X** [comment]
+1 为啥这个问题没人处理

**Comment by luckyriko** [comment]
+1

**Comment by killagu** [comment]
是自己部署了一套吗？ cnpm 的 whoami 接口是可以 work 的，可以检查下配置。

cnpmjs.org 的 whoami 没啥意义，cnpmjs.org 只是一个镜像，不需要登录的。

**Comment by jerikchan** [comment]
+1
