### ISSUE TITLE
下载模块报错

### ISSUE THREAD

**Issue by zhaozhuangwang** [cnpm/cnpmjs.org#1627]
cnpmjs : 3.0.0-rc.40
node :  14.15.0
我是部署到centos7系统里， 然后 通过npm(或者设置一个新的指令指定IP到此)，来下载包
目的是为了断网时候，常用的包可以本地获取到

centos7   配置
IP : 192.168.0.109
cnpmjs  config/index配置：
// 私有模式下，只有管理员才能发布模块。非管理员发布模块式命名必须
enablePrivate: false,
// none: 不进行同步，只管理用户上传的私有模块，公共模块直接从上游获取
// exist: 只同步已经存在于数据库的模块
// all: 定时同步所有源registry的模块
syncModel:'all',

win10  设置项
npm config set registry  http://192.168.0.109:7001/
问题如下 问题一
---------------------------------------------------------------------------------------------------
当我下载vue 或者 react的时候 会有以后报错说缺少包，我在端口7002 添加此包名也是报错
请问我该如何解决这个问题，谢谢！ 请回答一下

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vue/cli-ui@^5.0.0-alpha.7.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@vue/cli'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\赵庄王\AppData\Roaming\npm-cache\_logs\2021-03-11T13_25_28_127Z-debug.log

问题二
如果问题一解决了，我想开启私有包，会不会造成其他获取问题呢   如果有老猿，指点一下，谢谢！

**Comment by shrinktofit** [comment]
顶。只要用 npm 7.x 就总会找不到 taobao 和 cnpm 都找不到
