### ISSUE TITLE
建议增加一个sync 使用过 的模式

### ISSUE THREAD

**Issue by nAnderYang** [cnpm/cnpmjs.org#1631]
该模式不需要同步all和exist 只同步我从这个cnpm拉过的包。既减少磁盘占用，也加速安装的速度。还可以把本地的数据包同步到内网节点离线使用。

**Comment by sm0king** [comment]
同求

**Comment by laitianliu** [comment]
对啊，太需要这个了。只需要同步已使用的版本就行，又一些特别老的版本，就是浪费空间。没有必要所有版本都同步下来。
