### ISSUE TITLE
私有部署7001无法访问

### ISSUE THREAD

**Issue by Jonathan-Rao** [cnpm/cnpmjs.org#1633]
私有部署成功后，7002网站可以正常访问，但是7001无法访问？什么问题
![QQ截图20210326095840](https://user-images.githubusercontent.com/16660755/112566399-df808300-8e19-11eb-9bb6-41069ea123a7.png)

**Comment by Jonathan-Rao** [comment]
已解决

**Comment by spadeACE7** [comment]
> 已解决
请问老哥如何解决这个问题的

**Comment by spadeACE7** [comment]
请问老哥如何解决这个问题的？

**Comment by afuryboy** [comment]
应该是数据没连接上，有个数据库配置dialect ，看下，把默认的改为mysql
