### ISSUE TITLE
测试通了mysql数据库，但是在postgres下失败

### ISSUE THREAD

**Issue by zhangsai521314** [cnpm/cnpmjs.org#1652]
除了数据库配置信息更改外其他配置未更改。
因为包里只有mysql的db.sql语句。我在导入mysql后转换语句到了pg库中。主键、序列都有。
但是在使用cnpm登录时一致卡着，我怀疑是数据库新增用户失败导致。不知怎么处理
[cnpmjg_pg_db.zip](https://github.com/cnpm/cnpmjs.org/files/6715216/cnpmjg_pg_db.zip)
。附上pg的sql语句。

**Comment by fengmk2** [comment]
目前测试只在 mysql 和 sqlite 下跑通，pg 还没测试过。
