### ISSUE TITLE
执行 docker-compose up 报错

### ISSUE THREAD

**Issue by spadeACE7** [cnpm/cnpmjs.org#1663]
/var/app/cnpmjs.org/config/config.js:131
nfs: require('fs-cnpm')({
                  ^
TypeError: Class constructor LocalDiskClient cannot be invoked without 'new'

**Comment by spadeACE7** [comment]
已解决 劳烦将 docs/dockerize/config.js

**Comment by Link-X** [comment]
请问这个问题是啥情况

**Comment by Link-X** [comment]
> /var/app/cnpmjs.org/config/config.js:131
> nfs: require('fs-cnpm')({
> ^
> TypeError: Class constructor LocalDiskClient 不能在没有'new'的情况下被调用
这个问题是啥情况

**Comment by Link-X** [comment]
找到了。https://github.com/cnpm/cnpmjs.org/pull/1656
