### ISSUE TITLE
如何同步另外一个私有的npm的一些私有包，附带历史版本的？

### ISSUE THREAD

**Issue by yagang94** [cnpm/cnpmjs.org#1664]
看了下文档以及源码，没有发现有同步另外一个私有的包的操作

**Comment by yagang94** [comment]
@fengmk2   救救孩子

**Comment by gemwuu** [comment]
数据 dump 出来，然后更新到数据库？

**Comment by yagang94** [comment]
> 数据转储出来，然后更新到数据库？

数据库中有多个表，更新数据库表会有遗漏且会有问题吧

**Comment by fengmk2** [comment]
你可以配置你的同步源为这个 npm registry 即可。
