### ISSUE TITLE
npm7 下 addon 安装淘宝源和官方源的行为不一致

### ISSUE THREAD

**Issue by hyj1991** [cnpm/cnpmjs.org#1667]
## 复现步骤

* `npm i npm -g` 将 npm 升级到最新 （当前是 `7.24.1`）
* `npm set registry https://registry.npmjs.org` 指向官方源
  * `npm i xprofiler`         **安装成功**
* `npm set registry https://registry.npm.taobao.org` 指向淘宝源
  * `npm i xprofiler`         **安装失败**

---

## 失败信息

![image](https://user-images.githubusercontent.com/19908330/134610609-1309a725-4e99-423a-9313-7fa1d7a53723.png)

---

## 大致原因

`npm7` 指向官方源时，install 会根据返回信息正常使用 `xprofiler` 包的 `package.json` 定义的 `install` 脚本来安装：

```bash
node-pre-gyp install --fallback-to-build
```

这样就是正常安装。

而 `npm7` 指向淘宝源时，install 返回的信息里 `package.json` 定义的 `install` 为空，所以链到 cli 默认的 `node-gyp rebuild` 来安装 addon 导致失败。

---

## 更多信息

使用 `npm6` 及以下的 npm cli 安装不管是官方源还是淘宝源都是正常的。

**Comment by fengmk2** [comment]
看来又是精简 json 返回的数据有问题

npmmirror

curl -v https://registry.npmmirror.com/xprofiler -H 'accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*' |json|less

![image](https://user-images.githubusercontent.com/156269/140645960-e3ef4806-2481-4b6b-8b9e-3d232b60cb6d.png)

npm 官方，多了一个 `"hasInstallScript": true`

![image](https://user-images.githubusercontent.com/156269/140645981-1990107c-9458-40cd-86cf-f8031aa2d8da.png)

**Comment by fengmk2** [comment]
https://github.com/npm/arborist/commit/1e5ac3047845e27a9f421c8b05e33080053cf4e4

**Comment by fengmk2** [comment]
又是 https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md#abbreviated-version-object 没有写的私有属性。

**Comment by fengmk2** [comment]
https://github.com/npm/registry/pull/16

**Comment by fengmk2** [comment]
@hyj1991 fixed now

```bash
npm i xprofiler --registry=https://registry.npmmirror.com

added 92 packages in 4s

tree node_modules/xprofiler
node_modules/xprofiler
├── LICENSE
├── README.md
├── bin
│   ├── xprofctl
│   └── xprofctl.json
├── binding.gyp
├── build
│   └── binding
│       └── Release
│           └── node-v93-darwin-x64
│               └── xprofiler.node
├── index.d.ts
├── lib
│   ├── clean.js
│   ├── configure.js
│   ├── utils.js
│   └── xctl.js
├── package.json

```

**Comment by fengmk2** [comment]
libc https://github.com/cnpm/npminstall/issues/386

**Comment by kamilic** [comment]
我这边发现 npm 8 也是一样的问题，在安装 xprofiler 时必须要指定官方的源才能安装成功。
@fengmk2 这个修改是上线了吗？

**Comment by kamilic** [comment]
我对比了下，就是缺少了 `"hasInstallScript": true` 的问题
