### ISSUE TITLE
atom-shell库很久没同步了，希望能同步下

### ISSUE THREAD

**Issue by vae1970** [cnpm/cnpmjs.org#1669]
atom-shell里electron相关的库最新已经到15了，但是镜像库才到6，希望能同步下，谢谢了

**Comment by fengmk2** [comment]
@vae1970 你是怎样使用 electron 还会依赖到 atom-shell 呢？

**Comment by fengmk2** [comment]
@zcbenz atom-shell 现在还在维护么？是否有什么方式可以持续同步更新？

**Comment by zcbenz** [comment]
atom-shell这个包没人维护了，现在都是在用electron

**Comment by fengmk2** [comment]
@vae1970 请更新到最新的 electron 吧
