### ISSUE TITLE
NPM LOGOUT ERROR

### ISSUE THREAD

**Issue by danielsss** [cnpm/cnpmjs.org#1676]
* Node: 16.8.0
* cnpmjs.prg: branched from [3.0.0-rc.39](https://github.com/cnpm/cnpmjs.org/commits/3.0.0-rc.39)

> npm logout --registry=https://registry.xnpm.* gets error as below:
```js
10 verbose Darwin 20.6.0
11 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/*/.cnpmrc" "--disturl=https://npmmirror.com/mirrors/node" "--registry=https://registry.xnpm.*" "logout"
12 verbose node v16.8.0
13 verbose npm  v6.14.15
14 error code E404
15 error 404 Not Found - DELETE https://registry.xnpm.*/-/user/token/* - [not_found] document not found
16 verbose exit [ 1, true ]
```

* Tried to fix this issue

I've added `/-/user/token` instead of `/-/npm/v1/tokens/token/:UUID` and then, error disappeared.

Obviously, the error caused by router claims or NPM version. I don't know what is the best plan to fix this issue, then only reports here.

**Comment by fengmk2** [comment]
We have not implemented this interface yet. 😭
