### ISSUE TITLE
https://npmmirror.com/ 好像同步出问题了？

### ISSUE THREAD

**Issue by loveatting** [cnpm/cnpmjs.org#1678]
好像同步出问题了？，一直卡在这里
![image](https://user-images.githubusercontent.com/18542865/141045082-ebd0d733-6c75-4b82-931f-b00766e5e4e0.png)

**Comment by loveatting** [comment]
我用到的手动到npmmirror上点sync了，感觉应该还有很多是没更新过来的

**Comment by loveatting** [comment]
@fengmk2 需要尽快处理下

**Comment by danielsss** [comment]
@fengmk2 

这个问题处理的怎么样了 ？

今天遇见一个问题，安装 `electron-to-chromium` 时发现同步的版本不一致(Error: npm verb stack electron-to-chromium: No matching version found for electron-to-chromium@1.3.896.)。猜测是同步问题导致。

* npmjs.com 最新版本 `electron-to-chromium`@`1.3.896`
* npmmirror.com 最新版本 `electron-to-chromium`@`1.3.895`

**Comment by killagu** [comment]
已经跟上了，如果有没同步的可以手动同步一下。

![image](https://user-images.githubusercontent.com/6897780/141777746-96805fba-eff2-4aa4-93af-847825f121e0.png)

点击页面上的 sync 即可。

**Comment by danielsss** [comment]
@killagu 感谢，已经解决
