### ISSUE TITLE
怎么从 3.0.0-beta.1 升级到 3.0.0-rc.50 版？

### ISSUE THREAD

**Issue by benleilei** [cnpm/cnpmjs.org#1679]
原先安装的 3.0.0-beta.1 版本，怎么升级到 3.0.0-rc.50 版？
直接代码覆盖吗？数据库怎么升级？有没有文档？

3.0.0-beta.1 版对 npm 7/8 支持不好，不知道 3.0.0-rc.50 好不好

**Comment by zenxds** [comment]
自己diff一下两个分支，看下model的修改，docs/db.sql里面有注释后的ALTER TABLE语句，对应着执行一下就行，我刚从alpha.8升级上来，主要也就是几个varchar长度的修改
