### ISSUE TITLE
npm login : npm ERR! 500 Internal Server Error - PUT https://registry-npm.huami.com/-/user/org.couchdb.user:

### ISSUE THREAD

**Issue by redredredredredred** [cnpm/cnpmjs.org#1686]
错误描述：
部署私服，切换源正确。然后本地执行 npm login，结果需要输入用户名、密码、邮箱，然后执行结果变成调用 注册接口，并且显示501错误；

`npm ERR! 500 Internal Server Error - PUT https://registry-npm.huami.com/-/user/org.couchdb.user:someone`

npm login应该调用，登录接口吧，但是

`https://github.com/cnpm/cnpmjs.org/blob/master/routes/registry.js` 路由中未看到登录接口，此处是不是存在问题？如何解决这个报错，谢谢

命令行界面：
![image](https://user-images.githubusercontent.com/10527677/147351797-d88770fb-a5e5-4bb8-b2e0-e7fe3a31ca80.png)

**Comment by redredredredredred** [comment]
@fengmk2  跪求答复和解决

**Comment by fengmk2** [comment]
你看看 registry-npm.huami.com 的服务端报错日志，里面有报错信息的。

**Comment by redredredredredred** [comment]
问题已经解决。
原因：因为对token功能有需求，故对项目进行最新代码拉取进行升级，但是未对数据库进行升级，缺少了三张mysql数据表，导致接口报错。
解决方法：docs文件夹下找到db.sql，进行比对，在数据库中执行对应的建表命令。
