### ISSUE TITLE
cnpm私有仓库的scope包cnpm sync 执行成功，cnpm install 404

### ISSUE THREAD

**Issue by allentofight** [cnpm/cnpmjs.org#1687]
问题描述：
现在我用 cnpm 搭建了一个本地的私有仓库，需要从另一个cnpm仓库同步私有包过来，所以设置了 sourceNpmRegistry 为此仓库的地址，并且 scope 也和上游cnpm设置的一样，现在问题如下：

cnpm sync scope 的包（上游仓库的scope包），比如执行 cnpm sync @fe-base/abr 后是成功的，但在仓库里却无法搜索到,cnpm install @fe-base/abr 也是报错了，但如果不是 scope 的包，比如 cnpm sync abr 是没问题的，所以想问下可能是哪个地方有问题

**Comment by XXBeii** [comment]
假如新的仓库 配置了 @fe-base scope 的话，新的仓库会认为这个 scope 是本地包，不会从上游 sync 的

**Comment by Zian502** [comment]
> 问题描述： 现在我用 cnpm 搭建了一个本地的私有仓库，需要从另一个cnpm仓库同步私有包过来，所以设置了 sourceNpmRegistry 为此仓库的地址，并且 scope 也和上游cnpm设置的一样，现在问题如下：
> 
> cnpm sync scope 的包（上游仓库的scope包），比如执行 cnpm sync @fe-base/abr 后是成功的，但在仓库里却无法搜索到,cnpm install @fe-base/abr 也是报错了，但如果不是 scope 的包，比如 cnpm sync abr 是没问题的，所以想问下可能是哪个地方有问题

具体可看下这块：https://github.com/cnpm/cnpmjs.org/blob/19e5c3def257f4ceab3256a1c9d615d002c5fe49/middleware/sync_by_install.js#L40

**Comment by XXBeii** [comment]
已经新增 scope 同步功能，可自定义 scope source registry，具体查看 [https://github.com/cnpm/cnpmjs.org/pull/1701](feat: support sync private package from define registry)， @allentofight

**Comment by Aqiu007** [comment]
> 已经新增 scope 同步功能，可自定义 scope source registry，具体查看 [feat: support sync private package from define registry](https://github.com/cnpm/cnpmjs.org/pull/1701)， @allentofight

默认只能同步100个包，超过100个怎么同步呢
