### ISSUE TITLE
electron 少更新了一个包！

### ISSUE THREAD

**Issue by daodaolee** [cnpm/cnpmjs.org#1693]
地址：https://npm.taobao.org/mirrors/electron/
少更新了一个 13.6.7，electron官方把mirror说明给淘宝，麻烦你们把这个补上吧！用 electron-builder的人会拉取最新的版本包，不知道的人会一直以为是自己项目的问题，其实是镜像源少同步一个包！6天前这个包官方就更新了。

**Comment by nmMmnmMmn** [comment]
这个镜像好多天没同步了，也不知道怎么回事。
[v16.0.7](https://github.com/electron/electron/releases/tag/v16.0.7)也是发布了好多天，都没同步过来。

顺带，页面上的 `Mirror index of https://github.com/electron/electron/releases/x.x.x/` 链接地址是错误的，应该是`https://github.com/electron/electron/releases/tag/vx.x.x`
![image](https://user-images.githubusercontent.com/21982381/149360361-c9500d52-43cf-43ff-b06e-5e068a36a1de.png)

**Comment by daodaolee** [comment]
好吧😅
