### ISSUE TITLE
electron mirror中少了16.0.7这个版本

### ISSUE THREAD

**Issue by zykee** [cnpm/cnpmjs.org#1694]
虽然开发时可以指定16.0.6的版本，但是执行npx electron-forge import会自动下载最新的版本，无法执行打包操作。

HTTPError: Response code 404 (Not Found) for https://npmmirror.com/mirrors/electron/v16.0.7/electron-v16.0.7-darwin-x64.zip

**Comment by icedcrow** [comment]
+1，这个版本发了好多天了，没同步过来的样子

**Comment by fengmk2** [comment]
我看看。

**Comment by fengmk2** [comment]
还需要一些时间同步 https://npmmirror.com/mirrors/electron/16.0.7/ ，今晚9点之后回来看看。

**Comment by fengmk2** [comment]
https://npmmirror.com/mirrors/electron/v16.0.7/ 使用这个路径，可以省略 ELECTRON_CUSTOM_VERSION 参数
