### ISSUE TITLE
sentry-cli 1.72.1 NotFound

### ISSUE THREAD

**Issue by FeSeason** [cnpm/cnpmjs.org#1695]
https://npm.taobao.org/mirrors/sentry-cli/1.72.1/

https://github.com/getsentry/sentry-cli/releases/1.72.1/

Last version is 1.72.1

![image](https://user-images.githubusercontent.com/12840843/151160778-e53d801e-d347-4281-b353-1f1a73a9c5a7.png)

**Comment by FeSeason** [comment]
It has been synchronized in the morning, and there may be unpredictable time difference

Sad~ 😂

**Comment by fengmk2** [comment]
新的同步代码已经上线，应该会实现分钟级别的同步时差
