### ISSUE TITLE
case sensiitveness of package name

### ISSUE THREAD

**Issue by DustinCheng** [cnpm/cnpmjs.org#1698]
cnpm handles package name in case insensitive way while npm is case sensitve.
i.e.
`cnpm info filelist` gets same result as `cnpm info FileList` but
`npm info filelist` is different from `npm info FileList`

Some package, like filelist, is messed up in cnpmjs.org due to this issue.

**Comment by DustinCheng** [comment]
cnpm@7.1.0

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmjs.org/issues/1699
