### ISSUE TITLE
npm 包名大小写不同被认为是同一个包

### ISSUE THREAD

**Issue by LittleGragon** [cnpm/cnpmjs.org#1699]
npm 里 [filelist](https://www.npmjs.com/package/filelist) & [FileList](https://www.npmjs.com/package/FileList) 是两个包；

但 淘宝的镜像 只有 https://registry.npm.taobao.org/FileList/-/FileList-1.0.1.tgz 能拉到包

https://registry.npm.taobao.org/filelist/-/filelist-1.0.1.tgz 则是404

而且淘宝的镜像把  filelist & FileList 弄混了

**Comment by Baoyx007** [comment]
+1, 导致私服同步包出错

**Comment by fengmk2** [comment]
默认强制为都小写了，现在可以了。 https://npmmirror.com/package/filelist
