### ISSUE TITLE
3.x版本Private + Scope Mode 管理员为什么还可以发布非scope包？

### ISSUE THREAD

**Issue by fanbinghuadev** [cnpm/cnpmjs.org#1702]
从3.x版本开始，设置config.enablePrivate = true && config.scopes = ['@test']，按文档描述，管理员应该只能发布@test作用域包，现在是所有包都能发布，不受限制，是3.x版本开始去掉这个限制了吗？

**Comment by Zian502** [comment]
https://github.com/cnpm/cnpmjs.org/blob/19e5c3def257f4ceab3256a1c9d615d002c5fe49/middleware/publishable.js#L72
