### ISSUE TITLE
重定向淘宝源404问题

### ISSUE THREAD

**Issue by monsterboom** [cnpm/cnpmjs.org#1703]
### bug

场景：
1、私有源发布了命名空间包，@A/hello_world，该包依赖了非私有源的命名空间包，@B/good_bye
2、我通过重定向，将非私有源的命名空间包，指到https://registry.npm.taobao.org进行访问
3、重定向后的地址为 https://registry.npm.taobao.org/@B/good_bye/-/@B/good_bye-0.0.1.tgz ，该地址为 404
4、200的地址为：https://registry.npm.taobao.org/@B/good_bye/-/good_bye-0.0.1.tgz ，
     官方源的地址为：https://registry.npmjs.org/@B/good_bye/-/good_bye-0.0.1.tgz

之前404的地址是可以正常返回访问的。

**Comment by fengmk2** [comment]
你是直接拼接地址的？没有走 registry 返回的地址请求？
