### ISSUE TITLE
npm的镜像没了

### ISSUE THREAD

**Issue by cluyun** [cnpm/cnpmjs.org#1711]
原先用的
https://npm.taobao.org/mirrors/npm/
用的好好的，后面换成
https://npmmirror.com/mirrors/npm/
也用不了，请问到底要用哪个地址，我看官网也就只写了node的镜像没有npm的镜像

![image](https://user-images.githubusercontent.com/33676184/154238247-d961ca6e-ea45-4022-a977-34ef5b40c276.png)

**Comment by fengmk2** [comment]
npm 你需要镜像是来干嘛的？安装 node 就会自带 npm 。

**Comment by cluyun** [comment]
> npm 你需要镜像是来干嘛的？安装 node 就会自带 npm 。

你没用过nvm？

**Comment by fengmk2** [comment]
@cluyun https://github.com/nvm-sh/nvm/blob/master/nvm.sh nvm 依赖的是 node dist 镜像，不依赖 npm。而且 npm 没有独立的下载地址，都是跟随 node 发布的。

**Comment by cluyun** [comment]
> @cluyun https://github.com/nvm-sh/nvm/blob/master/nvm.sh nvm 依赖的是 node dist 镜像，不依赖 npm。而且 npm 没有独立的下载地址，都是跟随 node 发布的。

nvm有个配置项叫npm_mirror，是用来配置npm镜像地址的。如果配置错了或者配置地址是错的就会导致只安装了node而没有npm，不信你可以试试。你没必要给我发文档，文档不一定是正确的，试了才知道。我是试过才提出这个issue的

**Comment by cluyun** [comment]
> @cluyun https://github.com/nvm-sh/nvm/blob/master/nvm.sh nvm 依赖的是 node dist 镜像，不依赖 npm。而且 npm 没有独立的下载地址，都是跟随 node 发布的。

或许这个不是叫npm镜像地址，反正我之前用这个地址是对的，现在不知道为什么用不了换成新的也用不了
https://npm.taobao.org/mirrors/npm/

**Comment by fengmk2** [comment]
请参考 nodejs 的安装文档安装吧。

**Comment by cluyun** [comment]
> 请参考 nodejs 的安装文档安装吧。

我公司的情况只能用nvm。事实上我也只想用原生的nodejs

**Comment by cluyun** [comment]
> nvm 也不需要 npm 镜像的，你更新到最新的 nvm 即可。

那我只能试试了。目前来说网上所有的教程都是表示nvm安装后要设置npm_mirror的。我确实我用的一年前的nvm，待我有时间用最新版试试。

**Comment by fengmk2** [comment]
https://npmmirror.com/mirrors/npm/v6.14.12.zip 尝试兼容了一下。
