### ISSUE TITLE
electron 镜像: status code 404

### ISSUE THREAD

**Issue by pany-ang** [cnpm/cnpmjs.org#1712]
![image](https://user-images.githubusercontent.com/49087880/154420228-5ac58770-dde8-49da-9671-77b6106b59eb.png)

这是打包 yarn build 时出的错

**Comment by pany-ang** [comment]
请问是我镜像配置出了问题吗，electron 镜像: https://npmmirror.com/mirrors/electron/

**Comment by Zian502** [comment]
> ![image](https://user-images.githubusercontent.com/49087880/154420228-5ac58770-dde8-49da-9671-77b6106b59eb.png)

https://registry.npmmirror.com/binary.html?path=electron/v17.0.1/ 从这里看看有没有你想要的版本。

**Comment by Zian502** [comment]
使用这个：https://registry.npmmirror.com/-/binary/electron/v17.0.1/electron-v17.0.1-win32-x64.zip

**Comment by pany-ang** [comment]
@Zian502 我发现我在镜像后面加一个 'v' 字符就可以了：https://npmmirror.com/mirrors/electron/v。

**Comment by pany-ang** [comment]
现在配置文件变成了：ELECTRON_MIRROR = https://npmmirror.com/mirrors/electron/v
ELECTRON_BUILDER_BINARIES_MIRROR = http://npmmirror.com/mirrors/electron-builder-binaries/v

**Comment by pany-ang** [comment]
是镜像的版本号前面比以前对了一个 ‘v’ 字符吗

**Comment by pany-ang** [comment]
但是现在变成依赖（yarn）时 出现了重复的 'v' 字符
![image](https://user-images.githubusercontent.com/49087880/154425275-e11adcba-36fe-4b4a-abe4-8f9b2e7c7881.png)

总结一下就是

**Comment by Zian502** [comment]
看看这个：https://github.com/cnpm/cnpmjs.org/issues/1588

**Comment by pany-ang** [comment]
> 看看这个：#1588

好吧，我看见啦，看样子我得自己做做兼容了
