### ISSUE TITLE
[NOT_FOUND] -@short not found

### ISSUE THREAD

**Issue by lantsang** [cnpm/cnpmjs.org#1713]
sync mode: all, 
source npm registry: https://registry.npmmirror.com

sync_all.js文件中的getFirstSyncPackages()方法调用
npm.js文件中的getShort()方法，提示404错误。

ubuntu@docker:~/code/cnpmjs.org$ DEBUG=cnpm* node dispatch.js
Starting cnpmjs.org ...
cluster: false
admins: {"fengmk2":"fengmk2@gmail.com","admin":"admin@cnpmjs.org","dead_horse":"dead_horse@qq.com"}
scopes: ["@cnpm","@cnpmtest","@cnpm-test"]
sourceNpmRegistry: https://registry.npmmirror.com
syncModel: all
agentkeepalive deprecated options.keepAliveTimeout is deprecated, please use options.freeSocketTimeout instead common/urllib.js:47:15
agentkeepalive deprecated options.keepAliveTimeout is deprecated, please use options.freeSocketTimeout instead node_modules/agentkeepalive/lib/https_agent.js:12:5
[2022-02-17T13:15:35.780Z] [worker:14877] Server started, registry server listen at 0.0.0.0:7001, web listen at 0.0.0.0:7002, cluster: false
[Thu Feb 17 2022 13:15:35 GMT+0000 (Coordinated Universal Time)] [sync_worker:14877] syncing with all mode, changesStreamingSync: undefined
  cnpmjs.org:sync:index mode: all, syncing: false +0ms
  cnpmjs.org:sync:index start syncing +0ms
  cnpmjs.org:logger [2022-02-17 13:15:35.871][14877] Last sync time 1970-01-01T00:00:00.000Z +0ms
  cnpmjs.org:logger [2022-02-17 13:15:35.872][14877] First time sync all packages from official registry +1ms
  cnpmjs.org:sync:index checkSyncStatus start, lastSyncTime: 0, syncInterval: 600000 +105ms
{
  data: { error: '[NOT_FOUND] -@short not found' },
  status: 404,
  headers: {
    server: 'Tengine',
    'content-type': 'application/json; charset=utf-8',
    'content-length': '61',

**Comment by lantsang** [comment]
> 找个项目，然后执行下 npm install

感谢，这样确实可以了。不过建议官方在readme里面说明一下，我以为启动后可以自动同步呢

**Comment by fengmk2** [comment]
cnpm/cnpmjs.org 已经不再更新维护，后续请移步 https://github.com/cnpm/cnpmcore
