### ISSUE TITLE
registry.npmmirror.com 如何访问 puppeteer?

### ISSUE THREAD

**Issue by aladdin-add** [cnpm/cnpmjs.org#1717]
原来使用的 https://npm.taobao.org/mirrors/puppeteer/ ，现在换到新的域名：https://registry.npmmirror.com/binary.html?path=puppeteer/ 后这个目录下是空的。请问是否还有方法访问呢？换了路径？

**Comment by Zian502** [comment]
> 原来使用的 https://npm.taobao.org/mirrors/puppeteer/ ，现在换到新的域名：https://registry.npmmirror.com/binary.html?path=puppeteer/ 后这个目录下是空的。请问是否还有方法访问呢？换了路径？

https://registry.npmmirror.com/binary.html?path=chromium-browser-snapshots/
