### ISSUE TITLE
强制更新淘宝镜像源工具

### ISSUE THREAD

**Issue by xlei1123** [cnpm/cnpmjs.org#1720]
因为团队中有些同学更新，有些未更新，出现提交代码后大量lock文件不同，同时旧的镜像源即将停止服务，开发了一个更新工具，项目中使用后，如果有使用了旧镜像源，在安装之前会出现提示，并且可以强制更新。具体请看这里：https://github.com/xlei1123/please-update-cnpm

**Comment by fengmk2** [comment]
推荐到 https://github.com/cnpm/cnpmjs.org/issues/1706#issuecomment-1079811394
