### ISSUE TITLE
cnpm sync 同步命令没有效果

### ISSUE THREAD

**Issue by noyobo** [cnpm/cnpmjs.org#1730]
```js
cd ./project
npm install  cnpm
npx cnpm sync 
```

执行后查看 https://registry.npmmirror.com/ 的结果，没有同步版本信息。

**Comment by x157660503** [comment]
> ```js
> cd ./project
> npm install  cnpm
> npx cnpm sync 
> ```
> 
> 执行后查看 https://registry.npmmirror.com/ 的结果，没有同步版本信息。

**Comment by fengmk2** [comment]
如果同步失效，请使用 web 命令进行同步 

```bash
open https://npmmirror.com/sync/${packageName}
```
