### ISSUE TITLE
syncMode='None'，下载不了公有包

### ISSUE THREAD

**Issue by linxiaowu66** [cnpm/cnpmjs.org#1736]
请教各位大佬，设置同步模式为None，但是访问对应公有包的版本想下载，结果都是404：

比如: localhost:7001/node/-/node-16.11.21.tgz

看了下download.js的源码，发现代码并没有去下载公有的registry：

![image](https://user-images.githubusercontent.com/13563876/183386537-a3919dab-ddd7-4975-88da-7cbf9c8387a3.png)

所以有此疑问

**Comment by linxiaowu66** [comment]
@fengmk2 大佬帮忙解答一下

**Comment by fengmk2** [comment]
此项目已经不再进行维护，如果你需要部署私有的 registry，请参考 https://github.com/cnpm/cnpmcore
