### ISSUE TITLE
npm audit  报404

### ISSUE THREAD

**Issue by LittleGragon** [cnpm/cnpmjs.org#1738]
错误如下：

`➜  xxx-ui git:(develop) ✗ npm audit
npm WARN audit 404 Not Found - POST https://registry.npmmirror.com/-/npm/v1/security/audits/quick
<h1>404 Not Found</h1>
npm ERR! audit endpoint returned an error`

node  version:  v14.17.3
npm version: 8.1.3

**Comment by gemwuu** [comment]
这个服务暂时未实现。
