### ISSUE TITLE
sharp v0.32.0 镜像不完整 (https://registry.npmmirror.com/binary.html?path=sharp/v0.32.0/ )

### ISSUE THREAD

**Issue by joyexpr** [cnpm/cnpmjs.org#1750]
sharp v0.32.0 镜像不完整 (https://registry.npmmirror.com/binary.html?path=sharp/v0.32.0/ )

缺少了
[sharp-v0.32.0-napi-v7-win32-ia32.tar.gz](https://github.com/lovell/sharp/releases/download/v0.32.0/sharp-v0.32.0-napi-v7-win32-ia32.tar.gz)  
 [sharp-v0.32.0-napi-v7-win32-x64.tar.gz](https://github.com/lovell/sharp/releases/download/v0.32.0/sharp-v0.32.0-napi-v7-win32-x64.tar.gz)

请问有没有通用的方法同步binary.html里的包

**Comment by fengmk2** [comment]
是的，我重新同步一下。

**Comment by fengmk2** [comment]
https://registry.npmmirror.com/-/binary/sharp/v0.32.0/sharp-v0.32.0-napi-v7-win32-x64.tar.gz 已经恢复。

**Comment by fengmk2** [comment]
sharp binary 文件上传时间有几分钟时差，导致同步程序没有同步完整。
![image](https://user-images.githubusercontent.com/156269/231054604-6179aa52-0d69-4470-abf6-e51dfddb85b7.png)
