### ISSUE TITLE
sync_not_exist 很好用，但是依然有不少问题。

### ISSUE THREAD

**Issue by bugyak** [cnpm/cnpmjs.org#428]
我这页面上显示现在的模块数目是 89,618
https://www.npmjs.org/ 显示当前模块数是 89 745
说明已经很接近了...
但是我执行 sync_not_exist 却提示
[tools/sync_not_exist.js] start sync not exist modules
[Tue Aug 19 2014 22:06:06 GMT+0800 (CST)] [worker:3192] mysql ready, got 13 tables
  cnpmjs.org:tools:sync_not_exist Total 3190 packages to sync +0ms

还有3000多个模块要同步？
后来看了下 http://www.cnpmjs.org/ 确实是和cnpmjs相差3000多模块。
可是执行了一会大约一小时提示
All packages sync done, successes

然后马上继续运行sync_not_exist 又提示有3000个模块需要同步。。
这我就晕了，到底是同步完了，还是没有同步完啊？

**Comment by woodenfish** [comment]
@dead-horse 请问是否可以设置不同步unpublish的模块，防止出现left-pad模块删除类似的事件

**Comment by dead-horse** [comment]
http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy  npm 已经改掉了他的 unpublish 策略
