### ISSUE TITLE
sync python dist https://www.python.org/ftp/python/

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#492]
https://www.python.org/ftp/python/

**Comment by athrunsun** [comment]
@fengmk2 python镜像貌似已经过期了，能考虑启动一下同步么？用pyenv安装python从国外下源码包太痛苦了。

**Comment by fengmk2** [comment]
@athrunsun 我看看，确实很久没更新了 https://npm.taobao.org/mirrors/python/

**Comment by fengmk2** [comment]
呃，好像停了好久了。

**Comment by dead-horse** [comment]
额，页面结构变了么

**Comment by fengmk2** [comment]
我看是设置为 disable 了，我看看。

**Comment by fengmk2** [comment]
https://cnpmjs.org/mirrors/python/ 重新开始同步。

**Comment by athrunsun** [comment]
@fengmk2 Great! Thanks! 👍
