### ISSUE TITLE
io.js dist

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#523]
https://github.com/iojs/io.js/issues/40

**Comment by fengmk2** [comment]
downloads url https://iojs.org/download/

**Comment by dead-horse** [comment]
第一个测试包都已经出来了啊..

**Comment by fengmk2** [comment]
![image](https://cloud.githubusercontent.com/assets/156269/5695533/7905c706-99e3-11e4-8b3c-191f0fb4d4b4.png)

![image](https://cloud.githubusercontent.com/assets/156269/5695535/87fbaf5a-99e3-11e4-8e68-0f7b61456ed0.png)

**Comment by dead-horse** [comment]
https://github.com/cnpm/mirrors ，之前迁了一点
