### ISSUE TITLE
Can't sync on install if enablePrivate is false

### ISSUE THREAD

**Issue by theverything** [cnpm/cnpmjs.org#549]
For our set up we want our cnpm to sync on install and we want everyone in our org to be able to publish new modules without them being an admin.

I was wondering what the reasoning behind this is.

https://github.com/cnpm/cnpmjs.org/blob/master/middleware/sync_by_install.js#L25

**Comment by fengmk2** [comment]
set `enablePrivate=false` and `forcePublishWithScope=true`, add your company `scopes`, like:

```js
scopes = [ 'scope1', 'scope2', ... ]
```

**Comment by fengmk2** [comment]
@theverything @thecaddy any questions?

**Comment by thecaddy** [comment]
```
if (!config.syncByInstall || !config.enablePrivate) {
    // only config.enablePrivate should enable sync on install
    return yield* next;
}
```

With enablePrivate = false it will force it to yield next and fails to sync by install command.

**Comment by theverything** [comment]
To add to what @thecaddy said, it seems like checking `config.enablePrivate` isn't necessary here.

**Comment by theverything** [comment]
Sorry for the confusion. @thecaddy pointed out that I titled the issue wrong. I have edited.

**Comment by fengmk2** [comment]
Ok, I got the point . I will see the commit history and find out a solution.

**Comment by thecaddy** [comment]
To help you out, looks like it was this commit:

https://github.com/cnpm/cnpmjs.org/commit/591833b3d84aeae2a582ee661bf867b2b2e3cd0e

**Comment by fengmk2** [comment]
I think we should remove the total private mode. Cc @dead-horse

**Comment by dead-horse** [comment]
@thecaddy @theverything 
After a long time practice in our company, we think the best practice is let cnpm synchronize all packages from official registry(so we don't need sync on install now), set `enablePrivate = false`, and force everyone publish with a specified scope.

Will this satisfy you?

@fengmk2 remove private mode looks good for me.

**Comment by thecaddy** [comment]
@fengmk2 
We generally are trying to avoid syncing all 100k+ of packages in npm.  Currently we are only using 4500 of the 100k packages.  

If the sync by install doesn't work for us we may end up following your suggestion.  Were there any issues in particular that make sync by install cumbersome?

**Comment by fengmk2** [comment]
@thecaddy @theverything remove `enablePrivate` check now.

**Comment by fengmk2** [comment]
`npm install pkg` only check pkg eixsts or not, if pkg not exists, `syncByInstall` will auto create a sync task.

But if pkg exists and pkg@some-version not exists, `syncByInstall` wont help. And npm cli wont request `/pkg@some-version`, it only request `/pkg` only, so cnpm dont know which version is missing.

**Comment by fengmk2** [comment]
I debug npm cli again, find out it add a `referer` header to show out what version is installing.
This maybe a solution. 

https://github.com/cnpm/cnpmjs.org/issues/558

**Comment by theverything** [comment]
Awesome works great. Thanks for the help and thank you for making us aware of the pkg@ver issue. We'll keep an eye out for it.

**Comment by dead-horse** [comment]
@thecaddy @theverything  are you using `syncModel = 'exist'` to sync all the packages in your private registry automaticly?

**Comment by thecaddy** [comment]
Yes.
enablePrivate = false,
syncModel = 'exist',
forcePublishWithScope = true,
syncByInstall = true

**Comment by fengmk2** [comment]
@thecaddy that your private npm is ok, exists package will keep update. and #558 issue I'm going to  close it.
