### ISSUE TITLE
Use Sequelize Migrations for DB schema changes

### ISSUE THREAD

**Issue by thecaddy** [cnpm/cnpmjs.org#560]
The db uses sequelize objects which made it easier for non mysql db setups however schema changes are still a pain and we are unable to keep up.  Switching to sequelize migrations would make it easier to update db schema and keep up with changes.

Migrations docs:
http://sequelize.readthedocs.org/en/latest/docs/migrations/

Associated Sequelize Issue:
https://github.com/cnpm/cnpmjs.org/issues/470

**Comment by fengmk2** [comment]
+1
