### ISSUE TITLE
can not sync packet

### ISSUE THREAD

**Issue by o6875461** [cnpm/cnpmjs.org#562]
![image](https://cloud.githubusercontent.com/assets/2979404/5677008/c508349c-981a-11e4-9186-5940e1fa13b7.png)

use "     node --harmony_generators dispatch.js    " or "    node --harmony_generators worker.js   ",
start server success!!,but when I search an packet and sync it , the server show error :
![image](https://cloud.githubusercontent.com/assets/2979404/5677041/51cf6f30-981b-11e4-8fc7-d955715132ca.png)

why??please help me,thank you!

**Comment by fengmk2** [comment]
which nfs you're using?

**Comment by o6875461** [comment]
![image](https://cloud.githubusercontent.com/assets/2979404/5677585/8d2d3c80-9823-11e4-802a-ce2c46a85ae5.png)

I have no idea which nfs my system using, but it should be the default setting of centos 6.5

**Comment by fengmk2** [comment]
please pull the latest codes and try again

**Comment by o6875461** [comment]
already pull the latest codes ,but the same error occur
![image](https://cloud.githubusercontent.com/assets/2979404/5698142/e96ecc1a-9a40-11e4-824d-50199f639d1d.png)

![image](https://cloud.githubusercontent.com/assets/2979404/5698136/d2250132-9a40-11e4-901c-542211816c78.png)

**Comment by fengmk2** [comment]
can you show out your config?

**Comment by o6875461** [comment]
checkout lastest code,there is no problem now.
