### ISSUE TITLE
NPM install of phantomjs gives 404

### ISSUE THREAD

**Issue by deanclkclk** [cnpm/cnpmjs.org#563]
Been getting this since last night when I run npm install for Phantomjs. Wasn't getting this before:

          > phantomjs@1.9.13 install /home/rof/src/bitbucket.org/jorge- sandoval/xxxxxxxx_web/target-grunt/node_modules/karma-phantomjs-  launcher/node_modules/phantomjs
      > node install.js

     PhantomJS detected, but wrong version 1.9.7 @   /home/rof/.phantomjs/bin/phantomjs.
     Downloading http://cnpmjs.org/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
     Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
     Receiving...

     Error requesting archive.
     Status: 404
     Request options: {
     "uri": "http://cnpmjs.org/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2",
     "encoding": null,
     "followRedirect": true,
     "headers": {},
     "strictSSL": true
     }
     Response headers: {
     "server": "nginx/1.4.6 (Ubuntu)",
     "date": "Thu, 15 Jan 2015 09:32:55 GMT",
     "content-type": "text/plain; charset=utf-8",
     "content-length": "9",
     "connection": "keep-alive",
     "vary": "Accept-Encoding",
     "x-response-time": "600"
      }
     Make sure your network and proxy settings are correct.

      If you continue to have issues, please report this full log at     https://github.com/Medium/phantomjs
     npm ERR! phantomjs@1.9.13 install: `node install.js`
     npm ERR! Exit status 1
      npm ERR!  
      npm ERR! Failed at the phantomjs@1.9.13 install script.
      npm ERR! This is most likely a problem with the phantomjs package,
      npm ERR! not with npm itself.
      npm ERR! Tell the author that this fails on your system:
      npm ERR!     node install.js
      npm ERR! You can get their info via:
      npm ERR!     npm owner ls phantomjs
      npm ERR! There is likely additional logging output above.

**Comment by dead-horse** [comment]
sorry that we broke the phantom mirror today, are you using `cnpm` client right now?

**Comment by deanclkclk** [comment]
My build server is using it. Codeship.

**Comment by dead-horse** [comment]
@fengmk2 is working on this, wait a moment.

**Comment by dead-horse** [comment]
btw, where are you location? i'm curious that in which countries need a npm mirror. :)

**Comment by deanclkclk** [comment]
Codeship I believe is located in the US. 


I am currently in the Caribbean.

**Comment by dead-horse** [comment]
OK, I think @fengmk2 will fix it soon, sorry again for this accident.

**Comment by deanclkclk** [comment]
OK, can you guys update me on when it's fixed? Thanks again.

**Comment by fengmk2** [comment]
@deanclkclk http://cnpmjs.org/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2 recover now!

**Comment by alfrescian** [comment]
http://cnpmjs.org/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2 seems to broken again
