### ISSUE TITLE
problems with cpmjs

### ISSUE THREAD

**Issue by alfrescian** [cnpm/cnpmjs.org#569]
http://cnpmjs.org/downloads/phantomjs-* seems to broken again (e.g. http://cnpmjs.org/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2)

**Comment by fengmk2** [comment]
It seem only http://cnpmjs.org/mirrors/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2 missing. I will make it resync again.

**Comment by fengmk2** [comment]
@alfrescian Fixed now.

**Comment by alfrescian** [comment]
thx ;-)
