### ISSUE TITLE
r.cnpmjs.org 和 registry.npm.taobao.org 在 kappa 后面无法使用

### ISSUE THREAD

**Issue by uzcc** [cnpm/cnpmjs.org#581]
```json
{
    "servers": [
        {
            "host": "127.0.0.1",
            "port": "7000"
        }
    ],
    "plugins": {
        "kappa": {
            "vhost": "npmcc.creditcloud.com",
            "rewriteTarballs": true,
            "paths": [
                "http://127.0.0.1:7001/",
                "https://registry.npm.taobao.org/",
                "https://registry.npmjs.org/"
            ]
        }
    }
}
```

以上是我们的 kappa.json，不知道是不是因为 #576 的原因，对于 `http://127.0.0.1:7001` 404 的 module，以上配置的 kappa 在带 `Accept-Encoding: gzip` 的请求时会出现 500，而删掉 taobao.org 这一行让 kappa 反向代理到 npmjs.org 则不会 500.

现在我们在前面的 nginx 反向代理中加了一个 `Accept-Encoding: identity` 解决了此问题

```nginx
server {
  listen 80;
  server_name npmcc.creditcloud.com;

  location / {
    proxy_pass http://127.0.0.1:7000/;
    proxy_set_header Accept-Encoding identity;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
```

**Comment by fengmk2** [comment]
kappa 不支持 gzip？我现在配置是没错的啊，既然 kappa 的请求带了 Accept-Encoding: gzip，那么肯定会返回 gzip 的 json 数据

**Comment by dead-horse** [comment]
npm 官方是不会返回 gzip 的...

**Comment by fengmk2** [comment]
npm cli 支持 gzip 的

**Comment by uzcc** [comment]
有可能就是 kappa 不支持 gzip 的原因。你们最近的改变就是添加了 gzip 吗？

**Comment by fengmk2** [comment]
是的，很多 npm 包 meta 信息超过1MB 了，需要加 gzip 优化，要不然带宽跟速度都吃不消。

**Comment by fengmk2** [comment]
@uzcc 去给 kappa 提交 pr 吧

**Comment by fengmk2** [comment]
@uzcc 使用 http://registry.npm.taobao.org 阿里云的http负载均衡不支持gzip…… 你可以先用这个

**Comment by uzcc** [comment]
@fengmk2 我现在 nginx `Accept-Encoding: identity` 到 upstream 然后 nginx 设置

```nginx
gzip_proxied no-cache;
gzip_types application/json;
```

这样倒是可以解决问题

**Comment by uzcc** [comment]
https://github.com/krakenjs/kappa/issues/97

**Comment by fengmk2** [comment]
感觉你可以直接用cnpm搭一个私有npm好了，开启同步已存在的模块模式，也不需要全量同步

**Comment by uzcc** [comment]
我试过，但是已存在的模块是包括所有版本吧，仍然会非常大。所以现在完全关掉同步了，只用私有registry+kappa

**Comment by fengmk2** [comment]
看来可以加上这个功能，不做任何同步，非私有库全部走代理模式

**Comment by undoZen** [comment]
不错

**Comment by fengmk2** [comment]
@undoZen @uzcc  https://github.com/cnpm/cnpmjs.org/pull/590  可以试试这个分支

**Comment by jincdream** [comment]
意思是可以搭建cnpm, 然后可以加上这个功能:不做任何同步，非私有库全部走代理模式?

**Comment by fengmk2** [comment]
配置 `syncModel = "none"` 即可。 @jincdream 就是你说的这个意思。
