### ISSUE TITLE
Only allow logged in users to install packages

### ISSUE THREAD

**Issue by KidkArolis** [cnpm/cnpmjs.org#600]
Is there a mode where the registry can be hosted publicly but no APIs are public to anonymous users.

I want only logged in users to be able to install packages.

**Comment by fengmk2** [comment]
Maybe this also need to change npm client sent auth token every request.

**Comment by fengmk2** [comment]
https://docs.npmjs.com/misc/config#always-auth npm had done. I will impl this feature.

**Comment by fengmk2** [comment]
I will add a `alwaysAuth` config:

```js
// always-auth https://docs.npmjs.com/misc/config#always-auth
alwaysAuth: false,
```
