### ISSUE TITLE
sqlite、mysql、postgresSQL能支持什么数据量？是否有数据库迁移工具？

### ISSUE THREAD

**Issue by luqin** [cnpm/cnpmjs.org#613]
sqlite、mysql、postgresSQL能支持什么数据量？是否有数据库迁移工具？

**Comment by fengmk2** [comment]
sqlite 数据量能支持多少没有经验。
MySQL 和 pg 应该能支持海量。

**Comment by luqin** [comment]
已经选择pg了

**Comment by fengmk2** [comment]
good

**Comment by fengmk2** [comment]
@luqin 已经部署起来了？

**Comment by luqin** [comment]
@fengmk2 sqlite和pg部署起来了，但是安装有些依赖失败

**Comment by fengmk2** [comment]
哪些呢？

**Comment by luqin** [comment]
具体见[#613](https://github.com/cnpm/cnpmjs.org/issues/613#issuecomment-101472557)
