### ISSUE TITLE
通过apache 配置反向代理， 发布时 404错误

### ISSUE THREAD

**Issue by gogo1217** [cnpm/cnpmjs.org#618]
环境已经搭建好，本地项目可正常 publish 到私服的 7001 端口。
由于公司主机在外网只能访问80端口，所以我们把很多应用交给 apache 反向代理，从而暴露到公网上。

apache 配置信息：

<VirtualHost *:80>
ServerName r.npm.xx.cn
ProxyPass  / http://192.168.8.80:7001/
ProxyPassReverse / http://192.168.8.80:7001/
</VirtualHost>

<VirtualHost *:80>
ServerName npm.xx.cn
ProxyRequests Off
ProxyPass  / http://192.168.8.80:7002/
ProxyPassReverse / http://192.168.8.80:7002/
</VirtualHost>

配置重启后， r.npm.xx.cn 和  npm.xx.cn 均能正常访问，也能同步和下载。
但 npm install 时 ，出错，出错内容如下：
npm ERR! registry error parsing json
npm ERR! publish Failed PUT 404
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.4

npm ERR! Unexpected token <
npm ERR! <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
npm ERR! <html><head>
npm ERR! <title>404 Not Found</title>
npm ERR! </head><body>
npm ERR! <h1>Not Found</h1>
npm ERR! <p>The requested URL /@xx/abc was not found on this server.</p>
npm ERR! </body></html>
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

我理解服务器没有这个内容，应该返回JOSN格式数据，但是却返回了html 内容，导致解析失败。
请各位大佬帮助解决这问题。

**Comment by gogo1217** [comment]
自己回答吧。
这是因为 提交的时侯 使用了路径 '@xxx%2fabc'  即 '/' 被转义为 '%2f'。apache默认不支持 url 转义，需要在虚拟主机下添加配置以下配置。
AllowEncodedSlashes On

**Comment by fengmk2** [comment]
赞！

**Comment by luqin** [comment]
我也遇到这个问题了，还有没有其他的处理方式？
