### ISSUE TITLE
npm package update web hooks

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#624]
Let admin can add web hooks to listen package update events.

e.g.: I want to listen `@cnpm/xtool-*` prefix name packages update.
- `@cnpm/xtool-*`: `http://example.com/npm/update`

When `@cnpm/xtool-foo` package published, cnpmjs.org will send a post json request to  `http://example.com/npm/update`, json body:

``` json
Content-Type: application/json

{
  "name": "@cnpm/xtool-foo",
  "version": "1.0.0",
  "tag": "latest",
  "event": "published"
}
```

`event` values will be `publish`, `unpublish`, `addtag`, `rmtag`

**Comment by dead-horse** [comment]
:+1:

**Comment by babyzone2004** [comment]
web hook功能还没加上吗

**Comment by fengmk2** [comment]
业余时间严重不足，有兴趣的可以直接pr来实现

**Comment by fengmk2** [comment]
按 npm 官方 registry hooks 定义实现 https://github.com/npm/registry/tree/master/docs/hooks
