### ISSUE TITLE
cnpm本地仓库登录用户显示npm官方的邮箱

### ISSUE THREAD

**Issue by luqin** [cnpm/cnpmjs.org#628]
本地cnpm进行开发，使用cnpm登录账号，邮箱为公司邮箱，账户与npm同名，但是却显示npm的邮箱了。请问是怎么回事？

**Comment by dead-horse** [comment]
cnpm 不用登录，也不能发布模块到 cnpm

**Comment by luqin** [comment]
@dead-horse 那估计就是显示了npm的账户了
