### ISSUE TITLE
Total packages is 31998 ,can't increase

### ISSUE THREAD

**Issue by adaiguoguo** [cnpm/cnpmjs.org#632]
特请教下，是我哪个参数没有加的关系吗？谢谢

![11 31 52](https://cloud.githubusercontent.com/assets/4557740/8898377/d706a0a2-3455-11e5-8fcc-2417912a7663.png)

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmjs.org/blob/master/config/index.js#L197 

```js
// sync mode select
  // none: do not sync any module, proxy all public modules from sourceNpmRegistry
  // exist: only sync exist modules
  // all: sync all modules
  syncModel: 'none', // 'none', 'all', 'exist'
```

你现在是 exist 模式吧？

**Comment by fengmk2** [comment]
@adaiguoguo ele 也自己搭内部私有源了？

**Comment by adaiguoguo** [comment]
我改过是：syncModel: 'all'

**Comment by adaiguoguo** [comment]
是syncDevDependencies的关系？

**Comment by adaiguoguo** [comment]
对的，也开始搭内部的。

**Comment by fengmk2** [comment]
建议去数据库查询一下，目前的模块数统计有点问题 `SELECT DISTINCT(name) AS name FROM tag`

**Comment by adaiguoguo** [comment]
SELECT count( DISTINCT(name)) AS name FROM tag
确实查出来不多，只有31909条。
我需要初始化重现跑下吗？

**Comment by fengmk2** [comment]
呃。。不科学，按道理第一次肯定要跑完才行的

**Comment by adaiguoguo** [comment]
能否请教下现在阿里总共100W的包500G能放下吗？

**Comment by fengmk2** [comment]
![](https://t.alipayobjects.com/images/T1dpphXaNiXXXXXXXX.png)

@adaiguoguo  目前 cnpmjs.org 的存储量, 400G+，当然，还包含 mirrors http://cnpmjs.org/mirrors

**Comment by adaiguoguo** [comment]
@fengmk2 好的，非常感谢！

**Comment by adaiguoguo** [comment]
查了资料被坑在ext3上，ext3文件系统一级子目录的个数为31998(个)，所以在31998 package卡住了。
简单写了下ext3转ext4的方法
Ext3 mounted partition:
```bash
# mount | grep sdb1
/dev/sdb1 on /mnt/temp type ext3 (rw,relatime,errors=continue,user_xattr,acl,barrier=1,data=ordered)
```
Unmount your ext3 partition
```bash
#umount  /mnt/temp/
```
Modify ext3 filesystem to include ext4 features
```bash
# tune2fs -O extents,uninit_bg,dir_index /dev/sdb1 
```
Optimize/repair filesystem directories:
```bash
# e2fsck -fD /dev/sdb1
```
Mount our new ext4 filesytem:
```bash
# mount -t ext4 /dev/sdb1 /mnt/temp/
```
Don't forget change /etc/fstab

**Comment by fengmk2** [comment]
@adaiguoguo 碉堡！

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmjs.org/wiki#whos-using-cnpm 可以加到 wiki 上，帮我们增加一下人气 :)

**Comment by adaiguoguo** [comment]
@fengmk2 已经加了,close这个issue咯

**Comment by adaiguoguo** [comment]
@fengmk2 已经加了,close这个issue咯
