### ISSUE TITLE
cnpm同步文件的存储位置在哪里？

### ISSUE THREAD

**Issue by ywang1724** [cnpm/cnpmjs.org#635]
搭建私有源之后，install一个私有源上不存在的包，默认会去官方源（npm）上去下载，然后同步到私有源上，但是我在私有源所在服务器上并没有找到存储位置。请教下，默认会存储在哪里？谢谢～

**Comment by fengmk2** [comment]
你看看你的配置。。。

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmjs.org/blob/master/config/index.js#L145

**Comment by fengmk2** [comment]
默认是在 `$HOME/.cnpmjs.org/nfs` 下面

**Comment by ywang1724** [comment]
额。。可是我在这个目录下并没有找到。。是否其他地方的配置会影响？我的配置如下：
module.exports = {
     enableCluster: true,
     admins: {
          admin: 'xx@xx.com'
     },
     database: {
          db: 'npmtest',
          host: '127.0.0.1',
          port: 3306,
          username: 'npmtest',
          password: 'xxx',
          dialect: 'mysql'
     },
     scopes: ['@xx'],
     downloadRedirectToNFS: true,
     registryHost: '127.0.0.1',
     enablePrivate: true,
     sourceNpmRegistry: '127.0.0.1:7001',
     syncModel: 'exist'
};

**Comment by ywang1724** [comment]
@fengmk2 我publish私有包是在nfs下面。不知道为什么install不存在的包的时候只会在我当前目录添加，私有源上没有存储。

**Comment by fengmk2** [comment]
不会吧，你可以在页面上执行一下 sync 的功能，看看日志。

**Comment by fengmk2** [comment]
如果模块不存在，会自动同步的 https://github.com/cnpm/cnpmjs.org/blob/master/controllers/registry/package/list.js#L102

**Comment by fengmk2** [comment]
呃。。。你配置错了 sourceNpmRegistry，将 sourceNpmRegistry 的配置删除掉。

**Comment by ywang1724** [comment]
@fengmk2 
确实写错了，加上http就好了，谢谢～

**Comment by xiaqun** [comment]
我是根据这个文档安装的http://blog.fens.me/nodejs-cnpm-npm/，但是数据插不进去，官网源也不能同步不到本地，数据库是用mysql的
我是菜鸟，能帮忙解决下吗
