### ISSUE TITLE
安装有些包不成功，有些包成功

### ISSUE THREAD

**Issue by ywang1724** [cnpm/cnpmjs.org#636]
我在自己的远程服务器上搭建的私有源，在本地install包时出现问题，install像jQuery，underscore，zepto都很正常，但install像grunt，gulp就出现问题，比如install gulp时如下：
➜  ttt  npm install gulp --registry=http://r.npmjs.xx
> glob@1.1.0 preinstall /Users/ywang1724/learning/ttt/node_modules/gulp/node_modules/glob
> node-waf configure build
sh: node-waf: command not found
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "gulp" "--registry=http://r.npmjs.xx"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! glob@1.1.0 preinstall: `node-waf configure build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the glob@1.1.0 preinstall script 'node-waf configure build'.
npm ERR! This is most likely a problem with the glob package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls glob
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ywang1724/learning/ttt/npm-debug.log

而直接通过npm官方源进行install是没有问题的。咨询一下，这是什么原因导致的？谢谢～

**Comment by ywang1724** [comment]
在install grunt时报错：
➜  ttt  npm install grunt --registry=http://r.npmjs.dp
npm WARN package.json @dp/ttt@1.0.0 No repository field.
npm WARN package.json @dp/ttt@1.0.0 No license field.
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "grunt" "--registry=http://r.npmjs.dp"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: nodeunit@'>=0.6.4 <0.7.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.5.3","0.5.2","0.4.0","0.3.1","0.2.4","0.2.3","0.2.2","0.1.2","0.2.1","0.1.1","0.2.0","0.1.0","0.5.1","0.5.0"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'grunt'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ywang1724/learning/ttt/npm-debug.log

**Comment by fengmk2** [comment]
nodeunit 先同步一下

**Comment by ywang1724** [comment]
@fengmk2 
我在本地install不指定版本的某个私有源上不存在的包时会将历史版本同步到私有源上，这种情况能不能设置为只同步最新版或指定版本？

**Comment by ywang1724** [comment]
已解决

**Comment by tangtang4321** [comment]
我也遇到部分包安装不了，说找不到， 很多时候需要我去手动同步文件后，再来安装才成功，有看到说syncmodel='exist'时，私有库没有的资源需要手动同步，但是我改成all后还是不成功，请问最后是怎么解决的呢
