### ISSUE TITLE
私有源上包的同步能否去掉历史版本

### ISSUE THREAD

**Issue by ywang1724** [cnpm/cnpmjs.org#637]
我在本地install不指定版本的某个私有源上不存在的包时会将历史版本同步到私有源上，这种情况能不能设置为只同步最新版或指定版本？

**Comment by dead-horse** [comment]
npm 的依赖树其实很复杂，很难评估什么历史版本需要下载，而且 npm client 向server 发请求的时候很多时候请求的并不是指定版本的信息，而是指定模块的
