### ISSUE TITLE
支持带ID密码认证的Proxy么？

### ISSUE THREAD

**Issue by modoojunko** [cnpm/cnpmjs.org#641]
公司需要搭建npm源，看来看去cnpm的比较靠谱。

我看到有http_proxy的功能，但是示例没带有ID和密码认证，所以请教下这个CNPM的同步官网的支持带ID跟密码认证的http_proxy么？

这个同步是怎么同步的？看介绍没看明白

**Comment by fengmk2** [comment]
使用的是 https://github.com/mikeal/tunnel-agent 这个库，它支持我们就支持了。

**Comment by fengmk2** [comment]
https://github.com/mikeal/tunnel-agent/blob/master/index.js#L125 proxyAuth 有这个参数

**Comment by modoojunko** [comment]
能否告知下这个参数怎么在配置里面设置？

**Comment by fengmk2** [comment]
我目前没有这种代理啊，我只能去官方例子看看了
