### ISSUE TITLE
badge support custom `SUBJECT`

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#655]
like: https://cnpmjs.org/badge/v/npm.svg?tag=beta&subject=偏右

=>

![](https://img.shields.io/badge/%E5%81%8F%E5%8F%B3-3.3.1-blue.svg?style=flat-square)

**Comment by afc163** [comment]
:+1:

**Comment by fengmk2** [comment]
deploy now! ![](https://cnpmjs.org/badge/v/antd.svg?&tag=beta&subject=npm)

**Comment by afc163** [comment]
https://img.shields.io/badge/npm-0.9.0--beta6-green.svg?style=flat-square

https 的好像有问题，http 是好的。

**Comment by fengmk2** [comment]
中国被污染了？
