### ISSUE TITLE
 no_perms only allow publish with @cnpm, @cnpmtest, @cnpm-test scope(s): 

### ISSUE THREAD

**Issue by note520** [cnpm/cnpmjs.org#657]
发布模块到服务器上提示这信息，是代表什么意思，配置文件里的
registry scopes, if don't set, means do not support scopes
这段没看懂是代表什么意思.....
已经解决----------------------------------------
设置私有npm的问题....

**Comment by kimhou** [comment]
@note520 请问怎么解决的

**Comment by fengmk2** [comment]
发布模块需要带 scope

**Comment by kimhou** [comment]
不带scope就不行吗？这个有点蛋疼啊。。

**Comment by fengmk2** [comment]
不行，这是 npm 私有模块的约定。

**Comment by YardWill** [comment]
请问如何修改这个scope
![image](https://cloud.githubusercontent.com/assets/16497201/26055644/522efd6a-39a4-11e7-9c4b-8301abc786b2.png)
以下是我的配置
![image](https://cloud.githubusercontent.com/assets/16497201/26055671/70080bb0-39a4-11e7-96bd-8be36fcc4de5.png)
为什么表现不一致？
@fengmk2
