### ISSUE TITLE
同步async为什么会自动同步uglify-js

### ISSUE THREAD

**Issue by viclm** [cnpm/cnpmjs.org#660]

**Comment by dead-horse** [comment]
uglify-js  是 async  的依赖模块，所以会自动把所有的依赖模块都同步下来，不然你没法安装，如果不想要同步依赖模块的话：`cnpm sync async --no-deps`

**Comment by viclm** [comment]
uglify-js 是dev依赖，在config/index.js是关闭的，仍然会同步
