### ISSUE TITLE
list packages by username

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#661]
like https://npm.taobao.org/~fengmk2

**Comment by imsobear** [comment]
wait for you :smiley:

**Comment by fengmk2** [comment]
@imsobear 说一下你需要的信息。

**Comment by imsobear** [comment]
@fengmk2 另一位同事需要，我帮他问的，他稍晚点回复你，谢啦~

**Comment by nanqiu** [comment]
@fengmk2 需要查询某个用户有权限的的包：包名、版本、维护人

**Comment by fengmk2** [comment]
maintainers 不是在一个表里面的，目前鉴于性能考虑，如果一个人包含几千个模块，都去 join 查询 maintainers 的话，开销太大，只返回模块名称，latest 对应的版本号，description 描述信息

**Comment by fengmk2** [comment]
![image](https://cloud.githubusercontent.com/assets/156269/9997171/4f6176a6-60bd-11e5-98ac-c4a5fca27571.png)

大概这样，如果没问题，就继续开发了。

**Comment by fengmk2** [comment]
![image](https://cloud.githubusercontent.com/assets/156269/9997205/7a532080-60bd-11e5-86e4-f90f4b7bb4df.png)

**Comment by nanqiu** [comment]
@fengmk2 ok，非常感谢。

**Comment by fengmk2** [comment]
示例 http://r.cnpmjs.org/-/users/substack/packages

**Comment by fengmk2** [comment]
![image](https://cloud.githubusercontent.com/assets/156269/10143144/387904cc-6649-11e5-8214-076fbe990628.png)

![image](https://cloud.githubusercontent.com/assets/156269/10143153/47a86a0a-6649-11e5-8747-3320053f272c.png)

**Comment by fengmk2** [comment]
npm.taobao.org 也已经部署 https://registry.npm.taobao.org/-/users/fengmk2/packages
