### ISSUE TITLE
npm publish遇到这个问题

### ISSUE THREAD

**Issue by lyqdudu** [cnpm/cnpmjs.org#664]
npm ERR! publish Failed PUT 403
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\n
node_modules\\npm\\bin\\npm-cli.js" "publish"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code E403

npm ERR! no_perms only allow publish with @cnpm, @cnpmtest scope(s): lyq_
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\lyq_1\npm-debug.log

**Comment by fengmk2** [comment]
私有模块必须发布 scope 的。
