### ISSUE TITLE
package.json 中 repository 字段的解读

### ISSUE THREAD

**Issue by alsotang** [cnpm/cnpmjs.org#685]
`repository: { type: 'git', url: 'git+https://github.com/alsotang/qcos.git' },`

这个在 https://www.npmjs.com/package/qcos 是可以识别的，在 http://cnpmjs.org/package/qcos 有识别错误

**Comment by ibigbug** [comment]
https://github.com/repo-utils/giturl/blob/master/lib/giturl.js#L35

貌似没考虑到这种情况

**Comment by fengmk2** [comment]
https://github.com/repo-utils/giturl/pull/3/files

**Comment by fengmk2** [comment]
@popomore 已经修复

**Comment by fengmk2** [comment]
修复了
