### ISSUE TITLE
get package's dependents

### ISSUE THREAD

**Issue by windyGex** [cnpm/cnpmjs.org#694]
![image](https://cloud.githubusercontent.com/assets/197348/10633760/7cab9d0c-781f-11e5-965f-1cf1b602d877.png)

**Comment by fengmk2** [comment]
http://registry.npmjs.org/-/_view/dependedUpon?group_level=3&startkey=%5B%22socket.io%22%5D&endkey=%5B%22socket.io%22%2C%7B%7D%5D&skip=0&limit=1000

![image](https://cloud.githubusercontent.com/assets/156269/10636242/086a0ab6-7831-11e5-864f-b605ca5ccc77.png)

**Comment by fengmk2** [comment]
![image](https://cloud.githubusercontent.com/assets/156269/10636587/4866afbe-7833-11e5-9efa-0e8d12c27158.png)

**Comment by fengmk2** [comment]
registry api: http://r.cnpmjs.org/-/package/urllib/dependents
