### ISSUE TITLE
Adding admin page

### ISSUE THREAD

**Issue by ibigbug** [cnpm/cnpmjs.org#710]
- [x] Can assign or revoke an `admin` privilege
- [x] Add a column `role` to `User` model, for marking user role level. could be: 
  - 0: normal
  - 1: admin
  - 2: God
- [x] New `access_level` middleware
- [ ] No more `admins` field in [config.js](https://github.com/cnpm/cnpmjs.org/blob/master/config/index.js#L76) so as `common.isAdmin`
- [ ] Make `auth` middleware work for both `npm` client & web page
- [x] Using ant.design & Flux

**Comment by ibigbug** [comment]
@fengmk2 @dead-horse

**Comment by fengmk2** [comment]
:+1:

**Comment by ibigbug** [comment]
<img width="1345" alt="screen shot 2015-10-29 at 15 09 40" src="https://cloud.githubusercontent.com/assets/543405/10812250/293d5328-7e4f-11e5-8a04-77e0ff58758e.png">

**Comment by fengmk2** [comment]
赞啊，色调是否可以深蓝一些？

**Comment by fengmk2** [comment]
估计需要搜索用户

**Comment by ibigbug** [comment]
> 赞啊，色调是否可以深蓝一些？

可以基于 ant-design 的色调进行一些调整

> 估计需要搜索用户

是的。
