### ISSUE TITLE
服务显示已经启动，但是在浏览器打开后无法连接

### ISSUE THREAD

**Issue by mtyang** [cnpm/cnpmjs.org#730]
cnpmjs.org is already running, PID=34929

open http://localhost:7001

**Comment by alsotang** [comment]
没有启动成功吧？

2015-11-18 18:09 GMT+08:00 Enzo <notifications@github.com>:

**Comment by mtyang** [comment]
也没有报什么错啊，搞不懂哪里出问题了

**Comment by mtyang** [comment]
@ibigbug

**Comment by ibigbug** [comment]
> default ports: 7001-registry, 7002-web

访问 localhost:7002 试试呢

**Comment by mtyang** [comment]
也不行呢，都试过了，而且检查所有启动端口号也看不到7001 7002这两个端口

**Comment by ibigbug** [comment]
你是如何启动的，有出现类似的信息么?

<img width="806" alt="screenshot 2015-11-19 11 52 51" src="https://cloud.githubusercontent.com/assets/543405/11261908/19e44286-8eb4-11e5-84d7-7e18a83507ad.png">

**Comment by mtyang** [comment]
![image](https://cloud.githubusercontent.com/assets/6511456/11262239/bee32efc-8eb7-11e5-8d74-475048a4cd51.png)

**Comment by mtyang** [comment]
难道是我的config有问题么

![image](https://cloud.githubusercontent.com/assets/6511456/11262624/7180a680-8ebc-11e5-82f8-e0faf1ae1fac.png)


![image](https://cloud.githubusercontent.com/assets/6511456/11262667/da8c357c-8ebc-11e5-988c-a2b8ef676534.png)

**Comment by alsotang** [comment]
log 被重定向了，你去看看文件里面有什么报错信息吧

2015-11-19 12:56 GMT+08:00 Enzo <notifications@github.com>:

**Comment by mtyang** [comment]
跑起来了。我表示什么都没干~

![image](https://cloud.githubusercontent.com/assets/6511456/11268224/c4b172c0-8eea-11e5-98bd-e2b6bde65ffb.png)

**Comment by CodmerYin** [comment]
我也遇到了这个问题，同问如何解决。。。我怎么试都不行啊。我的机器环境是：vmware  ubuntu14.04

**Comment by zw-slime** [comment]
我现在遇到了这个问题，同问如何解决的啊？
