### ISSUE TITLE
支持带用户名与密码认证的proxy

### ISSUE THREAD

**Issue by modoojunko** [cnpm/cnpmjs.org#742]
很高兴看到了httpProxy在config.js里。

摆弄了一整天，终于装上了，7001，7002也能访问。

问题来了，同步的部分，看log全失败了。报错是连接不上registry。看来这个httpProxy还是不支持带用户名密码的。

是否能改进下？支持http://用户名:密码@proxy.xxx.com:8080的？

我看到tunel那个n久没更新了，指望那边好像没搞头。如果能支持这个带认证的proxy，cnpm肯定还要火。

**Comment by alsotang** [comment]
cnpm 对于这个功能的支持不知如何。不过如果你现在就要用这个功能的话（开发起来没那么快），建议你在本地搭一个 nginx
反向代理，让所有的请求自动加上 http auth 再去访问源站。

在 2015年11月25日 下午9:37，Alexander <notifications@github.com>写道：

**Comment by rowinzhuang** [comment]
npm 怎么加  http auth  啊  啊啊啊啊啊啊
我也想nginx反向代理一下，加个auth认证
