### ISSUE TITLE
atom/electron stopped updating

### ISSUE THREAD

**Issue by webarchymeta** [cnpm/cnpmjs.org#746]
The official version is now 0.35.2 but the mirror site stays at 0.35.0 for a while

**Comment by fengmk2** [comment]
cnpm/mirrors#87

**Comment by fengmk2** [comment]
done https://npm.taobao.org/mirrors/electron/0.35.2/

**Comment by alsotang** [comment]
能大致说下解决过程吗？

2015-12-02 10:34 GMT+08:00 fengmk2 <notifications@github.com>:

**Comment by fengmk2** [comment]
不看回复？cnpm/mirrors#87

**Comment by alsotang** [comment]
sorry，漏看了 pr。。。

2015-12-02 10:38 GMT+08:00 fengmk2 <notifications@github.com>:
