### ISSUE TITLE
download statistics issue

### ISSUE THREAD

**Issue by alsotang** [cnpm/cnpmjs.org#747]
I think we should put download statistics in `/middleware/sync_by_install.js`. 

Many `npm install` would only read `r.cnpmjs.org/pkg_name` and then find their cache tar ball local. But actually, the download behavior happened and cnpm dont record it.

There is some compile service in Tencent, and this service would cache tar ball locally, so even a framework has many download request, but not record.

**Comment by fengmk2** [comment]
http://registry.cnpmjs.org/pedding/download/pedding-1.0.0.tgz `/pedding/download/pedding-1.0.0.tgz` url 会进行统计的。

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmjs.org/blob/master/controllers/registry/package/download.js#L30

**Comment by alsotang** [comment]
我知道，但是 tar ball 缓存了之后，这个 url 不会被触及。

**Comment by alsotang** [comment]
放在 sync_by_install 中才不会掩盖真实的下载行为
