### ISSUE TITLE
Last sync time is Thu Jan 01 1970 08:00:00 GMT+0800 (CST).

### ISSUE THREAD

**Issue by ilife5** [cnpm/cnpmjs.org#750]
@fengmk2 

安装好了之后，同步时间的显示一直为1970年08:00:00

看了一下接口**/total**

```
last_sync_time: 0
```

**Comment by dead-horse** [comment]
你有开启同步功能么？

**Comment by ilife5** [comment]
我把我的同步的配置项贴出来：

```
 /**
   * sync configs
   */

  officialNpmRegistry: 'https://registry.npmjs.com',

  sourceNpmRegistry: 'https://registry.npm.taobao.org',

  sourceNpmRegistryIsCNpm: true,

  // if install return 404, try to sync from source registry
  syncByInstall: true,

  syncModel: 'all', // 'none', 'all', 'exist'

  syncConcurrency: 1,
  // sync interval, default is 10 minutes
  syncInterval: '10m',

  syncPopular: false,
  syncPopularInterval: '1h',
  // top 100
  topPopular: 100,

  // sync devDependencies or not, default is false
  syncDevDependencies: false,
```

**Comment by dead-horse** [comment]
syncModel: 'all' 是不是还没有完整的同步过一次？

**Comment by ilife5** [comment]
@dead-horse 是的

这里是不是我理解的有偏差，我以为这里的同步时间指的是上一个module的同步时间

这里的意思是所有的包同步完毕的时间吗？

**Comment by dead-horse** [comment]
恩，指的是上一次同步完成的时间

**Comment by ilife5** [comment]
@dead-horse 多谢

我搞了一个超级大的硬盘，打算全量同步，这个是否为好的策略呢？

cnpmjs.org是怎么做的，也是全量同步的吧。

**Comment by dead-horse** [comment]
如果从 cnpm 安装足够快的话，可以考虑走代理模式，只维护私有的仓库，公共的还是从 cnpm 走，如果觉得本地构建更快，可以全量同步也没有问题。

我们现在是把文件同步到 oss 上的，并不是放磁盘，因为我们有多台机器提供服务。

**Comment by ilife5** [comment]
oss高大上啊，我们现在内网没有云服务。

这块有相关的资料可以用来学习吗？

我的诉求是在公司环境内搭建npm源，如果想做成由多台机器提供存储服务要如何来做呢？

**Comment by dead-horse** [comment]
那你要自己实现一个分布式文件存储服务了，比 npm 都复杂。。 不建议

**Comment by ilife5** [comment]
嗯，这块我现在能做的可以把本地机器的下载速度和cnpm下载速度做一下对比，自己搭分布式文件存储确实代价太大。

再请教个问题：如果公司内已经有了分布式存储服务，想和cnpm做对接有没有资料可以参考。

**Comment by dead-horse** [comment]
https://github.com/cnpm/cnpmjs.org/wiki/NFS-Guide 实现这几个接口即可

**Comment by ilife5** [comment]
@dead-horse 多谢

**Comment by fengmk2** [comment]
去哪儿应该有云存储的，最好用云存储，本地磁盘估计很快会出现磁盘问题。小文件太多了。
