### ISSUE TITLE
"cnpm install -g xxx" install to wrong folder on osx (nodejs was installed with homebrew)

### ISSUE THREAD

**Issue by nmhnmh** [cnpm/cnpmjs.org#752]
homebrew installed to /usr/local

``` shell
which node
/usr/local/bin/node
which npm
/usr/local/bin/npm
which cnpm
/usr/local/bin/cnpm
```

nodejs installed with homebrew on /usr/local/bin/node (realpath: /usr/local/Cellar/node/5.1.1/bin/node)
`npm install -g live-server`
will install live-server in **/usr/local/lib/node_modules/**, and create live-server binary in **/usr/local/bin/**
`cnpm install -g live-server`
will install live-server in **/usr/local/Cellar/node/5.1.1/lib/node_modules**, and create binary in **/usr/local/Cellar/node/5.1.1/bin**

**Comment by alsotang** [comment]
https://gist.github.com/DanHerbert/9520689
https://github.com/npm/npm/issues/3794

seems it's also a issue in early age, when use homebrew with npm.

for short solution, you can set `$ export PATH=/usr/local/Cellar/node/5.1.1/
bin:$PATH`, and then use those global pkgs.

2015-12-06 10:59 GMT+08:00 Minghao Ni <notifications@github.com>:

**Comment by nmhnmh** [comment]
Adding a temporary path hack or just using original npm to install global packages is fine.
I just didn't anticipated such issue, I think cnpm is a transparent and drop-in replacement for npm, should  work out of box, with exactly same behaviours. So it really surprised me a  little.

**Comment by iplus26** [comment]
Having the same issue.
