### ISSUE TITLE
全量同步，总的package数目以及total package versions都差很多（差几万）

### ISSUE THREAD

**Issue by realzbc** [cnpm/cnpmjs.org#760]
现在全量同步的情况展示：

![image](https://cloud.githubusercontent.com/assets/3351124/11711156/69766a66-9f5f-11e5-8ed4-fd208b4477e1.png)
下面是config/config.js的配置信息：
![image](https://cloud.githubusercontent.com/assets/3351124/11711192/986f407c-9f5f-11e5-9b3b-4c235c0ffbb5.png)
最后是同步的log日志：
![image](https://cloud.githubusercontent.com/assets/3351124/11711208/af7c6f24-9f5f-11e5-89e5-5720792c36d7.png)

**Comment by dead-horse** [comment]
问题不大的，后续所有有更新的模块都会自动同步过来，而且发现有模块不存在的时候可以直接手动同步当前模块。
