### ISSUE TITLE
mysql module表name字段collation问题

### ISSUE THREAD

**Issue by gniavaj** [cnpm/cnpmjs.org#775]
cnpmjs.org代码中现在所有表使用的collation都是utf8_general_ci 也就是大小写不敏感
这样设置导致在同步https://registry.npm.taobao.org/md5和https://registry.npm.taobao.org/MD5时会出错

我把module整个表collation改为utf8_bin了
看了下sequeliz api似乎不支持把单个列的collation改成utf8_bin

**Comment by alsotang** [comment]
你的例子，我看 npm.taobao.org 没有问题，我自己这里腾讯内部搭的 cnpm 也没这个问题啊。

utf8_general_ci 是 mysql utf8 字符级的默认校对规则，我不是太懂这个校对的含义是什么。

话说回来，这个问题你实际遇到了吗？

在 2016年1月4日 下午5:06，gniavaj <notifications@github.com>写道：

**Comment by gniavaj** [comment]
校对规则就是比较字符串的规则
默认的utf8_general_ci 是不区分大小写的
也就是如果数据库module表里有一条记录name为md5的记录
select * from module where name = md5 或 Md5 或 mD5都可以查询出结果
npm上传模块时 是大小写敏感的 如果数据库不区分大小写会不会出问题?
你可以看下你们的数据库 执行下show full columns form module 看下module表 列的collation

**Comment by alsotang** [comment]
![image](https://cloud.githubusercontent.com/assets/1147375/12106805/31999174-b39e-11e5-8c2a-45b97a99f6a8.png)

**Comment by alsotang** [comment]
![image](https://cloud.githubusercontent.com/assets/1147375/12106840/7fdd1842-b39e-11e5-8c7a-3ffaf34c1abf.png)

**Comment by alsotang** [comment]
https://github.com/cnpm/cnpmjs.org/blob/master/docs/db.sql#L68

之前已经是 utf8_bin 的了。具体什么时候开始的，得看看 commit 记录

**Comment by gniavaj** [comment]
不是  用cnpmjs.org的代码 建出来的module name字段collation是utf8-general_ci的  
这个name可能是你们直接通过sql改的

**Comment by alsotang** [comment]
那可能是姿势问题。

我是直接导入这个 db.sql 建立的数据库，但如果是用 sequelize 自动建立的数据库的话，或许就漏了这个配置了。

还好我机智。。。



2016-01-05 11:24 GMT+08:00 gniavaj <notifications@github.com>:

**Comment by gniavaj** [comment]
对 如果用sequelize直接建库 就会有这个问题  
我就是直接用sequelize直接建的  然后install md5 和 MD5时出了错误
这个你可以在代码里改成使用utf8_bin  要不这个问题不是很容易发现 排查起来也比较困难

**Comment by alsotang** [comment]
是的，这个问题排查起来不容易，赞一个。

在 2016年1月5日 上午11:36，gniavaj <notifications@github.com>写道：

**Comment by ibigbug** [comment]
学习了

**Comment by dead-horse** [comment]
不过现在 npm 已经只允许小写了

**Comment by fengmk2** [comment]
> native js function for hashing messages with MD5 (deprecated, use lowercase md5@>=2.x from now on)
