### ISSUE TITLE
想要搭建私有仓库，源码编译起来像噩梦啊

### ISSUE THREAD

**Issue by LC2010** [cnpm/cnpmjs.org#780]
1.  安装文档更新不及时，看更新历史已经把Redis依赖去掉了，但docs的安装文档还是旧的。
2.  对环境的依赖描述相关的都没有。加上本身Node安装起来依赖也麻烦，所以出错了很难定位，都不知道该如何反馈。

大概放上几段编译的错误`make install`之后：

一种类型的错误是v8引擎报错：
```
../node_modules/nan/nan.h:1394: error:   in call to ‘Set’
../node_modules/nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)’:
../node_modules/nan/nan.h:1516: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) const’:
../node_modules/nan/nan.h:1534: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In member function ‘virtual void Nan::AsyncWorker::HandleErrorCallback()’:
../node_modules/nan/nan.h:1568: error: no matching function for call to ‘New(const char*)’
```

再一种错误是sqlite3的错误：
```
make[1]: Leaving directory `/home/liangchao/cnpmjs.org/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-220.4.2.el6.x86_64
gyp ERR! command "/usr/local/node/bin/node" "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/liangchao/cnpmjs.org/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/liangchao/cnpmjs.org/node_modules/sqlite3/lib/binding/node-v46-linux-x64"
gyp ERR! cwd /home/liangchao/cnpmjs.org/node_modules/sqlite3
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
```

总之编了几次，现在还是没有头绪，基本上也找不到相关资料了。

感觉文档以及后续服务应该稍微加强一下。

**Comment by alsotang** [comment]
按理说你这个版本的 node 不应该有编译问题的。我也是 4.2.1，刚才闲得无聊试了试，一路是成功的。

sqlite 也装上了。

2016-01-06 15:44 GMT+08:00 liangchao <notifications@github.com>:

**Comment by LC2010** [comment]
@alsotang 我后来开了代理装上去了，有可能是公司的网络问题。现在是跑起来了。

如果我使用 mysql 应该就不需要依赖 sqlite 了吧，发现sqllite反而编起来麻烦。

现在跑起来，看了下发现目前默认模式是 tar 包全量存储在本地磁盘。还需要按照接口写一个存储服务来存储才能分布式。

再就是 CNPM 目前文档相关的还是不太清晰，估计对外 Push 的还是相对少一些，共享的相对少一些。可以集中时间清理一次。

**Comment by dead-horse** [comment]
@fengmk2 感觉之前用 sequelize 重构还是坑略多啊，还不如只支持 mysql...

**Comment by fengmk2** [comment]
@dead-horse 。。。起个3.0。。

**Comment by LC2010** [comment]
@dead-horse mysql 是数据库界的 jQuery，像这种服务类的东西，感觉依赖越单一越好一些。

再一个就是希望能够提供一些使用的经验。比如推荐的最佳实践，或者是案例中的配置方式。

我现在想了解一下比如我使用 exist 的同步方式，大概需要多大的存储空间。 这样我会更容易的选择我是用单机先部署了，还是用七牛之类的，或者用七牛量大，投入太高，我就考虑使用公司的存储服务去单独封装一个存储 sdk。望指导~

**Comment by alsotang** [comment]
sqlite 只是 devdependencies，如果你安装的时候使用 `--production` 参数，就不会安装那东西。

关于数据库，我觉得支持 mysql 和 pg 都是必要的，sqlite 确实不必要。但为了支持 mysql 和 pg，比较方便的方案就是引入
sequelize。

tar包当然是默认存本地啊，默认嘛。config.js
里面写得还是比较清晰的，想存别的地方去，就实现存储读取的那个接口。那个接口实现起来还是比较容易的。已经抽象得很好了。

你说的文档和最佳实践这一块，目前我们在 issue 里面还是有一些沉淀的。几个月前我搭建的时候，发现文档是需要来一次整理了。

在 2016年1月7日 上午9:59，liangchao <notifications@github.com>写道：

**Comment by ibigbug** [comment]
sqlite 很方便啊。开发时候不用本地跑数据库了。

**Comment by LC2010** [comment]
@alsotang 好的，感谢悉心回答，下周我这边就搭建投入使用了，希望有一些坑或者其他问题你们可以更多的总结沉淀出来。

**Comment by alsotang** [comment]
![image](https://cloud.githubusercontent.com/assets/1147375/12215341/6d03a27e-b6f3-11e5-80a3-6d3b7f829ef9.png)
https://github.com/cnpm/cnpmjs.org/wiki/Deploy

@dead-horse @fengmk2 wiki这里，`Deploy With NPM Module` 这种方式仍然推荐吗？我看大家都是源码搭建的。

**Comment by fengmk2** [comment]
改吧

**Comment by alsotang** [comment]
楼主，你说的涉及 redis 的安装文档是哪一个？可以给个链接吗？

我看 

https://github.com/cnpm/cnpmjs.org/wiki/Deploy-a-private-npm-registry-in-5-minutes
https://github.com/cnpm/cnpmjs.org/wiki/Deploy-a-private-npm-registry-in-5-minutes

都没有提到 redis

**Comment by LC2010** [comment]
@alsotang 我是通过源码编译安装的，我看得文档是在源码仓库的docs/web/indstall.md文档。

**Comment by LC2010** [comment]
@alsotang 想继续追问一下

配置信息
```
  registryHost: 'r.cnpmjs.org',
```
这个Host的主要作用是什么？我搭建私有仓库的话，这个域名需要更换为自己的域名地址么？

**Comment by alsotang** [comment]
@fengmk2
https://github.com/cnpm/cnpmjs.org/blob/master/docs/web/install.md 这个和 https://github.com/cnpm/cnpmjs.org/wiki/Deploy 这个，我们保留后者就好了吧？

@LC2010 registryHost 字段的含义你 grep 代码看看吧，换成自己的地址再说呗。

**Comment by LC2010** [comment]
@alsotang 问之前已经grep过，不过实在是没有看懂具体的含义。包括conf里好几个字段，都没有在代码中体现，所以有点迷惑，主要registryHost字段看上去比较重要，但注释没有体现出作用，所以还是想弄清楚再改。

**Comment by fengmk2** [comment]
是的，前者是老的

**Comment by alsotang** [comment]
代码中如果没有体现的话，那那个配置应该是废弃不用了。。。。

https://github.com/cnpm/cnpmjs.org/blob/master/docs/web/install.md 这个我去删掉

2016-01-12 19:46 GMT+08:00 fengmk2 <notifications@github.com>:

> 是的，前者是老的
>
> Sent from my iPhone
>

**Comment by fengmk2** [comment]
好的

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmjs.org/blob/master/docs/web/install.md 删除了，关了。

sqlite3 也已经通过 cnpm 代理到中国了，不需要编译了。
