### ISSUE TITLE
invalid scope scope @x not match legal scopes: @cnpm, @cnpmtest, @cnpm-test: @x/y

### ISSUE THREAD

**Issue by glen-84** [cnpm/cnpmjs.org#785]
Windows 10
Node v5.3.0
NPM v3.5.2

When I run `cnpm publish`, I get:

```
npm ERR! publish Failed PUT 400
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Glen\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\Glen\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=C:\\Users\\Glen\\.cnpm" "--registry=http://localhost:7001/" "--node-gyp=C:\\Users\\Glen\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\node-gyp\\bin\\node-gyp.js" "publish"
npm ERR! node v5.3.0
npm ERR! npm  v2.14.15
npm ERR! code E400

npm ERR! invalid scope scope @x not match legal scopes: @cnpm, @cnpmtest, @cnpm-test: @x/y
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Programming\Projects\x\y\npm-debug.log
```

I ran the server with:

`nohup cnpmjs.org start --admins='glen' --scopes='@x' &`

C:\Users\Glen\.cnpmjs.org:

```
{
  "admins": {
    "glen": "glen@localhost.com"
  },
  "scopes": [
    "@x"
  ]
}
```

C:\Users\Glen\.cnpmrc:

```
email=
registry=http://localhost:7001/
//localhost:7001/:_password="***"
//localhost:7001/:username=glen
//localhost:7001/:email=glen@localhost.com
//localhost:7001/:always-auth=false
```

It looks like the package is in `C:\Users\Glen\.cnpm\@x`, but it's not listed at `http://localhost:7002/`, so I don't think that the publish operation completed.

What am I doing wrong?

**Comment by glen-84** [comment]
I found the problem:

My NODE_ENV is set to "development", so it tries to load the config from `path.join(root, 'config', 'config.js');` – why does it do this, when the config is written to `$dataDir/config.json`?

See [here](https://github.com/cnpm/cnpmjs.org/blob/master/config/index.js#L230).

**Comment by alsotang** [comment]
搭建起来之后，把 config.js 好好看一遍，里面有不少都是要自定义的

2016-01-08 21:15 GMT+08:00 Glen <notifications@github.com>:

**Comment by glen-84** [comment]
@alsotang I don't speak Chinese unfortunately. Does anyone on your team speak English?

Google translation of your message:

> After the build up, the config.js a good read, and there are a lot of you want to customize

I know that a lot can be customized, but by default (when NODE_ENV is set to "development"), the config is read from the wrong place.

**Comment by alsotang** [comment]
Sorry...

Google's translation is correct.

Of cource by default the NODE_ENV is development. cnpmjs as a project cant
judge your environment.

If you run cnpmjs on server, then I think you should set NODE_ENV to
`production`. Freeze it in your ~/.bashrc or somewhere.

2016-01-11 15:32 GMT+08:00 Glen <notifications@github.com>:

**Comment by glen-84** [comment]
> Sorry...

No worries. =)

> Of cource by default the NODE_ENV is development. cnpmjs as a project cant judge your environment.

I don't expect it to, but my NODE_ENV is set to `development` (because I'm on a development machine), and by default it:

1. Writes configuration data to `$dataDir/config.json` (when you start the server)
2. Reads configuration data from `path.join(root, 'config', 'config.js')`

So it doesn't read the data that it just wrote, and the result is that the admin and scope configuration is not loaded.

**Comment by alsotang** [comment]
@fengmk2 @dead-horse help look..

**Comment by dead-horse** [comment]
try `NODE_ENV=production nohup cnpmjs.org start --admins='glen' --scopes='@x' &`

**Comment by glen-84** [comment]
Yes, I'm sure that will work (I changed `=== development` to `!== development` as a temporary fix), but it seems silly to have to run the server in the `production` environment when that's not actually accurate.

My PC is using `development` because it is a development box used for developing websites and other software. It shouldn't mean that CNPM stops working. I'm not developing CNPM, I'm running it on a development machine. There is a difference.
