### ISSUE TITLE
Auth confusion

### ISSUE THREAD

**Issue by glen-84** [cnpm/cnpmjs.org#794]
First, I'll describe what we need:

1. A private registry for a company with scoped packages.
2. Only admins should be able to publish packages, add new users, etc.
3. Packages may only be installed by specific users, not the public.
4. *Specific* packages may only be installed by specific users (user `A` has access to packages `B` & `C`, but not `D`)

Number 4 is a "nice to have", but number 3 is a requirement.

I'm very confused as to how to achieve this setup. I've tried config like:

```
  "enablePrivate": true,
  "alwaysAuth": true
```

... but it doesn't seem to work. It seems that anyone can add users, and when I try to install a package, I get `unauthorized login first`, even though I have logged in.

Could you please explain what the correct configuration is, assuming that this is even possible?

Some more docs for this type of setup would be helpful. =)

**Comment by alsotang** [comment]
the auth system of cnpmjs perhaps not as flexible as your thought.

step 1 cnpmjs can do.
step 2, only admin can publish package is also easy.
but if you want only admin can add user, then you should code your own
logic. or you can prevent user register in usual time, when a user need
register, then shortly disable this retrict.
step 3, what you mean by `specific users`? seems cnpmjs can prevent public
user from installing package. just as `alwayAuth` option shows. if it dont
work, please figure it out.
step 4, cnpmjs cant do this. should build your own user system.

2016-01-14 1:15 GMT+08:00 Glen <notifications@github.com>:

**Comment by glen-84** [comment]
1. Great.
2. I've created a custom user service, so users will no longer be added automatically.
3. I misunderstood the `alwaysAuth` option, I didn't know that you had to also use `--always-auth` when logging in. It works now. =)
4. I'm not sure how you would do that. I think that these will help: #456, #577, #710. It's not urgent, but it would be nice.

Thanks for your help!

**Comment by alsotang** [comment]
3. I dont know too....I did not use this option before.

2016-01-16 0:12 GMT+08:00 Glen <notifications@github.com>:

**Comment by glen-84** [comment]
I'll close this issue now. Thanks again @alsotang. =)

**Comment by alsotang** [comment]
You are welcome

2016-01-18 15:28 GMT+08:00 Glen <notifications@github.com>:

**Comment by fengmk2** [comment]
alwaysAuth meaning every install request need contains auth header. Like npm private module install progress.
