### ISSUE TITLE
可以支持npm3.0了吗？

### ISSUE THREAD

**Issue by ibufu** [cnpm/cnpmjs.org#798]

**Comment by alsotang** [comment]
npm 3.0 的主要变化是客户端的，不受服务端的影响。

用目前的 cnpmjs.org，客户端用 3.0 没问题的。

但是如果客户端也用 cnpm 的话，那么 cnpm 客户端还是基于 2.x 的版本。

2016-01-15 21:52 GMT+08:00 ibufu <notifications@github.com>:

**Comment by YouHan26** [comment]
@alsotang 建议尽早支持npm3， npm3对windows用户来说还是蛮重要的，谢谢

**Comment by dead-horse** [comment]
源站与是否支持 npm3 没有关系，关掉了
