### ISSUE TITLE
想给现在的数据进行一次瘦身，求助？

### ISSUE THREAD

**Issue by adaiguoguo** [cnpm/cnpmjs.org#800]
请教各位大神，由于硬盘有限，之前syncModel: 'all' （现在已经切回exist了）导致数据文件占了近450G,我不动数据库，直接清除数据文件可以吗？

**Comment by fengmk2** [comment]
呃，建议删除了重新来。

**Comment by adaiguoguo** [comment]
已经重建了，谢谢
