### ISSUE TITLE
Support for project-level .[c]npmrc

### ISSUE THREAD

**Issue by glen-84** [cnpm/cnpmjs.org#801]
I have the registry set in local `.npmrc` and `.cnpmrc` files:

```
$ npm config get registry
http://127.0.0.1:7001/ # Correct

$ cnpm config get registry
http://10.0.2.2:7001/ # Incorrect (from ~/.cnpmrc)
```

Maybe this should be supported?

**Comment by alsotang** [comment]
Does official npm support this?

2016-01-18 15:42 GMT+08:00 Glen <notifications@github.com>:

**Comment by glen-84** [comment]
Yes, see [here](https://github.com/npm/npm/issues/4751). Also you can see the correct output above.
