### ISSUE TITLE
tarball url is not https

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#821]
![image](https://cloud.githubusercontent.com/assets/156269/12737827/c20f0186-c996-11e5-830f-c7f0b8d0e3e1.png)

**Comment by dead-horse** [comment]
X-Forwarded-Proto

**Comment by fengmk2** [comment]
use `$scheme` http://nginx.org/en/docs/http/ngx_http_core_module.html#scheme 

```
proxy_set_header X-Forwarded-Proto $scheme;
```

**Comment by fengmk2** [comment]
https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-load-balancing-with-ssl-termination

**Comment by alsotang** [comment]
要不用个 hsts ？

2016-02-02 11:08 GMT+08:00 fengmk2 <notifications@github.com>:
