### ISSUE TITLE
包名问题

### ISSUE THREAD

**Issue by leekangtaqi** [cnpm/cnpmjs.org#832]
私有库install完，包都是 @scope/module了，这样改动太大了，能不能保持以前的包名

**Comment by alsotang** [comment]
保持以前包名的话，官方如果有冲突包名那更麻烦。

2016-02-18 17:01 GMT+08:00 Rick Lee <notifications@github.com>:

**Comment by leekangtaqi** [comment]
不能设计成先从本地找，找不到再往中央库找吗？

**Comment by ibigbug** [comment]
@leekangtaqi 那想用中央的就没办法了。

**Comment by alsotang** [comment]
与其解决这些包名冲突问题，不如用 scope 彻底隔开。安心。

2016-02-18 20:25 GMT+08:00 Yuwei Ba <notifications@github.com>:

**Comment by dead-horse** [comment]
https://github.com/cnpm/cnpmjs.org/blob/master/config/index.js#L164

如果是以前有的私有模块，可以配置在这里保留，但是推荐还是用带 scope 的来做隔离。
