### ISSUE TITLE
安装时提示错误“下载 node v5.5.0 头文件错误” 如何解决？

### ISSUE THREAD

**Issue by XGHeaven** [cnpm/cnpmjs.org#836]
如题，提示以下错误
```
Error: 404 response downloading http://registry.npm.taobao.org/mirrors/node/v5.5.0/node-v5.5.0-headers.tar.gz
```
在安装 bufferutil 和 utf-8-validate 时都会出现，但是使用 npm 安装完全没有问题？

请问是不是 cnpm 并没有对上述头文件进行镜像？

**Comment by fengmk2** [comment]
地址应该是 http://npm.taobao.org/mirrors/node/v5.5.0/node-v5.5.0-headers.tar.gz

**Comment by fengmk2** [comment]
我测试了一下是 ok 的啊 cnpm@3.4.0

![image](https://cloud.githubusercontent.com/assets/156269/13180549/da6df7ca-d763-11e5-8aa0-466c56d6aaf2.png)

**Comment by XGHeaven** [comment]
我的 cnpm 就是按照官网上来了，是不是官网的不太正确。

这个是我的 alias
```
cnpm='npm --registry=http://registry.npm.taobao.org  cache=/Users/xgheaven/.npm/.cache/cnpm  disturl=http://registry.npm.taobao.org/mirrors/node  userconfig=/Users/xgheaven/.cnpmrc'
```
是不是应该吧 disturl 改成 http://npm.taobao.org/mirrors/node?

**Comment by alsotang** [comment]
确实官网这个 disturl 地址是不存在的，应该是  http://npm.taobao.org/mirrors/node

@fengmk2

2016-02-20 0:02 GMT+08:00 Xu Tianyang <notifications@github.com>:

**Comment by fengmk2** [comment]
了解，我修复。

**Comment by fengmk2** [comment]
fixed in 71f9014777c8f8dd8c66a7afb5a35269106f6b72

**Comment by fengmk2** [comment]
@XGHeaven 改成 `--disturl=https://npm.taobao.org/mirrors/node`
