### ISSUE TITLE
依赖包文件下载的问题

### ISSUE THREAD

**Issue by lubezhang** [cnpm/cnpmjs.org#844]
通过cnpm私服同步node模块，发现会把一个模块的所有版本都下载下来，而需要的只是某个版本，但是需要等所有版本都下载完才能提供服务，能不能改成只下载当前需要的版本。

找到了一个简化方案https://github.com/mixu/npm_lazy，它的逻辑就是用什么下载什么，特别快，但是没有管理和统计功能。

**Comment by alsotang** [comment]
你直接 cnpm install xxx@version，这样就可以不用等它同步完成了啊。这时候如果 cnpm 没有 xxx
包的话，会反代你所需要的版本。sync 的语法没必要搞那么复杂。

在 2016年2月26日 下午1:31，zhangqh <notifications@github.com>写道：

**Comment by fengmk2** [comment]
如果你深入看过npm cli发送的命令，你就会知道registry是不知道这次npm准备安装那个版本的，好多逻辑都在cli实现的。registry如果版本不全，cli就会直接报错。

**Comment by lubezhang** [comment]
@alsotang   
现在不是通过cli直接安装某个包，而是通过cnpm install安装packge.json中的所有的依赖包。你的意思是，依赖包的版本号不能是^1.0.3或1.0.x等这样的，而必须写入准确的版本号吗？

**Comment by alsotang** [comment]
不是不是。我可能理解错 cnpm 的同步机制了。。忽略我。。

在 2016年2月29日 下午4:42，zhangqh <notifications@github.com>写道：

**Comment by 999946** [comment]
@fengmk2 想了解一下，包的同步机制问题
我做了一个小测试，安装一个asysc包，而仓库上却是同步了这个包的所有版本，并且把这个包syncDevDependencies中的所有包的所有版本都下载下来了 ，这与我想要的效果有点出入。是不是我配置出错了呢？我的配置：

```JS
'use strict';
var path = require('path');

var root = path.dirname(__dirname);
var dataDir = path.join(process.env.HOME || root, '.cnpmjs.org');

module.exports = {
    bindingHost: '192.168.1.59',
    handleSyncRegistry: 'http://192.168.1.59:7001',
    database: {
		db: 'cnpmjs',
		username: 'root',
		password: '',
		dialect: 'sqlite',
		host: '127.0.0.1',
		port: 3306,
		pool: {
			maxConnections: 10,
			minConnections: 0,
			maxIdleTime: 30000
		},
		storage: path.join(dataDir, 'data.sqlite'),
		logging: !!process.env.SQL_DEBUG,
	},
	syncModel: 'exist',
	syncInterval: '3600m',
	enablePrivate: true
};
```
而我本地没有使用cnpm来安装包，采用的是nrm来切换仓库的做法，是否也会有影响？

如果我想实现的是缓存的功能，要怎么配置？
1. 本地仓库有的包直接取本地仓库的
2. 本地仓库没有的包通过代理取包，之后缓存到仓库
