### ISSUE TITLE
安装时传递的 --registry 不起作用

### ISSUE THREAD

**Issue by lili21** [cnpm/cnpmjs.org#845]
传递了这个参数，但registry 还是淘宝的。

**Comment by lubezhang** [comment]
在 ~/.cnpmrc文件中配置registry，就不需要每次都加--registry 参数了。
~~~javascript
registry=http://10.16.93.35:8888
~~~

**Comment by lili21** [comment]
```
npm install cnpm --registry=self.registry.com -g
```
这个参数不是这样用的吗？

**Comment by fengmk2** [comment]
http:// 协议没加

**Comment by lili21** [comment]
@fengmk2 实际的例子中是有加的，

但是发现这样装没有用，最后还是通过 alias 别名实现的。

实际的场景是这样的，我以前添加过 cnpm alias ，指向的是淘宝的地址。 然后我们公司弄了统一的私有库，名字也是cnpm，我就手动到.zahrc文件里把原来淘宝那一段别名配置删掉了。然后执行
```
npm install -g cnpm --registry=http://自己的私有库.com
```
然后发现安装私有库的时候，报错，报错提示信息里德registry 还是指向淘宝的。所以最后还是通过别名实现的。
