### ISSUE TITLE
Syncs package named "constructor" on new installation

### ISSUE THREAD

**Issue by glen-84** [cnpm/cnpmjs.org#857]
As mentioned [here](https://github.com/cnpm/cnpmjs.org/issues/793#issuecomment-176733092).

Clean installation of CNPM (no published packages): http://snag.gy/z02Z5.jpg

If you click the link to `constructor`, it takes you to a page that says `Can not found package match constructor. You can SYNC from official npm registry or SEARCH in official npm website.`.

What is this package?

**Comment by glen-84** [comment]
@fengmk2 Could this also be about `hasOwnProperty`? (similar to [this](https://github.com/cnpm/cnpmjs.org/pull/119))

**Comment by fengmk2** [comment]
`constructor` is worked for me, see https://npm.taobao.org/package/constructor .

Which url show you this message `Can not found package match constructor`?

**Comment by glen-84** [comment]
I never installed a package named `constructor`, and I don't want it. However, when I install CNPM for the first time, it just starts syncing this package.

I was wondering if it's because the code is iterating over an object and not excluding inherited properties.

See [here](http://stackoverflow.com/questions/31363182/how-to-understand-object-hasownpropertyconstructor). Somewhere in the sync code I think it may be missing a `hasOwnProperty` check.

`constructor` is not a package in my case, it's just an inherited JavaScript property.

**Comment by glen-84** [comment]
@fengmk2 Do you follow what I'm saying?

**Comment by fengmk2** [comment]
Yep, can you tell me a simple way to reappear this?

**Comment by glen-84** [comment]
@fengmk2,

Our configuration looks similar to this:

```js
const OurUserService = require("/path/to/our-user-service");

module.exports = {
    bindingHost: "0.0.0.0",
    registryHost: "registry.cnpm.dev.our-company.net",
    sessionSecret: "...",
    logdir: "/con/log/cnpm/",
    uploadDir: "/con/data/cnpm/downloads/",
    mail: {
        enable: true,
        appname: "Our Company CNPM",
        from: "CNPMJS <sysnotifications@our-company.net>",
        host: "mail.our-company.net",
        port: 587,
        auth: {
            user: "sysnotifications@our-company.net",
            pass: "..."
        }
    },
    npmClientName: "npm",
    admins: {
        one: "one@our-company.net",
        two: "two@our-company.net"
    },
    scopes: [
        "@our-company"
    ],
    syncModel: "exist",
    syncInterval: "24h",
    // Only admins can publish.
    enablePrivate: true,
    // Require authentication.
    alwaysAuth: true,
    // Use our custom user service.
    userService: new OurUserService()
};
```

Maybe it's something specific to `syncModel: "exist"`?

I can't get the exact values now, but we should be on Node 5.x and a recent version of NPM.

When we started the server for the first time (without installing any packages), it started to sync this `constructor` package, but obviously it doesn't really exist on our server.

**Comment by glen-84** [comment]
@fengmk2 Were you able to reproduce this issue?

**Comment by fengmk2** [comment]
I will try to reproduce this in these two days.
