### ISSUE TITLE
SyncExpriedError: Last sync time is expired

### ISSUE THREAD

**Issue by glen-84** [cnpm/cnpmjs.org#858]
New installation of CNPM, with this sync config:

```
    syncModel: "exist",
    syncInterval: "24h",
```

We get this e-mail every day:

```
Sync packages from official registry failed.
Start sync time is Sun Mar 13 2016 15:08:24 GMT+0000 (UTC).
Error message is SyncExpriedError: Last sync time is expired in 512752618 ms, lastSyncTime: Mon Mar 07 2016 16:42:31 GMT+0000 (UTC)
SyncExpriedError: Last sync time is expired in 512752618 ms, lastSyncTime: Mon Mar 07 2016 16:42:31 GMT+0000 (UTC)
at checkSyncStatus (/con/home/cnpm/sync/index.js:199:15)
at next (native)
at onFulfilled (/con/home/cnpm/node_modules/co/index.js:65:19).
```

`lastSyncTime` is always `Mon Mar 07 2016` (possibly the date of installation).

Why isn't the `lastSyncTime` being updated? How do we fix this? Could it be time zone issues?

Thanks.

PS. It should be `SyncExpiredError` and not `SyncExpriedError`.

Edit: Maybe on the first day, because the `syncInterval` is 24h, it actually tried to sync at just over 24h, which caused the error, and from that point on, it was always late? Maybe it should check `syncInterval` + 10 mins or something?

Edit 2: From the e-mails, it looks like the first sync was at `16:42:31`, and then it tries to sync at `15:08:20`.

**Comment by glen-84** [comment]
@fengmk2 I think that your commit [here](https://github.com/cnpm/cnpmjs.org/commit/4169ee9c6e8514f0834e9e1767dc5283852152d3) might be causing this issue.

**Comment by dead-horse** [comment]
You'd better keep the sync interval less than 1 hour, keep a large interval doesn't make any sense.

**Comment by fengmk2** [comment]
@glen-84 yep, `syncModel: "exist"` should not enable this check. I will make a pr to fix this.

**Comment by glen-84** [comment]
@dead-horse See my discussion with @alsotang [here](https://github.com/cnpm/cnpmjs.org/issues/793#issuecomment-171584619) (point 4).

@fengmk2 Great, thank you. =)
