### ISSUE TITLE
sync by install scoped packages

### ISSUE THREAD

**Issue by theverything** [cnpm/cnpmjs.org#860]
Why is it that cnpm doesn't try to sync on install scoped packages?

https://github.com/cnpm/cnpmjs.org/blob/master/middleware/sync_by_install.js#L42

**Comment by fengmk2** [comment]
Which scoped package you want to sync?

**Comment by theverything** [comment]
I would like to be able to run `npm --registry=http://registry.mycnpm.com @f/defaults' and if it hasn't been synced to my private registry then I would like it to sync on install

**Comment by theverything** [comment]
the problem is that if it is a scoped package then it isn't allow to be synced on install

``` javascript
  // scoped package dont sync
  if (name && name[0] === '@') {
    return yield* next;
  }
```

**Comment by theverything** [comment]
I found this line in the list controller which passes the url to the npm registry.

https://github.com/cnpm/cnpmjs.org/blob/master/controllers/registry/package/list.js#L111

but the npm registry wants the `/`  inbetween the scope and the package name to be url encoded

https://registry.npmjs.org/@f%2Fdefaults
