### ISSUE TITLE
Question about sql query optimization

### ISSUE THREAD

**Issue by wssgcg1213** [cnpm/cnpmjs.org#863]
I use mysql-community-server v5.7.9 as the storage of cnpmjs.org(2.8.1).

But I found when I access the registry, it costs about 30s and shown `504 gateway timeout`.

I trace the code and find a query in file 'services/total.js', `var TOTAL_VERSION_SQL = 'SELECT count(*) AS count FROM module;';` does not apply to any db index and costs more than 1m to return. I have about 600,000 rows in table module.

then i use `SELECT count(distinct id) AS count FROM module;` , it just cost 0.4s to return.

Is there any config mistake with my database?

**Comment by wssgcg1213** [comment]
我在自己电脑上又做了module表11W条数据的测试
mysql-5.7.10-osx10.9-x86_64

对下面这两条sql做分析, 查询的结果肯定是一样的, 但是查询耗时不一样
select count(name) as count from module;
select count(distinct id) as count from module;


```mysql
mysql> explain select count(name) as count from module;
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+------------------------------+
| id | select_type | table | partitions | type | possible_keys | key  | key_len | ref  | rows | filtered | Extra                        |
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+------------------------------+
|  1 | SIMPLE      | NULL  | NULL       | NULL | NULL          | NULL | NULL    | NULL | NULL |     NULL | Select tables optimized away |
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select count(name) as count from module;
+--------+
| count  |
+--------+
| 114755 |
+--------+
1 row in set (0.59 sec)
```

### 上面这条特别慢, 下面就快一些

```mysql
mysql> explain select count(distinct id) as count from module;
+----+-------------+--------+------------+-------+-----------------------------------------------+--------------+---------+------+-------+----------+-------------+
| id | select_type | table  | partitions | type  | possible_keys                                 | key          | key_len | ref  | rows  | filtered | Extra       |
+----+-------------+--------+------------+-------+-----------------------------------------------+--------------+---------+------+-------+----------+-------------+
|  1 | SIMPLE      | module | NULL       | index | PRIMARY,name,gmt_modified,publish_time,author | gmt_modified | 5       | NULL | 51001 |   100.00 | Using index |
+----+-------------+--------+------------+-------+-----------------------------------------------+--------------+---------+------+-------+----------+-------------+
1 row in set, 1 warning (0.00 sec)

mysql> select count(distinct id) as count from module;
+--------+
| count  |
+--------+
| 114755 |
+--------+
1 row in set (0.07 sec)
```

数据库结构完全是从最新的db.sql导入的

**Comment by dead-horse** [comment]
看起来第一条没有走到索引啊

**Comment by dead-horse** [comment]
额，这个你的数据是有问题的，真实的数据 name 并不是唯一的，一个 name 可能有多个版本，所以必须要 distinct name 才能拿到真实的模块数数据

**Comment by wssgcg1213** [comment]
@dead-horse 
其实`select count(name) as count from module;`这条sql是从你们的`services/total.js`文件里找出来的, 这个查询是给registry的doc_version_count字段提供数据的, 但是我这边这条67W的数据竟然需要跑36s显然是有问题, 然后我改成`SELECT count(distinct id) AS count FROM module;`就只需要0.4s, 我想知道问题在哪

**Comment by dead-horse** [comment]
按理说不应该这么慢的， name 上是有索引应该和 id 没这么大差别，不过我现在手头没线上数据库的配置，@fengmk2 看看吧

**Comment by fengmk2** [comment]
@wssgcg1213 我跑了一下，是可以利用索引的。

![image](https://cloud.githubusercontent.com/assets/156269/14117480/6f1cac1e-f617-11e5-95a6-36cd4c99940a.png)

你 `desc module` 看看表结构，难道 name 没有建索引？

![image](https://cloud.githubusercontent.com/assets/156269/14117512/8eb6e63e-f617-11e5-8461-98273e6658df.png)

**Comment by alsotang** [comment]
顺便问一句，@wssgcg1213 <https://github.com/wssgcg1213>  你的表是从哪里建的？sql文件导入还是什么的？

2016-03-30 1:34 GMT+08:00 fengmk2 <notifications@github.com>:

**Comment by wssgcg1213** [comment]
@fengmk2 

看起来是有索引的

```mysql
mysql> desc module;
+--------------+---------------------+------+-----+---------+----------------+
| Field        | Type                | Null | Key | Default | Extra          |
+--------------+---------------------+------+-----+---------+----------------+
| id           | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| gmt_create   | datetime            | NO   |     | NULL    |                |
| gmt_modified | datetime            | NO   | MUL | NULL    |                |
| author       | varchar(100)        | NO   | MUL | NULL    |                |
| name         | varchar(100)        | NO   | MUL | NULL    |                |
| version      | varchar(30)         | NO   |     | NULL    |                |
| description  | longtext            | YES  |     | NULL    |                |
| package      | longtext            | YES  |     | NULL    |                |
| dist_shasum  | varchar(100)        | YES  |     | NULL    |                |
| dist_tarball | varchar(2048)       | YES  |     | NULL    |                |
| dist_size    | int(10) unsigned    | NO   |     | 0       |                |
| publish_time | bigint(20) unsigned | YES  | MUL | NULL    |                |
+--------------+---------------------+------+-----+---------+----------------+
12 rows in set (0.00 sec)
```


@alsotang 
建表过程是: 我把`docs/db.sql`文件里的内容全部复制出来, 在 Navicat (a mysql GUI) 里执行.

**Comment by wssgcg1213** [comment]
我刚才把那个11W数据的样本`module`表单独备份出来, 放到另一个mysqld版本为5.1的环境测试, 就正常了. 

```mysql
mysql> explain select count(name) as count from module;
+----+-------------+--------+-------+---------------+------+---------+------+--------+-------------+
| id | select_type | table  | type  | possible_keys | key  | key_len | ref  | rows   | Extra       |
+----+-------------+--------+-------+---------------+------+---------+------+--------+-------------+
|  1 | SIMPLE      | module | index | NULL          | name | 394     | NULL | 322355 | Using index |
+----+-------------+--------+-------+---------------+------+---------+------+--------+-------------+
1 row in set (0.00 sec)

mysql> select count(name) as count from module;
+--------+
| count  |
+--------+
| 114755 |
+--------+
1 row in set (0.00 sec)

mysql> status
--------------
mysql  Ver 14.14 Distrib 5.1.50, for unknown-linux-gnu (x86_64) using readline 5.1
```

所以我怀疑是 mysql 版本引起的?
我生产环境和自己电脑都是mysql5.7, 都出现了同样的问题. 而另一台mysql5.1的则正常.

**Comment by alsotang** [comment]
感觉这坑有点深啊

2016-03-30 8:06 GMT+08:00 ZeroLing <notifications@github.com>:

**Comment by fengmk2** [comment]
@wssgcg1213 目前我们只在 mysql 5.5 运行，5.7 还没升级。你可以深入看看为什么 5.7 的索引没生效，按道理对于 mysql 来说这种不应该的。

**Comment by wssgcg1213** [comment]
我又重新部署了一套5.5的 mysqld, 是能够使用索引的. 所以目前看来问题好像仅仅出现在 mysql5.7

[http://stackoverflow.com/questions/1992312/meaning-of-select-tables-optimized-away-in-mysql-explain-plan](http://stackoverflow.com/questions/1992312/meaning-of-select-tables-optimized-away-in-mysql-explain-plan)

按照上面说的, Select tables optimized away. 的意思是查询已经优化到不能再优化了.

如果没有事务性操作, 可以不使用 innodb 而使用MyISAM, MyISAM对于not null的字段会在一个单独的区域存储行数, 这样count()操作就是一个 O(1) 的过程, 我实测是几乎0s就能读出11W的数据 (0.00s).

我这边暂时改成 count(distinct id) 来强行使用索引, 然后继续挖下去看看, 如果有 DBA 能够解惑就太好了

**Comment by youkpter** [comment]
不好意思来挖坟了。
最近正好在了解 mysql count(*)，搜到了这个 issue。

大概的情况应该是这样的：

从 mysql 5.7.2 开始，innodb 通过扫描聚集索引来计算行数，在这之前是通过扫描一个二级索引实现，见 
 [5.7.2 change log](https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-2.html)。虽然本意是优化，但某些情况下走二级索引反而还更快（这个在 5.7.18有进行修复，改回使用二级索引，见 [5.7.18 change log](https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-18.html)）。

在这里，select count(name) 走的是聚集索引，而 select count(distinct(id)) 走的是二级索引。
虽然前者的 explain 显示它被优化过了，但对于聚集索引比二级索引大太多的情况下，性能反而会更差；
而后者因为走了二级索引，没有采取新的优化手段，所以反而更快。

更多可参考：
[MySQL · 引擎特性 · InnoDB COUNT(*) 优化(?)](http://mysql.taobao.org/monthly/2016/06/10/#)  by 阿里云RDS-数据库内核组
