### ISSUE TITLE
Only admin user can unpublish

### ISSUE THREAD

**Issue by dead-horse** [cnpm/cnpmjs.org#866]
http://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm

- [ ] unpublish admin check
- [ ] placeholder package https://github.com/npm/security-holder

**Comment by fengmk2** [comment]
cc @ruanyf

**Comment by fengmk2** [comment]
![image](https://cloud.githubusercontent.com/assets/156269/14007261/070f32ce-f1b0-11e5-9688-bd3d917c1086.png)

**Comment by dead-horse** [comment]
我们不允许删除就不需要 placeholder package 了吧

**Comment by fengmk2** [comment]
嗯，也是
