### ISSUE TITLE
五分钟安装私有npm不能通过内网IP访问

### ISSUE THREAD

**Issue by Tonyhark** [cnpm/cnpmjs.org#869]
为什么只能用localhost或者127.0.0.1来访问
例如我的内网ip是：192.168.1.2。
192.168.1.2:7002 就不能访问了？有解决方案吗？

谢谢

**Comment by alsotang** [comment]
nginx 做反代。本来 node 程序也不适合直接暴露出来。

2016-03-28 20:37 GMT+08:00 Tonyhark <notifications@github.com>:

**Comment by wssgcg1213** [comment]
@Tonyhark 
改配置文件 bindingHost: '0.0.0.0'

@alsotang 
其实还是有这种需求的, 比如我这边的架构是基于KVM的
宿主机对外提供反代, 放置 nginx
kvm 上部署一个专门用来跑 node 的小集群, 私有 npm 服务就部署在这些 kvm 内, 虚拟机的 IP 都是 192.x , 那么就需要宿主机的 ng 来反代这些 kvm 的服务, 如果是虚拟机内 bind 127.0.0.1 的话, 就还需要在虚拟机里再起一个nginx, 太麻烦

**Comment by fengmk2** [comment]
@wssgcg1213 正解

**Comment by Tonyhark** [comment]
非常感谢楼上各位的回复！
@wssgcg1213  
1 具体是改哪个配置文件？ 是.cnpmjs.org 里的config.json ?我改了没用。
2 还是说使用这个命令时增加参数： nohup cnpmjs.org start --admins='myname,othername' \
  --scopes='@my-company-name,@other-name' & 

@alsotang  
能请教下具体nginx反向代理怎么做，能提供相关的链接吗？ 

谢谢！

**Comment by Tonyhark** [comment]
补充下 我是在Mac OS X 10.12上操作的。

我的目的是能让在局域网内的小伙伴通过私有NPM安装部及署私有包

**Comment by taoqf** [comment]
反向代理的方式有人用过吗？我反向代理后在其它机器上不能 install 只能 info.请问有人知道是为什么吗？
```
RequestError: connect ECONNREFUSED 127.0.0.1:7001 (req "error").
```

**Comment by alsotang** [comment]
如果不用反代没问题，用了反代出错的话，就从反代上面找问题嘛。看看 nginx 日志，那一个请求出错了。

2016-06-13 14:16 GMT+08:00 taoqf <notifications@github.com>:

**Comment by taoqf** [comment]
this solved my problem [https://github.com/cnpm/cnpmjs.org/issues/615](https://github.com/cnpm/cnpmjs.org/issues/615)
but, where is the profile bindinghost?

**Comment by GitNiko** [comment]
bindinghost 在 config/index.js 里。
我也遇到类似的问题，我解决方式比较鲁莽，直接改了worker.js
```js
//registry.listen(config.registryPort, config.bindingHost);
registry.listen(config.registryPort);
//web.listen(config.webPort, config.bindingHost);
web.listen(config.webPort);
