### ISSUE TITLE
mysqld and mysql cli 具体是指啥？

### ISSUE THREAD

**Issue by Tonyhark** [cnpm/cnpmjs.org#873]
wiki--How to deploy中提到的： 
MySQL >= 0.5.0, include mysqld and mysql cli  这两个工具具体是指什么？ 能帮忙提供相关的文档地址或者下载地址吗？

谢谢！

**Comment by dead-horse** [comment]
如果你是用 linux 的话，安装好 mysql 就会有这两个命令，`mysqld` 用来运行 mysql 服务，`mysql` 用来连接 mysql 服务

**Comment by Tonyhark** [comment]
我的是Mac 也是自带吗？

**Comment by alsotang** [comment]
你的mac没有自带 cnpm server 吗？好奇怪。

2016-03-29 18:07 GMT+08:00 Tonyhark <notifications@github.com>:

**Comment by Tonyhark** [comment]
@alsotang  我在mac上安装的mysql主程序 (mysql-5.7.11-osx10.10-x86_64.dmg)， 也自带 mysqld 和mysql CLI 吗？ 我装了之后好像是没mysqld 和 mysal这两个命令。
对mysql 不太了解问了身边的后台他们似乎也不太了解。所以在这里求助下。

**Comment by dead-horse** [comment]
@Tonyhark google 解决这个问题吧，查查 mysql 官方安装文档
