### ISSUE TITLE
Default logo cannot be accessed over https

### ISSUE THREAD

**Issue by glen-84** [cnpm/cnpmjs.org#887]
Works: http://ww4.sinaimg.cn/large/69c1d4acgw1ebfly5kjlij208202oglr.jpg
Doesn't: https://ww4.sinaimg.cn/large/69c1d4acgw1ebfly5kjlij208202oglr.jpg

```
ww4.sinaimg.cn uses an invalid security certificate.

The certificate is not trusted because it is self-signed. The certificate is only valid for *.cdngp.net

Error code: SEC_ERROR_UNKNOWN_ISSUER
```

Is this easy to fix, or should we use a custom logo?

**Comment by fengmk2** [comment]
I will replace it with https://os.alipayobjects.com/rmsportal/oygxuIUkkrRccUz.jpg

![](https://os.alipayobjects.com/rmsportal/oygxuIUkkrRccUz.jpg)

**Comment by alsotang** [comment]
http://www.whatfontis.com/Gubblebum-Blackn-Blocky-jelloween.font?text=cnpm

2016-04-12 11:22 GMT+08:00 fengmk2 <notifications@github.com>:
