### ISSUE TITLE
本地镜像是否支持只同步需要的版本？是否支持cnpm i时自动同步？

### ISSUE THREAD

**Issue by luqin** [cnpm/cnpmjs.org#889]
本地镜像是否支持只同步需要的版本？是否支持cnpm i时自动同步？

**Comment by dead-horse** [comment]
1. 不支持，因为 npm install 的时候是直接下载所有版本并在客户端进行 semver 匹配的，如果版本不全会拿不到信息
2. 支持，所有请求不到的包会去官方请求，并后台开启同步

**Comment by fengmk2** [comment]
我建议你将同步模式改为 none，这样你只需要管理私有模块，公有模块全部都 npm.taobao.org 。

**Comment by luqin** [comment]
maven的同步逻辑好像不是这样吧？只同步需要的版本？后续能否提供按版本同步功能？

本地需要频繁安装模块，但是经常会出现获取包不稳定

**Comment by luqin** [comment]
@dead-horse 如果切换为npm i时能否自动安装？

**Comment by fengmk2** [comment]
npm 又不是 maven。
