### ISSUE TITLE
sync Model疑惑

### ISSUE THREAD

**Issue by lijiexiang** [cnpm/cnpmjs.org#895]
// sync mode select
  // none: do not sync any module, proxy all public modules from sourceNpmRegistry
  // exist: only sync exist modules
  // all: sync all modules
  syncModel: 'all', // 'none', 'all', 'exist'

syncModel里的exist是相对于哪个部分的，哪些module才属于exist的？

**Comment by alsotang** [comment]
通过 cnpm install 下载的时候，不存在的包会被本地同步过来，这时候这些包就是 exist 的。

2016-04-18 15:14 GMT+08:00 lijiexiang <notifications@github.com>:
