### ISSUE TITLE
package.html 结构问题

### ISSUE THREAD

**Issue by jpuncle** [cnpm/cnpmjs.org#899]
<img width="569" alt="2016-04-22 7 18 16" src="https://cloud.githubusercontent.com/assets/1422472/14740108/0f74e276-08bf-11e6-96ba-4c6b15dd7b1e.png">

这个结构是故意的么？

**Comment by fengmk2** [comment]
bug？

**Comment by jpuncle** [comment]
@fengmk2 多了个 div，看着好像应该去掉
