### ISSUE TITLE
请问有官方的Docker镜像吗？

### ISSUE THREAD

**Issue by giphoo** [cnpm/cnpmjs.org#903]
RT

**Comment by fengmk2** [comment]
对 docker 还没深入玩过， @giphoo 可以尝试一下？

**Comment by hbrls** [comment]
@giphoo 我做了一个镜像 https://hub.docker.com/r/hbrls/cnpmjs/，公司内部正在试用，欢迎跟进

**Comment by fengmk2** [comment]
@hbrls 👍

**Comment by jesusalexander** [comment]
貌似COPY 进去的config.json run完被覆盖了。
今天试了一下无论是挂载还是COPY进去的run完内容都变成 ` {} `  。。

**Comment by Firef0x** [comment]
我根据 @hbrls 大神的镜像扩充了一个使用阿里云 OSS 作为存储的 Docker 镜像 [Docker-cnpmjs-oss](https://hub.docker.com/r/firef0x/docker-cnpmjs-oss/)，可以使用 MySQL 作为仓库数据库，感谢大神的前期成果！顺祝大家春节愉快！ 🌸
