### ISSUE TITLE
了解一下技术细节问题

### ISSUE THREAD

**Issue by LC2010** [cnpm/cnpmjs.org#905]
前些时间用cnpm搭建了私有仓库，顺便在基础上做了二次的扩展开发，有几个疑问：

1. 发现工程上咱们自己实现了cfork还有graceful以及启动脚本。想问下这个是处于什么考虑的，用PM2干这些事情有什么坑么？你们现在内部的监控都是直接nohub运行在后台么？是否选择PM2？

2. 目前这个项目是我现在找到Koa为数不多的实践，不知道贵团队有没有更多的Koa最佳实践可以推荐参考的

3. 看了代码中ejs模板引擎的用法，发现用了replace实现了footer和header等的替换，这样带来的问题是，如果修改footer和layout文件中的内容，是没法自动热更新吧？没法及时看到修改效果？

麻烦帮忙解惑一下，谢谢。

**Comment by alsotang** [comment]
1. 我们进行 node 工程实践的时候，pm2 还没有出来。以及 pm2 之所以叫 pm2，是因为
http://npm.taobao.org/package/pm 这个名字被 @fengmk2 用了。我觉得这也算是个历史原因？@fengmk2
@dead-horse

2. https://github.com/17koa

在 2016年5月4日 上午9:40，liangchao <notifications@github.com>写道：

**Comment by dead-horse** [comment]
我们并没有用到 pm2 那么多的功能，且已经有了一套简洁的多进程管理方案了，所以就没有使用 pm2

**Comment by alsotang** [comment]
我个人的话，新项目还是用 pm2 的，之前 nodeclub 我就改成 pm2 来管理多进程了。

现在 cnpmjs.org 的这套方案，如果想看进程是否存在，还需要用 `ps aux` 来看进程。不算是一个方案吧？只是把程序跑起来了。

在 2016年5月4日 上午11:24，Yiyu He <notifications@github.com>写道：

**Comment by dead-horse** [comment]
@alsotang 原因是内部有通用监控方案在做了 pm2 做的监控相关的事情

cnpm 只是提供服务，至于选择用什么进程管理方案，这个 cnpm 并不关心，只是仓库中默认使用了 cfork 而已

**Comment by alsotang** [comment]
这倒也是。进程管理跟项目逻辑是分离的。改造一下成本也不高。

在 2016年5月4日 上午11:31，Yiyu He <notifications@github.com>写道：

**Comment by fengmk2** [comment]
@LC2010 我回答一下吧。

> 1. 发现工程上咱们自己实现了cfork还有graceful以及启动脚本。想问下这个是处于什么考虑的，用PM2干这些事情有什么坑么？你们现在内部的监控都是直接nohub运行在后台么？是否选择PM2？

我的理由很简单，pm2本身比 cnpmjs.org 还要复杂 N 倍。

正如 @dead-horse 说的，cnpmjs.org 具体运行的时候使用 pm2 还是其他，这个由部署的角色来判断，熟悉 pm2的就用它吧。而 cnpmjs.org 默认带的 dispatch.js 是使用 cfork 来自动完成，这样不管在什么环境，我都能够使用 `$ node dispatch.js` 将应用以多进程方式运行起来，并且是生产级别的运行方式。

> 2. 目前这个项目是我现在找到Koa为数不多的实践，不知道贵团队有没有更多的Koa最佳实践可以推荐参考的

其实我们在公司内部已经使用 koa 做应用开发超过3年了，积累了很多也将能反馈的代码贡献到 koa 以及 koa 相关的各个项目，你可以从 github 上找到我们提交的 commits 和模块。今年9月份的 ningjs，我们也会将这几年的 koa 企业应用开发经验，通过一个基于 koa 的框架 egg 开源出去 http://weibo.com/5070687652/DtY33j1yo ，如果有时间，可以到时候线下详细交流。

> 3. 看了代码中ejs模板引擎的用法，发现用了replace实现了footer和header等的替换，这样带来的问题是，如果修改footer和layout文件中的内容，是没法自动热更新吧？没法及时看到修改效果？

这个不是一般 web 应用推荐的方式，这是我跟 @dead-horse 偷懒不想写 html 而取巧使用 markdown 自动生成首页 html 的方式，所以不建议你按照 cnpmjs.org 的方式来做。你应该看 ejs，nunjucks 等模板引擎官方推荐的使用方式来做。

---

cnpmjs.org 也是我跟 @dead-horse 的第一个 koa 应用，里面肯定不是使用不太合理的地方，参考的话还需要自行多思考，选择最合适你的方式。

**Comment by fengmk2** [comment]
@LC2010 才看见你是360的，我们这个月的20号跟 @itchina110 约了去 360 node 团队做交流，不知道是否你所在的团队。到时候也可以详细聊聊。

**Comment by LC2010** [comment]
嗯，因为淘宝在Node服务化走的比较早，所以一直知道几位在Node和Koa上贡献很多。所以就拿CNPM作为一个Koa的解决案例来参考了，因为比较权威，所以对于实践上的不理解就更迷惑了：）感谢 @fengmk2 @alsotang @dead-horse 三位的细心解惑。

波大果然交际花，已经约了几位，那就再好不过了，我正好也在奇舞团团队，最近正好在一个项目上做前后端分离，回头会有更多问题抛给各位，希望回头能够深度交流。 感谢各位：）

**Comment by fengmk2** [comment]
订正一下是 奇舞团团队，360目前是没有 node 团队的。

**Comment by itchina110** [comment]
原来是在这里聊！

2016-05-04 22:28 GMT+08:00 fengmk2 <notifications@github.com>:

> Closed #905 <https://github.com/cnpm/cnpmjs.org/issues/905>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cnpm/cnpmjs.org/issues/905#event-650258393>
>



-- 
此致

Mr. Zhou YuBo - 周裕波

 邮件：itchina110@gmail.com
