### ISSUE TITLE
binary-mirror-config/latest 返回404的问题

### ISSUE THREAD

**Issue by inickel** [cnpm/cnpmjs.org#906]
我的部署ip是：192.168.5.99
每次在发布或包的时候都会提示接口返回404：http://192.168.5.99:7001/binary-mirror-config/latest
cnpm update失效

**Comment by fengmk2** [comment]
https://registry.npm.taobao.org/binary-mirror-config/latest  这个是存在的

**Comment by inickel** [comment]
意思是cnpm客户端设置registry为本地的时候，这个服务是无效的？
cnpmjs.org没有这个服务么？

**Comment by dead-horse** [comment]
@fengmk2 看来要把这个独立搞个配置

**Comment by fengmk2** [comment]
@inickel 你开启了镜像模式了吗？

**Comment by inickel** [comment]
@fengmk2 镜像模式？在配置文件里面没有看见相关字眼，能解释下么？

**Comment by fengmk2** [comment]
我给 npminstall 修改一下吧，让它自动支持去多个 registry 寻址。

**Comment by fengmk2** [comment]
@inickel 使用 `npm i -g cnpm --registry=https://registry.npm.taobao.org` 重新安装一下 cnpm

**Comment by inickel** [comment]
@fengmk2  ok ths
