### ISSUE TITLE
Can I sync all existing modules at once?

### ISSUE THREAD

**Issue by bigeagle** [cnpm/cnpmjs.org#907]
I there,

I'm the maintainer of [TUNA](https://mirrors.tuna.tsinghua.edu.cn/) mirror site, and currently we wanna use cnpmjs.org to set up a npm mirror in Tsinghua.

I found that the cnpmjs syncs packages "lazily", that syncing is only applied to packages which are either triggered by `npm install` or `cnpm sync`.

I wanna make sure whether this kind of syncing is right, or is there a completely syncing mode that all exisiting modules can be synced at once.

Cheers,
Justin

**Comment by bigeagle** [comment]
I guess I've found how. Thx.

**Comment by fengmk2** [comment]
👍 for the TUNA mirror site.
