### ISSUE TITLE
public scope packages won't auto sync

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#908]
- https://github.com/cnpm/cnpm/issues/107
- need to wait https://github.com/npm/registry/issues/13 response

**Comment by wssgcg1213** [comment]
能不能*暂时*这么做: 对于 scoped package
1. HTTP302到registry.npmjs.org
2. 尝试从源站同步这个包
===
Can we do this temporarily:  for scoped package
1. send HTTP 302 to registry.npmjs.org
2. Try to synchronize the package from the source site

@fengmk2

**Comment by fengmk2** [comment]
https://replicate.npmjs.com/_changes?since=2607000 实时推送接口

**Comment by fengmk2** [comment]
![image](https://cloud.githubusercontent.com/assets/156269/16318599/7136bf8c-39c2-11e6-85e7-c6e7f4dc8ce5.png)

**Comment by fengmk2** [comment]
scope 也 ok 了

```
{"seq":2606743,"id":"jsonapi-linker","changes":[{"rev":"5-aaa3e4e1489e1868eeae2bbb63c9a316"}]}
{"seq":2606745,"id":"@wework/oui","changes":[{"rev":"88-78aad0e1fbe8b513e4d22bb02c54d4ea"}]}
{"seq":2606747,"id":"laravel-elixir-ngtemplatecache","changes":[{"rev":"4-f1c55086d203b035465656ab096acb83"}]}
{"seq":2606749,"id":"eslint-config-picnic","changes":[{"rev":"5-c5a49a94b3e83301e74e2cb9b5da37c8"}]}

```

**Comment by fengmk2** [comment]
changes-stream 来读取数据 https://github.com/npm/readme-tester/blob/master/index.js#L9

**Comment by fengmk2** [comment]
最后的 seq 可以通过 https://replicate.npmjs.com : update_seq 获取到
