### ISSUE TITLE
npm run start启动cnpmjs.org后，不能访问7001

### ISSUE THREAD

**Issue by alanjin** [cnpm/cnpmjs.org#913]
npm run start启动cnpmjs.org后，不能访问http://127.0.0.1:7001，返回“内部服务器错误”，但能访问http://127.0.0.1:7002，请问是什么原因？
补充：我在config/index.js里修改使用了mysql数据库。

**Comment by alanjin** [comment]
已经搞定

**Comment by xuezier** [comment]
请问如何解决？

**Comment by alanjin** [comment]
完全按照http://blog.fens.me/nodejs-cnpm-npm/的方法配置即可。我的问题主要集中在数据库以及依赖库上了。
