### ISSUE TITLE
Base url behind nginx proxy

### ISSUE THREAD

**Issue by calexandre** [cnpm/cnpmjs.org#915]
Hello guys,
Maybe you can help me on this one...

I am trying to setup a nginx reverse proxy to serve cnpmjs on a url like "http://my-server-url.net/npm/"
The page loads, but fails to download resources such as css, scripts, etc...

This is what I am seeing in the page inspector:

```
404 GET http://my-server-url.net/css/antd-0.9.1.min.css
404 GET http://my-server-url.net/css/main.css 
404 GET http://my-server-url.net/css/yue.css 
404 GET http://my-server-url.net/css/github.css 
404 GET http://my-server-url.net/css/github-markdown.css 
404 GET http://my-server-url.net/js/readme.js 
```

Apparently, the base url is missing in the page rendering...
This would be the correct url: http://my-server-url.net/npm/css/antd-0.9.1.min.css
The baseUrl is /npm/

Here is my nginx configuration:

```
location /npm/ {
        proxy_pass              http://localhost:7001/
        proxy_set_header        X-Real-IP               $remote_addr;
        proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header        Host                    $host;
}
```

Can you shed me some lights on how can setup this case properly ?
Thank you...

**Comment by alsotang** [comment]
surely there can be some method to solve this relative path problem.

but can you use a subdomain instead of `/npm`? if so, it is prefect.

otherwise you will meet some other problems because npm dont expect to
exist in a /path

2016-05-12 2:40 GMT+08:00 calexandre <notifications@github.com>:

**Comment by calexandre** [comment]
Unfortunately, I cannot setup a subdomain...
Is there any other way to setup a base path? 

I have a suggestion, but it requires a bit of development:
I've seen several apps making use of a custom "X-" header indicating a base path...usually, this header is injected by a proxy.

Something like:
```
proxy_set_header X-Cnpmjs-Base /npm
```

This way, cnpmjs.org could be proxy-aware and append the base path to all rendered urls...

**Comment by calexandre** [comment]
I am currently working on a pull request that will allow cnpmjs to run behind a nginx reverse proxy with a context base path.

Something like:

Nginx public url: **http://example.org/cnpmjs**
Private url: **http://localhost:7002**

The problem, as I mentioned above, is that cnpmjs has been designed to always pull content from the location's root, making it impossible to run on a contextual path.

I've been diggin a lot through the code, and found possible solution.
BUT, in order to make this work, some core changes need to be done:

1. All view urls must be changed to relative paths. This means that the urls **must not** start with `/` (example: `/css/some-css.css`). If they are absolute, the context path will always be ignored. In fact, I don't think it is a good practice to write urls in this form, unless you have a very good reason to.

2. A base tag must be added to the HEAD element. This is a W3C standard, and it tells the browser the actual base path to apply to all relative urls (hence the need to change from **absolute** to **relative** urls). You can more about it here: http://www.w3schools.com/tags/tag_base.asp

3. Finally, a koa middleware that reads a proxy injected header and sets the base tag with the actual. Something like: **http://example.org/cnpmjs/** (the host is optional, what matters is the context path **/cnpmjs/**

With this setup, I can write a nginx rule that injects the header and the site works as expected. I've already tested this in my private environment and it works like a charm...

What do you think?

**Comment by alsotang** [comment]
or use another port? not 80?

2016-05-15 22:42 GMT+08:00 Carlos Alexandre <notifications@github.com>:

**Comment by fengmk2** [comment]
Why not http://npm.my-server-url.net ?

**Comment by calexandre** [comment]
That would be the most optimal solution. Unfortunately, I cannot create a
subdomain...

2016-05-16 16:07 GMT+01:00 fengmk2 <notifications@github.com>:

> Why not http://npm.my-server-url.net ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cnpm/cnpmjs.org/issues/915#issuecomment-219449868>
>



-- 
Cumprimentos,
Carlos Alexandre

**Comment by ibigbug** [comment]
can you serve static files via nginx directly? such as

```
location ~ ^/(css|js) {
    root /tmp/cnpmjs.org/public;
}
```
