### ISSUE TITLE
[Error: TypeError config.userService.auth(...)]  npm adduser 失败 & 如何加入权限验证 

### ISSUE THREAD

**Issue by ucoker** [cnpm/cnpmjs.org#925]
- **环境**
  - ubuntu 14.04
  - node v5.11.1
  - npm 3.9.2
  - cnpm 从Github获取，按wiki教程安装

- **`npm adduser ...`失败**  
根据wiki的这篇文章搭建了cnpm －－》 [Deploy From Source Code [recommend]](https://github.com/cnpm/cnpmjs.org/wiki/Deploy#deploy-from-source-code-recommend)  
可以正常打开 http://localhost:7002
![qq20160520-0](https://cloud.githubusercontent.com/assets/12216739/15427917/ea7d1f3e-1eca-11e6-8a57-529020362988.png)  
在终端上执行：  
`npm adduser --registry=http://127.0.0.1:7001 --verbose`后，没能成功添加。错误代码：

	```bash
	npm verb adduser before first PUT { _id: 'org.couchdb.user:username',
	npm verb adduser   name: 'username',
	npm verb adduser   password: 'XXXXX',
	npm verb adduser   email: 'username@username.com',
	npm verb adduser   type: 'user',
	npm verb adduser   roles: [],
	npm verb adduser   date: '2016-05-20T09:46:35.917Z' }
	npm verb request uri http://localhost:7001/-/user/org.couchdb.user:username
	npm verb request new user, so can't send auth
	npm info attempt registry request try #1 at 5:46:35 PM
	npm verb request id 585ce5a9b9c40f9c
	npm http request PUT http://localhost:7001/-/user/org.couchdb.user:username
	npm http 500 http://localhost:7001/-/user/org.couchdb.user:username
	npm verb headers { 'content-type': 'application/json; charset=utf-8',
	npm verb headers   'x-readtime': '9',
	npm verb headers   'content-length': '101',
	npm verb headers   date: 'Fri, 20 May 2016 09:46:35 GMT',
	npm verb headers   connection: 'keep-alive' }
	npm info retry will retry, error on last attempt: Error: TypeError config.userService.auth(...)[(intermediate value)] is not a function: -/user/org.couchdb.user:username
	npm info attempt registry request try #2 at 5:46:46 PM
	npm http request PUT http://localhost:7001/-/user/org.couchdb.user:username
	npm http 500 http://localhost:7001/-/user/org.couchdb.user:username
	npm verb headers { 'content-type': 'application/json; charset=utf-8',
	npm verb headers   'x-readtime': '2',
	npm verb headers   'content-length': '101',
	npm verb headers   date: 'Fri, 20 May 2016 09:46:46 GMT',
	npm verb headers   connection: 'keep-alive' }
	npm info retry will retry, error on last attempt: Error: TypeError config.userService.auth(...)[(intermediate value)] is not a function: -/user/org.couchdb.user:username
	```

	**在issue或者Google上都未能找到与`Error: TypeError config.userService.auth(...)[(intermediate value)]`相关的错误解决办法，请问我应该如何解决？**

- **如何加入权限验证**  

	我想使用cnpm作为私有库，但是并非搭建在内网。而是在阿里云的ubuntu平台上搭建。
	若要加权限验证，是否是根据这篇－－》[Use-Your-Own-User-Authorization](https://github.com/cnpm/cnpmjs.org/wiki/Use-Your-Own-User-Authorization)来配置？
	例如这样配置：
	修改`cnpmjs.org/config/index.js`:
	
	```json
	...
	admins: {
	    // name: email
	    username: 'username@username.com'
	  },
	userService: {
	    "login": "username",
	    "email": "username@username.com",
	    "scopes": [ "@db" ]
	  },
	 alwaysAuth: true,
	```
	
	修改完这个配置，重新启动服务后。对应的账号密码是不是又 `npm adduser ...`来产生？

### 总结下遇到的两个问题：
- `npm adduser ...`失败，具体错误信息在上面。
- 将cnpm搭建在公网阿里云，如何正确添加权限验证。

**Comment by dead-horse** [comment]
userService 是你自己实现的一个接口集合，可以看这个：

https://github.com/cnpm/cnpmjs.org/wiki/Use-Your-Own-User-Authorization

**Comment by dead-horse** [comment]
仔细看一下，不是你填的这个东西。。。

**Comment by ucoker** [comment]
现在是 `npm adduser ...` 后失败，提示  `Error: TypeError config.userService.auth(...)[(intermediate value)] `  
奇怪我并在网上没找到跟我类似的情况，不清楚我是哪里错了，或者环境哪边没弄好。 
环境的搭建我参考这篇  https://github.com/cnpm/cnpmjs.org/wiki/Deploy#deploy-from-source-code-recommend

**Comment by dead-horse** [comment]
> userService 是你自己实现的一个接口集合，可以看这个：
> https://github.com/cnpm/cnpmjs.org/wiki/Use-Your-Own-User-Authorization

再复述一遍，你的配置配错了

**Comment by alsotang** [comment]
呃  userService 填得太错。

2016-05-20 23:26 GMT+08:00 Yiyu He <notifications@github.com>:

**Comment by alsotang** [comment]
userService 保持 null 就好了

2016-05-21 0:04 GMT+08:00 alsotang <alsotang@gmail.com>:

**Comment by ucoker** [comment]
@dead-horse @alsotang  不好意思，我确实看错，理解错了。
后来第二次测试，我把userService改回null，忘记restart。
现在adduser 正常。我验证下userService

**Comment by ucoker** [comment]
总结下为何犯错：  
以下的所提到的配置文件为：`cnpmjs.org/config/index.js`
1. 在配置文件中的database config，原`dialect: 'sqlite'`,而我在ubuntu安装的是**mysql**,应该改成`dialect: 'mysql'`，而引起第一个错误（大致错误代码为：`SQLITE_ERROR: no such table`）
2. 未看清并理解[Use Your Own User Authorization](https://github.com/cnpm/cnpmjs.org/wiki/Use-Your-Own-User-Authorization)这篇wiki，而将配置文件中的**userService**设置错，从而在`npm adduser`时引起`Error: TypeError config.userService.auth(...)[(intermediate value)]`这个错误
3. 起初有怀疑时**userService**设置错，将其设置回null，但因为粗心忘记`npm run restart`，而导致配置未生效，因而此前的错误还是在。
4. 按照默认的userService，只需将 `alwaysAuth: false,` 改成 `alwaysAuth: true,`  即可实现打开网页需要验证。可实现有管理员账号密码才能查看到具体页面。无需另外改动**userService**

谢谢 @dead-horse @alsotang 的提醒。
