### ISSUE TITLE
如何混合使用npm的公共仓库和cnpm搭建的私有仓库

### ISSUE THREAD

**Issue by ucoker** [cnpm/cnpmjs.org#929]
# 如何混合使用npm的公共仓库和cnpm搭建的私有仓库
- 在本地登录npm的账户，registry为 `https://registry.npmjs.org/`
	1. 安装在公共仓库的模块`lodash`,运行`npm install lodash --save`后，**成功安装**
	2. 安装在私有仓库的模块`jsComponent`,运行`npm install @cnpm/jsComponent --save`,提示错误`'@cnpm/jsComponent' is not in the npm registry.`  
		此时的错误是因为我们没登录私有仓库引起的。
	

		```bash
		$ npm install @cnpm/jsComponent --save
		npm ERR! Darwin 15.4.0
		npm ERR! argv "/usr/local/Cellar/node/6.0.0/bin/node" "/usr/local/bin/npm" "install" "@cnpm/jsComponent" "--save"
		npm ERR! node v6.0.0
		npm ERR! npm  v3.8.6
		npm ERR! code E404
		
		npm ERR! 404 Not found : @cnpm/jsComponent
		npm ERR! 404 
		npm ERR! 404  '@cnpm/jsComponent' is not in the npm registry.
		npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
		npm ERR! 404 
		npm ERR! 404 Note that you can also install from a
		npm ERR! 404 tarball, folder, http url, or git url.
		
		npm ERR! Please include the following file with any support request:
		npm ERR!     /Users/admin/Tools/e/npm-debug.log
		```
- 在本地登录私有仓库的帐户，registry为 `https://r.mywebsite.com`
	1. 执行`$ npm login --registry=https://r.mywebsite.com --scope=@cnpm`，输入私有仓库的帐户密码后登录。  
		成功登录，提示：`Logged in as admin to scope @cnpm on https://r.mywebsite.com/.`

	2. 安装在私有仓库的模块`jsComponent`,运行`npm install @cnpm/jsComponent --save`后，**成功安装**
	3. 安装在公共仓库的模块`lodash`,运行`npm install lodash --save`后，**提示错误**`unauthorized login first: lodash`  

		```bash
		$ npm install lodash --save
		npm ERR! Darwin 15.4.0
		npm ERR! argv "/usr/local/Cellar/node/6.0.0/bin/node" "/usr/local/bin/npm" "install" "lodash" "--save"
		npm ERR! node v6.0.0
		npm ERR! npm  v3.8.6
		npm ERR! code E401
		
		npm ERR! unauthorized login first: lodash
		npm ERR! 
		npm ERR! If you need help, you may report this error at:
		npm ERR!     <https://github.com/npm/npm/issues>
		
		npm ERR! Please include the following file with any support request:
		npm ERR!     /Users/admin/Tools/e/npm-debug.log
		```
		
		
**请教下，如何在登录私有仓库时，也可以成功通过scope来同步私有仓库，和公共仓库。或者能否同时登录npm的帐户和cnpm搭建的私有仓库帐户？**

**Comment by alsotang** [comment]
将私有仓库通过命令行区分开，公共的就是 npm 命令，自己的就用 pnpm 之类的命令，然后分别设置他们的登录信息。

用这个改造即可：https://github.com/cnpm/cnpm

2016-05-22 2:50 GMT+08:00 ucoker <notifications@github.com>:

**Comment by ucoker** [comment]
我参考了这篇 [npm 混合公共仓库和私有仓库
](https://breeswish.org/blog/2016/02/16/npm-hybridize-public-and-private-repository/)  
里面提到

> 例如 npm install @swx/logger 会走内部服务器，npm install logger 则走公共仓库。

通过scope来区分是私有仓库还是公共仓库。但实际上，登录私有仓库后，可以获取到私有仓库，但是获取公共仓库会报错（如上错误信息）。

能否在不改变npm命令的前提下，实现通过scope来选择走公共或着私有？
用cnpm改造后，是否命令都变成cnpm了？

我不大确定我问的问题是不是很小白，我之前开发iOS，近期在学习nodejs。

**Comment by dead-horse** [comment]
默认不同步模式下就会将所有 public 的包的请求都代理到 npm 去，不需要这样处理了吧

**Comment by ucoker** [comment]
@dead-horse 
你好，我将cnpm搭建到阿里上并映射到registry为https://r.mywebsite.com，
硬盘空间有限，所以我并没设置同步，都按默认配置。如图：  

![qq20160523-0](https://cloud.githubusercontent.com/assets/12216739/15467471/58e07d20-2111-11e6-813d-d9a3c2abab12.png)


然后我在本地登录 `npm login --registry=https://r.mywebsite.com --scope=@cnpm`，登陆后，获取自己私有仓库的包成功。
但是在获取public 包时发生错误，并没有像你说的，请求代理到npm，还需要额外配置什么吗？
例如：运行 `npm install lodash --save`, 获取lodash public 包发生错误如下：

```bash
$ npm install lodash --save
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.0.0/bin/node" "/usr/local/bin/npm" "install" "lodash" "--save"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code E401

npm ERR! unauthorized login first: lodash
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/admin/Tools/e/npm-debug.log
```

**Comment by dead-horse** [comment]
目测是把用户信息也发到了 npm 吧，我看看 @fengmk2 怎么实现转发的

**Comment by dead-horse** [comment]
原来是直接 redirect 过去的，`npm login --registry http://my_private_repo:1234 --scope=@swx` 加上 scope login 试试

**Comment by ucoker** [comment]
@dead-horse 
你好，我默认就是用scope  方式登录的。  
 `npm login --registry=https://r.mywebsite.com --scope=@cnpm`

**Comment by SummerWish** [comment]
在 follow 官方的教程的时候不要进行“Change cnpm default registry to your private registry”这一步。

http://pastebin.com/GYn074uz

**Comment by ucoker** [comment]
受 @SummerWish 启发，再次检查配置。  
发现，我在`config/index.js`配置中，將alwaysAuth设置为true。
而检查到，我在用npm login 的时候，并没有加`--always-auth`这个参数。

刚刚验证了，加上可以解决这个issue。

具体代码为：
在本地终端输入： 
`npm login --registry=https://r. mywebsite.com --scope=@db --always-auth`
再次感谢 @alsotang @dead-horse @SummerWish 。

**Comment by wenshan** [comment]
tag
