### ISSUE TITLE
cnpm私有仓库的scope包可以被另一个cnpm私有仓库同步吗？

### ISSUE THREAD

**Issue by ywang1724** [cnpm/cnpmjs.org#956]
先前两个团队分别利用cnpm搭建了自己的npm私有源，都设有scope，现考虑将两者合并，涉及scope包的迁移，想咨询一个仓库是否可以sync另一个仓库的scope包？如果不行，针对上述场景是否有较合适的迁移方案？谢谢~

**Comment by alsotang** [comment]
现有的迁移方案我倒是不清楚。如果我来做这件事的话，分两步弄：

1. 包迁移
2. 用户迁移


先说 2. 用户迁移吧，用户迁移直接从仓库1中的 user 表，把对应的用户数据迁移到仓库2 就好了。

1. 包迁移建议不要从 mysql 和 文件的角度来做。建议把仓库1设成仓库2的上游，然后从数据库中找到所有内部包的名字（就你的场景来说，就是所有对应
scope 开头的包）。然后批量执行 cnpm sync 命令，让那些包自动同步过来。

这时候仓库1就可以下线了。

在 2016年6月14日 下午3:43，wy <notifications@github.com>写道：

**Comment by ywang1724** [comment]
@alsotang 我现在的想法跟你提到的基本一致，但是测试包迁移时sync scope包404，如果cnpm本身没做限制的话，可能是我这边设置上某个环节出错了吧，我再排查下，谢谢~

**Comment by ywang1724** [comment]
@alsotang 现在web上sync scope包是404，直接cnpm sync是401，但我这边login过，直接sync非scope包在web上和cnpm客户端都是正常的，这个是需要在哪配置下吗？

**Comment by ywang1724** [comment]
升级新版本后就可以sync了

**Comment by alsotang** [comment]
升级了什么的新版本？

2016-06-14 17:50 GMT+08:00 wy <notifications@github.com>:

**Comment by ywang1724** [comment]
cnpmjs.org

**Comment by realzbc** [comment]
@ywang1724   你好   我升级了cnpmjs.org 然后用服务器A去镜像B，B上的私有包，还是不可以镜像到A，这是日志：

**Comment by ywang1724** [comment]
@realzbc A在同步前不要设置@testPrivate这个scope
