### ISSUE TITLE
cnpm install的逻辑是否支持纯本地安装？

### ISSUE THREAD

**Issue by shanggqm** [cnpm/cnpmjs.org#960]
目前CNPM的install逻辑是如果CNPM私服镜像上存在指定的包则直接下载，如果不存在，则直接指向备用的源比如：
- http://r.cnpmjs.org
- http://registry.npm.taobao.org
- ...

这样的逻辑本身不存在什么问题，也符合用户体验。但是我在开发的时候遇到这样一个需求：
在提测前需要使用[npm shrinkwrap --dev](https://docs.npmjs.com/cli/shrinkwrap) 固定住所有依赖的版本。这个操作会在工程根目录下生成一个npm-shrinkwrap.json文件：

片段如下：

``` javascript
{
"lodash._isiterateecall": {
     "version": "3.0.9",
     "from": "lodash._isiterateecall@>=3.0.0 <4.0.0",
     "resolved": "http://192.168.1.111:7001/lodash._isiterateecall/-/lodash._isiterateecall-3.0.9.tgz"
  },
  "lodash.restparam": {
      "version": "3.6.1",
      "from": "lodash.restparam@>=3.0.0 <4.0.0",
     "resolved": "http://r.cnpmjs.org/lodash.restparam/-/lodash.restparam-3.6.1.tgz"
   }
}
```

其中如果有第三方依赖的包升级了版本，但是CNPM仓库尚未镜像时，就会出现这种混合的resolved地址，在可以访问公网环境的机器上没有任何问题，但是在禁止访问公网的虚机上执行构建操作时则会因为r.cnpmjs.org无法访问导致npm install失败。

目前我们的解决方案是先 install一次，这样cnpm仓库中就有了最新的依赖，然后删掉node_modules再重新npm install && npm shrinkwrap，这样才能“保证“npm-shrinkwrap.json文件中所有的resolve都指向本地CNPM仓库。

这种方案仍然存在风险，首次npm shrinkwrap或者后续每次升级包、新增包都需要靠人工去检验，不知道cnpm关于这个问题是否有一些考虑，比如提供一个install 的参数：

```
cnpm install --local
```

这样就可以保证所有的下载源都指向本地cnpm仓库，即便install的速度慢一些。

盼复！

**Comment by fengmk2** [comment]
@shanggqm 不错的建议，欢迎指教给 https://github.com/cnpm/cnpm 提交 pr 实现此功能。

**Comment by fengmk2** [comment]
cnpm shrinkwrap 来实现会更加好。

**Comment by fengmk2** [comment]
如果使用 shrinkwrap 的话，我建议还不如写死版本号。shrinkwrap 带来的好处比坏处大，有安全漏洞的包其实你也无法及时更新。

**Comment by dead-horse** [comment]
@shanggqm 其实最好是最终发布的包就是提测的包，这样也不存在需要使用 shrinkwrap 的需求了

**Comment by alsotang** [comment]
说到 shrinkwrap，前几天我也遇到一个shrinkwrap的坑。

有个同事装某个demo的时候，私活装不上，卡在某个 npm install 的地方，可她明明用的是 tnpm。

后来排查发现，一个隐藏的很深的库使用了 shrinkwrap，里面写死了 r.npmjs.org。

**Comment by shanggqm** [comment]
@fengmk2 同意使用cnpm shrinkwrap来实现比install --local好。
写死版本号这个方案我们目前已经在用，但问题是dependencies的依赖树好控制，devDependencies很难控制，比如babel、webpack的依赖。

前端时间我们上线的时候遇到yo的一个[故障](https://github.com/yeoman/yo/issues/437)，导致构建一直不成功，原因就是yo发了个patch版本，cnpm给镜像过来了，这个时间差正好被我们赶上了，好在yo很快就修复了这个问题。

所以一直在考虑怎么固化依赖版本的问题， shrinkwrap研究了一两天了，研究越深觉得坑越多，还得影响组员的工作流程。感觉为了一个小概率事件做这么多工作收益有点低，可能还会引入新的风险，不知道你们在实际项目中是怎么解决这个问题的？

**Comment by shanggqm** [comment]
@dead-horse 好主意。之前我们的构建流程没有考虑到每次install依赖不一致的情况，所以上线前还会构建一次，看来是构建流程该优化一下了，3ks

**Comment by shanggqm** [comment]
@alsotang 这也是个坑啊！
