### ISSUE TITLE
私有CNPM查看不了包的历史版本信息

### ISSUE THREAD

**Issue by lijiexiang** [cnpm/cnpmjs.org#964]
在msql库里能查看到包的历史版本， 但是在详情页http://xxxx/package/gulp-browserify却没有显示历史版本。以前查看是能显示出来历史版本的，请问这是什么导致的？我看淘宝官方的cnpmjs.org查看包也有这样的问题。

![image](https://cloud.githubusercontent.com/assets/14355839/16251641/58928420-385a-11e6-86c2-b4625754e2e1.png)

**Comment by diytz** [comment]
同问

**Comment by fengmk2** [comment]
https://www.npmjs.com/package/gulp-browserify 官方也不好显示历史版本。

真要看历史版本，可以使用 npm info gulp-browserify 或者通过 registry 接口查看 https://registry.npm.taobao.org/gulp-browserify

**Comment by fengmk2** [comment]
> 以前查看是能显示出来历史版本的

web 上一直都没有这个功能。

**Comment by happier2** [comment]
@fengmk2 现在npmjs支持历史版本查看了，cnpm是不是也考虑添加下这个功能

**Comment by fengmk2** [comment]
@happier2 欢迎 pr 来实现，数据都是在的。
