### ISSUE TITLE
cnpm install 失败

### ISSUE THREAD

**Issue by limbo-lab** [cnpm/cnpmjs.org#977]
![](https://cloud.githubusercontent.com/assets/5107346/16407367/ee779a76-3d45-11e6-8eed-0754dd88f439.png)

**Comment by fengmk2** [comment]
你本地的 cnpmjs.org 是什么版本？请升级到最新版本吧。

**Comment by limbo-lab** [comment]
从官方源更新 cnpm 解决问题
