### ISSUE TITLE
如何更新用户信息？

### ISSUE THREAD

**Issue by limbo-lab** [cnpm/cnpmjs.org#979]
在路由中发现了

```js
app.put('/-/user/org.couchdb.user::name/-rev/:rev', login, updateUser);
```

但是没找到相应的 npm/cnpm 子命令

**Comment by fengmk2** [comment]
npm login --verbose ，你会发现的。

**Comment by fengmk2** [comment]
以前整理过非官方 registry api https://github.com/cnpm/cnpmjs.org/blob/master/docs/registry-api.md#add-a-new-user
