### ISSUE TITLE
环境搭建好后无法搜索包

### ISSUE THREAD

**Issue by liulangxiong** [cnpm/cnpmjs.org#980]
搜索packages出现500错误。查了一下信息发现SQL报错。
[Error: SQLITE_ERROR: no such table: tag]

1、我抓同样的语句在MySQL命令行可以运行查询。
2、config.js的账号密码绝对没有错。
3、我查了MySQL的日志，没有出现查询日志，说明cnpmjs系统根本没有与MySQL建立连接。
4、说不存在tag这个表，但MySQL又没有cnpmjs的查询日志，是不是逻辑有问题？

**Comment by liulangxiong** [comment]
dispatch-1 (out): { [SequelizeDatabaseError: SQLITE_ERROR: no such table: tag]
dispatch-1 (out):   name: 'SequelizeDatabaseError',
dispatch-1 (out):   message: 'SQLITE_ERROR: no such table: tag',
dispatch-1 (out):   parent:
dispatch-1 (out):    { [Error: SQLITE_ERROR: no such table: tag]
dispatch-1 (out):      errno: 1,
dispatch-1 (out):      code: 'SQLITE_ERROR',
dispatch-1 (out):      sql: 'SELECT module_id FROM tag WHERE LOWER(name) LIKE LOWER(\'111%\') AND tag=\'latest\'     ORDER BY name LIMIT 100;' },
dispatch-1 (out):   original:
dispatch-1 (out):    { [Error: SQLITE_ERROR: no such table: tag]
dispatch-1 (out):      errno: 1,
dispatch-1 (out):      code: 'SQLITE_ERROR',
dispatch-1 (out):      sql: 'SELECT module_id FROM tag WHERE LOWER(name) LIKE LOWER(\'111%\') AND tag=\'latest\'     ORDER BY name LIMIT 100;' },
dispatch-1 (out):   sql: 'SELECT module_id FROM tag WHERE LOWER(name) LIKE LOWER(\'111%\') AND tag=\'latest\'     ORDER BY name LIMIT 100;',
dispatch-1 (out):   url: '/browse/keyword/111' }
dispatch-1 (out): SequelizeDatabaseError: SQLITE_ERROR: no such table: tag
dispatch-1 (out):     at Query.formatError (/home/wwwroot/cnpmjs.org/node_modules/sequelize/lib/dialects/sqlite/query.js:348:14)
dispatch-1 (out):     at afterExecute (/home/wwwroot/cnpmjs.org/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
dispatch-1 (out):     at replacement (/home/wwwroot/cnpmjs.org/node_modules/sqlite3/lib/trace.js:20:31)
dispatch-1 (out):     at Statement.errBack (/home/wwwroot/cnpmjs.org/node_modules/sqlite3/lib/sqlite3.js:16:21)

**Comment by fengmk2** [comment]
从报错信息 `[Error: SQLITE_ERROR: no such table: tag]` 来看你连的不是 mysql，而是 sqlite
