### ISSUE TITLE
同步 nodejs nightly 的包

### ISSUE THREAD

**Issue by popomore** [cnpm/cnpmjs.org#985]
https://nodejs.org/download/nightly/

**Comment by fengmk2** [comment]
nightly 的包有点大，而且每天都会构建。。。

**Comment by popomore** [comment]
比较费钱么？

可以定期更新最新的包么？比如过几一天一更，因为只会下最新的。

**Comment by fengmk2** [comment]
这个功能用的人不多，是否直接去源站下载即可？

**Comment by popomore** [comment]
我直接用 node-nightly 下不翻墙挺慢的。或者手动吧。

**Comment by fengmk2** [comment]
那我全量吧，钱不是问题。

**Comment by fengmk2** [comment]
syncing https://cnpmjs.org/mirrors/node-nightly/v0.10.41-nightly20151203036580393d/

**Comment by fengmk2** [comment]
https://github.com/hemanth/node-nightly-version/pull/1

**Comment by fengmk2** [comment]
https://github.com/hemanth/node-nightly/pull/11

**Comment by fengmk2** [comment]
https://npm.taobao.org/mirrors/node-nightly/
