### ISSUE TITLE
安装electron遇到的问题，新手求助

### ISSUE THREAD

**Issue by longboy** [cnpm/cnpmjs.org#991]
由于直接去electron官网安装老是安装不了，所以只好切换到淘宝的镜像。

我的安装步骤是这样的：
1、npm config set registry https://registry.npm.taobao.org
2、来到https://npm.taobao.org/mirrors/electron/1.2.7/下载安装包（其实我搞不懂哪些是需要下载的安装包），就下载了electron-v1.2.7-win32-x64.zip、electron-v1.2.7-win32-x64-symbols.zip、ffmpeg-v1.2.7-win32-x64.zip、v1.2.7.zip
3、将下载好的包放到当前用户的根目录下的.electron文件夹下，C:\Users\MyName\.electron
4. 执行安装命令npm install electron-prebuilt -g

然后就报错了
如下：
![_20160714155123](https://cloud.githubusercontent.com/assets/6941888/16832021/dd289e86-49da-11e6-98f1-10a3b858b83d.png)

**Comment by fengmk2** [comment]
先安装 cnpm，然后通过 cnpm i electron-prebuilt 来安装，简单设置 registry 是不行的。
