### ISSUE TITLE
description和keywords包含中文的时候，发布会报错

### ISSUE THREAD

**Issue by guoxmin** [cnpm/cnpmjs.org#993]
```
npm ERR! registry error parsing json
npm ERR! registry error parsing json

```

**Comment by alsotang** [comment]
`npm ERR! registry error parsing json`

**Comment by alsotang** [comment]
是不是 package.json 不小心写进了中文的标点符号？去测测你的 json 是否合法

**Comment by guoxmin** [comment]
@alsotang  json格式没问题。多次测试发现一个很怪异的问题，description:"按需加" 正常，description:"倒计时" 则报错，同样是三个中文字符。

**Comment by alsotang** [comment]
.....

**Comment by guoxmin** [comment]
@alsotang 服务报500错误，这怎么破

**Comment by fengmk2** [comment]
请将 package.json 提交上来吧，还有你的数据库默认编码是什么？

**Comment by guoxmin** [comment]
@fengmk2 

```
{
  "name": "@test/test",
  "version": "1.0.0",
  "description": "倒计时",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "countdown",
    "倒计时"
  ],
  "author": "guoxmin",
  "license": "ISC"
}

```

数据库默认编码：
mysql.sock@cnpmjs> show variables like 'character_set_database';
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| character_set_database | gbk   |
+------------------------+-------+
