### ISSUE TITLE
关于syncModel: 'exist'的困惑。

### ISSUE THREAD

**Issue by dabaii** [cnpm/cnpmjs.org#994]
因为公司内网和外网是100%隔离的，仓库需要离线使用（在外网更新好，把整个系统用USB拷贝到内网搭建环境提供内网服务，仓库更新后需要重新完成拷贝工作）。
为了避免经常拷贝的系统过大，希望仓库只存放开发用的必要包。我选择了syncModel: 'exist'，
但是在给仓库添加包的时候，客户端用npm install less 安装一个很简单的模块，整个仓库会更几百个包并且还在一直运行。

首先确认了我的数据库里面的所有表在初始化里面都是没有数据的。在去尝试更新第一个包。  

是不是因为包又依赖，会吧依赖也全部更新到本地？

而且这些包有几千个版本，如问如何只在本地保存最新版本？

能否说明一下 syncModel: 'exist' 的工作机制。

**Comment by dead-horse** [comment]
> 是不是因为包又依赖，会吧依赖也全部更新到本地？

是

> 而且这些包有几千个版本，如问如何只在本地保存最新版本？

不能，因为 npm 命令行需要请求到全量的包信息才能决定安装哪个版本。

> 能否说明一下 syncModel: 'exist' 的工作机制。

会自动同步仓库中已经有的所有模块的所有版本。不能只同步最新版本。

**Comment by dabaii** [comment]
感谢 @dead-horse 的回答。
比较困惑的，是为啥一个简单的less模块 会需要同步上百个包而且还没有停止的迹象。对模块的依赖数没有太大的概念，但是从直觉上感觉一个less模块不会有这么多依赖. 
请问这种 一个包依赖上百个模块 是否正常？

**Comment by dead-horse** [comment]
你安装完 less，然后 npm ls 一下看看输出了多少个模块就知道了

**Comment by chrischjh** [comment]
syncMode: 'exist' 模式，似乎当安装一个本地不存在的包的时候会直接报错，而不是从source下载

**Comment by dead-horse** [comment]
1. https://github.com/cnpm/cnpmjs.org/blob/master/config/index.js#L177 这个必须配置成 true
2. npm 的安装方式导致可能并不能所有的请求都代理到 source，现在 syncByInstall 的实现也不完善，只能当做一个增强选项。
3. 强烈不推荐 exist 模式，否则要安装的时候请先 `cnpm sync` 一下。

**Comment by dabaii** [comment]
刚刚找了一个全新的文件夹安装了一下less。
使用npm ls

+-- aws-sign2@0.6.0
+-- aws4@1.4.1
+-- bl@1.1.2
| `-- readable-stream@2.0.6
|   +-- core-util-is@1.0.2
|   +-- inherits@2.0.1
|   +-- isarray@1.0.0
|   +-- process-nextick-args@1.0.7
|   +-- string_decoder@0.10.31
|   `-- util-deprecate@1.0.2
+-- caseless@0.11.0
+-- extend@3.0.0
+-- forever-agent@0.6.1
+-- hawk@3.1.3
| +-- boom@2.10.1
| +-- cryptiles@2.0.5
| +-- hoek@2.16.3
| `-- sntp@1.0.9
+-- is-typedarray@1.0.0
+-- isstream@0.1.2
+-- json-stringify-safe@5.0.1
+-- less@2.1.2
| +-- UNMET OPTIONAL DEPENDENCY graceful-fs@^3.0.4
| +-- mime@1.3.4
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8
| +-- promise@6.1.0
| | `-- asap@1.0.0
| +-- UNMET OPTIONAL DEPENDENCY request@^2.48.0
| `-- source-map@0.1.43
|   `-- amdefine@1.0.0
+-- mime-types@2.1.11
| `-- mime-db@1.23.0
+-- oauth-sign@0.8.2
+-- qs@6.2.0
+-- stringstream@0.0.5
+-- tough-cookie@2.2.2
`-- tunnel-agent@0.4.3

包确实蛮多。 看了一下 本地安装已经结束了，但是服务器还在同步包。
访问页面看到统计信息：217	total packages	      4,048	total package versions

包更新还在继续。。。

如果使用不使用exist 模式，请问还有其他手段 更新指定包么？因为我需要在完全的断网的环境提供给内网用户使用。而且从没办法直接把外网机器设置成内网机器，只能使用虚拟机形式 拷贝到内网，如果同步了所有库，太大了。

**Comment by dead-horse** [comment]
完全断网的情况下是无法使用 npm 的，就算你有所有的包，因为：

1. npm 可以指定从 github 安装模块
2. npm 可以指定从任意一个 url 上安装模块
3. npm 的 postinstall 脚本可能会去请求一些需要的文件（例如 phantomjs）
4. 一些 npm c++ addon 会预编译好，在 postinstall 的时候去下载

所以除非你们打通外网访问，否则基本不要想能正常使用 npm

**Comment by dabaii** [comment]
感谢解惑，看来的想其他办法在隔绝的环境下进行nodejs的开发工作了。

**Comment by alsotang** [comment]
@dead-horse 

> 强烈不推荐 exist 模式

啊？？我一直是用着这个模式的，感觉也能正常运作啊

**Comment by dead-horse** [comment]
就是发现缺模块了要 sync 一下..

**Comment by alsotang** [comment]
install 的时候不是会自动 sync 吗？

**Comment by dead-horse** [comment]
可能有些地方没覆盖到，因为这个代码我没怎么测过，哈哈

**Comment by alsotang** [comment]
之前这个 install 不自动 sync 的问题，我印象中只有在官方公开的 scoped package 上遇到，后来这个 bug 修复之后，我想应该就没什么问题了。。。

**Comment by alsotang** [comment]
马哥你那边还有这个问题的实例吗？如果我现在中 exist 改成 all 的话，会不会有潜在问题？

2016-07-17 19:00 GMT+08:00 Yiyu He <notifications@github.com>:

**Comment by alsotang** [comment]
> 马哥你那边还有这个问题的实例吗？

我指的是配置了 exist 却不自动 sync 的实例

**Comment by springuper** [comment]
使用 syncModel: 'exist' 并启用 syncByInstall，发现会有第一次 install 出错，第二次成功的情况。

log 如下：

第一次 install
```bash
$ npm install eslint --registry=http://10.104.10.68:7001/

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "eslint" "--registry=http://10.104.10.68:7001/"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: flat-cache@'>=1.2.1 <2.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.4","1.0.3","1.0.2","1.0.1","1.0.0"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'file-entry-cache'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/spring/Repo/ucarcommonwap/npm-debug.log
```

第二次很顺利，但是发现 eslint 的版本很老。。。
```bash
$ npm install eslint --registry=http://10.104.10.68:7001/

eslint@1.1.0 node_modules/eslint
├── object-assign@2.1.1
├── escape-string-regexp@1.0.5
├── path-is-absolute@1.0.0
├── path-is-inside@1.0.1
├── globals@8.18.0
├── estraverse@4.2.0
├── user-home@1.1.1
├── strip-json-comments@1.0.4
├── xml-escape@1.0.0
├── estraverse-fb@1.3.1
├── text-table@0.2.0
├── espree@2.2.5
├── debug@2.2.0 (ms@0.7.1)
├── chalk@1.1.3 (supports-color@2.0.0, ansi-styles@2.2.1, strip-ansi@3.0.1, has-ansi@2.0.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── optionator@0.5.0 (fast-levenshtein@1.0.7, type-check@0.3.2, levn@0.2.5, wordwrap@0.0.3, prelude-ls@1.1.2, deep-is@0.1.3)
├── minimatch@2.0.10 (brace-expansion@1.1.6)
├── concat-stream@1.5.1 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.6)
├── doctrine@0.6.4 (isarray@0.0.1, esutils@1.1.6)
├── lodash.clonedeep@3.0.2 (lodash._bindcallback@3.0.1, lodash._baseclone@3.3.0)
├── is-my-json-valid@2.13.1 (jsonpointer@2.0.0, generate-function@2.0.0, xtend@4.0.1, generate-object-property@1.2.0)
├── js-yaml@3.6.1 (esprima@2.7.2, argparse@1.0.7)
├── lodash.merge@3.3.2 (lodash.isarguments@3.0.9, lodash.isarray@3.0.4, lodash.keys@3.1.2, lodash._arraycopy@3.0.0, lodash._getnative@3.9.1, lodash._arrayeach@3.0.0, lodash.istypedarray@3.0.6, lodash.keysin@3.0.8, lodash.toplainobject@3.0.0, lodash.isplainobject@3.2.0, lodash._createassigner@3.1.1)
├── inquirer@0.9.0 (strip-ansi@3.0.1, ansi-regex@2.0.0, through@2.3.8, rx-lite@2.5.2, cli-width@1.1.1, figures@1.7.0, run-async@0.1.0, lodash@3.10.1, readline2@0.1.1)
├── escope@3.6.0 (esrecurse@4.1.0, es6-weak-map@2.0.1, es6-map@0.1.4)
└── lodash.omit@3.1.0 (lodash.restparam@3.6.1, lodash._bindcallback@3.0.1, lodash._arraymap@3.0.0, lodash._pickbyarray@3.0.2, lodash._pickbycallback@3.0.0, lodash.keysin@3.0.8, lodash._baseflatten@3.1.4, lodash._basedifference@3.0.3)
```

出现这个问题的原因是因为 private registry 没有高版本的包，在第一次 install 的时候并不是等待 sync 结束后再继续 install，而是直接返回了吗？

**Comment by liwenda122** [comment]
> 使用 syncModel: 'exist' 并启用 syncByInstall，发现会有第一次 install 出错，第二次成功的情况。
> 
> log 如下：
> 
> 第一次 install
> 
> ```shell
> $ npm install eslint --registry=http://10.104.10.68:7001/
> 
> npm ERR! Darwin 15.5.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "eslint" "--registry=http://10.104.10.68:7001/"
> npm ERR! node v4.4.5
> npm ERR! npm  v2.15.5
> npm ERR! code ETARGET
> 
> npm ERR! notarget No compatible version found: flat-cache@'>=1.2.1 <2.0.0'
> npm ERR! notarget Valid install targets:
> npm ERR! notarget ["1.0.4","1.0.3","1.0.2","1.0.1","1.0.0"]
> npm ERR! notarget
> npm ERR! notarget This is most likely not a problem with npm itself.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> npm ERR! notarget
> npm ERR! notarget It was specified as a dependency of 'file-entry-cache'
> npm ERR! notarget
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/spring/Repo/ucarcommonwap/npm-debug.log
> ```
> 
> 第二次很顺利，但是发现 eslint 的版本很老。。。
> 
> ```shell
> $ npm install eslint --registry=http://10.104.10.68:7001/
> 
> eslint@1.1.0 node_modules/eslint
> ├── object-assign@2.1.1
> ├── escape-string-regexp@1.0.5
> ├── path-is-absolute@1.0.0
> ├── path-is-inside@1.0.1
> ├── globals@8.18.0
> ├── estraverse@4.2.0
> ├── user-home@1.1.1
> ├── strip-json-comments@1.0.4
> ├── xml-escape@1.0.0
> ├── estraverse-fb@1.3.1
> ├── text-table@0.2.0
> ├── espree@2.2.5
> ├── debug@2.2.0 (ms@0.7.1)
> ├── chalk@1.1.3 (supports-color@2.0.0, ansi-styles@2.2.1, strip-ansi@3.0.1, has-ansi@2.0.0)
> ├── mkdirp@0.5.1 (minimist@0.0.8)
> ├── optionator@0.5.0 (fast-levenshtein@1.0.7, type-check@0.3.2, levn@0.2.5, wordwrap@0.0.3, prelude-ls@1.1.2, deep-is@0.1.3)
> ├── minimatch@2.0.10 (brace-expansion@1.1.6)
> ├── concat-stream@1.5.1 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.6)
> ├── doctrine@0.6.4 (isarray@0.0.1, esutils@1.1.6)
> ├── lodash.clonedeep@3.0.2 (lodash._bindcallback@3.0.1, lodash._baseclone@3.3.0)
> ├── is-my-json-valid@2.13.1 (jsonpointer@2.0.0, generate-function@2.0.0, xtend@4.0.1, generate-object-property@1.2.0)
> ├── js-yaml@3.6.1 (esprima@2.7.2, argparse@1.0.7)
> ├── lodash.merge@3.3.2 (lodash.isarguments@3.0.9, lodash.isarray@3.0.4, lodash.keys@3.1.2, lodash._arraycopy@3.0.0, lodash._getnative@3.9.1, lodash._arrayeach@3.0.0, lodash.istypedarray@3.0.6, lodash.keysin@3.0.8, lodash.toplainobject@3.0.0, lodash.isplainobject@3.2.0, lodash._createassigner@3.1.1)
> ├── inquirer@0.9.0 (strip-ansi@3.0.1, ansi-regex@2.0.0, through@2.3.8, rx-lite@2.5.2, cli-width@1.1.1, figures@1.7.0, run-async@0.1.0, lodash@3.10.1, readline2@0.1.1)
> ├── escope@3.6.0 (esrecurse@4.1.0, es6-weak-map@2.0.1, es6-map@0.1.4)
> └── lodash.omit@3.1.0 (lodash.restparam@3.6.1, lodash._bindcallback@3.0.1, lodash._arraymap@3.0.0, lodash._pickbyarray@3.0.2, lodash._pickbycallback@3.0.0, lodash.keysin@3.0.8, lodash._baseflatten@3.1.4, lodash._basedifference@3.0.3)
> ```
> 
> 出现这个问题的原因是因为 private registry 没有高版本的包，在第一次 install 的时候并不是等待 sync 结束后再继续 install，而是直接返回了吗？

这个问题解决了吗？现在发现开启exist模式看起来很美好，实际问题多多，用的2.9.4 升级最新版本能解决问题吗

**Comment by ijse** [comment]
这么多年过去了，这个问题果然很坑

后来把模式改为了'none'，可之前exist时同步的包存在，导致下载不了最新包
