### ISSUE TITLE
本地的npm包全部丢失。

### ISSUE THREAD

**Issue by abnerCrack** [cnpm/cnpmjs.org#998]
用root权限运行了一次npm 服务器 就结果  npm install的时候发现所有私有的的包都无法安装了。
报404.  为什么会出现这样的状况。有什么解决方案吗

**Comment by dead-horse** [comment]
私有包文件权限是不是被改了？

**Comment by abnerCrack** [comment]
权限没变  但是所有的包进去都是一个 - root的也是

**Comment by dead-horse** [comment]
都被改成 root 才能读了吧，试试把权限修回来吧

**Comment by abnerCrack** [comment]
权限正常的
```
ui@npm:~/.cnpmjs.org$ ls -ll
total 2012
drwxrwxr-x    2 ui ui 1818624 Jul 19 17:15 downloads
drwxrwxr-x    2 ui ui   28672 Jul 19 17:16 logs
drwxrwxr-x 5926 ui ui  200704 Jul 19 11:33 nfs
ui@npm:~/.cnpmjs.org$ 

```

**Comment by dead-horse** [comment]
里面呢？ 那些包文件

**Comment by abnerCrack** [comment]
ls出来就是一个  “-”
有点疑问这个真是存储方式是什么。能告诉一下吗
`ui@npm:~/.cnpmjs.org/nfs/@own/ui-core$ ls
-
ui@npm:~/.cnpmjs.org/nfs/@own/ui-core$ ls -ll
total 4
drwxrwxr-x 3 ui ui 4096 Mar 25 11:34 -
ui@npm:~/.cnpmjs.org/nfs/@own/ui-core$ 
`

**Comment by alsotang** [comment]
原来就是这样的，里面先是一个 -。

`ls ./-` 可以看看里面

2016-07-19 17:32 GMT+08:00 abnercrack <notifications@github.com>:

**Comment by alsotang** [comment]
以及，你可以去服务端读取文件的那个地方，看看 404 究竟是报什么错导致的。我跟死马想法一样，既然是切换用户导致的bug，应该是文件权限方面的问题。

2016-07-19 19:30 GMT+08:00 alsotang <alsotang@gmail.com>:

**Comment by abnerCrack** [comment]
@alsotang @dead-horse  已经解决。大部分包还是还原了。期间打tag publish的包全部丢了。不过幸好gitlab有备份。

**Comment by alsotang** [comment]
解决方案是？

**Comment by abnerCrack** [comment]
@alsotang 解决方案就是修复权限。手动移动所有包还有修复权限。但是不知道什么原因还是少了很多包。root目录下没有 原来的目录下面也没有。问题解决issue我关掉了。谢谢
